<a href="https://colab.research.google.com/github/MD2001/Self_traine_RAG_Model/blob/main/RAG_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
!nvidia-smi

Tue May 19 11:27:06 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P0             29W /   70W |     239MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1128      C   /usr/bin/python3                        236MiB |
+-----------------------------------------------------------------------------------------+

In [41]:
!pip install pymupdf bitsandbytes spacy sentence-transformers torch numpy pandas tqdm requests
!python -m spacy download en_core_web_sm

Requirement already satisfied: pymupdf in /usr/local/lib/python3.12/dist-packages (1.27.2.3)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 91.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [42]:
import os
import requests

url = r"https://arxiv.org/pdf/2412.19437"
pdf_path = os.path.join(os.getcwd(), "Data_file.pdf")

if not os.path.exists(pdf_path):
    response = requests.get(url)
    if response.status_code == 200:
        with open(pdf_path, "wb") as f:
            f.write(response.content)
        print(f"[INFO] the file is downloaded at : {pdf_path}")
else:
    print(f"[INFO] file exist : {pdf_path} ")

[INFO] file exist : /content/Data_file.pdf

In [43]:
import fitz  # PyMuPDF

def clean_text(text: str):
    text = text.replace("\n", " ").strip()
    return text

def open_pdf(file_path: str):
    document = fitz.open(file_path)
    pages_and_texts = []
    for page_num, page in enumerate(document):
        text = page.get_text()
        cleaned_text = clean_text(text)
        pages_and_texts.append({
            "text_of_page": cleaned_text,
            "page_count_char": len(cleaned_text),
            "page_count_word": len(cleaned_text.split(" ")),
            "page_count_sentences": len(cleaned_text.split(". ")),
            "tokens_num": len(cleaned_text) // 4,
            "page_number": page_num + 1
        })
    return pages_and_texts

pages_and_texts = open_pdf("Data_file.pdf")
pages_and_texts[3]

{'text_of_page': '1. Introduction In recent years, Large Language Models (LLMs) have been undergoing rapid iteration and evolution (Anthropic, 2024; Google, 2024; OpenAI, 2024a), progressively diminishing the gap to- wards Artificial General Intelligence (AGI). Beyond closed-source models, open-source models, including DeepSeek series (DeepSeek-AI, 2024a,b,c; Guo et al., 2024), LLaMA series (AI@Meta, 2024a,b; Touvron et al., 2023a,b), Qwen series (Qwen, 2023, 2024a,b), and Mistral series (Jiang et al., 2023; Mistral, 2024), are also making significant strides, endeavoring to close the gap with their closed-source counterparts. To further push the boundaries of open-source model capa- bilities, we scale up our models and introduce DeepSeek-V3, a large Mixture-of-Experts (MoE) model with 671B parameters, of which 37B are activated for each token. With a forward-looking perspective, we consistently strive for strong model performance and economical costs. Therefore, in terms of architecture, DeepSeek-V3 still adopts Multi-head Latent Attention (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for cost-effective training. These two architectures have been validated in DeepSeek- V2 (DeepSeek-AI, 2024c), demonstrating their capability to maintain robust model performance while achieving efficient training and inference. Beyond the basic architecture, we implement two additional strategies to further enhance the model capabilities. Firstly, DeepSeek-V3 pi- oneers an auxiliary-loss-free strategy (Wang et al., 2024a) for load balancing, with the aim of minimizing the adverse impact on model performance that arises from the effort to encourage load balancing. Secondly, DeepSeek-V3 employs a multi-token prediction training objective, which we have observed to enhance the overall performance on evaluation benchmarks. In order to achieve efficient training, we support the FP8 mixed precision training and implement comprehensive optimizations for the training framework. Low-precision training has emerged as a promising solution for efficient training (Dettmers et al., 2022; Kalamkar et al., 2019; Narang et al., 2017; Peng et al., 2023b), its evolution being closely tied to advancements in hardware capabilities (Luo et al., 2024; Micikevicius et al., 2022; Rouhani et al., 2023a). In this work, we introduce an FP8 mixed precision training framework and, for the first time, validate its effectiveness on an extremely large-scale model. Through the support for FP8 computation and storage, we achieve both accelerated training and reduced GPU memory usage. As for the training framework, we design the DualPipe algorithm for efficient pipeline parallelism, which has fewer pipeline bubbles and hides most of the communication during training through computation-communication overlap. This overlap ensures that, as the model further scales up, as long as we maintain a constant computation-to-communication ratio, we can still employ fine-grained experts across nodes while achieving a near-zero all-to-all communication overhead. In addition, we also develop efficient cross-node all-to-all communication kernels to fully utilize InfiniBand (IB) and NVLink bandwidths. Furthermore, we meticulously optimize the memory footprint, making it possible to train DeepSeek-V3 without using costly tensor parallelism. Combining these efforts, we achieve high training efficiency. During pre-training, we train DeepSeek-V3 on 14.8T high-quality and diverse tokens. The pre-training process is remarkably stable. Throughout the entire training process, we did not encounter any irrecoverable loss spikes or have to roll back. Next, we conduct a two-stage context length extension for DeepSeek-V3. In the first stage, the maximum context length is extended to 32K, and in the second stage, it is further extended to 128K. Following this, we conduct post-training, including Supervised Fine-Tuning (SFT) and Reinforcement Learning (RL) on the base model of DeepSeek-V3, to align it with human preferences and further unlock its potential. During the post-training stage, we distill the reasoning capability from the DeepSeek- R1 series of models, and meanwhile carefully maintain the balance between model accuracy 4',
 'page_count_char': 4248,
 'page_count_word': 594,
 'page_count_sentences': 26,
 'tokens_num': 1062,
 'page_number': 4}

In [44]:
import pandas as pd
df = pd.DataFrame(pages_and_texts)
df.head(10)

,text_of_page,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,1817,238,11,454,1
1,Contents 1 Introduction 4 2 Architecture 6 2.1...,2634,919,766,658,2
2,4.5.3 Batch-Wise Load Balance VS. Sequence-Wis...,1715,572,462,428,3
3,"1. Introduction In recent years, Large Languag...",4248,594,26,1062,4
4,Training Costs Pre-Training Context Extension ...,3287,468,21,821,5
5,verification and reflection patterns of R1 int...,3475,457,23,868,6
6,… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ...,1557,262,8,389,7
7,where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vecto...,2236,353,9,559,8
8,where 𝑁𝑠and 𝑁𝑟denote the numbers of shared exp...,2901,455,17,725,9
9,Main Model (Next Token Prediction) Embedding L...,2904,451,23,726,10

In [45]:
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
count,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00
std,799.86,178.18,124.63,199.99,15.44
min,699.00,99.00,1.00,174.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00
50%,2992.00,457.00,23.00,748.00,27.00
75%,3281.00,516.00,29.00,820.00,40.00
max,4248.00,919.00,766.00,1062.00,53.00

# Turn text to sentences

In [46]:
from spacy.lang.en import English

nlp = English()
nlp.add_pipe("sentencizer")

semtemces = "this my name . hellow mr.ahmed . what is your name ?"
doc = nlp(semtemces)
list(doc.sents)

[this my name ., hellow mr.ahmed ., what is your name ?]

# Now try the `data`

In [47]:
for page in pages_and_texts:
    page["sentences"] = list(nlp(page["text_of_page"]).sents)
    page["sentences_num"] = len(page["sentences"])

for page in pages_and_texts:
    page["sentences"] = [str(s) for s in page["sentences"]]

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25}

In [48]:
pages_and_texts[5]["sentences"][6]

'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.'

In [49]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num
count,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94
std,799.86,178.18,124.63,199.99,15.44,14.44
min,699.00,99.00,1.00,174.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00

In [50]:
test = list(range(1, 25))
slice_size = 10
x = [test[i:i+slice_size] for i in range(0, len(test), slice_size)]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24]]

In [51]:
def chunker(input_list: list[str], slice_size: int = slice_size) -> list[list[str]]:
    return [input_list[i:i+slice_size] for i in range(0, len(input_list), slice_size)]

for page in pages_and_texts:
    page["sentences_chunk"] = chunker(page["sentences"])
    page["sentences_chunk_num"] = len(page["sentences_chunk"])

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25,
 'sentences_chunk': [['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
   'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
   'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
   'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
   '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
   'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
   'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
   'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
   '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
   'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.'],
  ['In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
   'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
   'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
   'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
   'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
   '2.',
   'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
   '2024) for economical training.',
   'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
   'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).'],
  ['2.1.',
   'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
   '2017) framework.',
   'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
   'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6']],
 'sentences_chunk_num': 3}

In [52]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num,sentences_chunk_num
count,53.00,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94,2.89
std,799.86,178.18,124.63,199.99,15.44,14.44,1.40
min,699.00,99.00,1.00,174.00,1.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00,2.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00,3.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00,3.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00,6.00

In [53]:
pages_and_chunk = []
for page in pages_and_texts:
    for chunk in page["sentences_chunk"]:
        chunk_dict = {}
        paragragh = "".join(chunk).replace("  ", " ").strip()
        chunk_dict["paragraphe"] = paragragh
        chunk_dict["word_count"] = len(paragragh.split(" "))
        chunk_dict["char_count"] = len(paragragh)
        chunk_dict["tokens_count"] = len(paragragh) // 4
        chunk_dict["sentence_count"] = len(chunk)
        chunk_dict["page_number"] = page["page_number"]
        pages_and_chunk.append(chunk_dict)

pages_and_chunk[5], len(pages_and_chunk), len(pages_and_texts)

({'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
  'word_count': 298,
  'char_count': 830,
  'tokens_count': 207,
  'sentence_count': 10,
  'page_number': 3},
 153,
 53)

In [54]:
df = pd.DataFrame(pages_and_chunk)
df.describe().round(2)

       word_count  char_count  tokens_count  sentence_count  page_number
count      153.00      153.00        153.00          153.00       153.00
mean       157.03      974.48        243.26            8.29        26.52
std        145.88      584.64        146.14            2.95        13.86
min          1.00        1.00          0.00            1.00         1.00
25%         74.00      572.00        143.00            7.00        15.00
50%        134.00      912.00        228.00           10.00        28.00
75%        191.00     1301.00        325.00           10.00        39.00
max        877.00     2975.00        743.00           10.00        53.00

In [55]:
df[df["word_count"] < 4]

,paragraphe,word_count,char_count,tokens_count,sentence_count,page_number
21,9,1,1,0,1,9

In [56]:
filtered_chunks = [chunk for chunk in pages_and_chunk if chunk["tokens_count"] >= 30]
filtered_chunks[111]

{'paragraphe': 'A study of bfloat16 for deep learning training.arXiv preprint arXiv:1905.12322, 2019.S. Krishna, K. Krishna, A. Mohananey, S. Schwarcz, A. Stambler, S. Upadhyay, and M. Faruqui.Fact, fetch, and reason: A unified evaluation of retrieval-augmented generation.CoRR, abs/2409.12941, 2024.doi: 10.48550/ARXIV.2409.12941.URL https://doi.org/10.485 50/arXiv.2409.12941.T. Kwiatkowski, J. Palomaki, O. Redfield, M. Collins, A. P. Parikh, C. Alberti, D. Epstein, I. Polosukhin, J. Devlin, K. Lee, K. Toutanova, L. Jones, M. Kelcey, M. Chang, A. M. Dai, J. Uszkoreit, Q. Le, and S. Petrov.Natural questions: a benchmark for question answering research.Trans.',
 'word_count': 84,
 'char_count': 648,
 'tokens_count': 162,
 'sentence_count': 10,
 'page_number': 39}

In [57]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [58]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu128
True

In [59]:
test_set = ["my name", "her name", "the naem"]
embedding = model.encode(test_set)
embedding = dict(zip(test_set, embedding))
embedding, embedding["my name"].shape

({'my name': array([-1.11268573e-01,  3.23448479e-02, -3.83405983e-02,  2.23898515e-02,
         -4.03140448e-02, -5.62008433e-02,  2.33329967e-01,  3.92086506e-02,
         -1.01078916e-02, -6.38170317e-02,  1.64089613e-02, -3.45565118e-02,
          4.02090512e-02, -7.56014213e-02, -8.34885146e-03,  2.65755560e-02,
         -1.42915146e-02,  6.17216621e-03, -8.46135914e-02, -7.72886276e-02,
         -4.17721681e-02,  6.27691001e-02, -3.24081848e-05, -2.02984978e-02,
         -8.92573670e-02,  6.10290561e-03, -3.12835611e-02,  9.11155567e-02,
         -3.69639210e-02, -1.61543220e-01, -3.80761048e-04,  7.48015754e-03,
          9.98783335e-02,  5.72649203e-02, -4.66819946e-03, -4.17357497e-02,
         -1.26731172e-01, -2.11646315e-02,  5.62063605e-02, -1.07810730e-02,
         -4.70561814e-03, -1.19292334e-01,  2.42646094e-02,  5.37946960e-03,
          7.11642625e-03,  7.88037013e-03,  6.28924463e-04,  2.45066918e-02,
          1.61230508e-02,  9.47958529e-02, -9.59324911e-02, -8.88254121e-02,
         -5.96604608e-02,  1.89628340e-02,  1.31215546e-02, -7.77191296e-02,
          2.44200677e-02,  5.09177409e-02, -3.09439073e-03,  2.27675017e-04,
          4.02659625e-02,  1.79441981e-02, -7.26719722e-02,  3.98123749e-02,
          1.57936346e-02,  8.13501514e-03, -6.94848876e-03,  1.39237344e-02,
          4.64227470e-03, -9.63735115e-03, -2.38479264e-02, -6.72971504e-03,
          7.07241967e-02, -3.35569531e-02, -1.96107533e-02, -1.45387175e-02,
          1.61475949e-02, -1.77206565e-02, -1.31569132e-02,  6.13828674e-02,
         -8.46485421e-02,  4.43953089e-03, -9.70008522e-02, -8.54699966e-03,
         -2.76288819e-02,  4.83488142e-02,  3.65964770e-02, -3.85116972e-02,
         -2.87031792e-02, -5.48662012e-03,  2.66992766e-03, -7.49976933e-02,
          2.27708276e-02, -3.73113062e-03, -2.44773086e-02, -5.23786852e-03,
         -3.77427408e-04, -4.05307524e-02, -3.87832858e-02,  1.85519412e-01,
         -6.50252625e-02,  3.38605642e-02, -5.62591776e-02,  7.47068971e-02,
         -7.21327402e-03, -8.54292233e-03, -5.87107874e-02,  5.19505935e-03,
          5.03457617e-03, -2.29808893e-02, -5.23379222e-02, -2.39632111e-02,
         -5.20041212e-02,  4.00795117e-02,  3.42810266e-02,  7.10860863e-02,
          2.96648638e-03, -2.60684434e-02,  3.05781476e-02, -2.95662452e-02,
          4.49147411e-02,  2.99034305e-02, -8.65571722e-02, -1.93888247e-02,
         -2.02057883e-02,  1.09101320e-02, -1.28696987e-03, -3.38961143e-33,
          5.94923971e-03,  1.89251471e-02, -4.11719375e-04,  1.40347689e-01,
          2.08697114e-02,  1.44509701e-02, -5.77049181e-02,  7.57382531e-03,
         -3.34116220e-02, -4.86478937e-04,  1.18632512e-02,  1.23979412e-02,
         -2.82270722e-02,  6.32571355e-02,  2.87447441e-02,  3.98514196e-02,
         -2.19962895e-02,  5.86499013e-02, -3.66561636e-02,  2.81827729e-02,
         -3.64033990e-02,  6.67515397e-02,  3.82383959e-03,  3.85378152e-02,
         -5.31676114e-02, -1.20789602e-01, -1.26687428e-02, -7.43082687e-02,
          3.59358080e-02,  2.43288055e-02, -5.68794310e-02, -1.62085518e-02,
          8.52152929e-02, -1.06991157e-02,  2.98596621e-02, -8.78667161e-02,
         -1.15062436e-02,  1.56421792e-02, -4.40781899e-02,  1.03963710e-01,
         -9.96420253e-03,  1.12467865e-02, -7.92487040e-02,  4.75009754e-02,
         -2.51976997e-02, -1.84205286e-02,  3.58203910e-02,  5.33687174e-02,
         -9.88210440e-02, -1.01148700e-02, -5.02876937e-02,  3.62836607e-02,
         -1.07462831e-01, -1.13349000e-04, -8.78018141e-02,  2.03307290e-02,
         -1.38522219e-03,  9.96502955e-03, -1.05820239e-01, -1.08255353e-02,
         -5.61664673e-03,  3.54209915e-02, -1.99718289e-02,  1.85144190e-02,
          1.84968300e-02, -4.77539189e-02,  7.75206983e-02, -5.72839193e-02,
          2.59806383e-02,  3.01387981e-02, -7.60096461e-02, -5.30696064e-02,
          4.44190763e-03,  4.09770794e-02,  7.15029612e-02,  6.62901625e-03,
         -8.63271207e-03,  5.87880239e-02, -3.33780646e-02, -9.79789533e-03,
          3.39137763e-02, -1.12671731e-02,  2.68006534e-03,  3.78638729e-02,
          2.98798140e-02, -2.79738125e-03, -1.43967336e-02, -3.69952247e-02,
         -1.53699890e-02, -3.44166495e-02, -1.34393841e-01, -1.39010290e-03,
          1.08393110e-01, -2.45960075e-02, -5.27149923e-02,  1.20526944e-33,
         -1.27882240e-02,  4.35465947e-02,  1.87255144e-02,  9.56211314e-02,
          4.67724679e-03, -2.69599725e-02,  5.32098487e-03,  1.07820280e-01,
          1.92450429e-03,  5.60385659e-02, -2.19700299e-02, -8.23150426e-02,
          4.67023998e-03, -2.90249963e-03,  8.16676468e-02,  4.96276915e-02,
          4.06117775e-02, -1.76347175e-03, -4.65384275e-02,  2.63390807e-03,
         -5.90300411e-02,  5.77563234e-02, -1.08628972e-02, -6.16722256e-02,
         -4.12749639e-03,  1.70052741e-02,  3.90953161e-02,  2.52950154e-02,
          7.08594248e-02,  6.80856630e-02,  5.44355623e-03,  2.39246991e-02,
         -1.16943434e-01,  2.93325186e-02, -2.60607377e-02,  6.45446777e-02,
         -1.89388581e-02, -1.98988877e-02,  1.02716032e-02, -3.32665117e-03,
         -1.41809108e-02,  3.20844166e-02, -7.18640164e-02,  1.08568124e-01,
         -1.31833423e-02, -3.98828723e-02, -5.78844994e-02,  3.01688109e-02,
          1.03621753e-02,  4.26096134e-02, -3.35614122e-02, -6.73616156e-02,
         -6.93707317e-02, -3.82362828e-02,  1.17586204e-03,  3.61948684e-02,
          6.44930080e-02,  2.16482971e-02,  9.53722652e-03,  4.65249270e-03,
          1.59358215e-02,  3.41444798e-02,  6.12317100e-02,  7.34104440e-02,
          3.04528642e-02, -1.78817846e-02, -6.13178425e-02, -4.10457924e-02,
         -2.72018444e-02, -4.76150177e-02, -5.27509004e-02,  2.03911383e-02,
         -4.46444713e-02,  2.69611552e-02, -9.46116224e-02,  3.20556760e-02,
          1.63121745e-02,  2.63475999e-02, -2.50774976e-02,  5.37288338e-02,
          3.02447788e-02,  8.66488367e-02, -2.48541720e-02,  3.00488397e-02,
          1.60620529e-02, -2.64487602e-02,  3.59426737e-02,  8.03072006e-02,
         -2.33004615e-02, -3.87402140e-02,  2.93709319e-02,  3.48940827e-02,
         -1.20452987e-02, -1.63013097e-02, -9.69538242e-02, -1.50699115e-08,
          4.22302522e-02,  5.01371697e-02,  3.11900042e-02, -4.23704786e-03,
          5.10957465e-02,  8.86452720e-02, -3.07842949e-03, -2.18302831e-02,
          4.13647182e-02,  6.56359121e-02,  9.79078040e-02,  5.34657836e-02,
          3.15143019e-02,  9.64246038e-03,  9.51068252e-02, -2.79179122e-02,
         -5.68721518e-02,  8.92905332e-03, -4.92047006e-03, -2.21009869e-02,
         -3.58192921e-02, -2.98428796e-02,  8.19763988e-02, -7.19111487e-02,
          4.26656716e-02,  9.13804211e-03,  3.62761915e-02,  9.37117413e-02,
         -5.74504323e-02,  7.81973675e-02,  1.13642449e-02,  1.17897853e-01,
          1.24909841e-02,  6.13724999e-02, -3.99509445e-02, -9.76340962e-04,
          2.87474431e-02,  8.35279822e-02,  5.63313141e-02, -8.02358612e-03,
         -3.31368223e-02,  5.76817095e-02,  9.86445323e-02, -1.26726208e-02,
         -6.93445057e-02,  6.50679693e-02, -2.79135798e-04, -1.52546233e-02,
         -4.63721994e-03, -2.10706089e-02,  8.71945731e-03,  1.70729086e-02,
          2.25879066e-02,  7.89605230e-02,  2.01134626e-02,  4.21369597e-02,
          3.23688537e-02,  5.68195991e-02, -6.11764863e-02, -5.45439497e-02,
          7.75277615e-02,  5.29310107e-03, -9.12822783e-02,  1.33656142e-02],
        dtype=float32),
  'her name': array([-1.08516835e-01,  1.40265804e-02, -1.97903719e-02,  4.03932557e-02,
         -3.66050377e-02, -1.11383910e-03,  1.42931923e-01,  4.01251726e-02,
         -9.60895885e-03, -7.14013577e-02,  2.60373261e-02, -9.37794298e-02,
         -1.03092007e-02, -7.65828937e-02, -4.02911119e-02,  7.74797723e-02,
          3.67318690e-02,  3.94579843e-02, -9.53144282e-02, -5.77405766e-02,
         -2.17363499e-02, -2.40650587e-02,  3.27845924e-02,  4.04389314e-02,
         -3.74303684e-02,  2.06179288e-03, -5.38016707e-02,  1.28083834e-02,
         -3.16410102e-02, -1.22112028e-01,  1.27529195e-02, -1.95463318e-02,
          4.58517522e-02,  7.62845501e-02, -1.12639777e-02,  3.25134024e-02,
         -7.22715482e-02,  4.53228131e-02,  2.71108244e-02, -1.35517614e-02,
         -1.94001030e-02, -1.14641190e-01, -4.72653173e-02, -4.64220531e-02,
         -3.94386686e-02, -4.94745784e-02,  5.11805266e-02,  3.23776156e-02,
          2.72550080e-02, -2.67371703e-02, -6.49755523e-02, -5.32744974e-02,
         -1.18825667e-01,  2.55615334e-03,  7.93129802e-02, -2.25096550e-02,
          5.34011535e-02,  5.47847301e-02,  3.82738747e-02,  1.02927955e-02,
          6.06006235e-02,  5.18807285e-02, -7.12646544e-02,  4.85623144e-02,
         -5.31421509e-03, -9.10787564e-03,  3.76584157e-02, -4.69223261e-02,
          3.90819535e-02,  6.33181026e-03,  2.00461447e-02,  3.55321132e-02,
         -1.72345119e-03, -3.88698243e-02,  2.61442140e-02,  1.99030656e-02,
          7.56488368e-02,  1.09233623e-02,  2.11198106e-02,  6.88376650e-02,
         -7.15844110e-02,  1.77171491e-02,  5.93769248e-04,  1.94033571e-02,
          4.28237906e-03,  4.30800989e-02, -3.16121578e-02, -2.20457967e-02,
         -2.73831468e-02, -5.10556996e-02, -4.97697815e-02, -6.01557791e-02,
          3.76522988e-02, -1.17023606e-02, -2.06190217e-02, -2.93967761e-02,
         -2.07708683e-02, -2.78658457e-02, -1.51966019e-02,  1.78603187e-01,
         -9.23539549e-02,  1.01476811e-01, -9.04798973e-03,  9.42860767e-02,
         -3.34172621e-02, -5.97187765e-02,  4.86570969e-02, -5.82065247e-03,
         -3.47071178e-02, -1.29232677e-02, -1.64545723e-03, -1.47645604e-02,
         -9.90036428e-02, -5.19062486e-03,  3.52939218e-02,  3.13790888e-02,
          4.73542139e-02, -1.23639842e-02,  2.38937903e-02, -9.74604338e-02,
          4.04632986e-02, -4.96868491e-02, -4.79108617e-02, -2.40672920e-02,
         -5.60439974e-02, -2.87503097e-02,  2.83523370e-02, -3.16460785e-33,
         -3.55151109e-02,  2.95765847e-02,  8.10843334e-02,  8.34557489e-02,
          5.95203750e-02,  2.11190376e-02,  1.59792881e-02,  1.16894823e-02,
          3.46236560e-03, -2.01443378e-02, -2.27793818e-03, -8.82629156e-02,
         -5.42954654e-02, -8.02553445e-02,  1.01886190e-01,  1.27110016e-02,
         -3.21839377e-02,  7.77681321e-02, -7.86050484e-02,  5.41977994e-02,
          4.28526700e-02,  8.47249627e-02,  2.49307938e-02,  5.01613542e-02,
         -3.17426212e-02, -9.03307199e-02,  7.80699998e-02,  1.17246453e-02,
          1.61146629e-03,  3.63856032e-02, -2.68512554e-02,  1.80553237e-04,
          8.83467197e-02, -1.63772050e-02,  5.22142090e-02, -4.44410779e-02,
         -5.81521960e-03, -1.12066315e-02,  3.63275595e-03,  7.74848014e-02,
          2.00558752e-02, -1.65881515e-02,  2.73299143e-02,  1.84893813e-02,
         -1.34903461e-01,  4.32648808e-02,  5.84352650e-02,  1.03551177e-02,
          4.11863439e-02, -6.93688125e-05, -9.41860378e-02,  3.53580266e-02,
         -1.00075312e-01,  5.65286577e-02, -6.15795031e-02,  8.11114609e-02,
          3.31930406e-02, -1.32226376e-02, -1.87826566e-02, -3.98739800e-02,
          1.16541935e-02,  2.19120849e-02, -6.86918423e-02,  9.83213726e-03,
          4.92209680e-02, -5.10650910e-02,  2.85478476e-02, -1.02851339e-01,
          3.24431509e-02,  1.23117324e-02, -1.13674089e-01,  1.87593307e-02,
          2.25785170e-02,  4.31681499e-02, -5.41481040e-02,  2.82280240e-02,
          3.29296328e-02, -2.86127906e-02, -3.13658938e-02, -5.98064112e-03,
          1.17117772e-02,  3.75699624e-02, -2.54161321e-02,  8.43513757e-02,
         -4.38703112e-02, -3.62565671e-03, -2.06886642e-02, -1.42937945e-02,
         -3.48393731e-02, -7.15545639e-02, -6.16803765e-02,  2.06668843e-02,
          7.54758641e-02, -4.97289151e-02, -2.12219078e-02,  1.31706033e-33,
         -5.28453197e-03,  1.54753262e-02, -4.34725247e-02,  6.07264675e-02,
          5.43512106e-02, -1.14345383e-02, -1.48579862e-03,  1.01141512e-01,
         -4.60987538e-03, -1.25182755e-02,  2.76288670e-02, -1.24480285e-01,
          1.22275827e-02, -1.49447517e-02,  6.50415421e-02,  6.65458813e-02,
          8.23930874e-02, -6.69729486e-02, -3.24602798e-02, -6.40189871e-02,
         -9.25134569e-02,  1.08705983e-02,  1.46334646e-02, -7.67764151e-02,
         -2.50701662e-02,  2.24009957e-02,  9.63629857e-02, -2.89403205e-03,
         -4.82729040e-02, -1.27476882e-02,  3.41592655e-02,  1.86355393e-02,
         -7.29230717e-02,  6.13725074e-02, -3.97584587e-02,  4.89614829e-02,
          2.06597690e-02, -4.81188744e-02,  2.89742164e-02,  2.80812252e-02,
          4.12800722e-02,  8.84457584e-03, -2.17011198e-02,  1.02579266e-01,
          2.75864806e-02,  2.12726444e-02, -1.27490778e-02,  4.89049293e-02,
          8.61027986e-02,  2.64374614e-02, -2.06164829e-02, -7.87167400e-02,
         -2.70623844e-02,  8.11805483e-03,  5.95772527e-02, -3.19411308e-02,
          5.81040382e-02,  1.95024721e-02,  3.71584073e-02,  5.88329369e-03,
          1.53963631e-02,  3.51784229e-02, -2.35251244e-02,  7.92885870e-02,
         -3.05617414e-02, -1.99384727e-02, -8.13735276e-02, -1.25664681e-01,
         -2.59873904e-02, -5.24826460e-02,  3.75154172e-03,  2.80722268e-02,
         -4.10411470e-02,  6.88030720e-02, -9.14725065e-02,  1.63114965e-02,
         -9.08275023e-02, -2.50380635e-02, -2.15020403e-02,  3.57075781e-02,
          1.56708080e-02,  2.72471756e-02, -5.09988628e-02,  1.73474010e-03,
          2.54246704e-02, -4.76674363e-03,  8.02696422e-02,  1.11472107e-01,
         -2.18369551e-02, -1.08616427e-01, -1.27693126e-02, -8.22652131e-03,
         -1.66713297e-02, -6.58632964e-02, -7.73727223e-02, -1.59770810e-08,
          1.07899169e-02, -4.41676239e-03,  5.39550968e-02, -6.93758875e-02,
          4.82009649e-02,  7.87589401e-02,  2.61549763e-02, -1.01903314e-02,
          2.86767986e-02,  7.04269409e-02,  8.22025761e-02,  2.00291518e-02,
          5.73524125e-02,  3.10403351e-02,  6.98653609e-02, -3.70383821e-02,
          1.93623397e-02,  1.15336150e-01, -4.57215495e-03,  1.14648258e-02,
         -6.67648809e-03, -4.16181497e-02,  5.23354784e-02, -1.36465177e-01,
          1.81709714e-02,  6.24543289e-03, -1.47890784e-02,  1.09797142e-01,
         -4.21142615e-02,  1.01671042e-02, -3.07445489e-02,  1.13257200e-01,
          3.45925316e-02,  1.96993034e-02,  1.25570328e-03,  3.80589813e-02,
          4.83893715e-02,  2.26375088e-02, -1.67597346e-02,  3.04051172e-02,
         -1.51804322e-02,  2.86381561e-02,  9.29250866e-02, -2.69179884e-02,
         -5.29072545e-02,  2.60878168e-02,  1.27067007e-02, -4.53397222e-02,
         -2.70362617e-03, -1.21021410e-02, -7.78905023e-03,  1.35550862e-02,
          4.36936580e-02,  3.78443897e-02, -2.25435048e-02, -1.41144134e-02,
          2.71069724e-02, -2.39804816e-02, -3.96824554e-02,  1.36288349e-04,
          7.66980229e-03,  1.05079962e-02,  6.80239871e-02,  1.96243580e-02],
        dtype=float32),
  'the naem': array([-6.02948405e-02,  1.08011052e-01, -4.00737077e-02,  2.84997659e-04,
         -5.78279793e-02,  3.90510187e-02,  1.63081456e-02, -6.27290756e-02,
         -2.72917449e-02,  6.48954287e-02, -1.36010153e-02, -1.12080663e-01,
          4.29547280e-02, -3.33018824e-02,  3.84274088e-02,  1.98065944e-04,
         -9.92211513e-03,  3.54601024e-03, -1.39897596e-02, -5.76529130e-02,
         -3.93402614e-02,  4.99700494e-02,  2.77685206e-02, -9.71350446e-03,
         -7.29377419e-02,  3.06810922e-04,  5.28396294e-02,  1.97455790e-02,
          6.62655532e-02, -1.39705911e-01,  5.01693285e-04,  6.13604076e-02,
         -2.77932584e-02,  1.24619938e-02, -6.92578033e-02, -7.66454497e-03,
         -6.53420910e-02, -5.53792203e-03,  1.61085129e-02,  6.49705110e-03,
          7.51554295e-02, -4.55971584e-02, -3.45250778e-03, -3.36859412e-02,
          3.02659534e-02, -7.05949217e-02, -2.51310710e-02, -1.06170205e-02,
          4.80370596e-02,  5.61027974e-02,  3.07876244e-02, -5.77379912e-02,
         -2.93143615e-02,  2.36564856e-02,  6.86284751e-02,  3.42092179e-02,
         -3.66425663e-02, -1.07707456e-01,  2.47657653e-02, -1.87081529e-03,
          8.02794322e-02, -6.56679273e-03, -7.98377991e-02,  6.52273521e-02,
          6.82051852e-02, -9.37174186e-02,  6.07989132e-02,  3.30209807e-02,
         -3.37643661e-02,  2.64172256e-02,  3.17097679e-02, -5.40623516e-02,
          7.14883208e-02, -5.86048081e-05, -5.46505712e-02, -2.46140687e-03,
          6.93024844e-02,  2.13217158e-02,  4.47886400e-02, -1.18316356e-02,
          3.43479179e-02,  3.82324047e-02,  3.36475596e-02, -3.92940156e-02,
          5.31843156e-02, -2.18139519e-03,  8.81356224e-02, -2.54521728e-03,
          2.20382437e-02,  3.63924690e-02, -5.86665981e-02, -3.01841721e-02,
         -8.23800545e-03, -4.73330840e-02,  3.13263349e-02, -3.42283770e-02,
         -2.73820218e-02,  1.87601373e-02,  1.42661054e-02,  1.50500983e-01,
          8.95082727e-02,  1.07485481e-01,  3.75269633e-03,  2.73721423e-02,
          2.50877608e-02,  1.64601542e-02,  1.33112716e-02,  9.83588398e-03,
         -1.44914603e-02,  7.16948360e-02, -4.74362522e-02, -1.86514538e-02,
         -2.84116771e-02, -5.88076422e-03,  3.09784003e-02, -2.49706693e-02,
         -1.90918390e-02, -2.12573502e-02,  5.94183709e-03,  2.15574391e-02,
          6.16728934e-03, -8.75436738e-02, -8.20264071e-02,  3.19139138e-02,
          3.29091549e-02,  5.75121231e-02, -1.16018392e-02, -3.45252866e-33,
         -1.07773812e-02,  7.30657764e-03, -1.63617283e-02, -4.64672484e-02,
          3.70621607e-02,  2.73215324e-02, -2.31236573e-02,  5.66564389e-02,
         -9.57396328e-02, -1.78244002e-02, -2.85459906e-02,  7.88215026e-02,
         -7.85891786e-02,  1.38537576e-02,  8.36980119e-02,  1.03458306e-02,
         -7.59367049e-02, -2.64889039e-02, -3.77846695e-02, -9.53301787e-02,
         -1.12825729e-01,  1.13505103e-01,  7.91858975e-03,  4.91239987e-02,
         -4.25062105e-02,  2.93205883e-02, -2.66452711e-02, -8.48129913e-02,
         -2.70097647e-02,  3.14407609e-02,  4.99393307e-02,  4.24260534e-02,
         -5.03373370e-02,  4.26193103e-02, -8.63207132e-02, -7.60603929e-03,
         -2.76761241e-02, -2.03614663e-02, -5.48336878e-02, -3.26869525e-02,
         -3.44958417e-02,  2.51876153e-02,  1.70821752e-02,  6.42866567e-02,
         -8.01583976e-02, -4.63353172e-02, -1.50233461e-02, -6.26032501e-02,
          8.19116607e-02,  2.78966464e-02,  2.92815408e-03, -3.42845521e-03,
         -4.39038314e-02, -2.01127995e-02,  9.56656598e-03, -1.93480849e-02,
          1.94198670e-04,  4.55720536e-02,  6.61208481e-02, -1.77856423e-02,
          3.08940746e-02,  4.35537510e-02,  3.67996506e-02,  9.71465111e-02,
          3.79517265e-02,  3.49885896e-02, -6.32043649e-03, -6.03008345e-02,
          5.28266616e-02, -3.05552389e-02, -4.74490486e-02,  5.96354306e-02,
          6.59352168e-02,  7.80555308e-02, -1.09356199e-03,  1.21456999e-02,
         -5.06833196e-03, -8.68264660e-02, -9.48877260e-02, -3.95371541e-02,
          2.56637316e-02,  5.39868176e-02, -2.76523139e-02,  6.43403679e-02,
          3.58118787e-02, -1.93711314e-02, -2.32705716e-02, -1.75263528e-02,
          1.40554151e-02, -2.48366576e-02,  1.45109445e-02,  4.32571508e-02,
          1.46898227e-02, -6.47579804e-02, -5.66580296e-02,  3.23795870e-33,
          2.35631373e-02,  1.24060027e-02, -1.02182604e-01,  6.69505447e-02,
          6.45909831e-02, -4.55888733e-02,  4.77873795e-02,  2.63668559e-02,
         -1.10716760e-01,  3.60688679e-02,  1.58359986e-02, -2.84000952e-02,
          1.29867524e-01,  4.72247675e-02,  8.71693566e-02, -5.97080812e-02,
          1.27869114e-01, -8.50948021e-02,  2.15539783e-02, -3.34259532e-02,
          2.41573565e-02, -3.29210721e-02,  1.49753662e-02, -1.72330569e-02,
          1.08727599e-02,  7.22939298e-02,  1.39474440e-02, -7.08193406e-02,
         -7.42303059e-02, -2.18184907e-02,  1.94083136e-02,  3.13056633e-02,
         -1.57291163e-02,  9.62476525e-03, -4.63565588e-02,  3.84134464e-02,
          2.73784008e-02,  6.42660037e-02, -6.87038228e-02, -4.55769524e-02,

In [60]:
from tqdm import tqdm

for chunk in tqdm(pages_and_chunk):
    chunk["embedding"] = model.encode(chunk["paragraphe"], device="cuda")

100%|██████████| 153/153 [00:02<00:00, 55.63it/s]

In [61]:
page_and_Embedding_df = pd.DataFrame(pages_and_chunk)
page_and_Embedding_file_name = "page_and_Embedding.csv"
page_and_Embedding_path = os.path.join(os.getcwd(), page_and_Embedding_file_name)
page_and_Embedding_df.to_csv(page_and_Embedding_path, index=False)

In [62]:
pages_and_chunk = pd.read_csv(page_and_Embedding_path)
pages_and_chunk

,paragraphe,word_count,char_count,tokens_count,sentence_count,page_number,embedding
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,222,1767,441,10,1,[-7.36544952e-02 -5.92406169e-02 5.75507320e-...
1,arXiv:2412.19437v2 [cs.CL] 18 Feb 2025,5,38,9,2,1,[-1.14521943e-01 7.90134817e-03 -7.34652132e-...
2,Contents 1 Introduction 4 2 Architecture 6 2.1...,302,952,238,10,2,[-1.76019520e-02 -5.03365062e-02 -4.91420068e-...
3,14 3.3.1 Mixed Precision Framework . . . . . ....,324,912,228,10,2,[-1.62387546e-02 3.45402360e-02 -1.01859644e-...
4,21 4.2 Hyper-Parameters . . . . . . . . . . . ...,267,742,185,9,2,[ 2.22861618e-02 3.54707390e-02 -1.13855258e-...
...,...,...,...,...,...,...,...
148,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2961,740,1,49,[-8.76501352e-02 3.37730092e-03 -2.45083366e-...
149,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2968,742,1,50,[-8.87522548e-02 2.17784266e-03 -2.23974865e-...
150,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2975,743,1,51,[-8.97150487e-02 9.12359171e-03 -2.74221674e-...
151,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2975,743,1,52,[-8.86220858e-02 6.90447586e-03 -2.55782306e-...
152,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,346,1370,342,4,53,[-8.44786763e-02 4.49150056e-03 -2.48290338e-...

In [63]:
data = pages_and_chunk.to_dict(orient="records")
data[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': '[-5.76343276e-02  1.86269917e-02 -6.96299970e-02 -5.02143241e-03\n -6.43548295e-02  5.39917164e-02 -4.61325049e-02  3.96139473e-02\n -5.72229698e-02  5.44086890e-03 -4.39483300e-02 -6.78674597e-03\n  4.00273837e-02 -1.59042105e-02  7.62045942e-03  4.98709008e-02\n  1.28310904e-01 -3.56771536e-02 -4.98869941e-02 -8.15588757e-02\n  4.34629247e-02 -4.59041260e-02  8.90600160e-02  1.54037392e-02\n -7.79620633e-02  3.06390412e-02 -5.25193177e-02 -6.64413869e-02\n  3.31790932e-02 -6.93640783e-02 -6.77237054e-03  3.17598786e-03\n  5.10903373e-02 -8.24809447e-02 -8.37938860e-02  1.99515838e-02\n -5.22203818e-02 -5.73824197e-02  1.78819019e-02  2.67783813e-02\n  1.22663754e-04 -3.79559807e-02  2.66226567e-03  2.12215558e-02\n  3.83332558e-02 -2.20189169e-02 -5.95767982e-02 -2.69228593e-02\n -4.48381007e-02 -8.05420503e-02 -1.64256413e-02 -6.48153126e-02\n  5.06793987e-03 -2.43172818e-03 -5.40565476e-02 -8.12956691e-03\n  4.19080891e-02 -2.15617213e-02 -1.57968290e-02  3.31748500e-02\n -8.01364630e-02 -1.54115604e-02 -5.74465394e-02  1.44827422e-02\n  3.75399105e-02 -9.97637510e-02 -8.92189424e-03 -6.80584759e-02\n  5.85165992e-02 -3.27328257e-02 -2.40224670e-03 -6.30809413e-03\n  4.79136631e-02 -8.28514248e-02 -2.71539837e-02 -4.32533724e-03\n  2.57455055e-02 -3.27681564e-02  2.09331606e-02 -7.94779658e-02\n  1.91955995e-02 -1.16449483e-02  9.50381905e-03 -4.35635448e-02\n -3.66505608e-02 -9.70793590e-02  8.94266088e-03 -1.46270189e-02\n  5.45645058e-02  6.92140907e-02  1.05012514e-01  1.10859908e-01\n -1.34864496e-02  8.77497811e-03 -1.14636088e-03  1.05595537e-01\n -3.30545902e-02  1.49801029e-02 -7.64259622e-02  4.41714600e-02\n  8.06646571e-02  3.79375294e-02 -1.73761938e-02  4.10951115e-02\n -2.40345728e-02 -4.80216146e-02  1.50006134e-02  3.03007979e-02\n  4.40820400e-03 -1.10763662e-01  5.87852262e-02  5.47064468e-02\n  8.96652974e-03 -4.55786325e-02 -4.77992520e-02  8.83814991e-02\n -1.86152514e-02  2.07291674e-02 -2.19885390e-02  7.60801435e-02\n  1.60370134e-02 -1.16604425e-01  1.25039130e-01 -7.68829416e-03\n  3.03482655e-02 -1.52714467e-02 -6.32316098e-02 -2.49990767e-32\n -8.10584351e-02 -5.51191941e-02 -1.33699607e-02 -5.99329509e-02\n  1.10146608e-02  2.59977542e-02  3.60029563e-02  4.94823698e-03\n  1.81742187e-03 -7.88456053e-02 -5.46012260e-02 -3.52930725e-02\n -6.31590514e-03  6.83288723e-02  1.65331811e-02 -8.12145844e-02\n  5.00020897e-03  1.31413490e-01 -4.67871949e-02 -5.32843694e-02\n  6.42249137e-02 -5.45797348e-02 -4.81015071e-02  2.70939860e-02\n  8.49388167e-02 -5.11554908e-03  8.52151886e-02  4.48352210e-02\n -9.25948396e-02  8.05961993e-03  2.34440435e-02  4.24520262e-02\n -5.95207997e-02  1.05523877e-02 -6.87899217e-02  6.73988950e-04\n  4.62167524e-02 -6.29213499e-03  3.83899137e-02  2.46826862e-03\n -9.38247442e-02  5.74741811e-02  7.89214969e-02 -2.18204409e-02\n -4.18462045e-02 -5.63514270e-02 -4.13206369e-02  2.18045767e-02\n -9.33824331e-02  3.08046024e-02 -6.42291084e-02 -1.99529938e-02\n  3.61035056e-02 -3.50958668e-02  3.22242267e-02  6.15459308e-02\n  5.70552647e-02  1.59136709e-02 -2.45294236e-02  9.99930948e-02\n  5.59421070e-02 -4.10363302e-02 -6.51615858e-02  2.00894196e-02\n  4.90734242e-02  3.07649057e-02 -5.85500039e-02 -5.81286289e-03\n  3.74067612e-02  4.96496335e-02 -6.38445318e-02 -2.64049228e-03\n  5.88807352e-02 -4.38631736e-02  6.60317689e-02 -7.83692747e-02\n  6.36432245e-02  6.92375982e-03 -8.18328261e-02 -3.14816535e-02\n -3.57159995e-03  1.01911895e-01 -5.81695698e-02 -2.84043532e-02\n  1.21233072e-02  2.11808947e-03 -4.04892825e-02 -5.31520732e-02\n -1.43812383e-02  3.91903594e-02 -4.59962673e-02 -2.05652090e-03\n  6.13800529e-03  9.19524431e-02  1.95201077e-02  1.56344819e-32\n  2.62332689e-02  9.64797139e-02 -6.58232346e-02  4.79708798e-02\n  8.70390162e-02  4.03307192e-02  1.44299017e-02 -4.76208329e-02\n -8.86885263e-03  1.93300974e-02 -1.29635194e-02  4.97945696e-02\n -6.92616478e-02  3.16582248e-02 -3.13160531e-02 -3.00070457e-02\n -4.07414045e-03 -1.46255242e-02 -1.23309959e-02  2.74193808e-02\n  8.34065750e-02  6.97516724e-02 -1.05787516e-01  8.78470689e-02\n  5.59022604e-03 -1.86683554e-02 -6.24801479e-02 -3.62283085e-03\n -3.38804089e-02  4.26130183e-02 -3.24046053e-02 -9.78928655e-02\n  1.34582082e-02  4.51984964e-02 -4.52558361e-02 -1.61163528e-02\n  8.62949863e-02  2.88820770e-02 -8.69687740e-03  1.49755567e-01\n  3.60441692e-02  2.37741433e-02 -3.88362929e-02  5.74692413e-02\n -2.12660283e-02 -4.92212828e-03 -7.09291920e-03 -5.32866530e-02\n -8.20563212e-02  4.31007147e-02 -3.67642753e-02 -2.71880403e-02\n -1.35272190e-01 -2.56683771e-02 -2.91683804e-02 -8.94128904e-02\n  1.41426036e-02  7.27049867e-03 -7.77577385e-02 -9.60373878e-03\n -4.91313078e-02  5.92100918e-02 -2.87620779e-02 -1.12885237e-02\n -2.84832139e-02 -8.75003636e-03  1.74761582e-02  4.95307334e-02\n  3.17867659e-02  3.20893824e-02 -8.73306543e-02 -7.09946547e-03\n  5.87638766e-02 -6.80620433e-04  3.69722918e-02 -2.14158613e-02\n  9.12269898e-05 -1.07634766e-02 -5.68082482e-02 -2.79051084e-02\n -1.05843835e-01 -9.68965178e-04  1.14391912e-02 -9.73234884e-03\n -4.10722941e-02  3.72072794e-02  4.89398018e-02  4.51456420e-02\n  1.92308407e-02 -1.15438122e-02  5.01310313e-03  2.97262445e-02\n  6.92122504e-02  1.63906701e-02  8.69887974e-03 -4.69932324e-08\n  9.97946039e-03 -5.11728935e-02  7.04231411e-02  6.84351921e-02\n  3.95479836e-02  1.35890659e-04 -7.60001987e-02  4.00973186e-02\n -3.73462215e-02 -5.88455470e-03  1.22180879e-01  8.05513375e-03\n -1.34176379e-02  1.23288482e-02  2.55202223e-02  1.09683415e-02\n  6.05691748e-04 -2.16499381e-02 -5.05288541e-02 -1.30556244e-02\n  1.05004041e-02  1.00654748e-03 -3.34202424e-02 -1.19563034e-02\n  3.54323722e-02 -7.30695054e-02 -1.92586631e-02  6.82982504e-02\n -5.41706644e-02 -3.45374532e-02  5.45378961e-02  2.30299924e-02\n  1.27890157e-02  2.67073996e-02  2.77423523e-02  1.66754369e-02\n -9.89085436e-03 -1.50999734e-02  1.57295931e-02  1.33830786e-01\n  4.96073859e-03 -5.15575474e-03  2.67172903e-02  9.28949378e-03\n  5.75693548e-02 -3.65180746e-02 -1.39185488e-01 -5.01696169e-02\n  4.19337079e-02 -7.75044411e-02 -4.21275012e-02 -2.39885282e-02\n -6.29835725e-02  7.19865784e-02  1.34467065e-01 -8.73646326e-03\n -7.97656830e-03 -6.91411272e-02  3.03547792e-02  6.15586117e-02\n -2.00269022e-03 -6.09333143e-02 -6.89559132e-02 -6.41390383e-02]'}

In [64]:
import torch
import numpy as np
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
for item in data:
    item['embedding'] = np.fromstring(item['embedding'].strip('[]'), sep=' ')

In [66]:
embeddings = np.array([item["embedding"] for item in data])
embeddings_df = pd.DataFrame(embeddings)
print(embeddings_df.shape)  # should be (153, 384)

(153, 384)

153 rows x 384 dimensions — one embedding vector per chunk.

In [67]:
from time import perf_counter as timer

query = "attentions in models datas"
embeddings_tensor = torch.tensor(np.array(embeddings), dtype=torch.float32)
query_embedding = model.encode(query, device=device)

start = timer()
dot_product = util.dot_score(a=query_embedding, b=embeddings_tensor)[0]
end = timer()
print(f"[INFO]: time it take {(end-start):.5f} seconds")

dot_topk = torch.topk(dot_product, 3)
dot_topk

[INFO]: time it take 0.00033 seconds

torch.return_types.topk(
values=tensor([0.4049, 0.3879, 0.3805]),
indices=tensor([113, 119,  17]))

In [68]:
# just test what idx.item() do
[idx.item() for idx in dot_topk.indices]

#it turn tensor to scaller

[113, 119, 17]

In [69]:
# Show the top-k matching paragraphs
for score, idx in zip(dot_topk.values, dot_topk.indices):
    print(f"Score: {score:.4f} | Page: {data[idx.item()]['page_number']}")
    print(data[idx.item()]['paragraphe'])
    print("-" * 120)

Score: 0.4049 | Page: 38
In The Thirty-eighth Annual Conference on Neural Information Processing Systems.Y. He, S. Li, J. Liu, Y. Tan, W. Wang, H. Huang, X. Bu, H. Guo, C. Hu, B. Zheng, et al.Chi- nese simpleqa: A chinese factuality evaluation for large language models.arXiv preprint arXiv:2411.07140, 2024.D. Hendrycks, C. Burns, S. Basart, A. Zou, M. Mazeika, D. Song, and J. Steinhardt.Measuring massive multitask language understanding.arXiv preprint arXiv:2009.03300, 2020.38
------------------------------------------------------------------------------------------------------------------------
Score: 0.3879 | Page: 40
Y. Leviathan, M. Kalman, and Y. Matias.Fast inference from transformers via speculative decoding.In International Conference on Machine Learning, ICML 2023, 23-29 July 2023, Honolulu, Hawaii, USA, volume 202 of Proceedings of Machine Learning Research, pages 19274–19286.PMLR, 2023.URL https://proceedings.mlr.press/v202/leviathan23 a.html.H. Li, Y. Zhang, F. Koto, Y. Yang, H. Zhao, Y. Gong, N. Duan, and T. Baldwin.CMMLU: Measur- ing massive multitask language understanding in Chinese.arXiv preprint arXiv:2306.09212, 2023.S. Li and T. Hoefler.Chimera: efficiently training large-scale neural networks with bidirectional pipelines.
------------------------------------------------------------------------------------------------------------------------
Score: 0.3805 | Page: 8
where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vector for keys and values; 𝑑𝑐(≪𝑑ℎ𝑛ℎ) indicates the KV compression dimension; 𝑊𝐷𝐾𝑉∈R𝑑𝑐×𝑑denotes the down-projection matrix; 𝑊𝑈𝐾,𝑊𝑈𝑉∈R𝑑ℎ𝑛ℎ×𝑑𝑐 are the up-projection matrices for keys and values, respectively; 𝑊𝐾𝑅∈R𝑑𝑅 ℎ×𝑑is the matrix used to produce the decoupled key that carries Rotary Positional Embedding (RoPE) (Su et al.,2024); RoPE(·) denotes the operation that applies RoPE matrices; and [·; ·] denotes concatenation.Note that for MLA, only the blue-boxed vectors (i.e., c𝐾𝑉 𝑡 and k𝑅 𝑡) need to be cached during generation, which results in significantly reduced KV cache while maintaining performance comparable to standard Multi-Head Attention (MHA) (Vaswani et al.,2017).For the attention queries, we also perform a low-rank compression, which can reduce the activation memory during training: c𝑄 𝑡= 𝑊𝐷𝑄h𝑡, (6) [q𝐶 𝑡,1; q𝐶 𝑡,2; ...; q𝐶 𝑡,𝑛ℎ] = q𝐶 𝑡= 𝑊𝑈𝑄c𝑄 𝑡, (7) [q𝑅 𝑡,1; q𝑅 𝑡,2; ...; q𝑅 𝑡,𝑛ℎ] = q𝑅 𝑡= RoPE(𝑊𝑄𝑅c𝑄 𝑡), (8) q𝑡,𝑖= [q𝐶 𝑡,𝑖; q𝑅 𝑡,𝑖], (9) where c𝑄 𝑡 ∈R𝑑′ 𝑐is the compressed latent vector for queries; 𝑑′ 𝑐(≪𝑑ℎ𝑛ℎ) denotes the query compression dimension; 𝑊𝐷𝑄∈R𝑑′ 𝑐×𝑑,𝑊𝑈𝑄∈R𝑑ℎ𝑛ℎ×𝑑′ 𝑐are the down-projection and up-projection matrices for queries, respectively; and 𝑊𝑄𝑅∈R𝑑𝑅 ℎ𝑛ℎ×𝑑′ 𝑐is the matrix to produce the decoupled queries that carry RoPE.Ultimately, the attention queries (q𝑡,𝑖), keys (k𝑗,𝑖), and values (v𝐶 𝑗,𝑖) are combined to yield the final attention output u𝑡: o𝑡,𝑖= 𝑡∑︁ 𝑗=1 Softmax𝑗( q𝑇 𝑡,𝑖k𝑗,𝑖 √︃ 𝑑ℎ+ 𝑑𝑅 ℎ )v𝐶 𝑗,𝑖, (10) u𝑡= 𝑊𝑂[o𝑡,1; o𝑡,2; ...; o𝑡,𝑛ℎ], (11) where 𝑊𝑂∈R𝑑×𝑑ℎ𝑛ℎdenotes the output projection matrix.2.1.2.DeepSeekMoE with Auxiliary-Loss-Free Load Balancing Basic Architecture of DeepSeekMoE. For Feed-Forward Networks (FFNs), DeepSeek-V3 employs the DeepSeekMoE architecture (Dai et al.,2024).Compared with traditional MoE architectures like GShard (Lepikhin et al.,
------------------------------------------------------------------------------------------------------------------------

# functionalize the query search

In [70]:
def get_answer(query:str,
               embedings_data=embeddings,
               embedding_model: SentenceTransformer=model,
               top_k :int = 5,
               time_taken:bool =True):
    # embed the query
    query_embed= embedding_model.encode(query,convert_to_tensor=True)

    # make sure that data are in the same device (cuda) the GPU in this case
    embedings_data = torch.tensor(np.array(embedings_data), dtype=torch.float32).to('cuda')

    # compare the embedding of query with ather embeddings frome book/dataset
    start = timer()
    dot_product = util.dot_score(a=query_embed, b=embedings_data)[0]
    end = timer()

    if time_taken:
        print(f"[INFO]time {(end-start):.5f}")
    top_results = torch.topk(dot_product,top_k)
    scores=[score.item() for score in top_results[0]]
    indeces =[score.item() for score in top_results[1]]
    # scores,indeces = top_results
    # print(f"{top_results}")
    return scores,indeces

def print_top_Result(query:str,
               embedings_data=embeddings,
               embedding_model: SentenceTransformer=model,
               top_k :int = 5,
               time_taken:bool =True,
               pages_and_chunk=data):
    score,indcis=get_answer(query,embedings_data,embedding_model,top_k,time_taken)

    for s, i in zip(score, indcis):
        print(f"Score: {s:.4f} | Index: {i} | Page_number: {pages_and_chunk[i]['page_number']}\nChunk: {pages_and_chunk[i]["paragraphe"]}")
        print("-"*120)

In [71]:
print_top_Result("names")

[INFO]time 0.00011
Score: 0.2919 | Index: 143 | Page_number: 45
Chunk: Appendix A. Contributions and Acknowledgments Research & Engineering Aixin Liu Bing Xue Bingxuan Wang Bochao Wu Chengda Lu Chenggang Zhao Chengqi Deng Chenyu Zhang* Chong Ruan Damai Dai Daya Guo Dejian Yang Deli Chen Erhang Li Fangyun Lin Fucong Dai Fuli Luo* Guangbo Hao Guanting Chen Guowei Li H. Zhang Han Bao* Hanwei Xu Haocheng Wang* Haowei Zhang Honghui Ding Huajian Xin* Huazuo Gao Hui Qu Jianzhong Guo Jiashi Li Jiawei Wang* Jingchang Chen Jingyang Yuan Junjie Qiu Junlong Li Junxiao Song Kai Dong Kai Hu* Kaige Gao Kang Guan Kexin Huang Kuai Yu Lean Wang Lecong Zhang Liang Zhao Litong Wang Liyue Zhang Mingchuan Zhang Minghua Zhang Minghui Tang Panpan Huang Peiyi Wang Qiancheng Wang Qihao Zhu Qinyu Chen Qiushi Du Ruiqi Ge Ruisong Zhang Ruizhe Pan Runji Wang Runxin Xu Ruoyu Zhang Shanghao Lu Shangyan Zhou Shanhuang Chen Shengfeng Ye Shirong Ma Shiyu Wang Shuiping Yu Shunfeng Zhou Shuting Pan Tao Yun Tian Pei Wangding Zeng Wanjia Zhao* Wen Liu Wenfeng Liang Wenjun Gao Wenqin Yu Wentao Zhang Xiao Bi Xiaodong Liu Xiaohan Wang Xiaokang Chen Xiaokang Zhang Xiaotao Nie Xin Cheng Xin Liu 45
------------------------------------------------------------------------------------------------------------------------
Score: 0.2912 | Index: 21 | Page_number: 9
Chunk: 9
------------------------------------------------------------------------------------------------------------------------
Score: 0.2412 | Index: 144 | Page_number: 46
Chunk: Xin Xie Xingchao Liu Xingkai Yu Xinyu Yang Xinyuan Li Xuecheng Su Xuheng Lin Y.K. Li Y.Q. Wang Y.X. Wei Yang Zhang Yanhong Xu Yao Li Yao Zhao Yaofeng Sun Yaohui Wang Yi Yu Yichao Zhang Yifan Shi Yiliang Xiong Ying He Yishi Piao Yisong Wang Yixuan Tan Yiyang Ma* Yiyuan Liu Yongqiang Guo Yu Wu Yuan Ou Yuduan Wang Yue Gong Yuheng Zou Yujia He Yunfan Xiong Yuxiang Luo Yuxiang You Yuxuan Liu Yuyang Zhou Z.F. Wu Z.Z. Ren Zehui Ren Zhangli Sha Zhe Fu Zhean Xu Zhenda Xie Zhengyan Zhang Zhewen Hao Zhibin Gou Zhicheng Ma Zhigang Yan Zhihong Shao Zhiyu Wu Zhuoshu Li Zihui Gu Zijia Zhu Zijun Liu* Zilin Li Ziwei Xie Ziyang Song Ziyi Gao Zizheng Pan Data Annotation Bei Feng Hui Li J.L. Cai Jiaqi Ni Lei Xu Meng Li Ning Tian R.J. Chen R.L. Jin Ruyi Chen S.S. Li Shuang Zhou Tianyu Sun X.Q. Li Xiangyue Jin Xiaojin Shen Xiaosha Chen Xiaowen Sun Xiaoxiang Wang Xinnan Song Xinyi Zhou Y.X. Zhu Yanhong Xu Yanping Huang Yaohui Li Yi Zheng Yuchen Zhu Yunxian Ma Zhen Huang Zhipeng Xu Zhongyu Zhang Business & Compliance Dongjie Ji 46
------------------------------------------------------------------------------------------------------------------------
Score: 0.2385 | Index: 124 | Page_number: 40
Chunk: on Learning Representation, 2017.40
------------------------------------------------------------------------------------------------------------------------
Score: 0.2361 | Index: 135 | Page_number: 42
Chunk: H. Touvron, L. Martin, K. Stone, P. Albert, A. Almahairi, Y. Babaei, N. Bashlykov, S. Batra, P. Bhargava, S. Bhosale, D. Bikel, L. Blecher, C. Canton-Ferrer, M. Chen, G. Cucurull, D. Esiobu, J. Fernandes, J. Fu, W. Fu, B. Fuller, C. Gao, V. Goswami, N. Goyal, A. Hartshorn, S. Hosseini, 42
------------------------------------------------------------------------------------------------------------------------

In [72]:
# Get GPU available memory
import torch
gpu_memory_bytes = torch.cuda.get_device_properties(0).total_memory
gpu_memory_gb = round(gpu_memory_bytes / (2 ** 30))
print(f"Available GPU memory: {gpu_memory_gb} GB")

Available GPU memory: 15 GB

# This test from tetorial

In [73]:
# Note: the following is Gemma focused, however, there are more and more LLMs of the 2B and 7B size appearing for local use.
if gpu_memory_gb < 5.1:
  print(f"Your available GPU memory is {gpu_memory_gb}GB, you may not have enough memory to run a Gemma LLM locally without quantization.")
elif gpu_memory_gb < 8.1:
  print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in 4-bit precision.")
  use_quantization_config = True
  model_id = "google/gemma-2b-it"
elif gpu_memory_gb < 19.0:
  print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in float16 or Gemma 7B in 4-bit precision.")
  use_quantization_config = False
  model_id = "google/gemma-2b-it"
elif gpu_memory_gb > 19.0:
  print(f"GPU memory: {gpu_memory_gb} | Recommend model: Gemma 7B in 4-bit or float16 precision.")
  use_quantization_config = False
  model_id = "google/gemma-7b-it"

print(f"use_quantization_config set to: {use_quantization_config}")
print(f"model_id set to: {model_id}")

GPU memory: 15 | Recommended model: Gemma 2B in float16 or Gemma 7B in 4-bit precision.
use_quantization_config set to: False
model_id set to: google/gemma-2b-it

In [74]:
from google.colab import userdata
from huggingface_hub import login

login(token=userdata.get('HF_TOKEN'))

In [75]:
import torch
from transformers import AutoTokenizer,AutoModelForCausalLM,BitsAndBytesConfig
from transformers.utils import is_flash_attn_2_available

#configer quntization configruation
quantize_config = BitsAndBytesConfig(load_in_4bit=True,
                                     bnb_4bit_compute_dtype=torch.float16)

if (is_flash_attn_2_available()) and (torch.cuda.get_device_capability()[0] >=8):
  attention_imp = "flash_attention_2"
else :
  attention_imp ="sdpa"

model_id = "google/gemma-2b-it"

#toknization
toknizer= AutoTokenizer.from_pretrained(pretrained_model_name_or_path=model_id)