In [1]:
!nvidia-smi

Mon May 18 14:58:24 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   32C    P8              3W /   35W |     953MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2512    C+G   ...cwf2zmmt10c\PSExpressCore.exe      N/A      |
|    0   N/A  N/A           10156    C+G   C:\Windows\explorer.exe               N/A      |
|    0   N/A  N/A           10368    C+G   ...2txyewy\CrossDeviceResume.exe      N/A      |
|    0   N/A  N/A           11224    C+G   ...ms\Microsoft VS Code\Code.exe      N/A      |
|    0   N/A  N/A           11392    C+G   ...y\StartMenuExperienceHost.exe      N/A      |
|    0   N/A  N/A           11416    C+G   ..._cw5n1h2txyewy\SearchHost.exe      N/A      |
|    0   N/A  N/A           13004    C+G   ....0.3967.70\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           13228    C+G   ....0.3967.54\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           14084    C+G   ...t\Edge\Application\msedge.exe      N/A      |
|    0   N/A  N/A           14752    C+G   ...App_cw5n1h2txyewy\LockApp.exe      N/A      |
|    0   N/A  N/A           15216    C+G   ...5n1h2txyewy\TextInputHost.exe      N/A      |
|    0   N/A  N/A           16088    C+G   ...lot\Application\mscopilot.exe      N/A      |
|    0   N/A  N/A           17632    C+G   ...crosoft OneDrive\OneDrive.exe      N/A      |
|    0   N/A  N/A           17756    C+G   ...SnippingTool\SnippingTool.exe      N/A      |
|    0   N/A  N/A           19236    C+G   ...4__8wekyb3d8bbwe\ms-teams.exe      N/A      |
|    0   N/A  N/A           19568    C+G   ...indows\System32\ShellHost.exe      N/A      |
|    0   N/A  N/A           19788    C+G   ....0.3967.54\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           19952    C+G   ...8wekyb3d8bbwe\M365Copilot.exe      N/A      |
|    0   N/A  N/A           23456    C+G   ...t\Edge\Application\msedge.exe      N/A      |
|    0   N/A  N/A           26312    C+G   ...4__8wekyb3d8bbwe\ms-teams.exe      N/A      |
|    0   N/A  N/A           27080    C+G   ...xyewy\ShellExperienceHost.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [2]:
import os
import requests

url = r"https://arxiv.org/pdf/2412.19437"
pdf_path = os.path.join(os.getcwd(), "Data_file.pdf")

if not os.path.exists(pdf_path):
    response = requests.get(url)
    if response.status_code == 200:
        with open(pdf_path, "wb") as f:
            f.write(response.content)
        print(f"[INFO] the file is downloaded at : {pdf_path}")
else:
    print(f"[INFO] file exist : {pdf_path} ")

[INFO] file exist : c:\Users\Tarek Hamada Hussien\Downloads\s24153dw\Mohamed diaa test files\Self_traine_RAG_Model\Data_file.pdf

In [3]:
import fitz  # PyMuPDF

def clean_text(text: str):
    text = text.replace("\n", " ").strip()
    return text

def open_pdf(file_path: str):
    document = fitz.open(file_path)
    pages_and_texts = []
    for page_num, page in enumerate(document):
        text = page.get_text()
        cleaned_text = clean_text(text)
        pages_and_texts.append({
            "text_of_page": cleaned_text,
            "page_count_char": len(cleaned_text),
            "page_count_word": len(cleaned_text.split(" ")),
            "page_count_sentences": len(cleaned_text.split(". ")),
            "tokens_num": len(cleaned_text) // 4,
            "page_number": page_num + 1
        })
    return pages_and_texts

pages_and_texts = open_pdf("Data_file.pdf")
pages_and_texts[3]

{'text_of_page': '1. Introduction In recent years, Large Language Models (LLMs) have been undergoing rapid iteration and evolution (Anthropic, 2024; Google, 2024; OpenAI, 2024a), progressively diminishing the gap to- wards Artificial General Intelligence (AGI). Beyond closed-source models, open-source models, including DeepSeek series (DeepSeek-AI, 2024a,b,c; Guo et al., 2024), LLaMA series (AI@Meta, 2024a,b; Touvron et al., 2023a,b), Qwen series (Qwen, 2023, 2024a,b), and Mistral series (Jiang et al., 2023; Mistral, 2024), are also making significant strides, endeavoring to close the gap with their closed-source counterparts. To further push the boundaries of open-source model capa- bilities, we scale up our models and introduce DeepSeek-V3, a large Mixture-of-Experts (MoE) model with 671B parameters, of which 37B are activated for each token. With a forward-looking perspective, we consistently strive for strong model performance and economical costs. Therefore, in terms of architecture, DeepSeek-V3 still adopts Multi-head Latent Attention (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for cost-effective training. These two architectures have been validated in DeepSeek- V2 (DeepSeek-AI, 2024c), demonstrating their capability to maintain robust model performance while achieving efficient training and inference. Beyond the basic architecture, we implement two additional strategies to further enhance the model capabilities. Firstly, DeepSeek-V3 pi- oneers an auxiliary-loss-free strategy (Wang et al., 2024a) for load balancing, with the aim of minimizing the adverse impact on model performance that arises from the effort to encourage load balancing. Secondly, DeepSeek-V3 employs a multi-token prediction training objective, which we have observed to enhance the overall performance on evaluation benchmarks. In order to achieve efficient training, we support the FP8 mixed precision training and implement comprehensive optimizations for the training framework. Low-precision training has emerged as a promising solution for efficient training (Dettmers et al., 2022; Kalamkar et al., 2019; Narang et al., 2017; Peng et al., 2023b), its evolution being closely tied to advancements in hardware capabilities (Luo et al., 2024; Micikevicius et al., 2022; Rouhani et al., 2023a). In this work, we introduce an FP8 mixed precision training framework and, for the first time, validate its effectiveness on an extremely large-scale model. Through the support for FP8 computation and storage, we achieve both accelerated training and reduced GPU memory usage. As for the training framework, we design the DualPipe algorithm for efficient pipeline parallelism, which has fewer pipeline bubbles and hides most of the communication during training through computation-communication overlap. This overlap ensures that, as the model further scales up, as long as we maintain a constant computation-to-communication ratio, we can still employ fine-grained experts across nodes while achieving a near-zero all-to-all communication overhead. In addition, we also develop efficient cross-node all-to-all communication kernels to fully utilize InfiniBand (IB) and NVLink bandwidths. Furthermore, we meticulously optimize the memory footprint, making it possible to train DeepSeek-V3 without using costly tensor parallelism. Combining these efforts, we achieve high training efficiency. During pre-training, we train DeepSeek-V3 on 14.8T high-quality and diverse tokens. The pre-training process is remarkably stable. Throughout the entire training process, we did not encounter any irrecoverable loss spikes or have to roll back. Next, we conduct a two-stage context length extension for DeepSeek-V3. In the first stage, the maximum context length is extended to 32K, and in the second stage, it is further extended to 128K. Following this, we conduct post-training, including Supervised Fine-Tuning (SFT) and Reinforcement Learning (RL) on the base model of DeepSeek-V3, to align it with human preferences and further unlock its potential. During the post-training stage, we distill the reasoning capability from the DeepSeek- R1 series of models, and meanwhile carefully maintain the balance between model accuracy 4',
 'page_count_char': 4248,
 'page_count_word': 594,
 'page_count_sentences': 26,
 'tokens_num': 1062,
 'page_number': 4}

In [4]:
import pandas as pd
df = pd.DataFrame(pages_and_texts)
df.head(10)

,text_of_page,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,1817,238,11,454,1
1,Contents 1 Introduction 4 2 Architecture 6 2.1...,2634,919,766,658,2
2,4.5.3 Batch-Wise Load Balance VS. Sequence-Wis...,1715,572,462,428,3
3,"1. Introduction In recent years, Large Languag...",4248,594,26,1062,4
4,Training Costs Pre-Training Context Extension ...,3287,468,21,821,5
5,verification and reflection patterns of R1 int...,3475,457,23,868,6
6,… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ...,1557,262,8,389,7
7,where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vecto...,2236,353,9,559,8
8,where 𝑁𝑠and 𝑁𝑟denote the numbers of shared exp...,2901,455,17,725,9
9,Main Model (Next Token Prediction) Embedding L...,2904,451,23,726,10

In [5]:
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
count,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00
std,799.86,178.18,124.63,199.99,15.44
min,699.00,99.00,1.00,174.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00
50%,2992.00,457.00,23.00,748.00,27.00
75%,3281.00,516.00,29.00,820.00,40.00
max,4248.00,919.00,766.00,1062.00,53.00

# Turn text to sentences

In [6]:
from spacy.lang.en import English

nlp = English()
nlp.add_pipe("sentencizer")

semtemces = "this my name . hellow mr.ahmed . what is your name ?"
doc = nlp(semtemces)
list(doc.sents)

[this my name ., hellow mr.ahmed ., what is your name ?]

# Now try the `data`

In [7]:
for page in pages_and_texts:
    page["sentences"] = list(nlp(page["text_of_page"]).sents)
    page["sentences_num"] = len(page["sentences"])

for page in pages_and_texts:
    page["sentences"] = [str(s) for s in page["sentences"]]

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25}

In [8]:
pages_and_texts[5]["sentences"][6]

'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.'

In [9]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num
count,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94
std,799.86,178.18,124.63,199.99,15.44,14.44
min,699.00,99.00,1.00,174.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00

In [10]:
test = list(range(1, 25))
slice_size = 10
x = [test[i:i+slice_size] for i in range(0, len(test), slice_size)]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24]]

In [11]:
def chunker(input_list: list[str], slice_size: int = slice_size) -> list[list[str]]:
    return [input_list[i:i+slice_size] for i in range(0, len(input_list), slice_size)]

for page in pages_and_texts:
    page["sentences_chunk"] = chunker(page["sentences"])
    page["sentences_chunk_num"] = len(page["sentences_chunk"])

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25,
 'sentences_chunk': [['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
   'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
   'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
   'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
   '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
   'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
   'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
   'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
   '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
   'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.'],
  ['In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
   'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
   'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
   'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
   'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
   '2.',
   'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
   '2024) for economical training.',
   'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
   'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).'],
  ['2.1.',
   'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
   '2017) framework.',
   'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
   'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6']],
 'sentences_chunk_num': 3}

In [12]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num,sentences_chunk_num
count,53.00,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94,2.89
std,799.86,178.18,124.63,199.99,15.44,14.44,1.40
min,699.00,99.00,1.00,174.00,1.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00,2.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00,3.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00,3.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00,6.00

In [13]:
pages_and_chunk = []
for page in pages_and_texts:
    for chunk in page["sentences_chunk"]:
        chunk_dict = {}
        paragragh = "".join(chunk).replace("  ", " ").strip()
        chunk_dict["paragraphe"] = paragragh
        chunk_dict["word_count"] = len(paragragh.split(" "))
        chunk_dict["char_count"] = len(paragragh)
        chunk_dict["tokens_count"] = len(paragragh) // 4
        chunk_dict["sentence_count"] = len(chunk)
        chunk_dict["page_number"] = page["page_number"]
        pages_and_chunk.append(chunk_dict)

pages_and_chunk[5], len(pages_and_chunk), len(pages_and_texts)

({'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
  'word_count': 298,
  'char_count': 830,
  'tokens_count': 207,
  'sentence_count': 10,
  'page_number': 3},
 153,
 53)

In [14]:
df = pd.DataFrame(pages_and_chunk)
df.describe().round(2)

       word_count  char_count  tokens_count  sentence_count  page_number
count      153.00      153.00        153.00          153.00       153.00
mean       157.03      974.48        243.26            8.29        26.52
std        145.88      584.64        146.14            2.95        13.86
min          1.00        1.00          0.00            1.00         1.00
25%         74.00      572.00        143.00            7.00        15.00
50%        134.00      912.00        228.00           10.00        28.00
75%        191.00     1301.00        325.00           10.00        39.00
max        877.00     2975.00        743.00           10.00        53.00

In [15]:
df[df["word_count"] < 4]

,paragraphe,word_count,char_count,tokens_count,sentence_count,page_number
21,9,1,1,0,1,9

In [16]:
filtered_chunks = [chunk for chunk in pages_and_chunk if chunk["tokens_count"] >= 30]
filtered_chunks[111]

{'paragraphe': 'A study of bfloat16 for deep learning training.arXiv preprint arXiv:1905.12322, 2019.S. Krishna, K. Krishna, A. Mohananey, S. Schwarcz, A. Stambler, S. Upadhyay, and M. Faruqui.Fact, fetch, and reason: A unified evaluation of retrieval-augmented generation.CoRR, abs/2409.12941, 2024.doi: 10.48550/ARXIV.2409.12941.URL https://doi.org/10.485 50/arXiv.2409.12941.T. Kwiatkowski, J. Palomaki, O. Redfield, M. Collins, A. P. Parikh, C. Alberti, D. Epstein, I. Polosukhin, J. Devlin, K. Lee, K. Toutanova, L. Jones, M. Kelcey, M. Chang, A. M. Dai, J. Uszkoreit, Q. Le, and S. Petrov.Natural questions: a benchmark for question answering research.Trans.',
 'word_count': 84,
 'char_count': 648,
 'tokens_count': 162,
 'sentence_count': 10,
 'page_number': 39}

In [17]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer("all-MiniLM-L6-v2")

c:\Users\Tarek Hamada Hussien\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6585.37it/s]

In [18]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True

In [19]:
test_set = ["my name", "her name", "the naem"]
embedding = model.encode(test_set)
embedding = dict(zip(test_set, embedding))
embedding, embedding["my name"].shape

({'my name': array([-1.11268580e-01,  3.23448554e-02, -3.83406095e-02,  2.23898105e-02,
         -4.03140672e-02, -5.62008582e-02,  2.33329952e-01,  3.92086990e-02,
         -1.01079093e-02, -6.38170168e-02,  1.64090004e-02, -3.45564187e-02,
          4.02090475e-02, -7.56014735e-02, -8.34890269e-03,  2.65754685e-02,
         -1.42914746e-02,  6.17222628e-03, -8.46135467e-02, -7.72886276e-02,
         -4.17721942e-02,  6.27690554e-02, -3.23730674e-05, -2.02984791e-02,
         -8.92573446e-02,  6.10294519e-03, -3.12835686e-02,  9.11155790e-02,
         -3.69638763e-02, -1.61543325e-01, -3.80753976e-04,  7.48011237e-03,
          9.98783186e-02,  5.72648905e-02, -4.66821576e-03, -4.17357869e-02,
         -1.26731113e-01, -2.11647209e-02,  5.62064126e-02, -1.07810786e-02,
         -4.70564188e-03, -1.19292267e-01,  2.42646392e-02,  5.37947984e-03,
          7.11641647e-03,  7.88039062e-03,  6.28899375e-04,  2.45067067e-02,
          1.61230173e-02,  9.47958305e-02, -9.59324911e-02, -8.88254270e-02,
         -5.96604496e-02,  1.89628843e-02,  1.31215192e-02, -7.77191743e-02,
          2.44200807e-02,  5.09176999e-02, -3.09438957e-03,  2.27700104e-04,
          4.02659327e-02,  1.79442037e-02, -7.26719722e-02,  3.98123786e-02,
          1.57935694e-02,  8.13503191e-03, -6.94841985e-03,  1.39237260e-02,
          4.64229239e-03, -9.63738840e-03, -2.38478761e-02, -6.72974251e-03,
          7.07241818e-02, -3.35569754e-02, -1.96108017e-02, -1.45387501e-02,
          1.61476377e-02, -1.77206248e-02, -1.31568927e-02,  6.13829419e-02,
         -8.46485421e-02,  4.43953974e-03, -9.70008969e-02, -8.54696240e-03,
         -2.76288688e-02,  4.83488552e-02,  3.65964659e-02, -3.85117345e-02,
         -2.87032239e-02, -5.48662292e-03,  2.66992766e-03, -7.49976262e-02,
          2.27707271e-02, -3.73108499e-03, -2.44773272e-02, -5.23779169e-03,
         -3.77407356e-04, -4.05308232e-02, -3.87832448e-02,  1.85519427e-01,
         -6.50252551e-02,  3.38606313e-02, -5.62591776e-02,  7.47068971e-02,
         -7.21327262e-03, -8.54289532e-03, -5.87107874e-02,  5.19503327e-03,
          5.03454590e-03, -2.29809135e-02, -5.23379669e-02, -2.39632558e-02,
         -5.20041585e-02,  4.00795862e-02,  3.42810415e-02,  7.10861534e-02,
          2.96652270e-03, -2.60684248e-02,  3.05781867e-02, -2.95662098e-02,
          4.49147038e-02,  2.99034696e-02, -8.65571201e-02, -1.93888452e-02,
         -2.02057566e-02,  1.09100686e-02, -1.28697988e-03, -3.38961106e-33,
          5.94929978e-03,  1.89252961e-02, -4.11679241e-04,  1.40347689e-01,
          2.08697207e-02,  1.44509971e-02, -5.77048995e-02,  7.57384580e-03,
         -3.34116407e-02, -4.86456382e-04,  1.18632335e-02,  1.23980064e-02,
         -2.82271393e-02,  6.32571355e-02,  2.87447143e-02,  3.98513861e-02,
         -2.19962765e-02,  5.86499311e-02, -3.66561897e-02,  2.81827562e-02,
         -3.64034362e-02,  6.67515546e-02,  3.82383959e-03,  3.85377593e-02,
         -5.31675816e-02, -1.20789573e-01, -1.26687465e-02, -7.43082538e-02,
          3.59357297e-02,  2.43287627e-02, -5.68793975e-02, -1.62085015e-02,
          8.52153003e-02, -1.06991231e-02,  2.98596807e-02, -8.78666714e-02,
         -1.15062194e-02,  1.56422369e-02, -4.40782309e-02,  1.03963725e-01,
         -9.96416435e-03,  1.12467837e-02, -7.92487711e-02,  4.75009270e-02,
         -2.51976568e-02, -1.84205789e-02,  3.58203277e-02,  5.33687025e-02,
         -9.88210738e-02, -1.01148803e-02, -5.02877682e-02,  3.62837017e-02,
         -1.07462861e-01, -1.13403556e-04, -8.78018364e-02,  2.03307234e-02,
         -1.38523336e-03,  9.96502023e-03, -1.05820224e-01, -1.08255688e-02,
         -5.61658386e-03,  3.54209691e-02, -1.99717898e-02,  1.85143836e-02,
          1.84968058e-02, -4.77539450e-02,  7.75206834e-02, -5.72839044e-02,
          2.59806626e-02,  3.01388558e-02, -7.60096535e-02, -5.30696437e-02,
          4.44191787e-03,  4.09771055e-02,  7.15029538e-02,  6.62903115e-03,
         -8.63278098e-03,  5.87880351e-02, -3.33780348e-02, -9.79792327e-03,
          3.39137726e-02, -1.12670539e-02,  2.68001505e-03,  3.78638245e-02,
          2.98797525e-02, -2.79736565e-03, -1.43966833e-02, -3.69952768e-02,
         -1.53700756e-02, -3.44166346e-02, -1.34393811e-01, -1.39014679e-03,
          1.08393155e-01, -2.45960206e-02, -5.27150109e-02,  1.20526971e-33,
         -1.27881849e-02,  4.35465761e-02,  1.87255032e-02,  9.56210420e-02,
          4.67722490e-03, -2.69599799e-02,  5.32099605e-03,  1.07820198e-01,
          1.92448671e-03,  5.60386367e-02, -2.19700690e-02, -8.23150426e-02,
          4.67023486e-03, -2.90251663e-03,  8.16676021e-02,  4.96276692e-02,
          4.06118222e-02, -1.76346418e-03, -4.65383939e-02,  2.63397209e-03,
         -5.90299927e-02,  5.77562712e-02, -1.08629446e-02, -6.16721772e-02,
         -4.12750943e-03,  1.70052797e-02,  3.90952937e-02,  2.52950415e-02,
          7.08593577e-02,  6.80857226e-02,  5.44351758e-03,  2.39246991e-02,
         -1.16943397e-01,  2.93324869e-02, -2.60606948e-02,  6.45446628e-02,
         -1.89389065e-02, -1.98988859e-02,  1.02715604e-02, -3.32670496e-03,
         -1.41808679e-02,  3.20844166e-02, -7.18639269e-02,  1.08568087e-01,
         -1.31832883e-02, -3.98828387e-02, -5.78844808e-02,  3.01687978e-02,
          1.03621464e-02,  4.26096432e-02, -3.35613787e-02, -6.73616007e-02,
         -6.93707317e-02, -3.82362083e-02,  1.17583445e-03,  3.61948349e-02,
          6.44930303e-02,  2.16482673e-02,  9.53720789e-03,  4.65247547e-03,
          1.59357488e-02,  3.41445766e-02,  6.12317249e-02,  7.34104365e-02,
          3.04528587e-02, -1.78817566e-02, -6.13178425e-02, -4.10456955e-02,
         -2.72018500e-02, -4.76149954e-02, -5.27508892e-02,  2.03911848e-02,
         -4.46445271e-02,  2.69611403e-02, -9.46116671e-02,  3.20556872e-02,
          1.63121633e-02,  2.63475683e-02, -2.50775069e-02,  5.37288897e-02,
          3.02446969e-02,  8.66488665e-02, -2.48541292e-02,  3.00488584e-02,
          1.60619766e-02, -2.64488347e-02,  3.59426513e-02,  8.03071856e-02,
         -2.33003795e-02, -3.87402177e-02,  2.93709431e-02,  3.48941013e-02,
         -1.20452791e-02, -1.63013171e-02, -9.69538391e-02, -1.50699115e-08,
          4.22302820e-02,  5.01372255e-02,  3.11900005e-02, -4.23702644e-03,
          5.10957949e-02,  8.86452794e-02, -3.07836104e-03, -2.18302049e-02,
          4.13647629e-02,  6.56359866e-02,  9.79078040e-02,  5.34658059e-02,
          3.15143205e-02,  9.64244269e-03,  9.51067731e-02, -2.79178843e-02,
         -5.68721667e-02,  8.92900024e-03, -4.92045423e-03, -2.21010372e-02,
         -3.58192548e-02, -2.98429057e-02,  8.19764435e-02, -7.19111860e-02,
          4.26655933e-02,  9.13802627e-03,  3.62761356e-02,  9.37117264e-02,
         -5.74504025e-02,  7.81974196e-02,  1.13642039e-02,  1.17897809e-01,
          1.24910166e-02,  6.13725223e-02, -3.99509855e-02, -9.76376468e-04,
          2.87474915e-02,  8.35280567e-02,  5.63312918e-02, -8.02360382e-03,
         -3.31368595e-02,  5.76817393e-02,  9.86445546e-02, -1.26726497e-02,
         -6.93444610e-02,  6.50679171e-02, -2.79169413e-04, -1.52545450e-02,
         -4.63719992e-03, -2.10705642e-02,  8.71943962e-03,  1.70729607e-02,
          2.25879624e-02,  7.89606124e-02,  2.01135650e-02,  4.21369411e-02,
          3.23688239e-02,  5.68195693e-02, -6.11765124e-02, -5.45439497e-02,
          7.75277615e-02,  5.29304380e-03, -9.12822783e-02,  1.33656869e-02],
        dtype=float32),
  'her name': array([-1.08516812e-01,  1.40265273e-02, -1.97903439e-02,  4.03933004e-02,
         -3.66050489e-02, -1.11381628e-03,  1.42931893e-01,  4.01251987e-02,
         -9.60895885e-03, -7.14013427e-02,  2.60373130e-02, -9.37794000e-02,
         -1.03091663e-02, -7.65828341e-02, -4.02911492e-02,  7.74797201e-02,
          3.67319547e-02,  3.94580737e-02, -9.53144208e-02, -5.77405803e-02,
         -2.17363406e-02, -2.40650661e-02,  3.27846743e-02,  4.04388942e-02,
         -3.74304131e-02,  2.06179172e-03, -5.38016893e-02,  1.28083304e-02,
         -3.16409580e-02, -1.22112058e-01,  1.27528682e-02, -1.95463598e-02,
          4.58518155e-02,  7.62845501e-02, -1.12640094e-02,  3.25133465e-02,
         -7.22715184e-02,  4.53228094e-02,  2.71108281e-02, -1.35518443e-02,
         -1.94001030e-02, -1.14641204e-01, -4.72653061e-02, -4.64220382e-02,
         -3.94386649e-02, -4.94745523e-02,  5.11805527e-02,  3.23776193e-02,
          2.72550024e-02, -2.67372094e-02, -6.49755672e-02, -5.32744452e-02,
         -1.18825607e-01,  2.55614868e-03,  7.93129876e-02, -2.25096028e-02,
          5.34011386e-02,  5.47846928e-02,  3.82738300e-02,  1.02928197e-02,
          6.06006570e-02,  5.18807359e-02, -7.12646618e-02,  4.85623106e-02,
         -5.31428307e-03, -9.10788868e-03,  3.76583934e-02, -4.69222218e-02,
          3.90819572e-02,  6.33172365e-03,  2.00461615e-02,  3.55321281e-02,
         -1.72343792e-03, -3.88699099e-02,  2.61441935e-02,  1.99030954e-02,
          7.56488740e-02,  1.09233484e-02,  2.11198144e-02,  6.88376501e-02,
         -7.15844557e-02,  1.77171659e-02,  5.93788747e-04,  1.94032826e-02,
          4.28240793e-03,  4.30800878e-02, -3.16122361e-02, -2.20458470e-02,
         -2.73831841e-02, -5.10557108e-02, -4.97698188e-02, -6.01557046e-02,
          3.76523137e-02, -1.17023624e-02, -2.06190012e-02, -2.93967575e-02,
         -2.07708254e-02, -2.78658569e-02, -1.51966698e-02,  1.78603172e-01,
         -9.23539698e-02,  1.01476826e-01, -9.04797483e-03,  9.42860916e-02,
         -3.34173329e-02, -5.97187504e-02,  4.86570969e-02, -5.82067808e-03,
         -3.47071290e-02, -1.29232397e-02, -1.64540485e-03, -1.47645576e-02,
         -9.90035981e-02, -5.19064581e-03,  3.52939591e-02,  3.13790701e-02,
          4.73542027e-02, -1.23639675e-02,  2.38937978e-02, -9.74604562e-02,
          4.04632762e-02, -4.96868975e-02, -4.79107834e-02, -2.40672808e-02,
         -5.60440533e-02, -2.87502855e-02,  2.83523202e-02, -3.16461042e-33,
         -3.55150737e-02,  2.95765717e-02,  8.10843781e-02,  8.34557042e-02,
          5.95203601e-02,  2.11190376e-02,  1.59793049e-02,  1.16895102e-02,
          3.46239097e-03, -2.01443415e-02, -2.27793632e-03, -8.82628337e-02,
         -5.42954691e-02, -8.02553743e-02,  1.01886183e-01,  1.27110286e-02,
         -3.21838781e-02,  7.77680948e-02, -7.86051005e-02,  5.41978478e-02,
          4.28526029e-02,  8.47249776e-02,  2.49308236e-02,  5.01613729e-02,
         -3.17426324e-02, -9.03306678e-02,  7.80700073e-02,  1.17246043e-02,
          1.61149749e-03,  3.63856107e-02, -2.68512331e-02,  1.80520568e-04,
          8.83467570e-02, -1.63772907e-02,  5.22143021e-02, -4.44410853e-02,
         -5.81526849e-03, -1.12066604e-02,  3.63270962e-03,  7.74848089e-02,
          2.00558361e-02, -1.65880993e-02,  2.73299292e-02,  1.84894484e-02,
         -1.34903476e-01,  4.32648212e-02,  5.84352911e-02,  1.03550954e-02,
          4.11863960e-02, -6.93635884e-05, -9.41860825e-02,  3.53580154e-02,
         -1.00075282e-01,  5.65286316e-02, -6.15794919e-02,  8.11114460e-02,
          3.31929848e-02, -1.32226804e-02, -1.87827107e-02, -3.98739874e-02,
          1.16541451e-02,  2.19121352e-02, -6.86919019e-02,  9.83212050e-03,
          4.92209382e-02, -5.10650650e-02,  2.85478421e-02, -1.02851249e-01,
          3.24431807e-02,  1.23117333e-02, -1.13674067e-01,  1.87592655e-02,
          2.25785933e-02,  4.31681834e-02, -5.41480482e-02,  2.82280240e-02,
          3.29296701e-02, -2.86127534e-02, -3.13659310e-02, -5.98064950e-03,
          1.17117204e-02,  3.75699997e-02, -2.54160855e-02,  8.43513608e-02,
         -4.38703299e-02, -3.62573355e-03, -2.06886567e-02, -1.42937778e-02,
         -3.48394066e-02, -7.15545863e-02, -6.16803393e-02,  2.06668731e-02,
          7.54759163e-02, -4.97288778e-02, -2.12219935e-02,  1.31706189e-33,
         -5.28453290e-03,  1.54752620e-02, -4.34725024e-02,  6.07264563e-02,
          5.43512106e-02, -1.14345299e-02, -1.48576940e-03,  1.01141520e-01,
         -4.60984884e-03, -1.25182820e-02,  2.76288763e-02, -1.24480255e-01,
          1.22275706e-02, -1.49447555e-02,  6.50415048e-02,  6.65459409e-02,
          8.23930427e-02, -6.69729486e-02, -3.24602872e-02, -6.40190020e-02,
         -9.25135389e-02,  1.08706467e-02,  1.46333948e-02, -7.67764375e-02,
         -2.50701923e-02,  2.24010255e-02,  9.63629931e-02, -2.89402180e-03,
         -4.82729077e-02, -1.27476947e-02,  3.41591947e-02,  1.86355244e-02,
         -7.29230791e-02,  6.13724701e-02, -3.97584513e-02,  4.89615314e-02,
          2.06597745e-02, -4.81187999e-02,  2.89742295e-02,  2.80811824e-02,
          4.12800424e-02,  8.84455722e-03, -2.17010826e-02,  1.02579288e-01,
          2.75865085e-02,  2.12726314e-02, -1.27491001e-02,  4.89049889e-02,
          8.61027688e-02,  2.64374111e-02, -2.06164308e-02, -7.87166804e-02,
         -2.70624030e-02,  8.11807346e-03,  5.95772788e-02, -3.19411978e-02,
          5.81039600e-02,  1.95025578e-02,  3.71583849e-02,  5.88324107e-03,
          1.53963529e-02,  3.51784155e-02, -2.35251021e-02,  7.92885795e-02,
         -3.05617154e-02, -1.99385118e-02, -8.13734755e-02, -1.25664786e-01,
         -2.59873625e-02, -5.24826534e-02,  3.75152309e-03,  2.80721951e-02,
         -4.10410687e-02,  6.88031241e-02, -9.14725363e-02,  1.63114928e-02,
         -9.08274949e-02, -2.50381194e-02, -2.15020385e-02,  3.57075445e-02,
          1.56707801e-02,  2.72471290e-02, -5.09989001e-02,  1.73480134e-03,
          2.54246984e-02, -4.76679159e-03,  8.02696571e-02,  1.11472078e-01,
         -2.18368880e-02, -1.08616404e-01, -1.27692334e-02, -8.22653901e-03,
         -1.66712962e-02, -6.58633336e-02, -7.73727000e-02, -1.59770792e-08,
          1.07898703e-02, -4.41678148e-03,  5.39550707e-02, -6.93759546e-02,
          4.82009463e-02,  7.87589177e-02,  2.61550136e-02, -1.01903388e-02,
          2.86767874e-02,  7.04269558e-02,  8.22025314e-02,  2.00291499e-02,
          5.73524423e-02,  3.10402829e-02,  6.98653758e-02, -3.70384417e-02,
          1.93623435e-02,  1.15336157e-01, -4.57215169e-03,  1.14648081e-02,
         -6.67654164e-03, -4.16180864e-02,  5.23354746e-02, -1.36465162e-01,
          1.81709565e-02,  6.24540774e-03, -1.47890905e-02,  1.09797262e-01,
         -4.21142392e-02,  1.01671042e-02, -3.07445824e-02,  1.13257222e-01,
          3.45925279e-02,  1.96993519e-02,  1.25564833e-03,  3.80589925e-02,
          4.83894274e-02,  2.26374753e-02, -1.67597719e-02,  3.04050911e-02,
         -1.51804360e-02,  2.86381487e-02,  9.29250941e-02, -2.69179866e-02,
         -5.29071726e-02,  2.60877572e-02,  1.27067761e-02, -4.53397073e-02,
         -2.70356843e-03, -1.21021373e-02, -7.78902089e-03,  1.35551188e-02,
          4.36936915e-02,  3.78443599e-02, -2.25434527e-02, -1.41144097e-02,
          2.71068811e-02, -2.39804164e-02, -3.96824628e-02,  1.36298346e-04,
          7.66982278e-03,  1.05080632e-02,  6.80240244e-02,  1.96243692e-02],
        dtype=float32),
  'the naem': array([-6.02948219e-02,  1.08011059e-01, -4.00736816e-02,  2.84986367e-04,
         -5.78279607e-02,  3.90510485e-02,  1.63081363e-02, -6.27290308e-02,
         -2.72917673e-02,  6.48954362e-02, -1.36010274e-02, -1.12080656e-01,
          4.29547578e-02, -3.33018899e-02,  3.84274013e-02,  1.98137830e-04,
         -9.92214493e-03,  3.54607916e-03, -1.39897941e-02, -5.76529317e-02,
         -3.93402874e-02,  4.99700382e-02,  2.77685113e-02, -9.71351005e-03,
         -7.29377121e-02,  3.06804606e-04,  5.28396107e-02,  1.97455939e-02,
          6.62655681e-02, -1.39705896e-01,  5.01708651e-04,  6.13604449e-02,
         -2.77932324e-02,  1.24620097e-02, -6.92578256e-02, -7.66454358e-03,
         -6.53420836e-02, -5.53792249e-03,  1.61085241e-02,  6.49706181e-03,
          7.51554444e-02, -4.55971584e-02, -3.45253339e-03, -3.36859487e-02,
          3.02659851e-02, -7.05948845e-02, -2.51310803e-02, -1.06170215e-02,
          4.80370149e-02,  5.61028048e-02,  3.07876430e-02, -5.77379987e-02,
         -2.93143447e-02,  2.36564688e-02,  6.86284378e-02,  3.42092142e-02,
         -3.66425663e-02, -1.07707500e-01,  2.47657467e-02, -1.87080668e-03,
          8.02794397e-02, -6.56677922e-03, -7.98377991e-02,  6.52273372e-02,
          6.82052225e-02, -9.37174559e-02,  6.07989468e-02,  3.30209956e-02,
         -3.37643698e-02,  2.64172070e-02,  3.17097381e-02, -5.40623777e-02,
          7.14883283e-02, -5.85954294e-05, -5.46505712e-02, -2.46139779e-03,
          6.93024918e-02,  2.13216897e-02,  4.47886586e-02, -1.18316412e-02,
          3.43478993e-02,  3.82323898e-02,  3.36475521e-02, -3.92940678e-02,
          5.31843156e-02, -2.18143081e-03,  8.81356597e-02, -2.54524779e-03,
          2.20382493e-02,  3.63924690e-02, -5.86665832e-02, -3.01842093e-02,
         -8.23798776e-03, -4.73331064e-02,  3.13263424e-02, -3.42283919e-02,
         -2.73819845e-02,  1.87601298e-02,  1.42660839e-02,  1.50501087e-01,
          8.95082578e-02,  1.07485510e-01,  3.75266606e-03,  2.73721516e-02,
          2.50877403e-02,  1.64601430e-02,  1.33112613e-02,  9.83587839e-03,
         -1.44914966e-02,  7.16948360e-02, -4.74362671e-02, -1.86514463e-02,
         -2.84116566e-02, -5.88079123e-03,  3.09783909e-02, -2.49706171e-02,
         -1.90918818e-02, -2.12573130e-02,  5.94183151e-03,  2.15574261e-02,
          6.16728701e-03, -8.75436589e-02, -8.20264444e-02,  3.19139473e-02,
          3.29091512e-02,  5.75121269e-02, -1.16018280e-02, -3.45253013e-33,
         -1.07773654e-02,  7.30660232e-03, -1.63617432e-02, -4.64672670e-02,
          3.70621644e-02,  2.73215417e-02, -2.31236648e-02,  5.66564389e-02,
         -9.57396403e-02, -1.78244058e-02, -2.85459626e-02,  7.88215175e-02,
         -7.85891190e-02,  1.38537372e-02,  8.36979970e-02,  1.03458129e-02,
         -7.59367272e-02, -2.64888816e-02, -3.77846211e-02, -9.53301936e-02,
         -1.12825729e-01,  1.13505073e-01,  7.91859720e-03,  4.91239764e-02,
         -4.25062217e-02,  2.93205529e-02, -2.66452413e-02, -8.48129913e-02,
         -2.70097610e-02,  3.14407647e-02,  4.99393456e-02,  4.24260758e-02,
         -5.03373146e-02,  4.26193215e-02, -8.63207206e-02, -7.60602532e-03,
         -2.76761297e-02, -2.03614552e-02, -5.48336618e-02, -3.26869301e-02,
         -3.44958715e-02,  2.51876265e-02,  1.70821827e-02,  6.42866790e-02,
         -8.01583827e-02, -4.63353433e-02, -1.50233628e-02, -6.26033098e-02,
          8.19116607e-02,  2.78966278e-02,  2.92818109e-03, -3.42847942e-03,
         -4.39037941e-02, -2.01128069e-02,  9.56659298e-03, -1.93481166e-02,
          1.94190754e-04,  4.55720723e-02,  6.61208257e-02, -1.77856572e-02,
          3.08940839e-02,  4.35537733e-02,  3.67996395e-02,  9.71465111e-02,
          3.79517078e-02,  3.49885821e-02, -6.32042810e-03, -6.03008382e-02,
          5.28266318e-02, -3.05552408e-02, -4.74490337e-02,  5.96354604e-02,
          6.59352094e-02,  7.80555382e-02, -1.09362078e-03,  1.21456785e-02,
         -5.06829657e-03, -8.68264958e-02, -9.48877186e-02, -3.95371802e-02,
          2.56637372e-02,  5.39868325e-02, -2.76523270e-02,  6.43403754e-02,
          3.58118862e-02, -1.93711761e-02, -2.32705493e-02, -1.75263323e-02,
          1.40554206e-02, -2.48366240e-02,  1.45109519e-02,  4.32571545e-02,
          1.46898357e-02, -6.47579655e-02, -5.66580407e-02,  3.23796090e-33,
          2.35630684e-02,  1.24059683e-02, -1.02182612e-01,  6.69505745e-02,
          6.45909831e-02, -4.55888771e-02,  4.77873981e-02,  2.63668410e-02,
         -1.10716738e-01,  3.60688642e-02,  1.58360135e-02, -2.84001026e-02,
          1.29867494e-01,  4.72247489e-02,  8.71693641e-02, -5.97081110e-02,
          1.27869129e-01, -8.50948021e-02,  2.15540100e-02, -3.34259197e-02,
          2.41573993e-02, -3.29210311e-02,  1.49753662e-02, -1.72330830e-02,
          1.08727915e-02,  7.22939298e-02,  1.39474561e-02, -7.08193928e-02,
         -7.42303208e-02, -2.18185019e-02,  1.94083285e-02,  3.13056670e-02,
         -1.57291330e-02,  9.62476805e-03, -4.63565588e-02,  3.84134501e-02,
          2.73784064e-02,  6.42660186e-02, -6.87038451e-02, -4.55769412e-02,

In [20]:
from tqdm import tqdm

for chunk in tqdm(pages_and_chunk):
    chunk["embedding"] = model.encode(chunk["paragraphe"], device="cuda")

100%|██████████| 153/153 [00:00<00:00, 183.97it/s]

In [21]:
page_and_Embedding_df = pd.DataFrame(pages_and_chunk)
page_and_Embedding_file_name = "page_and_Embedding.csv"
page_and_Embedding_path = os.path.join(os.getcwd(), page_and_Embedding_file_name)
page_and_Embedding_df.to_csv(page_and_Embedding_path, index=False)

In [22]:
pages_and_chunk = pd.read_csv(page_and_Embedding_path)
pages_and_chunk

,paragraphe,word_count,char_count,tokens_count,sentence_count,page_number,embedding
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,222,1767,441,10,1,[-7.36545101e-02 -5.92405535e-02 5.75507917e-...
1,arXiv:2412.19437v2 [cs.CL] 18 Feb 2025,5,38,9,2,1,[-1.14521928e-01 7.90135004e-03 -7.34651685e-...
2,Contents 1 Introduction 4 2 Architecture 6 2.1...,302,952,238,10,2,[-1.76019724e-02 -5.03365993e-02 -4.91420552e-...
3,14 3.3.1 Mixed Precision Framework . . . . . ....,324,912,228,10,2,[-1.62388142e-02 3.45401727e-02 -1.01859637e-...
4,21 4.2 Hyper-Parameters . . . . . . . . . . . ...,267,742,185,9,2,[ 2.22861432e-02 3.54707316e-02 -1.13855220e-...
...,...,...,...,...,...,...,...
148,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2961,740,1,49,[-8.76501799e-02 3.37728113e-03 -2.45083477e-...
149,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2968,742,1,50,[-8.87523293e-02 2.17781449e-03 -2.23974977e-...
150,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2975,743,1,51,[-8.97151008e-02 9.12356935e-03 -2.74222512e-...
151,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2975,743,1,52,[-8.86221230e-02 6.90442836e-03 -2.55782288e-...
152,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,346,1370,342,4,53,[-8.44787434e-02 4.49142931e-03 -2.48290580e-...

In [23]:
data = pages_and_chunk.to_dict(orient="records")
data[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': '[-5.76342642e-02  1.86270513e-02 -6.96300939e-02 -5.02151484e-03\n -6.43548295e-02  5.39917722e-02 -4.61325161e-02  3.96140479e-02\n -5.72230071e-02  5.44097507e-03 -4.39483449e-02 -6.78690989e-03\n  4.00274098e-02 -1.59040969e-02  7.62041006e-03  4.98709492e-02\n  1.28310844e-01 -3.56771424e-02 -4.98869866e-02 -8.15588683e-02\n  4.34629619e-02 -4.59041297e-02  8.90599862e-02  1.54037271e-02\n -7.79619813e-02  3.06390580e-02 -5.25192842e-02 -6.64412901e-02\n  3.31790484e-02 -6.93642348e-02 -6.77236822e-03  3.17600835e-03\n  5.10904342e-02 -8.24809149e-02 -8.37938786e-02  1.99514590e-02\n -5.22203557e-02 -5.73823750e-02  1.78819466e-02  2.67784391e-02\n  1.22638667e-04 -3.79560366e-02  2.66230456e-03  2.12215632e-02\n  3.83331478e-02 -2.20189728e-02 -5.95768988e-02 -2.69228090e-02\n -4.48380411e-02 -8.05420280e-02 -1.64255090e-02 -6.48153797e-02\n  5.06782858e-03 -2.43175868e-03 -5.40565178e-02 -8.12960323e-03\n  4.19079550e-02 -2.15617977e-02 -1.57967899e-02  3.31747867e-02\n -8.01364630e-02 -1.54114645e-02 -5.74465916e-02  1.44828800e-02\n  3.75398025e-02 -9.97637808e-02 -8.92196968e-03 -6.80585429e-02\n  5.85166179e-02 -3.27327773e-02 -2.40229815e-03 -6.30820077e-03\n  4.79136705e-02 -8.28515515e-02 -2.71539204e-02 -4.32537962e-03\n  2.57454626e-02 -3.27682085e-02  2.09330637e-02 -7.94779956e-02\n  1.91955678e-02 -1.16449185e-02  9.50378273e-03 -4.35635038e-02\n -3.66505533e-02 -9.70793366e-02  8.94268136e-03 -1.46269398e-02\n  5.45645840e-02  6.92141205e-02  1.05012529e-01  1.10859863e-01\n -1.34864971e-02  8.77503306e-03 -1.14638149e-03  1.05595574e-01\n -3.30545455e-02  1.49801131e-02 -7.64260069e-02  4.41715568e-02\n  8.06645304e-02  3.79374810e-02 -1.73761696e-02  4.10951860e-02\n -2.40345821e-02 -4.80216332e-02  1.50007065e-02  3.03008184e-02\n  4.40813182e-03 -1.10763662e-01  5.87851778e-02  5.47064729e-02\n  8.96646827e-03 -4.55785692e-02 -4.77991328e-02  8.83815959e-02\n -1.86152197e-02  2.07292549e-02 -2.19883397e-02  7.60800242e-02\n  1.60371698e-02 -1.16604365e-01  1.25039175e-01 -7.68837333e-03\n  3.03481687e-02 -1.52714243e-02 -6.32316470e-02 -2.49990914e-32\n -8.10585022e-02 -5.51191568e-02 -1.33699374e-02 -5.99327907e-02\n  1.10146394e-02  2.59977896e-02  3.60030234e-02  4.94830823e-03\n  1.81742699e-03 -7.88456202e-02 -5.46012409e-02 -3.52930427e-02\n -6.31591398e-03  6.83287606e-02  1.65332407e-02 -8.12145397e-02\n  5.00030024e-03  1.31413504e-01 -4.67872508e-02 -5.32843284e-02\n  6.42249063e-02 -5.45797981e-02 -4.81015742e-02  2.70940475e-02\n  8.49387497e-02 -5.11573721e-03  8.52151513e-02  4.48351949e-02\n -9.25949216e-02  8.05962086e-03  2.34439634e-02  4.24520560e-02\n -5.95207177e-02  1.05523206e-02 -6.87899813e-02  6.73937728e-04\n  4.62168045e-02 -6.29209820e-03  3.83899324e-02  2.46823020e-03\n -9.38248113e-02  5.74741922e-02  7.89213926e-02 -2.18204875e-02\n -4.18461375e-02 -5.63514344e-02 -4.13205549e-02  2.18046643e-02\n -9.33823735e-02  3.08047123e-02 -6.42291158e-02 -1.99530181e-02\n  3.61034833e-02 -3.50957811e-02  3.22241597e-02  6.15459457e-02\n  5.70552759e-02  1.59135945e-02 -2.45294087e-02  9.99931172e-02\n  5.59420958e-02 -4.10363562e-02 -6.51614890e-02  2.00892612e-02\n  4.90734093e-02  3.07650082e-02 -5.85500784e-02 -5.81300771e-03\n  3.74068208e-02  4.96497601e-02 -6.38446733e-02 -2.64048181e-03\n  5.88807538e-02 -4.38631549e-02  6.60317093e-02 -7.83692077e-02\n  6.36432096e-02  6.92372583e-03 -8.18328112e-02 -3.14817317e-02\n -3.57160321e-03  1.01911925e-01 -5.81695735e-02 -2.84043569e-02\n  1.21233733e-02  2.11809226e-03 -4.04893272e-02 -5.31520881e-02\n -1.43813621e-02  3.91902626e-02 -4.59962897e-02 -2.05660868e-03\n  6.13806909e-03  9.19523835e-02  1.95201244e-02  1.56344922e-32\n  2.62332484e-02  9.64798480e-02 -6.58232719e-02  4.79708761e-02\n  8.70390460e-02  4.03306670e-02  1.44300619e-02 -4.76207808e-02\n -8.86879582e-03  1.93301495e-02 -1.29634440e-02  4.97946739e-02\n -6.92615882e-02  3.16581689e-02 -3.13160643e-02 -3.00069898e-02\n -4.07419307e-03 -1.46255158e-02 -1.23310108e-02  2.74193212e-02\n  8.34065378e-02  6.97517619e-02 -1.05787523e-01  8.78471509e-02\n  5.59022231e-03 -1.86682567e-02 -6.24801964e-02 -3.62294214e-03\n -3.38804536e-02  4.26130667e-02 -3.24046277e-02 -9.78929177e-02\n  1.34582929e-02  4.51985709e-02 -4.52558734e-02 -1.61164999e-02\n  8.62949118e-02  2.88819801e-02 -8.69680103e-03  1.49755552e-01\n  3.60441841e-02  2.37741750e-02 -3.88363563e-02  5.74692935e-02\n -2.12660152e-02 -4.92211245e-03 -7.09280139e-03 -5.32866456e-02\n -8.20563585e-02  4.31005657e-02 -3.67642939e-02 -2.71880608e-02\n -1.35272205e-01 -2.56682355e-02 -2.91684028e-02 -8.94128382e-02\n  1.41426641e-02  7.27050100e-03 -7.77576491e-02 -9.60375089e-03\n -4.91312295e-02  5.92100769e-02 -2.87621375e-02 -1.12884371e-02\n -2.84832269e-02 -8.75013601e-03  1.74761526e-02  4.95308675e-02\n  3.17866504e-02  3.20894495e-02 -8.73307511e-02 -7.09942076e-03\n  5.87638542e-02 -6.80810947e-04  3.69722694e-02 -2.14159191e-02\n  9.13810582e-05 -1.07633816e-02 -5.68082258e-02 -2.79051326e-02\n -1.05843894e-01 -9.68937122e-04  1.14391567e-02 -9.73246060e-03\n -4.10722606e-02  3.72071378e-02  4.89398278e-02  4.51454930e-02\n  1.92308407e-02 -1.15436651e-02  5.01300581e-03  2.97262445e-02\n  6.92122579e-02  1.63906328e-02  8.69894680e-03 -4.69932573e-08\n  9.97944549e-03 -5.11729307e-02  7.04230741e-02  6.84352070e-02\n  3.95479538e-02  1.35835100e-04 -7.60002732e-02  4.00973707e-02\n -3.73462401e-02 -5.88462828e-03  1.22180901e-01  8.05509184e-03\n -1.34176323e-02  1.23290345e-02  2.55201720e-02  1.09683396e-02\n  6.05740584e-04 -2.16496997e-02 -5.05289622e-02 -1.30557213e-02\n  1.05004385e-02  1.00649591e-03 -3.34202051e-02 -1.19563006e-02\n  3.54323424e-02 -7.30695277e-02 -1.92586686e-02  6.82983696e-02\n -5.41707389e-02 -3.45373824e-02  5.45379631e-02  2.30299924e-02\n  1.27890641e-02  2.67073419e-02  2.77423747e-02  1.66754276e-02\n -9.89097822e-03 -1.50999101e-02  1.57295670e-02  1.33830905e-01\n  4.96073673e-03 -5.15581341e-03  2.67172307e-02  9.28953476e-03\n  5.75694405e-02 -3.65181193e-02 -1.39185563e-01 -5.01695983e-02\n  4.19336818e-02 -7.75045007e-02 -4.21275385e-02 -2.39884313e-02\n -6.29835576e-02  7.19864741e-02  1.34467065e-01 -8.73645023e-03\n -7.97666982e-03 -6.91410005e-02  3.03546451e-02  6.15585037e-02\n -2.00266228e-03 -6.09333478e-02 -6.89558536e-02 -6.41390905e-02]'}

In [24]:
import torch
import numpy as np
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [25]:
for item in data:
    item['embedding'] = np.fromstring(item['embedding'].strip('[]'), sep=' ')

In [26]:
embeddings = np.array([item["embedding"] for item in data])
embeddings_df = pd.DataFrame(embeddings)
print(embeddings_df.shape)  # should be (153, 384)

(153, 384)

153 rows x 384 dimensions — one embedding vector per chunk.

In [27]:
from time import perf_counter as timer

query = "attentions in models datas"
embeddings_tensor = torch.tensor(np.array(embeddings), dtype=torch.float32)
query_embedding = model.encode(query, device=device)

start = timer()
dot_product = util.dot_score(a=query_embedding, b=embeddings_tensor)[0]
end = timer()
print(f"[INFO]: time it take {(end-start):.5f} seconds")

dot_topk = torch.topk(dot_product, 3)
dot_topk

[INFO]: time it take 0.00043 seconds

torch.return_types.topk(
values=tensor([0.4049, 0.3879, 0.3805]),
indices=tensor([113, 119,  17]))

In [28]:
# just test what idx.item() do
[idx.item() for idx in dot_topk.indices]

#it turn tensor to scaller

[113, 119, 17]

In [29]:
# Show the top-k matching paragraphs
for score, idx in zip(dot_topk.values, dot_topk.indices):
    print(f"Score: {score:.4f} | Page: {data[idx.item()]['page_number']}")
    print(data[idx.item()]['paragraphe'])
    print("-" * 120)

Score: 0.4049 | Page: 38
In The Thirty-eighth Annual Conference on Neural Information Processing Systems.Y. He, S. Li, J. Liu, Y. Tan, W. Wang, H. Huang, X. Bu, H. Guo, C. Hu, B. Zheng, et al.Chi- nese simpleqa: A chinese factuality evaluation for large language models.arXiv preprint arXiv:2411.07140, 2024.D. Hendrycks, C. Burns, S. Basart, A. Zou, M. Mazeika, D. Song, and J. Steinhardt.Measuring massive multitask language understanding.arXiv preprint arXiv:2009.03300, 2020.38
------------------------------------------------------------------------------------------------------------------------
Score: 0.3879 | Page: 40
Y. Leviathan, M. Kalman, and Y. Matias.Fast inference from transformers via speculative decoding.In International Conference on Machine Learning, ICML 2023, 23-29 July 2023, Honolulu, Hawaii, USA, volume 202 of Proceedings of Machine Learning Research, pages 19274–19286.PMLR, 2023.URL https://proceedings.mlr.press/v202/leviathan23 a.html.H. Li, Y. Zhang, F. Koto, Y. Yang, H. Zhao, Y. Gong, N. Duan, and T. Baldwin.CMMLU: Measur- ing massive multitask language understanding in Chinese.arXiv preprint arXiv:2306.09212, 2023.S. Li and T. Hoefler.Chimera: efficiently training large-scale neural networks with bidirectional pipelines.
------------------------------------------------------------------------------------------------------------------------
Score: 0.3805 | Page: 8
where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vector for keys and values; 𝑑𝑐(≪𝑑ℎ𝑛ℎ) indicates the KV compression dimension; 𝑊𝐷𝐾𝑉∈R𝑑𝑐×𝑑denotes the down-projection matrix; 𝑊𝑈𝐾,𝑊𝑈𝑉∈R𝑑ℎ𝑛ℎ×𝑑𝑐 are the up-projection matrices for keys and values, respectively; 𝑊𝐾𝑅∈R𝑑𝑅 ℎ×𝑑is the matrix used to produce the decoupled key that carries Rotary Positional Embedding (RoPE) (Su et al.,2024); RoPE(·) denotes the operation that applies RoPE matrices; and [·; ·] denotes concatenation.Note that for MLA, only the blue-boxed vectors (i.e., c𝐾𝑉 𝑡 and k𝑅 𝑡) need to be cached during generation, which results in significantly reduced KV cache while maintaining performance comparable to standard Multi-Head Attention (MHA) (Vaswani et al.,2017).For the attention queries, we also perform a low-rank compression, which can reduce the activation memory during training: c𝑄 𝑡= 𝑊𝐷𝑄h𝑡, (6) [q𝐶 𝑡,1; q𝐶 𝑡,2; ...; q𝐶 𝑡,𝑛ℎ] = q𝐶 𝑡= 𝑊𝑈𝑄c𝑄 𝑡, (7) [q𝑅 𝑡,1; q𝑅 𝑡,2; ...; q𝑅 𝑡,𝑛ℎ] = q𝑅 𝑡= RoPE(𝑊𝑄𝑅c𝑄 𝑡), (8) q𝑡,𝑖= [q𝐶 𝑡,𝑖; q𝑅 𝑡,𝑖], (9) where c𝑄 𝑡 ∈R𝑑′ 𝑐is the compressed latent vector for queries; 𝑑′ 𝑐(≪𝑑ℎ𝑛ℎ) denotes the query compression dimension; 𝑊𝐷𝑄∈R𝑑′ 𝑐×𝑑,𝑊𝑈𝑄∈R𝑑ℎ𝑛ℎ×𝑑′ 𝑐are the down-projection and up-projection matrices for queries, respectively; and 𝑊𝑄𝑅∈R𝑑𝑅 ℎ𝑛ℎ×𝑑′ 𝑐is the matrix to produce the decoupled queries that carry RoPE.Ultimately, the attention queries (q𝑡,𝑖), keys (k𝑗,𝑖), and values (v𝐶 𝑗,𝑖) are combined to yield the final attention output u𝑡: o𝑡,𝑖= 𝑡∑︁ 𝑗=1 Softmax𝑗( q𝑇 𝑡,𝑖k𝑗,𝑖 √︃ 𝑑ℎ+ 𝑑𝑅 ℎ )v𝐶 𝑗,𝑖, (10) u𝑡= 𝑊𝑂[o𝑡,1; o𝑡,2; ...; o𝑡,𝑛ℎ], (11) where 𝑊𝑂∈R𝑑×𝑑ℎ𝑛ℎdenotes the output projection matrix.2.1.2.DeepSeekMoE with Auxiliary-Loss-Free Load Balancing Basic Architecture of DeepSeekMoE. For Feed-Forward Networks (FFNs), DeepSeek-V3 employs the DeepSeekMoE architecture (Dai et al.,2024).Compared with traditional MoE architectures like GShard (Lepikhin et al.,
------------------------------------------------------------------------------------------------------------------------

# functionalize the query search

In [30]:
def get_answer(query:str,
               embedings_data=embeddings,
               embedding_model: SentenceTransformer=model,
               top_k :int = 5,
               time_taken:bool =True):
    # embed the query
    query_embed= embedding_model.encode(query,convert_to_tensor=True)

    # make sure that data are in the same device (cuda) the GPU in this case
    embedings_data = torch.tensor(np.array(embedings_data), dtype=torch.float32).to('cuda')

    # compare the embedding of query with ather embeddings frome book/dataset
    start = timer()
    dot_product = util.dot_score(a=query_embed, b=embedings_data)[0]
    end = timer()    

    if time_taken:
        print(f"[INFO]time {(end-start):.5f}")
    top_results = torch.topk(dot_product,top_k)
    scores=[score.item() for score in top_results[0]]
    indeces =[score.item() for score in top_results[1]]
    # scores,indeces = top_results
    # print(f"{top_results}")
    return scores,indeces 

def print_top_Result(query:str,
               embedings_data=embeddings,
               embedding_model: SentenceTransformer=model,
               top_k :int = 5,
               time_taken:bool =True,
               pages_and_chunk=data):
    score,indcis=get_answer(query,embedings_data,embedding_model,top_k,time_taken)

    for s, i in zip(score, indcis):
        print(f"Score: {s:.4f} | Index: {i} | Page_number: {pages_and_chunk[i]['page_number']}\nChunk: {pages_and_chunk[i]["paragraphe"]}")
        print("-"*120)

In [31]:
print_top_Result("github")

[INFO]time 0.00014
Score: 0.2818 | Index: 86 | Page_number: 31
Chunk: Standard Evaluation Table 6 presents the evaluation results, showcasing that DeepSeek-V3 stands as the best- performing open-source model.Additionally, it is competitive against frontier closed-source models like GPT-4o and Claude-3.5-Sonnet.31
------------------------------------------------------------------------------------------------------------------------
Score: 0.2415 | Index: 68 | Page_number: 24
Chunk: Math datasets include GSM8K (Cobbe et al.,2021), MATH (Hendrycks et al.,2021), MGSM (Shi et al.,2023), and CMath (Wei et al.,2023).Code datasets include HumanEval (Chen et al.,2021), LiveCodeBench-Base (0801-1101) (Jain et al.,2024), MBPP (Austin et al.,2021), and CRUXEval (Gu et al.,2024).
------------------------------------------------------------------------------------------------------------------------
Score: 0.1890 | Index: 88 | Page_number: 32
Chunk: On the factual knowledge benchmark, SimpleQA, DeepSeek-V3 falls behind GPT-4o and Claude-Sonnet, primarily due to its design focus and resource allocation.DeepSeek-V3 assigns more training tokens to learn Chinese knowledge, leading to exceptional performance on the C-SimpleQA.On the instruction-following benchmark, DeepSeek-V3 significantly outperforms its predecessor, DeepSeek-V2-series, highlighting its improved ability to understand and adhere to user-defined format constraints.Code and Math Benchmarks.Coding is a challenging and practical task for LLMs, encom- passing engineering-focused tasks like SWE-Bench-Verified and Aider, as well as algorithmic tasks such as HumanEval and LiveCodeBench.In engineering tasks, DeepSeek-V3 trails behind Claude-Sonnet-3.5-1022 but significantly outperforms open-source models.The open-source DeepSeek-V3 is expected to foster advancements in coding-related engineering tasks.By pro- viding access to its robust capabilities, DeepSeek-V3 can drive innovation and improvement in areas such as software engineering and algorithm development, empowering developers and researchers to push the boundaries of what open-source models can achieve in coding tasks.In algorithmic tasks, DeepSeek-V3 demonstrates superior performance, outperforming all baselines on benchmarks like HumanEval-Mul and LiveCodeBench.This success can be attributed to its advanced knowledge distillation technique, which effectively enhances its code generation and problem-solving capabilities in algorithm-focused tasks.
------------------------------------------------------------------------------------------------------------------------
Score: 0.1869 | Index: 91 | Page_number: 33
Chunk: This underscores the robust capabilities of DeepSeek-V3, especially in dealing with complex prompts, including coding and debugging tasks.Furthermore, DeepSeek-V3 achieves a groundbreaking milestone as the first open-source model to surpass 85% on the Arena-Hard benchmark.This achievement significantly bridges the performance gap between open-source and closed-source models, setting a new standard for what open-source models can accomplish in challenging domains.Similarly, DeepSeek-V3 showcases exceptional performance on AlpacaEval 2.0, outperform- ing both closed-source and open-source models.This demonstrates its outstanding proficiency in writing tasks and handling straightforward question-answering scenarios.Notably, it surpasses DeepSeek-V2.5-0905 by a significant margin of 20%, highlighting substantial improvements in tackling simple tasks and showcasing the effectiveness of its advancements.5.3.4.DeepSeek-V3 as a Generative Reward Model We compare the judgment ability of DeepSeek-V3 with state-of-the-art models, namely GPT-4o and Claude-3.5.Table 8 presents the performance of these models in RewardBench (Lambert et al.,2024).
------------------------------------------------------------------------------------------------------------------------
Score: 0.1823 | Index: 84 | Page_number: 31
Chunk: We utilize the Zero-Eval prompt format (Lin, 2024) for MMLU-Redux in a zero-shot setting.For other datasets, we follow their original evaluation protocols with default prompts as pro- vided by the dataset creators.For code and math benchmarks, the HumanEval-Mul dataset includes 8 mainstream programming languages (Python, Java, Cpp, C#, JavaScript, TypeScript, PHP, and Bash) in total.We use CoT and non-CoT methods to evaluate model performance on LiveCodeBench, where the data are collected from August 2024 to November 2024.The Codeforces dataset is measured using the percentage of competitors.SWE-Bench verified is evaluated using the agentless framework (Xia et al.,2024).We use the “diff” format to evaluate the Aider-related benchmarks.For mathematical assessments, AIME and CNMO 2024 are evaluated with a temperature of 0.7, and the results are averaged over 16 runs, while MATH-500 employs greedy decoding.We allow all models to output a maximum of 8192 tokens for each benchmark.
------------------------------------------------------------------------------------------------------------------------

In [ ]:
# Get GPU available memory
gpu_memory_bytes = torch.cuda.get_device_properties(0).total_memory
gpu_memory_gb = round(gpu_memory_bytes / (2 ** 30))
print(f"Available GPU memory: {gpu_memory_gb} GB")

Available GPU memory: 4 GB