In [1]:
import os 
import requests
url= r"https://arxiv.org/pdf/2412.19437"
pdf_path=os.path.join(os.getcwd() , "Data_file.pdf")

if not os.path.exists(pdf_path):

    response= requests.get(url)
    if response.status_code == 200:
        with open(pdf_path,"wb") as f:
            f.write(response.content)
        print(f"[INFO] the file is downloaded at : {pdf_path}")
else:
    print(f"[INFO] file exist : {pdf_path} ")

[INFO] file exist : e:\Tests\Data_file.pdf

In [2]:
# import fitz  # PyMuPDF
# pages_and_texts=[]
# doc = fitz.open("Data_file.pdf")
# data_text = []

# for page_num , page in enumerate(doc):
#     text = page.get_text()
#     pages_and_texts.append({
#         "text_of_page" : text,
#         "page_number" : page_num + 1
#     })
# print(pages_and_texts[3]) 
# for text in pages_and_texts:
#     text["text_of_page"] =text["text_of_page"].replace(r"-\n"," ").strip()
# print(pages_and_texts[3] )

In [3]:
import fitz  # PyMuPDF

def clean_text(text: str):
    text = text.replace("\n", " ").strip()
    return text

def open_pdf(file_path:str):
    doc=fitz.open(file_path)
    pages_and_texts=[]
    for page_num , page in enumerate(doc):
        text = page.get_text()
        cleaned_text = clean_text(text)
        pages_and_texts.append({
            "text_of_page" : cleaned_text,
            "page_count_char" : len(cleaned_text),
            "page_count_word" : len(cleaned_text.split(" ")),
            "page_count_sentences" : len(cleaned_text.split(". ")),
            "tokens_num" : len(cleaned_text) // 4 , # i dont get it but it is what it is 
            "page_number" : page_num + 1
        })
    return pages_and_texts

pages_and_texts=open_pdf("Data_file.pdf")
pages_and_texts[3]

{'text_of_page': '1. Introduction In recent years, Large Language Models (LLMs) have been undergoing rapid iteration and evolution (Anthropic, 2024; Google, 2024; OpenAI, 2024a), progressively diminishing the gap to- wards Artificial General Intelligence (AGI). Beyond closed-source models, open-source models, including DeepSeek series (DeepSeek-AI, 2024a,b,c; Guo et al., 2024), LLaMA series (AI@Meta, 2024a,b; Touvron et al., 2023a,b), Qwen series (Qwen, 2023, 2024a,b), and Mistral series (Jiang et al., 2023; Mistral, 2024), are also making significant strides, endeavoring to close the gap with their closed-source counterparts. To further push the boundaries of open-source model capa- bilities, we scale up our models and introduce DeepSeek-V3, a large Mixture-of-Experts (MoE) model with 671B parameters, of which 37B are activated for each token. With a forward-looking perspective, we consistently strive for strong model performance and economical costs. Therefore, in terms of architecture, DeepSeek-V3 still adopts Multi-head Latent Attention (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for cost-effective training. These two architectures have been validated in DeepSeek- V2 (DeepSeek-AI, 2024c), demonstrating their capability to maintain robust model performance while achieving efficient training and inference. Beyond the basic architecture, we implement two additional strategies to further enhance the model capabilities. Firstly, DeepSeek-V3 pi- oneers an auxiliary-loss-free strategy (Wang et al., 2024a) for load balancing, with the aim of minimizing the adverse impact on model performance that arises from the effort to encourage load balancing. Secondly, DeepSeek-V3 employs a multi-token prediction training objective, which we have observed to enhance the overall performance on evaluation benchmarks. In order to achieve efficient training, we support the FP8 mixed precision training and implement comprehensive optimizations for the training framework. Low-precision training has emerged as a promising solution for efficient training (Dettmers et al., 2022; Kalamkar et al., 2019; Narang et al., 2017; Peng et al., 2023b), its evolution being closely tied to advancements in hardware capabilities (Luo et al., 2024; Micikevicius et al., 2022; Rouhani et al., 2023a). In this work, we introduce an FP8 mixed precision training framework and, for the first time, validate its effectiveness on an extremely large-scale model. Through the support for FP8 computation and storage, we achieve both accelerated training and reduced GPU memory usage. As for the training framework, we design the DualPipe algorithm for efficient pipeline parallelism, which has fewer pipeline bubbles and hides most of the communication during training through computation-communication overlap. This overlap ensures that, as the model further scales up, as long as we maintain a constant computation-to-communication ratio, we can still employ fine-grained experts across nodes while achieving a near-zero all-to-all communication overhead. In addition, we also develop efficient cross-node all-to-all communication kernels to fully utilize InfiniBand (IB) and NVLink bandwidths. Furthermore, we meticulously optimize the memory footprint, making it possible to train DeepSeek-V3 without using costly tensor parallelism. Combining these efforts, we achieve high training efficiency. During pre-training, we train DeepSeek-V3 on 14.8T high-quality and diverse tokens. The pre-training process is remarkably stable. Throughout the entire training process, we did not encounter any irrecoverable loss spikes or have to roll back. Next, we conduct a two-stage context length extension for DeepSeek-V3. In the first stage, the maximum context length is extended to 32K, and in the second stage, it is further extended to 128K. Following this, we conduct post-training, including Supervised Fine-Tuning (SFT) and Reinforcement Learning (RL) on the base model of DeepSeek-V3, to align it with human preferences and further unlock its potential. During the post-training stage, we distill the reasoning capability from the DeepSeek- R1 series of models, and meanwhile carefully maintain the balance between model accuracy 4',
 'page_count_char': 4248,
 'page_count_word': 594,
 'page_count_sentences': 26,
 'tokens_num': 1062,
 'page_number': 4}

In [4]:
import pandas as pd 

df = pd.DataFrame(pages_and_texts)
df.head(10)

,text_of_page,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,1817,238,11,454,1
1,Contents 1 Introduction 4 2 Architecture 6 2.1...,2634,919,766,658,2
2,4.5.3 Batch-Wise Load Balance VS. Sequence-Wis...,1715,572,462,428,3
3,"1. Introduction In recent years, Large Languag...",4248,594,26,1062,4
4,Training Costs Pre-Training Context Extension ...,3287,468,21,821,5
5,verification and reflection patterns of R1 int...,3475,457,23,868,6
6,… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ...,1557,262,8,389,7
7,where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vecto...,2236,353,9,559,8
8,where 𝑁𝑠and 𝑁𝑟denote the numbers of shared exp...,2901,455,17,725,9
9,Main Model (Next Token Prediction) Embedding L...,2904,451,23,726,10

In [5]:
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
count,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00
std,799.86,178.18,124.63,199.99,15.44
min,699.00,99.00,1.00,174.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00
50%,2992.00,457.00,23.00,748.00,27.00
75%,3281.00,516.00,29.00,820.00,40.00
max,4248.00,919.00,766.00,1062.00,53.00

# Turn text to sentences

In [6]:
from spacy.lang.en import English

nlp= English()

# add sentencizer to pipeliine

nlp.add_pipe("sentencizer")

#example sentence to test
semtemces = "this my name . hellow mr.ahmed . what is your name ?"

doc = nlp(semtemces)
# list the sentences to show 
list(doc.sents)

[this my name ., hellow mr.ahmed ., what is your name ?]

# Now try the `data`

In [7]:
for page in pages_and_texts:
    page["sentences"] = list(nlp(page["text_of_page"]).sents)
    page["sentences_num"] =len(page["sentences"])

#make sure tha all sentences is string not spacy type
for page in pages_and_texts:
    page["sentences"]=[str(sentences) for sentences in page["sentences"]]

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25}

In [8]:
#read specific sentence
pages_and_texts[5]["sentences"][6]

'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.'

In [9]:
# see some statistics about this data 
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num
count,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94
std,799.86,178.18,124.63,199.99,15.44,14.44
min,699.00,99.00,1.00,174.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00

In [10]:
test=list(range(1,25))
input_list=[]
slice_size=10
x=[test[i:i+slice_size] for i in range(0,len(test),slice_size)]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24]]

In [11]:
def chunker (input_list : list[str],slice_size:int)->list[list[str]]:

    return[input_list[i:i+slice_size] for i in range(0,len(input_list),slice_size)]

for page in pages_and_texts:
    page["sentences_chunk"] = chunker(page["sentences"],slice_size)
    page["sentences_chunk_num"] =len( page["sentences_chunk"]) 

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25,
 'sentences_chunk': [['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
   'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
   'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
   'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
   '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
   'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
   'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
   'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
   '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
   'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.'],
  ['In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
   'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
   'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
   'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
   'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
   '2.',
   'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
   '2024) for economical training.',
   'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
   'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).'],
  ['2.1.',
   'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
   '2017) framework.',
   'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
   'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6']],
 'sentences_chunk_num': 3}

In [12]:
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num,sentences_chunk_num
count,53.00,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94,2.89
std,799.86,178.18,124.63,199.99,15.44,14.44,1.40
min,699.00,99.00,1.00,174.00,1.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00,2.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00,3.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00,3.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00,6.00

In [13]:
pages_and_chunk=[]
for page in pages_and_texts:
    for chunk in page["sentences_chunk"]:
        chunk_dict = {}

        # join all sentences in chunk to be one paragraphe
        paragragh = "".join(chunk).replace("  "," ").strip()
        chunk_dict ["paragraphe"] = paragragh
        
        # Calculate statistics
        words = paragragh.split(" ")
        word_count = len(words)
        char_count = len(paragragh)
        tokens_count = char_count // 4  # approximate tokens
        sentence_count = len(chunk)  # number of sentences in chunk
        
        # Store statistics
        chunk_dict["word_count"] = word_count
        chunk_dict["char_count"] = char_count
        chunk_dict["tokens_count"] = tokens_count
        chunk_dict["sentence_count"] = sentence_count
        chunk_dict ["page_number"] = page["page_number"]

        pages_and_chunk.append(chunk_dict)
pages_and_chunk[5] ,len(pages_and_chunk),len(pages_and_texts)

({'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
  'word_count': 298,
  'char_count': 830,
  'tokens_count': 207,
  'sentence_count': 10,
  'page_number': 3},
 153,
 53)

In [14]:
df = pd.DataFrame(pages_and_chunk)
df.describe().round(2)

       word_count  char_count  tokens_count  sentence_count  page_number
count      153.00      153.00        153.00          153.00       153.00
mean       157.03      974.48        243.26            8.29        26.52
std        145.88      584.64        146.14            2.95        13.86
min          1.00        1.00          0.00            1.00         1.00
25%         74.00      572.00        143.00            7.00        15.00
50%        134.00      912.00        228.00           10.00        28.00
75%        191.00     1301.00        325.00           10.00        39.00
max        877.00     2975.00        743.00           10.00        53.00

In [15]:
df[df["word_count"]<4]
pages_and_texts[8]

{'text_of_page': 'where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts. Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values. Auxiliary-Loss-Free Load Balancing. For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al., 2017) and diminish computational efficiency in scenarios with expert parallelism. Conventional solutions usually rely on the auxiliary loss (Fedus et al., 2021; Lepikhin et al., 2021) to avoid unbalanced load. However, too large an auxiliary loss will impair the model performance (Wang et al., 2024a). To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al., 2024a) to ensure load balance. To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (16) Note that the bias term is only used for routing. The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step. At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed. Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses. Complementary Sequence-Wise Auxiliary Loss. Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence. The sequence-wise balance loss encourages the expert load on each sequence to be balanced. 9',
 'page_count_char': 2901,
 'page_count_word': 455,
 'page_count_sentences': 17,
 'tokens_num': 725,
 'page_number': 9,
 'sentences': ['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
  'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
  'Auxiliary-Loss-Free Load Balancing.',
  'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
  '2017) and diminish computational efficiency in scenarios with expert parallelism.',
  'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
  '2021; Lepikhin et al.,',
  '2021) to avoid unbalanced load.',
  'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
  '2024a).',
  'To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
  '2024a) to ensure load balance.',
  'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
  '16) Note that the bias term is only used for routing.',
  'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
  'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
  'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
  'Complementary Sequence-Wise Auxiliary Loss.',
  'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
  'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.',
  '9'],
 'sentences_num': 21,
 'sentences_chunk': [['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
   'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
   'Auxiliary-Loss-Free Load Balancing.',
   'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
   '2017) and diminish computational efficiency in scenarios with expert parallelism.',
   'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
   '2021; Lepikhin et al.,',
   '2021) to avoid unbalanced load.',
   'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
   '2024a).'],
  ['To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
   '2024a) to ensure load balance.',
   'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
   '16) Note that the bias term is only used for routing.',
   'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
   'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
   'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
   'Complementary Sequence-Wise Auxiliary Loss.',
   'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
   'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.'],
  ['9']],
 'sentences_chunk_num': 3}

In [16]:
#filter out tokens less than 30
filtered_chunks = [chunk for chunk in pages_and_chunk if chunk["tokens_count"] >= 30]
filtered_chunks[111]

{'paragraphe': 'A study of bfloat16 for deep learning training.arXiv preprint arXiv:1905.12322, 2019.S. Krishna, K. Krishna, A. Mohananey, S. Schwarcz, A. Stambler, S. Upadhyay, and M. Faruqui.Fact, fetch, and reason: A unified evaluation of retrieval-augmented generation.CoRR, abs/2409.12941, 2024.doi: 10.48550/ARXIV.2409.12941.URL https://doi.org/10.485 50/arXiv.2409.12941.T. Kwiatkowski, J. Palomaki, O. Redfield, M. Collins, A. P. Parikh, C. Alberti, D. Epstein, I. Polosukhin, J. Devlin, K. Lee, K. Toutanova, L. Jones, M. Kelcey, M. Chang, A. M. Dai, J. Uszkoreit, Q. Le, and S. Petrov.Natural questions: a benchmark for question answering research.Trans.',
 'word_count': 84,
 'char_count': 648,
 'tokens_count': 162,
 'sentence_count': 10,
 'page_number': 39}

In [17]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [18]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False

In [19]:
set = ["my name", "her name", "the naem"]
embeding = model.encode(set)
embeding = dict(zip(set,embeding))

embeding,embeding["my name"].shape

({'my name': array([-1.11268625e-01,  3.23447920e-02, -3.83406430e-02,  2.23897584e-02,
         -4.03141081e-02, -5.62008880e-02,  2.33329892e-01,  3.92086953e-02,
         -1.01079056e-02, -6.38170093e-02,  1.64090171e-02, -3.45565043e-02,
          4.02090475e-02, -7.56014735e-02, -8.34893435e-03,  2.65754201e-02,
         -1.42914457e-02,  6.17227843e-03, -8.46135393e-02, -7.72886723e-02,
         -4.17722203e-02,  6.27690181e-02, -3.24106877e-05, -2.02984530e-02,
         -8.92573446e-02,  6.10290328e-03, -3.12836133e-02,  9.11155716e-02,
         -3.69638987e-02, -1.61543280e-01, -3.80763202e-04,  7.48014171e-03,
          9.98783484e-02,  5.72649240e-02, -4.66819294e-03, -4.17357087e-02,
         -1.26731232e-01, -2.11647116e-02,  5.62063605e-02, -1.07810339e-02,
         -4.70564887e-03, -1.19292378e-01,  2.42646076e-02,  5.37947472e-03,
          7.11646024e-03,  7.88040832e-03,  6.28919399e-04,  2.45067608e-02,
          1.61230154e-02,  9.47958678e-02, -9.59325731e-02, -8.88254344e-02,
         -5.96604124e-02,  1.89629067e-02,  1.31215220e-02, -7.77192116e-02,
          2.44200733e-02,  5.09176888e-02, -3.09433788e-03,  2.27720142e-04,
          4.02659476e-02,  1.79441459e-02, -7.26719722e-02,  3.98123525e-02,
          1.57935228e-02,  8.13505799e-03, -6.94839889e-03,  1.39237260e-02,
          4.64233942e-03, -9.63727478e-03, -2.38478351e-02, -6.72972947e-03,
          7.07241595e-02, -3.35569158e-02, -1.96107011e-02, -1.45386765e-02,
          1.61475968e-02, -1.77206155e-02, -1.31569719e-02,  6.13828711e-02,
         -8.46485645e-02,  4.43959236e-03, -9.70008969e-02, -8.54698941e-03,
         -2.76289228e-02,  4.83488925e-02,  3.65964435e-02, -3.85117196e-02,
         -2.87032891e-02, -5.48661221e-03,  2.66998378e-03, -7.49977306e-02,
          2.27707960e-02, -3.73113109e-03, -2.44772136e-02, -5.23787970e-03,
         -3.77404795e-04, -4.05307487e-02, -3.87832560e-02,  1.85519412e-01,
         -6.50252104e-02,  3.38605940e-02, -5.62591106e-02,  7.47068003e-02,
         -7.21331500e-03, -8.54291487e-03, -5.87107614e-02,  5.19506168e-03,
          5.03448071e-03, -2.29808819e-02, -5.23379445e-02, -2.39632595e-02,
         -5.20041175e-02,  4.00795899e-02,  3.42810787e-02,  7.10860714e-02,
          2.96655251e-03, -2.60683857e-02,  3.05781476e-02, -2.95662526e-02,
          4.49147001e-02,  2.99034193e-02, -8.65571424e-02, -1.93887595e-02,
         -2.02058237e-02,  1.09100323e-02, -1.28696719e-03, -3.38960739e-33,
          5.94925927e-03,  1.89252514e-02, -4.11764515e-04,  1.40347674e-01,
          2.08697356e-02,  1.44510260e-02, -5.77049032e-02,  7.57384906e-03,
         -3.34116220e-02, -4.86569217e-04,  1.18633155e-02,  1.23979505e-02,
         -2.82271113e-02,  6.32571951e-02,  2.87447479e-02,  3.98514085e-02,
         -2.19962653e-02,  5.86498566e-02, -3.66561897e-02,  2.81827971e-02,
         -3.64034548e-02,  6.67514801e-02,  3.82380676e-03,  3.85377407e-02,
         -5.31674959e-02, -1.20789453e-01, -1.26687791e-02, -7.43082836e-02,
          3.59358229e-02,  2.43287664e-02, -5.68793379e-02, -1.62084270e-02,
          8.52153078e-02, -1.06990915e-02,  2.98596490e-02, -8.78667086e-02,
         -1.15061877e-02,  1.56422779e-02, -4.40781973e-02,  1.03963748e-01,
         -9.96418484e-03,  1.12468582e-02, -7.92487711e-02,  4.75009121e-02,
         -2.51976401e-02, -1.84206329e-02,  3.58203016e-02,  5.33686653e-02,
         -9.88210291e-02, -1.01149222e-02, -5.02877943e-02,  3.62836197e-02,
         -1.07462958e-01, -1.13412330e-04, -8.78019333e-02,  2.03306992e-02,
         -1.38518203e-03,  9.96500440e-03, -1.05820335e-01, -1.08255744e-02,
         -5.61656849e-03,  3.54209132e-02, -1.99717619e-02,  1.85143016e-02,
          1.84967909e-02, -4.77539077e-02,  7.75206685e-02, -5.72838970e-02,
          2.59807613e-02,  3.01387962e-02, -7.60095567e-02, -5.30696511e-02,
          4.44191508e-03,  4.09771129e-02,  7.15029091e-02,  6.62904698e-03,
         -8.63275770e-03,  5.87880574e-02, -3.33780460e-02, -9.79794655e-03,
          3.39138173e-02, -1.12671340e-02,  2.68001994e-03,  3.78638767e-02,
          2.98797805e-02, -2.79735844e-03, -1.43966656e-02, -3.69953848e-02,
         -1.53701026e-02, -3.44165936e-02, -1.34393841e-01, -1.39014353e-03,
          1.08393148e-01, -2.45960187e-02, -5.27150072e-02,  1.20526668e-33,
         -1.27881579e-02,  4.35465612e-02,  1.87255442e-02,  9.56210494e-02,
          4.67719277e-03, -2.69599613e-02,  5.32098440e-03,  1.07820250e-01,
          1.92448404e-03,  5.60386106e-02, -2.19701063e-02, -8.23150426e-02,
          4.67026467e-03, -2.90252571e-03,  8.16676393e-02,  4.96276654e-02,
          4.06118371e-02, -1.76352425e-03, -4.65383530e-02,  2.63393857e-03,
         -5.90300076e-02,  5.77563345e-02, -1.08630117e-02, -6.16721511e-02,
         -4.12747264e-03,  1.70052405e-02,  3.90952826e-02,  2.52949875e-02,
          7.08593950e-02,  6.80856630e-02,  5.44352364e-03,  2.39246823e-02,
         -1.16943426e-01,  2.93325614e-02, -2.60607153e-02,  6.45446554e-02,
         -1.89388413e-02, -1.98988318e-02,  1.02715576e-02, -3.32668354e-03,
         -1.41809471e-02,  3.20844539e-02, -7.18638748e-02,  1.08568147e-01,
         -1.31833460e-02, -3.98828760e-02, -5.78845628e-02,  3.01688109e-02,
          1.03621036e-02,  4.26096544e-02, -3.35614569e-02, -6.73615709e-02,
         -6.93707466e-02, -3.82361822e-02,  1.17580371e-03,  3.61947939e-02,
          6.44929931e-02,  2.16483045e-02,  9.53721348e-03,  4.65250248e-03,
          1.59357954e-02,  3.41445617e-02,  6.12316877e-02,  7.34103769e-02,
          3.04529015e-02, -1.78818274e-02, -6.13178238e-02, -4.10456322e-02,
         -2.72018518e-02, -4.76149842e-02, -5.27509153e-02,  2.03911494e-02,
         -4.46444973e-02,  2.69611869e-02, -9.46115404e-02,  3.20556723e-02,
          1.63122043e-02,  2.63475459e-02, -2.50774957e-02,  5.37289754e-02,
          3.02447323e-02,  8.66488442e-02, -2.48541273e-02,  3.00488807e-02,
          1.60619672e-02, -2.64487863e-02,  3.59426886e-02,  8.03072453e-02,
         -2.33004428e-02, -3.87402475e-02,  2.93709449e-02,  3.48940976e-02,
         -1.20453108e-02, -1.63013730e-02, -9.69538093e-02, -1.50699098e-08,
          4.22302336e-02,  5.01372516e-02,  3.11900042e-02, -4.23695706e-03,
          5.10957018e-02,  8.86452645e-02, -3.07834544e-03, -2.18302179e-02,
          4.13647592e-02,  6.56360015e-02,  9.79078114e-02,  5.34658171e-02,
          3.15143280e-02,  9.64246318e-03,  9.51067731e-02, -2.79178713e-02,
         -5.68720922e-02,  8.92905612e-03, -4.92043840e-03, -2.21010502e-02,
         -3.58193442e-02, -2.98429579e-02,  8.19764361e-02, -7.19112381e-02,
          4.26656827e-02,  9.13804118e-03,  3.62761430e-02,  9.37117338e-02,
         -5.74504659e-02,  7.81973526e-02,  1.13642057e-02,  1.17897779e-01,
          1.24910437e-02,  6.13725223e-02, -3.99511233e-02, -9.76389274e-04,
          2.87475120e-02,  8.35279599e-02,  5.63312620e-02, -8.02364387e-03,
         -3.31367925e-02,  5.76818250e-02,  9.86446515e-02, -1.26726413e-02,
         -6.93444088e-02,  6.50679767e-02, -2.79062544e-04, -1.52545506e-02,
         -4.63723950e-03, -2.10706163e-02,  8.71946476e-03,  1.70729700e-02,
          2.25880053e-02,  7.89606124e-02,  2.01135501e-02,  4.21368666e-02,
          3.23688909e-02,  5.68196476e-02, -6.11764304e-02, -5.45439273e-02,
          7.75278881e-02,  5.29308245e-03, -9.12822410e-02,  1.33655407e-02],
        dtype=float32),
  'her name': array([-1.08516753e-01,  1.40265739e-02, -1.97904799e-02,  4.03932743e-02,
         -3.66050228e-02, -1.11377437e-03,  1.42931879e-01,  4.01251763e-02,
         -9.60894208e-03, -7.14014024e-02,  2.60373279e-02, -9.37794670e-02,
         -1.03091989e-02, -7.65828565e-02, -4.02911305e-02,  7.74798095e-02,
          3.67319360e-02,  3.94580290e-02, -9.53143463e-02, -5.77405468e-02,
         -2.17364132e-02, -2.40651127e-02,  3.27846445e-02,  4.04389426e-02,
         -3.74303870e-02,  2.06182059e-03, -5.38017713e-02,  1.28083387e-02,
         -3.16410139e-02, -1.22112036e-01,  1.27528757e-02, -1.95463020e-02,
          4.58517894e-02,  7.62844682e-02, -1.12640327e-02,  3.25133242e-02,
         -7.22716004e-02,  4.53228280e-02,  2.71107592e-02, -1.35517847e-02,
         -1.94000732e-02, -1.14641152e-01, -4.72653434e-02, -4.64220233e-02,
         -3.94387506e-02, -4.94745262e-02,  5.11806048e-02,  3.23776342e-02,
          2.72550602e-02, -2.67371610e-02, -6.49756044e-02, -5.32745868e-02,
         -1.18825585e-01,  2.55619874e-03,  7.93129355e-02, -2.25096662e-02,
          5.34011684e-02,  5.47846667e-02,  3.82738784e-02,  1.02928169e-02,
          6.06006421e-02,  5.18807955e-02, -7.12645799e-02,  4.85623218e-02,
         -5.31429797e-03, -9.10779275e-03,  3.76584232e-02, -4.69222702e-02,
          3.90819609e-02,  6.33177580e-03,  2.00461764e-02,  3.55320945e-02,
         -1.72347482e-03, -3.88698317e-02,  2.61442885e-02,  1.99031085e-02,
          7.56487399e-02,  1.09233288e-02,  2.11198591e-02,  6.88377097e-02,
         -7.15844780e-02,  1.77172031e-02,  5.93701378e-04,  1.94032155e-02,
          4.28238930e-03,  4.30801474e-02, -3.16122845e-02, -2.20458657e-02,
         -2.73831263e-02, -5.10556921e-02, -4.97696958e-02, -6.01557828e-02,
          3.76523435e-02, -1.17023308e-02, -2.06190348e-02, -2.93967966e-02,
         -2.07708105e-02, -2.78657544e-02, -1.51965674e-02,  1.78603202e-01,
         -9.23539847e-02,  1.01476870e-01, -9.04803909e-03,  9.42860842e-02,
         -3.34172323e-02, -5.97187951e-02,  4.86570857e-02, -5.82063990e-03,
         -3.47071104e-02, -1.29232397e-02, -1.64535549e-03, -1.47645818e-02,
         -9.90037173e-02, -5.19066211e-03,  3.52938734e-02,  3.13790366e-02,
          4.73542549e-02, -1.23639442e-02,  2.38937400e-02, -9.74604115e-02,
          4.04632874e-02, -4.96869646e-02, -4.79108095e-02, -2.40672734e-02,
         -5.60441166e-02, -2.87503321e-02,  2.83523314e-02, -3.16461042e-33,
         -3.55150998e-02,  2.95765661e-02,  8.10843781e-02,  8.34556967e-02,
          5.95203340e-02,  2.11191140e-02,  1.59793366e-02,  1.16894878e-02,
          3.46234208e-03, -2.01444123e-02, -2.27780477e-03, -8.82629156e-02,
         -5.42954393e-02, -8.02555159e-02,  1.01886205e-01,  1.27109820e-02,
         -3.21838669e-02,  7.77680501e-02, -7.86050260e-02,  5.41978404e-02,
          4.28525768e-02,  8.47249255e-02,  2.49307156e-02,  5.01612388e-02,
         -3.17425840e-02, -9.03307050e-02,  7.80699551e-02,  1.17246732e-02,
          1.61148468e-03,  3.63856032e-02, -2.68511735e-02,  1.80591771e-04,
          8.83467719e-02, -1.63772423e-02,  5.22142984e-02, -4.44410704e-02,
         -5.81520889e-03, -1.12065962e-02,  3.63275502e-03,  7.74847791e-02,
          2.00558379e-02, -1.65880863e-02,  2.73299795e-02,  1.84893683e-02,
         -1.34903446e-01,  4.32648323e-02,  5.84352762e-02,  1.03551736e-02,
          4.11863625e-02, -6.94354167e-05, -9.41861421e-02,  3.53580080e-02,
         -1.00075364e-01,  5.65286875e-02, -6.15795143e-02,  8.11113492e-02,
          3.31930220e-02, -1.32226348e-02, -1.87826287e-02, -3.98740210e-02,
          1.16541609e-02,  2.19120625e-02, -6.86919093e-02,  9.83216427e-03,
          4.92209345e-02, -5.10650538e-02,  2.85478570e-02, -1.02851346e-01,
          3.24432254e-02,  1.23117240e-02, -1.13674037e-01,  1.87593363e-02,
          2.25785449e-02,  4.31681275e-02, -5.41481413e-02,  2.82280073e-02,
          3.29297073e-02, -2.86127627e-02, -3.13659906e-02, -5.98053867e-03,
          1.17117986e-02,  3.75699103e-02, -2.54161078e-02,  8.43514353e-02,
         -4.38702926e-02, -3.62563902e-03, -2.06886102e-02, -1.42938495e-02,
         -3.48393731e-02, -7.15545788e-02, -6.16804697e-02,  2.06668470e-02,
          7.54758269e-02, -4.97288704e-02, -2.12219022e-02,  1.31706070e-33,
         -5.28453570e-03,  1.54752564e-02, -4.34726067e-02,  6.07264191e-02,
          5.43512404e-02, -1.14345793e-02, -1.48572423e-03,  1.01141565e-01,
         -4.60986514e-03, -1.25182299e-02,  2.76289117e-02, -1.24480300e-01,
          1.22275809e-02, -1.49447499e-02,  6.50415048e-02,  6.65458813e-02,
          8.23930353e-02, -6.69729337e-02, -3.24603245e-02, -6.40190616e-02,
         -9.25135389e-02,  1.08706662e-02,  1.46334050e-02, -7.67764002e-02,
         -2.50701625e-02,  2.24010032e-02,  9.63629261e-02, -2.89403833e-03,
         -4.82729860e-02, -1.27477665e-02,  3.41591351e-02,  1.86355356e-02,
         -7.29231089e-02,  6.13725483e-02, -3.97584178e-02,  4.89615090e-02,
          2.06597541e-02, -4.81188074e-02,  2.89741512e-02,  2.80811600e-02,
          4.12800573e-02,  8.84463359e-03, -2.17011329e-02,  1.02579281e-01,
          2.75864955e-02,  2.12726668e-02, -1.27490703e-02,  4.89049591e-02,
          8.61028358e-02,  2.64374912e-02, -2.06164625e-02, -7.87167847e-02,
         -2.70623267e-02,  8.11803155e-03,  5.95773011e-02, -3.19411866e-02,
          5.81039898e-02,  1.95025485e-02,  3.71583104e-02,  5.88321453e-03,
          1.53963044e-02,  3.51784304e-02, -2.35251486e-02,  7.92885944e-02,
         -3.05616967e-02, -1.99385565e-02, -8.13734978e-02, -1.25664636e-01,
         -2.59873457e-02, -5.24826795e-02,  3.75152892e-03,  2.80722808e-02,
         -4.10410836e-02,  6.88030869e-02, -9.14724767e-02,  1.63114239e-02,
         -9.08275098e-02, -2.50381250e-02, -2.15019993e-02,  3.57076116e-02,
          1.56708341e-02,  2.72470582e-02, -5.09988405e-02,  1.73474418e-03,
          2.54247114e-02, -4.76675294e-03,  8.02697390e-02,  1.11472167e-01,
         -2.18369011e-02, -1.08616360e-01, -1.27692670e-02, -8.22659396e-03,
         -1.66712385e-02, -6.58632666e-02, -7.73727000e-02, -1.59770828e-08,
          1.07898423e-02, -4.41679964e-03,  5.39551079e-02, -6.93758279e-02,
          4.82010059e-02,  7.87588954e-02,  2.61550490e-02, -1.01902643e-02,
          2.86767539e-02,  7.04269111e-02,  8.22024643e-02,  2.00291388e-02,
          5.73523864e-02,  3.10402978e-02,  6.98653832e-02, -3.70384604e-02,
          1.93623900e-02,  1.15336120e-01, -4.57217079e-03,  1.14648081e-02,
         -6.67662825e-03, -4.16181870e-02,  5.23354895e-02, -1.36465162e-01,
          1.81710273e-02,  6.24539936e-03, -1.47890709e-02,  1.09797142e-01,
         -4.21141796e-02,  1.01670334e-02, -3.07445750e-02,  1.13257207e-01,
          3.45925726e-02,  1.96993034e-02,  1.25568768e-03,  3.80589478e-02,
          4.83893938e-02,  2.26375218e-02, -1.67597979e-02,  3.04050222e-02,
         -1.51803959e-02,  2.86381487e-02,  9.29250717e-02, -2.69180015e-02,
         -5.29071502e-02,  2.60878112e-02,  1.27068479e-02, -4.53396775e-02,
         -2.70358985e-03, -1.21021131e-02, -7.78910471e-03,  1.35551365e-02,
          4.36937213e-02,  3.78443561e-02, -2.25434434e-02, -1.41143259e-02,
          2.71069352e-02, -2.39804052e-02, -3.96824293e-02,  1.36236107e-04,
          7.66986050e-03,  1.05079636e-02,  6.80240244e-02,  1.96243376e-02],
        dtype=float32),
  'the naem': array([-6.02948032e-02,  1.08011067e-01, -4.00737338e-02,  2.84985494e-04,
         -5.78279607e-02,  3.90510820e-02,  1.63081419e-02, -6.27290606e-02,
         -2.72917282e-02,  6.48954362e-02, -1.36010172e-02, -1.12080663e-01,
          4.29547280e-02, -3.33019011e-02,  3.84274125e-02,  1.98112204e-04,
         -9.92217194e-03,  3.54609475e-03, -1.39897931e-02, -5.76529317e-02,
         -3.93402465e-02,  4.99699786e-02,  2.77685337e-02, -9.71354917e-03,
         -7.29377046e-02,  3.06829024e-04,  5.28395958e-02,  1.97455827e-02,
          6.62655607e-02, -1.39705911e-01,  5.01704169e-04,  6.13604411e-02,
         -2.77932603e-02,  1.24620153e-02, -6.92578331e-02, -7.66453473e-03,
         -6.53421208e-02, -5.53789642e-03,  1.61085501e-02,  6.49703573e-03,
          7.51554295e-02, -4.55971621e-02, -3.45251057e-03, -3.36859301e-02,
          3.02660000e-02, -7.05948174e-02, -2.51310859e-02, -1.06170252e-02,
          4.80369888e-02,  5.61027862e-02,  3.07876095e-02, -5.77379763e-02,
         -2.93143615e-02,  2.36564856e-02,  6.86284602e-02,  3.42092142e-02,
         -3.66425551e-02, -1.07707486e-01,  2.47657765e-02, -1.87084486e-03,
          8.02794024e-02, -6.56676851e-03, -7.98377842e-02,  6.52273670e-02,
          6.82051927e-02, -9.37174857e-02,  6.07989281e-02,  3.30210477e-02,
         -3.37643772e-02,  2.64172629e-02,  3.17097381e-02, -5.40623516e-02,
          7.14882985e-02, -5.85860544e-05, -5.46505973e-02, -2.46138312e-03,
          6.93024620e-02,  2.13216897e-02,  4.47886623e-02, -1.18316626e-02,
          3.43478732e-02,  3.82323898e-02,  3.36475074e-02, -3.92940603e-02,
          5.31842783e-02, -2.18139892e-03,  8.81356150e-02, -2.54525803e-03,
          2.20382567e-02,  3.63924652e-02, -5.86665832e-02, -3.01842336e-02,
         -8.23795982e-03, -4.73330915e-02,  3.13263573e-02, -3.42283584e-02,
         -2.73819733e-02,  1.87601317e-02,  1.42660886e-02,  1.50500998e-01,
          8.95082727e-02,  1.07485473e-01,  3.75267281e-03,  2.73721144e-02,
          2.50877477e-02,  1.64601337e-02,  1.33112203e-02,  9.83589888e-03,
         -1.44914808e-02,  7.16948211e-02, -4.74362783e-02, -1.86515078e-02,
         -2.84116715e-02, -5.88079728e-03,  3.09783388e-02, -2.49706488e-02,
         -1.90918632e-02, -2.12573223e-02,  5.94185106e-03,  2.15574317e-02,
          6.16734801e-03, -8.75437036e-02, -8.20264071e-02,  3.19139287e-02,
          3.29091623e-02,  5.75121306e-02, -1.16018178e-02, -3.45253050e-33,
         -1.07773477e-02,  7.30653014e-03, -1.63617209e-02, -4.64672521e-02,
          3.70622054e-02,  2.73214988e-02, -2.31236443e-02,  5.66564128e-02,
         -9.57396179e-02, -1.78243946e-02, -2.85459347e-02,  7.88215324e-02,
         -7.85891339e-02,  1.38537595e-02,  8.36980492e-02,  1.03458576e-02,
         -7.59367421e-02, -2.64888853e-02, -3.77846248e-02, -9.53301564e-02,
         -1.12825766e-01,  1.13505058e-01,  7.91863631e-03,  4.91239838e-02,
         -4.25061882e-02,  2.93205604e-02, -2.66452432e-02, -8.48130062e-02,
         -2.70097759e-02,  3.14407460e-02,  4.99393567e-02,  4.24261168e-02,
         -5.03373221e-02,  4.26192880e-02, -8.63207355e-02, -7.60598807e-03,
         -2.76761111e-02, -2.03614999e-02, -5.48336729e-02, -3.26869674e-02,
         -3.44958454e-02,  2.51876116e-02,  1.70822348e-02,  6.42866418e-02,
         -8.01583976e-02, -4.63352986e-02, -1.50233395e-02, -6.26032576e-02,
          8.19116384e-02,  2.78966837e-02,  2.92818923e-03, -3.42843286e-03,
         -4.39038314e-02, -2.01128107e-02,  9.56659019e-03, -1.93480980e-02,
          1.94172200e-04,  4.55721095e-02,  6.61207959e-02, -1.77856628e-02,
          3.08940336e-02,  4.35537398e-02,  3.67996767e-02,  9.71465334e-02,
          3.79517078e-02,  3.49885412e-02, -6.32043043e-03, -6.03008606e-02,
          5.28265983e-02, -3.05552464e-02, -4.74490523e-02,  5.96354268e-02,
          6.59351796e-02,  7.80554712e-02, -1.09362171e-03,  1.21456645e-02,
         -5.06830355e-03, -8.68264213e-02, -9.48877558e-02, -3.95372175e-02,
          2.56637204e-02,  5.39868660e-02, -2.76523307e-02,  6.43403456e-02,
          3.58118378e-02, -1.93711612e-02, -2.32705679e-02, -1.75263584e-02,
          1.40553983e-02, -2.48366445e-02,  1.45109445e-02,  4.32571173e-02,
          1.46898217e-02, -6.47579581e-02, -5.66580519e-02,  3.23796127e-33,
          2.35630143e-02,  1.24059422e-02, -1.02182597e-01,  6.69505894e-02,
          6.45910501e-02, -4.55888584e-02,  4.77873981e-02,  2.63668373e-02,
         -1.10716753e-01,  3.60688344e-02,  1.58360172e-02, -2.84000821e-02,
          1.29867494e-01,  4.72247899e-02,  8.71693417e-02, -5.97081482e-02,
          1.27869159e-01, -8.50947574e-02,  2.15540510e-02, -3.34258899e-02,
          2.41574664e-02, -3.29210646e-02,  1.49753895e-02, -1.72330588e-02,
          1.08727962e-02,  7.22939372e-02,  1.39474878e-02, -7.08194077e-02,
         -7.42303506e-02, -2.18185131e-02,  1.94083471e-02,  3.13056782e-02,
         -1.57291163e-02,  9.62475967e-03, -4.63565961e-02,  3.84134240e-02,
          2.73784250e-02,  6.42660335e-02, -6.87038675e-02, -4.55769263e-02,

In [20]:
from tqdm import tqdm

for chunk in tqdm(pages_and_chunk):
    chunk["embeding"] = model.encode(chunk["paragraphe"])

100%|██████████| 153/153 [00:07<00:00, 20.06it/s]

In [21]:
import random

random.sample(pages_and_chunk,k=1)

[{'paragraphe': '… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ′ 1 𝑁𝑁𝑠𝑠 1 2 𝑁𝑁𝑟𝑟-1 𝑁𝑁𝑟𝑟 Shared Expert Routed Expert Top-𝐾𝐾𝑟𝑟 Attention Feed-Forward Network … 3 4 RMSNorm RMSNorm Transformer Block ×𝐿𝐿 DeepSeekMoE 0 Input Hidden 𝐡𝐡𝑡𝑡 Multi-Head Latent Attention (MLA) 0 {𝐪𝐪𝑡𝑡,𝑖𝑖 𝐶𝐶} {𝐯𝐯𝑡𝑡,𝑖𝑖 𝐶𝐶} {𝐤𝐤𝑡𝑡,𝑖𝑖 𝐶𝐶} Latent 𝐜𝐜𝑡𝑡 𝐾𝐾𝐾𝐾 Latent 𝐜𝐜𝑡𝑡 𝑄𝑄 {𝐪𝐪𝑡𝑡,𝑖𝑖 𝑅𝑅} 𝐤𝐤𝑡𝑡 𝑅𝑅 Cached During Inference Multi-Head Attention concatenate concatenate {[𝐪𝐪𝑡𝑡,𝑖𝑖 𝐶𝐶; 𝐪𝐪𝑡𝑡,𝑖𝑖 𝑅𝑅]} {[𝐤𝐤𝑡𝑡,𝑖𝑖 𝐶𝐶; 𝐤𝐤𝑡𝑡 𝑅𝑅]} … Output Hidden 𝐮𝐮𝑡𝑡 … … … … … 1 … … … … apply RoPE apply RoPE Figure 2 | Illustration of the basic architecture of DeepSeek-V3.Following DeepSeek-V2, we adopt MLA and DeepSeekMoE for efficient inference and economical training.strategy (Wang et al.,2024a) for DeepSeekMoE to mitigate the performance degradation induced by the effort to ensure load balance.Figure 2 illustrates the basic architecture of DeepSeek-V3, and we will briefly review the details of MLA and DeepSeekMoE in this section.2.1.1.Multi-Head Latent Attention For attention, DeepSeek-V3 adopts the MLA architecture.Let 𝑑denote the embedding dimen- sion, 𝑛ℎdenote the number of attention heads, 𝑑ℎdenote the dimension per head, and h𝑡∈R𝑑 denote the attention input for the 𝑡-th token at a given attention layer.The core of MLA is the low-rank joint compression for attention keys and values to reduce Key-Value (KV) cache during inference: c𝐾𝑉 𝑡 = 𝑊𝐷𝐾𝑉h𝑡, (1) [k𝐶 𝑡,1; k𝐶 𝑡,2; ...; k𝐶 𝑡,𝑛ℎ] = k𝐶 𝑡= 𝑊𝑈𝐾c𝐾𝑉 𝑡, (2) k𝑅 𝑡 = RoPE(𝑊𝐾𝑅h𝑡), (3) k𝑡,𝑖= [k𝐶 𝑡,𝑖; k𝑅 𝑡], (4) [v𝐶 𝑡,1; v𝐶 𝑡,2; ...; v𝐶 𝑡,𝑛ℎ] = v𝐶 𝑡= 𝑊𝑈𝑉c𝐾𝑉 𝑡, (5) 7',
  'word_count': 254,
  'char_count': 1549,
  'tokens_count': 387,
  'sentence_count': 9,
  'page_number': 7,
  'embeding': array([-8.87722671e-02, -3.85591723e-02,  1.08293947e-02,  2.78351046e-02,
          6.01950288e-03, -1.96857825e-02, -1.12241432e-01,  2.66212672e-02,
         -3.54095250e-02, -1.75190382e-02, -4.27583717e-02, -8.06580111e-03,
         -5.92707330e-03, -3.33500206e-02, -6.21534558e-03,  1.34485573e-01,
         -9.74791218e-03,  9.22841057e-02, -6.07663281e-02, -6.64562210e-02,
          5.55012412e-02,  3.52930166e-02,  3.84536907e-02, -6.74717426e-02,
          1.60507094e-02,  5.15430532e-02,  4.58846858e-04, -5.20323962e-02,
          3.79336402e-02, -6.46411628e-02,  6.54383227e-02, -2.95936856e-02,
         -3.41966040e-02,  3.03454734e-02, -8.70299116e-02,  1.34087875e-01,
         -1.15662821e-01, -2.88659707e-02, -1.07938247e-02,  1.32814730e-02,
          1.89789440e-02,  2.09602918e-02, -8.54832400e-03,  1.00265872e-02,
          1.39560699e-02,  3.37122902e-02, -4.61284928e-02,  8.63028970e-03,
         -1.46106109e-02, -1.51329003e-02, -4.76510040e-02, -1.16592996e-01,
          7.77374534e-03,  6.15759119e-02,  1.57817570e-03,  5.67979701e-02,
          2.07146760e-02,  1.80045888e-02, -8.10327083e-02,  3.11822128e-02,
          2.77699549e-02, -7.53774121e-02,  1.26363179e-02, -7.41565153e-02,
          2.74460278e-02, -1.40318545e-02,  3.53539214e-02,  2.63652466e-02,
         -1.65667459e-02,  2.70552877e-02, -5.84254526e-02,  5.49922287e-02,
         -2.49728765e-02, -5.15641682e-02,  3.54444161e-02,  4.48704138e-02,
          5.97781204e-02,  3.97419035e-02,  8.30077007e-02, -9.79942307e-02,
          1.54512897e-02,  1.48058701e-02, -1.96011681e-02, -2.17984039e-02,
          4.28459831e-02,  2.06250194e-02, -7.07000941e-02,  1.96681882e-04,
         -4.13527824e-02, -5.87043837e-02, -2.20958237e-02, -9.03703496e-02,
         -3.39084230e-02,  2.68815737e-02,  5.61292842e-02,  4.28635068e-02,
         -6.29607514e-02,  3.11864098e-03, -1.41330183e-01,  5.50429821e-02,
          5.63018955e-02, -3.16009074e-02,  4.76551913e-02,  1.27388164e-03,
         -1.23553015e-02,  1.90544557e-02,  6.06436133e-02,  3.88086364e-02,
          1.81136448e-02, -3.95531319e-02,  8.64190795e-03,  3.55340987e-02,
          3.06925867e-02, -4.56241295e-02, -4.55909818e-02,  7.98503030e-03,
          1.51811028e-02, -2.11458635e-02, -8.56738351e-03,  1.39786545e-02,
         -6.17140085e-02, -2.07497948e-03,  2.96615786e-03, -4.45415676e-02,
          7.07807019e-02, -2.12772712e-02, -7.51043577e-03,  4.89600009e-33,
          7.73169799e-03,  5.48585244e-02, -1.55096045e-02, -6.77580610e-02,
          2.04965676e-04,  5.43861592e-04, -2.17167847e-03, -1.53850426e-03,
         -1.77855771e-02,  3.51469852e-02, -4.58740667e-02, -6.59814328e-02,
         -5.32950088e-02,  1.04949564e-01, -3.60119157e-02, -8.10711011e-02,
         -1.97068951e-03,  8.01360458e-02, -1.82407722e-02,  4.32810234e-03,
          8.69683623e-02, -7.58967269e-03, -2.54246816e-02, -6.62442818e-02,
         -1.33601064e-02, -2.00040825e-03,  1.19437240e-01, -5.05330861e-02,
         -7.08252341e-02, -3.35484248e-04, -8.77340809e-02, -2.68283412e-02,
         -4.16090041e-02, -1.85228186e-03, -7.37663358e-02, -6.03352971e-02,
          2.13147458e-02, -8.80638510e-02,  1.90739445e-02, -1.65788513e-02,
          3.68071385e-02,  5.11923768e-02,  1.37323169e-02, -5.50951548e-02,
         -1.29098371e-01, -5.48494905e-02,  1.56307705e-02,  5.02458774e-02,
         -2.36400459e-02, -3.36148834e-04,  2.61797905e-02, -1.24242390e-02,
         -5.24419779e-03, -8.59861299e-02,  6.65717348e-02, -7.53087625e-02,
          5.05108535e-02,  8.81656632e-02,  1.14040002e-01,  4.16082144e-02,
          1.16459588e-02, -3.81652638e-02,  5.34441229e-03,  8.59049037e-02,
         -3.18934768e-02,  7.80514106e-02,  3.48219797e-02,  8.31844285e-02,
          4.25381325e-02, -1.92071572e-02, -5.91812581e-02,  1.40413390e-02,
          6.97766244e-03,  1.78543087e-02,  8.23645107e-03,  2.31229439e-02,
         -1.63337048e-02, -9.56178382e-02,  2.70804185e-02, -1.02351988e-02,
         -1.49973156e-02,  1.32974699e-01, -4.38637324e-02,  5.32304980e-02,
         -1.33547261e-02,  3.85813192e-02,  2.13631000e-02, -1.54855326e-01,
          5.58837666e-04,  7.94657916e-02, -2.72382218e-02, -1.97847225e-02,
         -4.59738187e-02,  1.74470209e-02, -2.97359321e-02, -3.49951354e-33,
         -1.59328450e-02,  1.78639442e-01, -7.20779970e-02,  5.16754016e-02,
         -1.22486684e-03, -5.85713843e-03,  2.93488353e-02, -4.53328481e-03,
         -2.25136876e-02, -6.86119450e-03,  4.54216497e-03, -4.05343361e-02,
         -1.47186797e-02, -4.06021439e-02,  8.39402229e-02,  1.15601430e-02,
          3.76514765e-03, -2.12271488e-03, -9.70251299e-03, -4.45252694e-02,
          8.19155499e-02,  6.27022013e-02, -1.10990748e-01,  2.12292280e-02,
         -2.73746662e-02,  1.66706834e-02,  3.02670784e-02,  9.40725654e-02,
         -4.81421091e-02, -3.83866671e-03, -4.45901416e-03, -4.79097962e-02,
         -1.71742272e-02,  5.32660028e-03, -1.04340641e-02,  6.15906976e-02,
          4.71048728e-02,  3.03857811e-02,  1.13727991e-02, -1.09112579e-02,
          1.23714864e-01, -2.05152631e-02, -6.68811938e-03,  4.79203202e-02,
         -1.28983006e-01, -6.13530576e-02, -7.84955844e-02, -9.84420776e-02,
         -5.17538860e-02,  3.64500135e-02, -1.13329068e-02, -1.48284109e-02,
         -3.99586819e-02,  3.15741403e-03, -4.23080362e-02, -5.42682968e-03,
         -1.34242773e-02,  3.34273353e-02,  7.63464794e-02,  6.75029471e-04,
         -4.40540388e-02, -6.04891144e-02, -2.42088605e-02, -1.05867796e-02,
          3.82796004e-02, -1.44888851e-04, -1.93436630e-02, -3.31092775e-02,
          2.88379677e-02,  1.65063348e-02,  1.21368095e-02,  7.03624859e-02,
          6.77521080e-02,  6.84449226e-02,  7.60655627e-02,  4.26003709e-02,
          2.37527322e-02, -5.84339947e-02, -2.76579056e-02, -2.47259364e-02,
         -5.14185242e-02, -2.36337837e-02, -3.64830829e-02,  3.02357804e-02,
          5.75667247e-02,  5.69922850e-02,  6.19989149e-02,  5.25432788e-02,
         -1.66251510e-02,  6.23543689e-04, -1.49364704e-02,  1.09060600e-01,
         -6.69601038e-02,  4.03926894e-02, -3.23925843e-03, -5.07394518e-08,
         -7.80876279e-02,  2.65805572e-02,  2.26859078e-02,  8.19539651e-03,
          2.24578716e-02, -4.79866117e-02,  1.05045037e-02,  1.07136570e-01,
         -2.95899063e-02,  5.96073223e-03,  1.40407071e-01, -3.92402746e-02,
         -3.42738330e-02, -8.52106605e-03,  5.41049466e-02,  6.52781352e-02,
          1.80691201e-03,  2.74303630e-02, -5.38633466e-02, -6.59972504e-02,
          2.41825096e-02,  6.18072934e-02,  5.00086546e-02, -1.61338467e-02,
          8.37846249e-02, -6.33204430e-02, -2.59196628e-02,  1.00391053e-01,
          1.95024833e-02,  4.13046917e-03,  7.59910978e-03,  7.36431032e-02,
         -1.19210621e-02, -1.83788054e-02,  4.89503238e-03,  1.41288310e-01,
          1.25635909e-02,  6.14161305e-02,  3.19471397e-02,  8.73219445e-02,
         -4.74622436e-02,  8.71868618e-03, -4.02442217e-02,  4.82514165e-02,
          2.02540308e-03, -2.97741704e-02, -6.22651614e-02, -5.27282543e-02,
         -1.63752548e-02, -7.22478479e-02,  1.21601205e-02, -1.76356733e-02,
          5.26805744e-02,  5.18452153e-02,  3.24236415e-02, -3.30656674e-03,
          1.35949338e-02, -1.25147793e-02, -1.12028569e-02,  5.32510579e-02,
          1.00799203e-02, -5.69271259e-02, -6.42086938e-02,  1.85409945e-03],
        dtype=float32)}]

In [22]:
page_and_Embedding_df = pd.DataFrame(pages_and_chunk)
page_and_Embedding_file_name="page_and_Embedding.csv"
page_and_Embedding_path = os.path.join(os.getcwd(),page_and_Embedding_file_name)
page_and_Embedding_df.to_csv(page_and_Embedding_path,index=False)

In [23]:
pages_and_chunk[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embeding': array([-5.76343089e-02,  1.86270159e-02, -6.96300119e-02, -5.02149435e-03,
        -6.43548444e-02,  5.39917238e-02, -4.61325124e-02,  3.96139659e-02,
        -5.72229438e-02,  5.44092571e-03, -4.39483821e-02, -6.78669754e-03,
         4.00273986e-02, -1.59042422e-02,  7.62050925e-03,  4.98709306e-02,
         1.28310844e-01, -3.56771462e-02, -4.98870090e-02, -8.15588608e-02,
         4.34629768e-02, -4.59041521e-02,  8.90599564e-02,  1.54036777e-02,
        -7.79620782e-02,  3.06390692e-02, -5.25193140e-02, -6.64413199e-02,
         3.31791677e-02, -6.93641007e-02, -6.77241525e-03,  3.17596318e-03,
         5.10903522e-02, -8.24809372e-02, -8.37938637e-02,  1.99515466e-02,
        -5.22204340e-02, -5.73824346e-02,  1.78819112e-02,  2.67783925e-02,
         1.22638347e-04, -3.79559770e-02,  2.66227219e-03,  2.12215781e-02,
         3.83332856e-02, -2.20189225e-02, -5.95768094e-02, -2.69227941e-02,
        -4.48380671e-02, -8.05420429e-02, -1.64256189e-02, -6.48152456e-02,
         5.06795803e-03, -2.43171910e-03, -5.40565774e-02, -8.12953338e-03,
         4.19081151e-02, -2.15617474e-02, -1.57968570e-02,  3.31748202e-02,
        -8.01364481e-02, -1.54115716e-02, -5.74465469e-02,  1.44827357e-02,
         3.75399292e-02, -9.97637212e-02, -8.92186724e-03, -6.80584386e-02,
         5.85165806e-02, -3.27328183e-02, -2.40222551e-03, -6.30813884e-03,
         4.79136780e-02, -8.28514770e-02, -2.71539316e-02, -4.32538847e-03,
         2.57454552e-02, -3.27681378e-02,  2.09331289e-02, -7.94779435e-02,
         1.91956144e-02, -1.16448877e-02,  9.50383861e-03, -4.35636081e-02,
        -3.66505943e-02, -9.70793813e-02,  8.94263387e-03, -1.46270031e-02,
         5.45645915e-02,  6.92140684e-02,  1.05012462e-01,  1.10859916e-01,
        -1.34864375e-02,  8.77503678e-03, -1.14631315e-03,  1.05595514e-01,
        -3.30545083e-02,  1.49801150e-02, -7.64259174e-02,  4.41714227e-02,
         8.06646571e-02,  3.79375182e-02, -1.73761491e-02,  4.10950817e-02,
        -2.40345374e-02, -4.80216332e-02,  1.50005687e-02,  3.03008668e-02,
         4.40819236e-03, -1.10763721e-01,  5.87852411e-02,  5.47064804e-02,
         8.96657445e-03, -4.55786735e-02, -4.77992222e-02,  8.83814320e-02,
        -1.86152160e-02,  2.07292084e-02, -2.19885111e-02,  7.60801136e-02,
         1.60370376e-02, -1.16604447e-01,  1.25039130e-01, -7.68830627e-03,
         3.03482283e-02, -1.52714215e-02, -6.32316694e-02, -2.49990650e-32,
        -8.10585096e-02, -5.51192462e-02, -1.33700026e-02, -5.99329695e-02,
         1.10146534e-02,  2.59977579e-02,  3.60029824e-02,  4.94826166e-03,
         1.81739719e-03, -7.88456500e-02, -5.46012186e-02, -3.52931283e-02,
        -6.31593820e-03,  6.83288351e-02,  1.65331978e-02, -8.12145993e-02,
         5.00019547e-03,  1.31413475e-01, -4.67871837e-02, -5.32844104e-02,
         6.42249584e-02, -5.45797758e-02, -4.81014848e-02,  2.70939693e-02,
         8.49387869e-02, -5.11556305e-03,  8.52152407e-02,  4.48352210e-02,
        -9.25949663e-02,  8.05959385e-03,  2.34441031e-02,  4.24520262e-02,
        -5.95207587e-02,  1.05523672e-02, -6.87900186e-02,  6.73955597e-04,
         4.62167561e-02, -6.29212381e-03,  3.83899212e-02,  2.46818806e-03,
        -9.38247964e-02,  5.74742146e-02,  7.89215118e-02, -2.18204521e-02,
        -4.18462269e-02, -5.63514419e-02, -4.13205549e-02,  2.18046289e-02,
        -9.33824629e-02,  3.08046341e-02, -6.42290562e-02, -1.99530255e-02,
         3.61034647e-02, -3.50958519e-02,  3.22242379e-02,  6.15458563e-02,
         5.70552312e-02,  1.59136429e-02, -2.45294496e-02,  9.99930948e-02,
         5.59420660e-02, -4.10363935e-02, -6.51615188e-02,  2.00893637e-02,
         4.90734950e-02,  3.07649784e-02, -5.85499853e-02, -5.81291597e-03,
         3.74067426e-02,  4.96496595e-02, -6.38445094e-02, -2.64050672e-03,
         5.88807613e-02, -4.38632183e-02,  6.60317168e-02, -7.83692822e-02,
         6.36432096e-02,  6.92378683e-03, -8.18328783e-02, -3.14816386e-02,
        -3.57161718e-03,  1.01911955e-01, -5.81695773e-02, -2.84043960e-02,
         1.21232634e-02,  2.11809855e-03, -4.04892489e-02, -5.31520732e-02,
        -1.43812811e-02,  3.91902775e-02, -4.59962040e-02, -2.05653044e-03,
         6.13807235e-03,  9.19524506e-02,  1.95201188e-02,  1.56344731e-32,
         2.62332689e-02,  9.64797139e-02, -6.58232272e-02,  4.79708910e-02,
         8.70390609e-02,  4.03307155e-02,  1.44298906e-02, -4.76209149e-02,
        -8.86883773e-03,  1.93301290e-02, -1.29635502e-02,  4.97945249e-02,
        -6.92616329e-02,  3.16582173e-02, -3.13160084e-02, -3.00070513e-02,
        -4.07405430e-03, -1.46255363e-02, -1.23309707e-02,  2.74193771e-02,
         8.34065452e-02,  6.97516873e-02, -1.05787575e-01,  8.78470987e-02,
         5.59021253e-03, -1.86683796e-02, -6.24802597e-02, -3.62287904e-03,
        -3.38803902e-02,  4.26130146e-02, -3.24046537e-02, -9.78928283e-02,
         1.34581318e-02,  4.51985151e-02, -4.52557839e-02, -1.61164198e-02,
         8.62949565e-02,  2.88821347e-02, -8.69684760e-03,  1.49755538e-01,
         3.60441953e-02,  2.37741731e-02, -3.88363153e-02,  5.74692823e-02,
        -2.12659724e-02, -4.92210314e-03, -7.09288800e-03, -5.32867201e-02,
        -8.20563361e-02,  4.31006737e-02, -3.67642343e-02, -2.71880813e-02,
        -1.35272190e-01, -2.56683659e-02, -2.91683674e-02, -8.94128233e-02,
         1.41425878e-02,  7.27051403e-03, -7.77577758e-02, -9.60377790e-03,
        -4.91312779e-02,  5.92100658e-02, -2.87620984e-02, -1.12884715e-02,
        -2.84832418e-02, -8.74997769e-03,  1.74761545e-02,  4.95307334e-02,
         3.17867659e-02,  3.20893675e-02, -8.73306468e-02, -7.09948875e-03,
         5.87638840e-02, -6.80635974e-04,  3.69722769e-02, -2.14158203e-02,
         9.13142721e-05, -1.07634170e-02, -5.68082631e-02, -2.79051047e-02,
        -1.05843849e-01, -9.68925422e-04,  1.14391260e-02, -9.73239169e-03,
        -4.10723649e-02,  3.72072868e-02,  4.89398316e-02,  4.51455526e-02,
         1.92308445e-02, -1.15438197e-02,  5.01308450e-03,  2.97262073e-02,
         6.92122653e-02,  1.63906384e-02,  8.69887043e-03, -4.69932324e-08,
         9.97949112e-03, -5.11729419e-02,  7.04231337e-02,  6.84351623e-02,
         3.95479426e-02,  1.35848328e-04, -7.60001689e-02,  4.00973484e-02,
        -3.73462737e-02, -5.88454772e-03,  1.22180916e-01,  8.05510674e-03,
        -1.34176249e-02,  1.23289088e-02,  2.55202316e-02,  1.09683685e-02,
         6.05722074e-04, -2.16499418e-02, -5.05288616e-02, -1.30556235e-02,
         1.05004301e-02,  1.00650650e-03, -3.34202237e-02, -1.19562764e-02,
         3.54323685e-02, -7.30694830e-02, -1.92586500e-02,  6.82981983e-02,
        -5.41706793e-02, -3.45374197e-02,  5.45378998e-02,  2.30299719e-02,
         1.27890138e-02,  2.67073568e-02,  2.77423766e-02,  1.66754648e-02,
        -9.89085250e-03, -1.50999296e-02,  1.57296378e-02,  1.33830816e-01,
         4.96076886e-03, -5.15579339e-03,  2.67172828e-02,  9.28951893e-03,
         5.75693659e-02, -3.65180857e-02, -1.39185548e-01, -5.01695909e-02,
         4.19337489e-02, -7.75044337e-02, -4.21275496e-02, -2.39885356e-02,
        -6.29835874e-02,  7.19865337e-02,  1.34467110e-01, -8.73651449e-03,
        -7.97660276e-03, -6.91411197e-02,  3.03548444e-02,  6.15585931e-02,
        -2.00267625e-03, -6.09332956e-02, -6.89558908e-02, -6.41390383e-02],
       dtype=float32)}

In [24]:
pages_and_chunk=[]
pages_and_chunk

[]

In [29]:
pages_and_chunk =pd.read_csv(page_and_Embedding_path)
data = pages_and_chunk.to_dict(orient="records")
data[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embeding': '[-5.76343089e-02  1.86270159e-02 -6.96300119e-02 -5.02149435e-03\n -6.43548444e-02  5.39917238e-02 -4.61325124e-02  3.96139659e-02\n -5.72229438e-02  5.44092571e-03 -4.39483821e-02 -6.78669754e-03\n  4.00273986e-02 -1.59042422e-02  7.62050925e-03  4.98709306e-02\n  1.28310844e-01 -3.56771462e-02 -4.98870090e-02 -8.15588608e-02\n  4.34629768e-02 -4.59041521e-02  8.90599564e-02  1.54036777e-02\n -7.79620782e-02  3.06390692e-02 -5.25193140e-02 -6.64413199e-02\n  3.31791677e-02 -6.93641007e-02 -6.77241525e-03  3.17596318e-03\n  5.10903522e-02 -8.24809372e-02 -8.37938637e-02  1.99515466e-02\n -5.22204340e-02 -5.73824346e-02  1.78819112e-02  2.67783925e-02\n  1.22638347e-04 -3.79559770e-02  2.66227219e-03  2.12215781e-02\n  3.83332856e-02 -2.20189225e-02 -5.95768094e-02 -2.69227941e-02\n -4.48380671e-02 -8.05420429e-02 -1.64256189e-02 -6.48152456e-02\n  5.06795803e-03 -2.43171910e-03 -5.40565774e-02 -8.12953338e-03\n  4.19081151e-02 -2.15617474e-02 -1.57968570e-02  3.31748202e-02\n -8.01364481e-02 -1.54115716e-02 -5.74465469e-02  1.44827357e-02\n  3.75399292e-02 -9.97637212e-02 -8.92186724e-03 -6.80584386e-02\n  5.85165806e-02 -3.27328183e-02 -2.40222551e-03 -6.30813884e-03\n  4.79136780e-02 -8.28514770e-02 -2.71539316e-02 -4.32538847e-03\n  2.57454552e-02 -3.27681378e-02  2.09331289e-02 -7.94779435e-02\n  1.91956144e-02 -1.16448877e-02  9.50383861e-03 -4.35636081e-02\n -3.66505943e-02 -9.70793813e-02  8.94263387e-03 -1.46270031e-02\n  5.45645915e-02  6.92140684e-02  1.05012462e-01  1.10859916e-01\n -1.34864375e-02  8.77503678e-03 -1.14631315e-03  1.05595514e-01\n -3.30545083e-02  1.49801150e-02 -7.64259174e-02  4.41714227e-02\n  8.06646571e-02  3.79375182e-02 -1.73761491e-02  4.10950817e-02\n -2.40345374e-02 -4.80216332e-02  1.50005687e-02  3.03008668e-02\n  4.40819236e-03 -1.10763721e-01  5.87852411e-02  5.47064804e-02\n  8.96657445e-03 -4.55786735e-02 -4.77992222e-02  8.83814320e-02\n -1.86152160e-02  2.07292084e-02 -2.19885111e-02  7.60801136e-02\n  1.60370376e-02 -1.16604447e-01  1.25039130e-01 -7.68830627e-03\n  3.03482283e-02 -1.52714215e-02 -6.32316694e-02 -2.49990650e-32\n -8.10585096e-02 -5.51192462e-02 -1.33700026e-02 -5.99329695e-02\n  1.10146534e-02  2.59977579e-02  3.60029824e-02  4.94826166e-03\n  1.81739719e-03 -7.88456500e-02 -5.46012186e-02 -3.52931283e-02\n -6.31593820e-03  6.83288351e-02  1.65331978e-02 -8.12145993e-02\n  5.00019547e-03  1.31413475e-01 -4.67871837e-02 -5.32844104e-02\n  6.42249584e-02 -5.45797758e-02 -4.81014848e-02  2.70939693e-02\n  8.49387869e-02 -5.11556305e-03  8.52152407e-02  4.48352210e-02\n -9.25949663e-02  8.05959385e-03  2.34441031e-02  4.24520262e-02\n -5.95207587e-02  1.05523672e-02 -6.87900186e-02  6.73955597e-04\n  4.62167561e-02 -6.29212381e-03  3.83899212e-02  2.46818806e-03\n -9.38247964e-02  5.74742146e-02  7.89215118e-02 -2.18204521e-02\n -4.18462269e-02 -5.63514419e-02 -4.13205549e-02  2.18046289e-02\n -9.33824629e-02  3.08046341e-02 -6.42290562e-02 -1.99530255e-02\n  3.61034647e-02 -3.50958519e-02  3.22242379e-02  6.15458563e-02\n  5.70552312e-02  1.59136429e-02 -2.45294496e-02  9.99930948e-02\n  5.59420660e-02 -4.10363935e-02 -6.51615188e-02  2.00893637e-02\n  4.90734950e-02  3.07649784e-02 -5.85499853e-02 -5.81291597e-03\n  3.74067426e-02  4.96496595e-02 -6.38445094e-02 -2.64050672e-03\n  5.88807613e-02 -4.38632183e-02  6.60317168e-02 -7.83692822e-02\n  6.36432096e-02  6.92378683e-03 -8.18328783e-02 -3.14816386e-02\n -3.57161718e-03  1.01911955e-01 -5.81695773e-02 -2.84043960e-02\n  1.21232634e-02  2.11809855e-03 -4.04892489e-02 -5.31520732e-02\n -1.43812811e-02  3.91902775e-02 -4.59962040e-02 -2.05653044e-03\n  6.13807235e-03  9.19524506e-02  1.95201188e-02  1.56344731e-32\n  2.62332689e-02  9.64797139e-02 -6.58232272e-02  4.79708910e-02\n  8.70390609e-02  4.03307155e-02  1.44298906e-02 -4.76209149e-02\n -8.86883773e-03  1.93301290e-02 -1.29635502e-02  4.97945249e-02\n -6.92616329e-02  3.16582173e-02 -3.13160084e-02 -3.00070513e-02\n -4.07405430e-03 -1.46255363e-02 -1.23309707e-02  2.74193771e-02\n  8.34065452e-02  6.97516873e-02 -1.05787575e-01  8.78470987e-02\n  5.59021253e-03 -1.86683796e-02 -6.24802597e-02 -3.62287904e-03\n -3.38803902e-02  4.26130146e-02 -3.24046537e-02 -9.78928283e-02\n  1.34581318e-02  4.51985151e-02 -4.52557839e-02 -1.61164198e-02\n  8.62949565e-02  2.88821347e-02 -8.69684760e-03  1.49755538e-01\n  3.60441953e-02  2.37741731e-02 -3.88363153e-02  5.74692823e-02\n -2.12659724e-02 -4.92210314e-03 -7.09288800e-03 -5.32867201e-02\n -8.20563361e-02  4.31006737e-02 -3.67642343e-02 -2.71880813e-02\n -1.35272190e-01 -2.56683659e-02 -2.91683674e-02 -8.94128233e-02\n  1.41425878e-02  7.27051403e-03 -7.77577758e-02 -9.60377790e-03\n -4.91312779e-02  5.92100658e-02 -2.87620984e-02 -1.12884715e-02\n -2.84832418e-02 -8.74997769e-03  1.74761545e-02  4.95307334e-02\n  3.17867659e-02  3.20893675e-02 -8.73306468e-02 -7.09948875e-03\n  5.87638840e-02 -6.80635974e-04  3.69722769e-02 -2.14158203e-02\n  9.13142721e-05 -1.07634170e-02 -5.68082631e-02 -2.79051047e-02\n -1.05843849e-01 -9.68925422e-04  1.14391260e-02 -9.73239169e-03\n -4.10723649e-02  3.72072868e-02  4.89398316e-02  4.51455526e-02\n  1.92308445e-02 -1.15438197e-02  5.01308450e-03  2.97262073e-02\n  6.92122653e-02  1.63906384e-02  8.69887043e-03 -4.69932324e-08\n  9.97949112e-03 -5.11729419e-02  7.04231337e-02  6.84351623e-02\n  3.95479426e-02  1.35848328e-04 -7.60001689e-02  4.00973484e-02\n -3.73462737e-02 -5.88454772e-03  1.22180916e-01  8.05510674e-03\n -1.34176249e-02  1.23289088e-02  2.55202316e-02  1.09683685e-02\n  6.05722074e-04 -2.16499418e-02 -5.05288616e-02 -1.30556235e-02\n  1.05004301e-02  1.00650650e-03 -3.34202237e-02 -1.19562764e-02\n  3.54323685e-02 -7.30694830e-02 -1.92586500e-02  6.82981983e-02\n -5.41706793e-02 -3.45374197e-02  5.45378998e-02  2.30299719e-02\n  1.27890138e-02  2.67073568e-02  2.77423766e-02  1.66754648e-02\n -9.89085250e-03 -1.50999296e-02  1.57296378e-02  1.33830816e-01\n  4.96076886e-03 -5.15579339e-03  2.67172828e-02  9.28951893e-03\n  5.75693659e-02 -3.65180857e-02 -1.39185548e-01 -5.01695909e-02\n  4.19337489e-02 -7.75044337e-02 -4.21275496e-02 -2.39885356e-02\n -6.29835874e-02  7.19865337e-02  1.34467110e-01 -8.73651449e-03\n -7.97660276e-03 -6.91411197e-02  3.03548444e-02  6.15585931e-02\n -2.00267625e-03 -6.09332956e-02 -6.89558908e-02 -6.41390383e-02]'}