In [1]:
!nvidia-smi

Sat May  2 07:37:05 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.86                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro T1000                 WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8              3W /   50W |     160MiB /   4096MiB |     29%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            3252    C+G   ...ms\Microsoft VS Code\Code.exe      N/A      |
|    0   N/A  N/A           16612    C+G   ...s\Win64\EpicGamesLauncher.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [2]:
import os  # library to deal with operating system
import requests # library use to dell with GET/POST requestes

#the url of book we test on 
url= r"https://arxiv.org/pdf/2412.19437"

#this path automatic assinge to the same folder we are her and name the book : "Data_file.pdf"
pdf_path=os.path.join(os.getcwd() , "Data_file.pdf")

# Confirming the existing of book and reinstall if not found 
if not os.path.exists(pdf_path):    
    response= requests.get(url) #downloadin is get request 
    if response.status_code == 200:
        with open(pdf_path,"wb") as f:  # more efficient than `for` in c level 
            f.write(response.content)
        print(f"[INFO] the file is downloaded at : {pdf_path}")
else:
    print(f"[INFO] file exist : {pdf_path} ")

[INFO] file exist : e:\Tests\Data_file.pdf

In [3]:
# import fitz  # PyMuPDF
# pages_and_texts=[]
# doc = fitz.open("Data_file.pdf")
# data_text = []

# for page_num , page in enumerate(doc):
#     text = page.get_text()
#     pages_and_texts.append({
#         "text_of_page" : text,
#         "page_number" : page_num + 1
#     })
# print(pages_and_texts[3]) 
# for text in pages_and_texts:
#     text["text_of_page"] =text["text_of_page"].replace(r"-\n"," ").strip()
# print(pages_and_texts[3] )

In [4]:
import fitz  # PyMuPDF :{ library used to hadnel PDF files }.

# `clean_text` : remove the spaces from begnining and ending of string
def clean_text(text: str):  
    text = text.replace("\n", " ").strip()
    return text


# open opdf and make array of pages with some statistics and use `clean_text`
def open_pdf(file_path:str):
    document=fitz.open(file_path)
    pages_and_texts=[]
    for page_num , page in enumerate(document):
        text = page.get_text()
        cleaned_text = clean_text(text)
        pages_and_texts.append({
            "text_of_page" : cleaned_text,
            "page_count_char" : len(cleaned_text),
            "page_count_word" : len(cleaned_text.split(" ")),
            "page_count_sentences" : len(cleaned_text.split(". ")),
            "tokens_num" : len(cleaned_text) // 4 , # i dont get it but it is what it is 
            "page_number" : page_num + 1
        })
    return pages_and_texts

pages_and_texts=open_pdf("Data_file.pdf")
pages_and_texts[3]

{'text_of_page': '1. Introduction In recent years, Large Language Models (LLMs) have been undergoing rapid iteration and evolution (Anthropic, 2024; Google, 2024; OpenAI, 2024a), progressively diminishing the gap to- wards Artificial General Intelligence (AGI). Beyond closed-source models, open-source models, including DeepSeek series (DeepSeek-AI, 2024a,b,c; Guo et al., 2024), LLaMA series (AI@Meta, 2024a,b; Touvron et al., 2023a,b), Qwen series (Qwen, 2023, 2024a,b), and Mistral series (Jiang et al., 2023; Mistral, 2024), are also making significant strides, endeavoring to close the gap with their closed-source counterparts. To further push the boundaries of open-source model capa- bilities, we scale up our models and introduce DeepSeek-V3, a large Mixture-of-Experts (MoE) model with 671B parameters, of which 37B are activated for each token. With a forward-looking perspective, we consistently strive for strong model performance and economical costs. Therefore, in terms of architecture, DeepSeek-V3 still adopts Multi-head Latent Attention (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for cost-effective training. These two architectures have been validated in DeepSeek- V2 (DeepSeek-AI, 2024c), demonstrating their capability to maintain robust model performance while achieving efficient training and inference. Beyond the basic architecture, we implement two additional strategies to further enhance the model capabilities. Firstly, DeepSeek-V3 pi- oneers an auxiliary-loss-free strategy (Wang et al., 2024a) for load balancing, with the aim of minimizing the adverse impact on model performance that arises from the effort to encourage load balancing. Secondly, DeepSeek-V3 employs a multi-token prediction training objective, which we have observed to enhance the overall performance on evaluation benchmarks. In order to achieve efficient training, we support the FP8 mixed precision training and implement comprehensive optimizations for the training framework. Low-precision training has emerged as a promising solution for efficient training (Dettmers et al., 2022; Kalamkar et al., 2019; Narang et al., 2017; Peng et al., 2023b), its evolution being closely tied to advancements in hardware capabilities (Luo et al., 2024; Micikevicius et al., 2022; Rouhani et al., 2023a). In this work, we introduce an FP8 mixed precision training framework and, for the first time, validate its effectiveness on an extremely large-scale model. Through the support for FP8 computation and storage, we achieve both accelerated training and reduced GPU memory usage. As for the training framework, we design the DualPipe algorithm for efficient pipeline parallelism, which has fewer pipeline bubbles and hides most of the communication during training through computation-communication overlap. This overlap ensures that, as the model further scales up, as long as we maintain a constant computation-to-communication ratio, we can still employ fine-grained experts across nodes while achieving a near-zero all-to-all communication overhead. In addition, we also develop efficient cross-node all-to-all communication kernels to fully utilize InfiniBand (IB) and NVLink bandwidths. Furthermore, we meticulously optimize the memory footprint, making it possible to train DeepSeek-V3 without using costly tensor parallelism. Combining these efforts, we achieve high training efficiency. During pre-training, we train DeepSeek-V3 on 14.8T high-quality and diverse tokens. The pre-training process is remarkably stable. Throughout the entire training process, we did not encounter any irrecoverable loss spikes or have to roll back. Next, we conduct a two-stage context length extension for DeepSeek-V3. In the first stage, the maximum context length is extended to 32K, and in the second stage, it is further extended to 128K. Following this, we conduct post-training, including Supervised Fine-Tuning (SFT) and Reinforcement Learning (RL) on the base model of DeepSeek-V3, to align it with human preferences and further unlock its potential. During the post-training stage, we distill the reasoning capability from the DeepSeek- R1 series of models, and meanwhile carefully maintain the balance between model accuracy 4',
 'page_count_char': 4248,
 'page_count_word': 594,
 'page_count_sentences': 26,
 'tokens_num': 1062,
 'page_number': 4}

In [5]:
import pandas as pd

# use `DataFrame` to display top 10 rows 
df = pd.DataFrame(pages_and_texts)
df.head(10)

,text_of_page,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,1817,238,11,454,1
1,Contents 1 Introduction 4 2 Architecture 6 2.1...,2634,919,766,658,2
2,4.5.3 Batch-Wise Load Balance VS. Sequence-Wis...,1715,572,462,428,3
3,"1. Introduction In recent years, Large Languag...",4248,594,26,1062,4
4,Training Costs Pre-Training Context Extension ...,3287,468,21,821,5
5,verification and reflection patterns of R1 int...,3475,457,23,868,6
6,… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ...,1557,262,8,389,7
7,where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vecto...,2236,353,9,559,8
8,where 𝑁𝑠and 𝑁𝑟denote the numbers of shared exp...,2901,455,17,725,9
9,Main Model (Next Token Prediction) Embedding L...,2904,451,23,726,10

In [6]:
# use this `DataFrame` to do some statistics 
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
count,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00
std,799.86,178.18,124.63,199.99,15.44
min,699.00,99.00,1.00,174.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00
50%,2992.00,457.00,23.00,748.00,27.00
75%,3281.00,516.00,29.00,820.00,40.00
max,4248.00,919.00,766.00,1062.00,53.00

# Turn text to sentences

In [7]:
from spacy.lang.en import English

nlp= English() # just create pipline (do nothing to text)

# add sentencizer to pipeliine (split text)
nlp.add_pipe("sentencizer")

#example sentence to test
semtemces = "this my name . hellow mr.ahmed . what is your name ?"
doc = nlp(semtemces)

# list the sentences to show 
list(doc.sents)

[this my name ., hellow mr.ahmed ., what is your name ?]

# Now try the `data`

In [8]:
# turn all text on each page to sentences and count it
for page in pages_and_texts:
    page["sentences"] = list(nlp(page["text_of_page"]).sents)
    page["sentences_num"] =len(page["sentences"])

#make sure tha all sentences is string not spacy type
for page in pages_and_texts:
    page["sentences"]=[str(sentences) for sentences in page["sentences"]]

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25}

In [9]:
#read specific sentence :{page number 6 , sentences number 7}
pages_and_texts[5]["sentences"][6]

'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.'

In [10]:
# see some statistics about this data 
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num
count,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94
std,799.86,178.18,124.63,199.99,15.44,14.44
min,699.00,99.00,1.00,174.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00

In [11]:
# test spliting way to split senetences to chuncks
test=list(range(1,25))
input_list=[]
slice_size=10
x=[test[i:i+slice_size] for i in range(0,len(test),slice_size)]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24]]

In [12]:
# define `chunker` to chunk one sentences list to list of punch of list strings 
def chunker (input_list : list[str],slice_size:int= slice_size)->list[list[str]]:
    return[input_list[i:i+slice_size] for i in range(0,len(input_list),slice_size)]

# apply `chunker` and count it
for page in pages_and_texts:
    page["sentences_chunk"] = chunker(page["sentences"])
    page["sentences_chunk_num"] =len( page["sentences_chunk"]) 

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25,
 'sentences_chunk': [['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
   'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
   'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
   'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
   '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
   'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
   'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
   'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
   '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
   'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.'],
  ['In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
   'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
   'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
   'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
   'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
   '2.',
   'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
   '2024) for economical training.',
   'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
   'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).'],
  ['2.1.',
   'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
   '2017) framework.',
   'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
   'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6']],
 'sentences_chunk_num': 3}

In [13]:
# read the statistics agien
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num,sentences_chunk_num
count,53.00,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94,2.89
std,799.86,178.18,124.63,199.99,15.44,14.44,1.40
min,699.00,99.00,1.00,174.00,1.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00,2.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00,3.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00,3.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00,6.00

In [14]:
# rejoine all chunks to make pargaphe almost 10 sentences
pages_and_chunk=[]
for page in pages_and_texts:
    for chunk in page["sentences_chunk"]:
        chunk_dict = {}

        # join all sentences in chunk to be one paragraphe
        paragragh = "".join(chunk).replace("  "," ").strip()
        chunk_dict ["paragraphe"] = paragragh
        
        # Calculate statistics
        words = paragragh.split(" ")
        word_count = len(words)
        char_count = len(paragragh)
        tokens_count = char_count // 4  # approximate tokens
        sentence_count = len(chunk)  # number of sentences in chunk
        
        # Store statistics
        chunk_dict["word_count"] = word_count
        chunk_dict["char_count"] = char_count
        chunk_dict["tokens_count"] = tokens_count
        chunk_dict["sentence_count"] = sentence_count
        chunk_dict ["page_number"] = page["page_number"]

        pages_and_chunk.append(chunk_dict)
pages_and_chunk[5] ,len(pages_and_chunk),len(pages_and_texts)

({'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
  'word_count': 298,
  'char_count': 830,
  'tokens_count': 207,
  'sentence_count': 10,
  'page_number': 3},
 153,
 53)

In [15]:
# read the statistics agien
df = pd.DataFrame(pages_and_chunk)
df.describe().round(2)

       word_count  char_count  tokens_count  sentence_count  page_number
count      153.00      153.00        153.00          153.00       153.00
mean       157.03      974.48        243.26            8.29        26.52
std        145.88      584.64        146.14            2.95        13.86
min          1.00        1.00          0.00            1.00         1.00
25%         74.00      572.00        143.00            7.00        15.00
50%        134.00      912.00        228.00           10.00        28.00
75%        191.00     1301.00        325.00           10.00        39.00
max        877.00     2975.00        743.00           10.00        53.00

In [16]:
# get way to remove the less than 4 word
df[df["word_count"]<4]
pages_and_texts[8]

{'text_of_page': 'where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts. Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values. Auxiliary-Loss-Free Load Balancing. For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al., 2017) and diminish computational efficiency in scenarios with expert parallelism. Conventional solutions usually rely on the auxiliary loss (Fedus et al., 2021; Lepikhin et al., 2021) to avoid unbalanced load. However, too large an auxiliary loss will impair the model performance (Wang et al., 2024a). To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al., 2024a) to ensure load balance. To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (16) Note that the bias term is only used for routing. The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step. At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed. Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses. Complementary Sequence-Wise Auxiliary Loss. Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence. The sequence-wise balance loss encourages the expert load on each sequence to be balanced. 9',
 'page_count_char': 2901,
 'page_count_word': 455,
 'page_count_sentences': 17,
 'tokens_num': 725,
 'page_number': 9,
 'sentences': ['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
  'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
  'Auxiliary-Loss-Free Load Balancing.',
  'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
  '2017) and diminish computational efficiency in scenarios with expert parallelism.',
  'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
  '2021; Lepikhin et al.,',
  '2021) to avoid unbalanced load.',
  'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
  '2024a).',
  'To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
  '2024a) to ensure load balance.',
  'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
  '16) Note that the bias term is only used for routing.',
  'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
  'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
  'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
  'Complementary Sequence-Wise Auxiliary Loss.',
  'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
  'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.',
  '9'],
 'sentences_num': 21,
 'sentences_chunk': [['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
   'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
   'Auxiliary-Loss-Free Load Balancing.',
   'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
   '2017) and diminish computational efficiency in scenarios with expert parallelism.',
   'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
   '2021; Lepikhin et al.,',
   '2021) to avoid unbalanced load.',
   'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
   '2024a).'],
  ['To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
   '2024a) to ensure load balance.',
   'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
   '16) Note that the bias term is only used for routing.',
   'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
   'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
   'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
   'Complementary Sequence-Wise Auxiliary Loss.',
   'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
   'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.'],
  ['9']],
 'sentences_chunk_num': 3}

In [17]:
#filter out tokens less than 30
filtered_chunks = [chunk for chunk in pages_and_chunk if chunk["tokens_count"] >= 30]
filtered_chunks[111]

{'paragraphe': 'A study of bfloat16 for deep learning training.arXiv preprint arXiv:1905.12322, 2019.S. Krishna, K. Krishna, A. Mohananey, S. Schwarcz, A. Stambler, S. Upadhyay, and M. Faruqui.Fact, fetch, and reason: A unified evaluation of retrieval-augmented generation.CoRR, abs/2409.12941, 2024.doi: 10.48550/ARXIV.2409.12941.URL https://doi.org/10.485 50/arXiv.2409.12941.T. Kwiatkowski, J. Palomaki, O. Redfield, M. Collins, A. P. Parikh, C. Alberti, D. Epstein, I. Polosukhin, J. Devlin, K. Lee, K. Toutanova, L. Jones, M. Kelcey, M. Chang, A. M. Dai, J. Uszkoreit, Q. Le, and S. Petrov.Natural questions: a benchmark for question answering research.Trans.',
 'word_count': 84,
 'char_count': 648,
 'tokens_count': 162,
 'sentence_count': 10,
 'page_number': 39}

In [18]:
# download `all-MiniLM-L6-v2` model and use it
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer("all-MiniLM-L6-v2")

c:\Users\Mohamed\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6191.70it/s]

In [19]:
# chick torch version and cuda (nvidia GPU)
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True

In [20]:
# list for test
set = ["my name", "her name", "the naem"]
# encode list
embeding = model.encode(set)

#join each sentencse in list with it's embedding
embeding = dict(zip(set,embeding))

#show
embeding,embeding["my name"].shape

({'my name': array([-1.11268602e-01,  3.23448591e-02, -3.83405834e-02,  2.23898627e-02,
         -4.03140783e-02, -5.62008433e-02,  2.33329967e-01,  3.92086729e-02,
         -1.01079242e-02, -6.38170391e-02,  1.64090227e-02, -3.45564671e-02,
          4.02090251e-02, -7.56014660e-02, -8.34888965e-03,  2.65754387e-02,
         -1.42914923e-02,  6.17231149e-03, -8.46135616e-02, -7.72886351e-02,
         -4.17721868e-02,  6.27691001e-02, -3.23680506e-05, -2.02984773e-02,
         -8.92573744e-02,  6.10294333e-03, -3.12835611e-02,  9.11155194e-02,
         -3.69639173e-02, -1.61543280e-01, -3.80769518e-04,  7.48009467e-03,
          9.98783186e-02,  5.72648980e-02, -4.66816034e-03, -4.17357311e-02,
         -1.26731142e-01, -2.11646669e-02,  5.62063567e-02, -1.07810488e-02,
         -4.70565679e-03, -1.19292334e-01,  2.42646299e-02,  5.37948310e-03,
          7.11644581e-03,  7.88039621e-03,  6.28924463e-04,  2.45067645e-02,
          1.61230303e-02,  9.47958231e-02, -9.59324986e-02, -8.88254344e-02,
         -5.96604422e-02,  1.89628787e-02,  1.31215407e-02, -7.77191371e-02,
          2.44201161e-02,  5.09177484e-02, -3.09437583e-03,  2.27765311e-04,
          4.02659625e-02,  1.79442074e-02, -7.26719275e-02,  3.98123711e-02,
          1.57936160e-02,  8.13504867e-03, -6.94837375e-03,  1.39237326e-02,
          4.64227656e-03, -9.63736884e-03, -2.38478649e-02, -6.72965450e-03,
          7.07242340e-02, -3.35569419e-02, -1.96107812e-02, -1.45387556e-02,
          1.61475949e-02, -1.77206695e-02, -1.31568862e-02,  6.13829195e-02,
         -8.46485496e-02,  4.43952717e-03, -9.70008671e-02, -8.54695868e-03,
         -2.76289042e-02,  4.83488068e-02,  3.65964994e-02, -3.85117233e-02,
         -2.87031792e-02, -5.48657775e-03,  2.66993325e-03, -7.49976933e-02,
          2.27707773e-02, -3.73113062e-03, -2.44773440e-02, -5.23784664e-03,
         -3.77394812e-04, -4.05308045e-02, -3.87832411e-02,  1.85519353e-01,
         -6.50252774e-02,  3.38606313e-02, -5.62591217e-02,  7.47068524e-02,
         -7.21330149e-03, -8.54292046e-03, -5.87108247e-02,  5.19497925e-03,
          5.03454125e-03, -2.29808614e-02, -5.23379929e-02, -2.39632837e-02,
         -5.20040542e-02,  4.00796086e-02,  3.42810489e-02,  7.10861087e-02,
          2.96648638e-03, -2.60684136e-02,  3.05782016e-02, -2.95661837e-02,
          4.49147262e-02,  2.99034249e-02, -8.65572020e-02, -1.93888042e-02,
         -2.02058069e-02,  1.09100919e-02, -1.28705765e-03, -3.38961069e-33,
          5.94924437e-03,  1.89252160e-02, -4.11714369e-04,  1.40347689e-01,
          2.08696984e-02,  1.44509543e-02, -5.77049702e-02,  7.57386768e-03,
         -3.34116220e-02, -4.86473931e-04,  1.18632261e-02,  1.23979710e-02,
         -2.82271616e-02,  6.32571504e-02,  2.87447739e-02,  3.98514457e-02,
         -2.19962839e-02,  5.86499237e-02, -3.66562046e-02,  2.81827636e-02,
         -3.64034772e-02,  6.67515323e-02,  3.82383214e-03,  3.85378189e-02,
         -5.31675816e-02, -1.20789595e-01, -1.26687186e-02, -7.43082836e-02,
          3.59357931e-02,  2.43287757e-02, -5.68793975e-02, -1.62085071e-02,
          8.52153525e-02, -1.06991231e-02,  2.98596621e-02, -8.78666714e-02,
         -1.15062119e-02,  1.56421755e-02, -4.40782085e-02,  1.03963681e-01,
         -9.96414479e-03,  1.12467455e-02, -7.92487264e-02,  4.75009345e-02,
         -2.51976848e-02, -1.84205454e-02,  3.58203575e-02,  5.33687398e-02,
         -9.88210589e-02, -1.01148849e-02, -5.02877273e-02,  3.62836011e-02,
         -1.07462898e-01, -1.13364054e-04, -8.78018439e-02,  2.03307029e-02,
         -1.38519984e-03,  9.96504165e-03, -1.05820306e-01, -1.08255902e-02,
         -5.61665418e-03,  3.54209617e-02, -1.99718494e-02,  1.85143687e-02,
          1.84967872e-02, -4.77539301e-02,  7.75206983e-02, -5.72839528e-02,
          2.59807035e-02,  3.01387981e-02, -7.60096982e-02, -5.30696213e-02,
          4.44190018e-03,  4.09771018e-02,  7.15029314e-02,  6.62903022e-03,
         -8.63277167e-03,  5.87880649e-02, -3.33780386e-02, -9.79795307e-03,
          3.39137428e-02, -1.12670697e-02,  2.68006767e-03,  3.78638431e-02,
          2.98797954e-02, -2.79733795e-03, -1.43967113e-02, -3.69952619e-02,
         -1.53701017e-02, -3.44166532e-02, -1.34393826e-01, -1.39013270e-03,
          1.08393133e-01, -2.45960653e-02, -5.27150147e-02,  1.20526999e-33,
         -1.27882026e-02,  4.35465351e-02,  1.87254958e-02,  9.56210569e-02,
          4.67719603e-03, -2.69599725e-02,  5.32101979e-03,  1.07820265e-01,
          1.92453689e-03,  5.60386255e-02, -2.19701175e-02, -8.23149979e-02,
          4.67025489e-03, -2.90252338e-03,  8.16676468e-02,  4.96277139e-02,
          4.06118482e-02, -1.76349177e-03, -4.65383530e-02,  2.63393368e-03,
         -5.90300523e-02,  5.77562898e-02, -1.08629251e-02, -6.16722032e-02,
         -4.12747310e-03,  1.70052815e-02,  3.90952788e-02,  2.52950341e-02,
          7.08593577e-02,  6.80857077e-02,  5.44357393e-03,  2.39246972e-02,
         -1.16943434e-01,  2.93325037e-02, -2.60607079e-02,  6.45446777e-02,
         -1.89389009e-02, -1.98988672e-02,  1.02715334e-02, -3.32666491e-03,
         -1.41809136e-02,  3.20844874e-02, -7.18639344e-02,  1.08568095e-01,
         -1.31833227e-02, -3.98828611e-02, -5.78845441e-02,  3.01687773e-02,
          1.03621352e-02,  4.26096991e-02, -3.35614532e-02, -6.73616007e-02,
         -6.93707392e-02, -3.82362455e-02,  1.17582828e-03,  3.61948758e-02,
          6.44930154e-02,  2.16483474e-02,  9.53725539e-03,  4.65247361e-03,
          1.59357935e-02,  3.41445282e-02,  6.12317175e-02,  7.34104589e-02,
          3.04528922e-02, -1.78817715e-02, -6.13178089e-02, -4.10457030e-02,
         -2.72018649e-02, -4.76150028e-02, -5.27509265e-02,  2.03911513e-02,
         -4.46444489e-02,  2.69611403e-02, -9.46116373e-02,  3.20556834e-02,
          1.63121428e-02,  2.63476055e-02, -2.50775199e-02,  5.37288971e-02,
          3.02447416e-02,  8.66488442e-02, -2.48541404e-02,  3.00489012e-02,
          1.60620119e-02, -2.64488161e-02,  3.59426700e-02,  8.03072080e-02,
         -2.33003721e-02, -3.87402549e-02,  2.93709300e-02,  3.48940790e-02,
         -1.20453164e-02, -1.63013488e-02, -9.69538465e-02, -1.50699115e-08,
          4.22302522e-02,  5.01371957e-02,  3.11900470e-02, -4.23698360e-03,
          5.10957800e-02,  8.86452645e-02, -3.07830912e-03, -2.18302403e-02,
          4.13647331e-02,  6.56360015e-02,  9.79078338e-02,  5.34657985e-02,
          3.15143391e-02,  9.64247156e-03,  9.51067731e-02, -2.79179197e-02,
         -5.68721481e-02,  8.92903190e-03, -4.92045935e-03, -2.21010149e-02,
         -3.58192995e-02, -2.98429020e-02,  8.19763839e-02, -7.19112009e-02,
          4.26656641e-02,  9.13801696e-03,  3.62761579e-02,  9.37117562e-02,
         -5.74504621e-02,  7.81974643e-02,  1.13642160e-02,  1.17897831e-01,
          1.24910325e-02,  6.13725260e-02, -3.99509855e-02, -9.76392010e-04,
          2.87474766e-02,  8.35280120e-02,  5.63313179e-02, -8.02361127e-03,
         -3.31368297e-02,  5.76817542e-02,  9.86445621e-02, -1.26726562e-02,
         -6.93444908e-02,  6.50679320e-02, -2.79120664e-04, -1.52545832e-02,
         -4.63721994e-03, -2.10705902e-02,  8.71946383e-03,  1.70729980e-02,
          2.25880053e-02,  7.89605752e-02,  2.01135594e-02,  4.21369486e-02,
          3.23688388e-02,  5.68196215e-02, -6.11764826e-02, -5.45439497e-02,
          7.75278136e-02,  5.29305823e-03, -9.12822634e-02,  1.33655965e-02],
        dtype=float32),
  'her name': array([-1.08516805e-01,  1.40265562e-02, -1.97903570e-02,  4.03933004e-02,
         -3.66050415e-02, -1.11382268e-03,  1.42931879e-01,  4.01251875e-02,
         -9.60893184e-03, -7.14012906e-02,  2.60373130e-02, -9.37794447e-02,
         -1.03091607e-02, -7.65828341e-02, -4.02911119e-02,  7.74797127e-02,
          3.67319472e-02,  3.94580625e-02, -9.53144431e-02, -5.77405542e-02,
         -2.17363127e-02, -2.40650773e-02,  3.27846035e-02,  4.04388905e-02,
         -3.74303870e-02,  2.06175190e-03, -5.38016632e-02,  1.28083434e-02,
         -3.16409841e-02, -1.22112051e-01,  1.27528738e-02, -1.95463300e-02,
          4.58517894e-02,  7.62845352e-02, -1.12639777e-02,  3.25133726e-02,
         -7.22714812e-02,  4.53227870e-02,  2.71108262e-02, -1.35518415e-02,
         -1.94000956e-02, -1.14641130e-01, -4.72653173e-02, -4.64220420e-02,
         -3.94386947e-02, -4.94745895e-02,  5.11805341e-02,  3.23775671e-02,
          2.72550080e-02, -2.67371908e-02, -6.49755448e-02, -5.32744825e-02,
         -1.18825644e-01,  2.55613402e-03,  7.93129951e-02, -2.25096010e-02,
          5.34011275e-02,  5.47847375e-02,  3.82738262e-02,  1.02928244e-02,
          6.06006309e-02,  5.18806875e-02, -7.12646097e-02,  4.85623032e-02,
         -5.31427562e-03, -9.10784490e-03,  3.76583636e-02, -4.69223112e-02,
          3.90819050e-02,  6.33175904e-03,  2.00461652e-02,  3.55321430e-02,
         -1.72345887e-03, -3.88698317e-02,  2.61442214e-02,  1.99030880e-02,
          7.56488964e-02,  1.09233195e-02,  2.11198498e-02,  6.88376352e-02,
         -7.15844184e-02,  1.77171398e-02,  5.93838398e-04,  1.94033179e-02,
          4.28241678e-03,  4.30800878e-02, -3.16122100e-02, -2.20458545e-02,
         -2.73830909e-02, -5.10557480e-02, -4.97698188e-02, -6.01557270e-02,
          3.76522504e-02, -1.17023699e-02, -2.06190459e-02, -2.93967631e-02,
         -2.07708031e-02, -2.78658532e-02, -1.51965749e-02,  1.78603187e-01,
         -9.23539177e-02,  1.01476848e-01, -9.04801860e-03,  9.42860693e-02,
         -3.34172510e-02, -5.97187690e-02,  4.86570559e-02, -5.82064129e-03,
         -3.47071066e-02, -1.29233170e-02, -1.64538657e-03, -1.47645706e-02,
         -9.90036204e-02, -5.19061787e-03,  3.52939293e-02,  3.13790590e-02,
          4.73542251e-02, -1.23639191e-02,  2.38938183e-02, -9.74604487e-02,
          4.04632837e-02, -4.96868864e-02, -4.79107834e-02, -2.40673106e-02,
         -5.60441054e-02, -2.87502948e-02,  2.83523630e-02, -3.16461226e-33,
         -3.55151370e-02,  2.95765921e-02,  8.10843781e-02,  8.34556818e-02,
          5.95203601e-02,  2.11190581e-02,  1.59793403e-02,  1.16894916e-02,
          3.46234115e-03, -2.01443806e-02, -2.27796333e-03, -8.82629082e-02,
         -5.42954467e-02, -8.02553818e-02,  1.01886146e-01,  1.27109950e-02,
         -3.21838632e-02,  7.77680203e-02, -7.86050484e-02,  5.41977845e-02,
          4.28526364e-02,  8.47250149e-02,  2.49308385e-02,  5.01613766e-02,
         -3.17425765e-02, -9.03306454e-02,  7.80699626e-02,  1.17246397e-02,
          1.61143474e-03,  3.63856368e-02, -2.68512685e-02,  1.80523188e-04,
          8.83467346e-02, -1.63772944e-02,  5.22143096e-02, -4.44411039e-02,
         -5.81525406e-03, -1.12066157e-02,  3.63274524e-03,  7.74847865e-02,
          2.00559217e-02, -1.65881235e-02,  2.73299608e-02,  1.84894260e-02,
         -1.34903491e-01,  4.32647988e-02,  5.84352836e-02,  1.03551196e-02,
          4.11864370e-02, -6.93740367e-05, -9.41860825e-02,  3.53580117e-02,
         -1.00075260e-01,  5.65286353e-02, -6.15794547e-02,  8.11114460e-02,
          3.31929997e-02, -1.32226441e-02, -1.87826250e-02, -3.98740135e-02,
          1.16542084e-02,  2.19120793e-02, -6.86919540e-02,  9.83211026e-03,
          4.92209084e-02, -5.10650724e-02,  2.85478700e-02, -1.02851331e-01,
          3.24431285e-02,  1.23117128e-02, -1.13674045e-01,  1.87593140e-02,
          2.25785431e-02,  4.31682058e-02, -5.41481152e-02,  2.82279607e-02,
          3.29296663e-02, -2.86128316e-02, -3.13659832e-02, -5.98061783e-03,
          1.17117343e-02,  3.75699550e-02, -2.54161488e-02,  8.43513682e-02,
         -4.38703373e-02, -3.62565741e-03, -2.06886549e-02, -1.42937908e-02,
         -3.48394141e-02, -7.15545565e-02, -6.16803728e-02,  2.06668545e-02,
          7.54758492e-02, -4.97289374e-02, -2.12219357e-02,  1.31706244e-33,
         -5.28452778e-03,  1.54752489e-02, -4.34725322e-02,  6.07264303e-02,
          5.43512739e-02, -1.14345578e-02, -1.48575346e-03,  1.01141483e-01,
         -4.60984372e-03, -1.25182383e-02,  2.76288278e-02, -1.24480315e-01,
          1.22275706e-02, -1.49447229e-02,  6.50415197e-02,  6.65459111e-02,
          8.23930651e-02, -6.69729263e-02, -3.24602276e-02, -6.40190020e-02,
         -9.25135538e-02,  1.08705871e-02,  1.46334730e-02, -7.67764524e-02,
         -2.50701830e-02,  2.24010088e-02,  9.63630825e-02, -2.89402250e-03,
         -4.82729189e-02, -1.27476687e-02,  3.41592059e-02,  1.86355300e-02,
         -7.29231089e-02,  6.13725185e-02, -3.97584289e-02,  4.89614829e-02,
          2.06597354e-02, -4.81188521e-02,  2.89741941e-02,  2.80811973e-02,
          4.12800573e-02,  8.84461682e-03, -2.17010900e-02,  1.02579340e-01,
          2.75865197e-02,  2.12727152e-02, -1.27490787e-02,  4.89049293e-02,
          8.61027986e-02,  2.64374278e-02, -2.06164587e-02, -7.87167028e-02,
         -2.70623583e-02,  8.11806042e-03,  5.95773123e-02, -3.19411531e-02,
          5.81039898e-02,  1.95025001e-02,  3.71584073e-02,  5.88323036e-03,
          1.53962849e-02,  3.51784602e-02, -2.35251132e-02,  7.92885572e-02,
         -3.05617563e-02, -1.99384745e-02, -8.13734904e-02, -1.25664771e-01,
         -2.59873886e-02, -5.24826422e-02,  3.75156617e-03,  2.80722268e-02,
         -4.10410799e-02,  6.88030943e-02, -9.14724991e-02,  1.63114406e-02,
         -9.08275172e-02, -2.50380971e-02, -2.15020496e-02,  3.57075408e-02,
          1.56707522e-02,  2.72470638e-02, -5.09988181e-02,  1.73475698e-03,
          2.54247282e-02, -4.76679951e-03,  8.02696571e-02,  1.11472152e-01,
         -2.18369029e-02, -1.08616456e-01, -1.27692120e-02, -8.22651293e-03,
         -1.66713204e-02, -6.58632964e-02, -7.73727074e-02, -1.59770792e-08,
          1.07898936e-02, -4.41672280e-03,  5.39550669e-02, -6.93759844e-02,
          4.82009724e-02,  7.87588656e-02,  2.61549931e-02, -1.01904087e-02,
          2.86767855e-02,  7.04269260e-02,  8.22025687e-02,  2.00291593e-02,
          5.73524386e-02,  3.10402717e-02,  6.98653609e-02, -3.70384194e-02,
          1.93623975e-02,  1.15336105e-01, -4.57215821e-03,  1.14648025e-02,
         -6.67652395e-03, -4.16180827e-02,  5.23354597e-02, -1.36465088e-01,
          1.81709565e-02,  6.24541007e-03, -1.47890877e-02,  1.09797210e-01,
         -4.21142466e-02,  1.01671284e-02, -3.07445507e-02,  1.13257244e-01,
          3.45925428e-02,  1.96992867e-02,  1.25573715e-03,  3.80590148e-02,
          4.83893678e-02,  2.26374716e-02, -1.67597476e-02,  3.04050911e-02,
         -1.51804108e-02,  2.86381226e-02,  9.29250717e-02, -2.69179512e-02,
         -5.29072173e-02,  2.60877945e-02,  1.27067398e-02, -4.53396812e-02,
         -2.70353723e-03, -1.21021578e-02, -7.78898690e-03,  1.35551114e-02,
          4.36936915e-02,  3.78443748e-02, -2.25434843e-02, -1.41144283e-02,
          2.71069203e-02, -2.39804778e-02, -3.96825001e-02,  1.36273113e-04,
          7.66980182e-03,  1.05080036e-02,  6.80240169e-02,  1.96243785e-02],
        dtype=float32),
  'the naem': array([-6.02948368e-02,  1.08011052e-01, -4.00737152e-02,  2.84987706e-04,
         -5.78279756e-02,  3.90510634e-02,  1.63081363e-02, -6.27290532e-02,
         -2.72917245e-02,  6.48954511e-02, -1.36009976e-02, -1.12080678e-01,
          4.29547355e-02, -3.33018713e-02,  3.84274125e-02,  1.98117574e-04,
         -9.92214028e-03,  3.54607147e-03, -1.39897885e-02, -5.76529354e-02,
         -3.93402390e-02,  4.99700494e-02,  2.77685262e-02, -9.71353520e-03,
         -7.29377046e-02,  3.06774338e-04,  5.28396070e-02,  1.97455753e-02,
          6.62655681e-02, -1.39705881e-01,  5.01716742e-04,  6.13604039e-02,
         -2.77932715e-02,  1.24620153e-02, -6.92577884e-02, -7.66454451e-03,
         -6.53420836e-02, -5.53790107e-03,  1.61085222e-02,  6.49704505e-03,
          7.51554444e-02, -4.55971509e-02, -3.45250918e-03, -3.36859189e-02,
          3.02659664e-02, -7.05948770e-02, -2.51310728e-02, -1.06170345e-02,
          4.80370186e-02,  5.61027899e-02,  3.07876095e-02, -5.77379651e-02,
         -2.93143485e-02,  2.36564446e-02,  6.86284453e-02,  3.42092179e-02,
         -3.66425514e-02, -1.07707478e-01,  2.47657727e-02, -1.87081704e-03,
          8.02794322e-02, -6.56674523e-03, -7.98377916e-02,  6.52273372e-02,
          6.82051927e-02, -9.37174484e-02,  6.07989393e-02,  3.30210067e-02,
         -3.37643698e-02,  2.64172200e-02,  3.17097791e-02, -5.40623739e-02,
          7.14883283e-02, -5.86151982e-05, -5.46505861e-02, -2.46138684e-03,
          6.93024918e-02,  2.13217065e-02,  4.47886698e-02, -1.18316235e-02,
          3.43479067e-02,  3.82323861e-02,  3.36475745e-02, -3.92940417e-02,
          5.31843379e-02, -2.18139612e-03,  8.81356448e-02, -2.54524872e-03,
          2.20382381e-02,  3.63924839e-02, -5.86666018e-02, -3.01842000e-02,
         -8.23798683e-03, -4.73330878e-02,  3.13263424e-02, -3.42283696e-02,
         -2.73820106e-02,  1.87601261e-02,  1.42660681e-02,  1.50501013e-01,
          8.95082653e-02,  1.07485525e-01,  3.75267747e-03,  2.73721553e-02,
          2.50877477e-02,  1.64601672e-02,  1.33112883e-02,  9.83588491e-03,
         -1.44914724e-02,  7.16948509e-02, -4.74362597e-02, -1.86514575e-02,
         -2.84116659e-02, -5.88079542e-03,  3.09784003e-02, -2.49706283e-02,
         -1.90918464e-02, -2.12573595e-02,  5.94183663e-03,  2.15574298e-02,
          6.16730470e-03, -8.75436887e-02, -8.20264295e-02,  3.19139361e-02,
          3.29091623e-02,  5.75121380e-02, -1.16018206e-02, -3.45252829e-33,
         -1.07773626e-02,  7.30658788e-03, -1.63617525e-02, -4.64672260e-02,
          3.70621607e-02,  2.73215473e-02, -2.31236815e-02,  5.66564575e-02,
         -9.57396105e-02, -1.78244039e-02, -2.85459794e-02,  7.88214877e-02,
         -7.85891488e-02,  1.38537521e-02,  8.36979896e-02,  1.03458334e-02,
         -7.59366751e-02, -2.64888834e-02, -3.77846546e-02, -9.53301787e-02,
         -1.12825751e-01,  1.13505095e-01,  7.91859906e-03,  4.91239540e-02,
         -4.25062217e-02,  2.93205623e-02, -2.66452655e-02, -8.48129988e-02,
         -2.70097535e-02,  3.14407498e-02,  4.99393530e-02,  4.24260907e-02,
         -5.03373332e-02,  4.26193252e-02, -8.63207206e-02, -7.60602811e-03,
         -2.76761204e-02, -2.03614421e-02, -5.48336618e-02, -3.26869451e-02,
         -3.44958529e-02,  2.51876283e-02,  1.70821920e-02,  6.42866492e-02,
         -8.01584050e-02, -4.63353507e-02, -1.50233721e-02, -6.26032725e-02,
          8.19116533e-02,  2.78966185e-02,  2.92819412e-03, -3.42843216e-03,
         -4.39038277e-02, -2.01127920e-02,  9.56660230e-03, -1.93480980e-02,
          1.94181470e-04,  4.55720685e-02,  6.61208481e-02, -1.77856423e-02,
          3.08940876e-02,  4.35537174e-02,  3.67996246e-02,  9.71465036e-02,
          3.79517041e-02,  3.49885598e-02, -6.32042298e-03, -6.03008382e-02,
          5.28266616e-02, -3.05552352e-02, -4.74490300e-02,  5.96354567e-02,
          6.59352094e-02,  7.80555457e-02, -1.09360891e-03,  1.21456832e-02,
         -5.06833196e-03, -8.68264735e-02, -9.48877335e-02, -3.95371765e-02,
          2.56637298e-02,  5.39868511e-02, -2.76523568e-02,  6.43403605e-02,
          3.58118936e-02, -1.93711687e-02, -2.32705586e-02, -1.75262950e-02,
          1.40554244e-02, -2.48366334e-02,  1.45109603e-02,  4.32571582e-02,
          1.46898115e-02, -6.47579730e-02, -5.66580184e-02,  3.23795980e-33,
          2.35630665e-02,  1.24059962e-02, -1.02182642e-01,  6.69505373e-02,
          6.45909831e-02, -4.55888845e-02,  4.77874316e-02,  2.63668355e-02,
         -1.10716738e-01,  3.60688604e-02,  1.58359949e-02, -2.84001231e-02,
          1.29867524e-01,  4.72247377e-02,  8.71693417e-02, -5.97081184e-02,
          1.27869114e-01, -8.50947872e-02,  2.15539802e-02, -3.34259607e-02,
          2.41573919e-02, -3.29210460e-02,  1.49753746e-02, -1.72330551e-02,
          1.08727654e-02,  7.22939223e-02,  1.39474655e-02, -7.08193704e-02,
         -7.42303282e-02, -2.18185224e-02,  1.94082949e-02,  3.13056856e-02,
         -1.57291405e-02,  9.62476339e-03, -4.63565923e-02,  3.84134576e-02,
          2.73783859e-02,  6.42660111e-02, -6.87038526e-02, -4.55769077e-02,

In [21]:
# chick the type and formate of chunks

print(type(pages_and_chunk[0]))
print(pages_and_chunk[0])

<class 'dict'>
{'paragraphe': 'DeepSeek-V3 Technical Report DeepSeek-AI research@deepseek.com Abstract We present DeepSeek-V3, a strong Mixture-of-Experts (MoE) language model with 671B total parameters with 37B activated for each token.To achieve efficient inference and cost-effective training, DeepSeek-V3 adopts Multi-head Latent Attention (MLA) and DeepSeekMoE architec- tures, which were thoroughly validated in DeepSeek-V2.Furthermore, DeepSeek-V3 pioneers an auxiliary-loss-free strategy for load balancing and sets a multi-token prediction training objective for stronger performance.We pre-train DeepSeek-V3 on 14.8 trillion diverse and high-quality tokens, followed by Supervised Fine-Tuning and Reinforcement Learning stages to fully harness its capabilities.Comprehensive evaluations reveal that DeepSeek-V3 outperforms other open-source models and achieves performance comparable to leading closed-source models.Despite its excellent performance, DeepSeek-V3 requires only 2.788M H800 GPU hours for its full training.In addition, its training process is remarkably stable.Throughout the entire training process, we did not experience any irrecoverable loss spikes or perform any rollbacks.The model checkpoints are available at https://github.com/deepseek-ai/DeepSeek-V3.MMLU-Pro (EM) GPQA-Diamond (Pass@1) MATH 500 (EM) AIME 2024 (Pass@1) Codeforces (Percentile) SWE-bench Verified (Resolved) 0 20 40 60 80 100 Accuracy / Percentile (%) 75.9 59.1 90.2 39.2 51.6 42.0 66.2 41.3 74.7 16.7 35.6 22.6 71.6 49.0 80.0 23.3 24.8 23.8 73.3 51.1 73.8 23.3 25.3 24.5 72.6 49.9 74.6 9.3 23.6 38.8 78.0 65.0 78.3 16.0 20.3 50.8 DeepSeek-V3 DeepSeek-V2.5 Qwen2.5-72B-Inst Llama-3.1-405B-Inst GPT-4o-0513 Claude-3.5-Sonnet-1022 Figure 1 | Benchmark performance of DeepSeek-V3 and its counterparts.', 'word_count': 222, 'char_count': 1767, 'tokens_count': 441, 'sentence_count': 10, 'page_number': 1}

In [22]:
from tqdm import tqdm # use to show loading bar

# buting in embedding the embeding vector of chunk senetence we just made
for chunk in tqdm(pages_and_chunk):
    chunk["embedding"] = model.encode(chunk["paragraphe"], device="cuda")

100%|██████████| 153/153 [00:02<00:00, 72.84it/s]

In [23]:
# show random sample
import random
random.sample(pages_and_chunk,k=1)

[{'paragraphe': '2021), DeepSeekMoE uses finer-grained experts and isolates some experts as shared ones.Let u𝑡denote the FFN input of the 𝑡-th token, we compute the FFN output h′ 𝑡as follows: h′ 𝑡= u𝑡+ 𝑁𝑠 ∑︁ 𝑖=1 FFN(𝑠) 𝑖 (u𝑡) + 𝑁𝑟 ∑︁ 𝑖=1 𝑔𝑖,𝑡FFN(𝑟) 𝑖 (u𝑡), (12) 𝑔𝑖,𝑡= 𝑔′ 𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑔′ 𝑗,𝑡 , (13) 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise, (14) 𝑠𝑖,𝑡= Sigmoid \x00u𝑡 𝑇e𝑖 \x01 , (15) 8',
  'word_count': 72,
  'char_count': 378,
  'tokens_count': 94,
  'sentence_count': 2,
  'page_number': 8,
  'embedding': array([-5.27206399e-02, -2.89740879e-02,  6.96083084e-02, -4.44384553e-02,
         -2.49645449e-02, -8.47924799e-02, -3.63194384e-02,  4.35491204e-02,
         -3.29558477e-02, -6.92596957e-02, -1.77073311e-02, -8.02995190e-02,
         -2.79801190e-02, -4.40066569e-02, -3.54410410e-02,  1.61083564e-02,
         -2.98298560e-02,  9.26595032e-02, -8.70648026e-02, -9.72529948e-02,
         -1.13086244e-02, -5.56938499e-02,  4.61379299e-03, -6.87665269e-02,
          3.95332016e-02,  3.73190381e-02,  3.51829715e-02,  1.92677453e-02,
          7.52283558e-02, -5.13015985e-02,  3.46822441e-02,  5.68529777e-02,
          2.89437585e-02,  5.22827879e-02,  2.21209065e-03,  6.94915131e-02,
         -1.16648681e-01, -6.35979548e-02,  5.53510450e-02,  2.12743692e-02,
          1.12868240e-02, -4.61942283e-03,  5.19125871e-02,  1.04060024e-02,
         -1.61846913e-02,  7.92317688e-02, -1.16233379e-02,  1.59749892e-02,
         -3.16743776e-02, -1.15935979e-02, -4.88303043e-02,  2.21010093e-02,
         -2.98924297e-02,  7.41066560e-02, -1.38999848e-02,  1.43603664e-02,
         -5.78877479e-02,  1.22181978e-02,  3.54971439e-02, -9.35668650e-04,
          8.98234081e-03, -4.75358106e-02,  9.52887442e-03, -5.35087883e-02,
          6.50552148e-03,  2.20144093e-02, -5.82264178e-03, -3.86910103e-02,
          5.13026156e-02,  5.75851575e-02,  4.82719317e-02,  7.74356201e-02,
         -8.55892301e-02, -3.62706222e-02,  2.47047190e-03,  8.10705125e-02,
          7.03267828e-02,  6.16093054e-02,  6.53455406e-02, -8.21892172e-02,
          4.57087420e-02,  2.19849776e-03,  8.12364221e-02,  6.27330621e-04,
          7.43702203e-02,  8.99133179e-03, -6.10383376e-02,  1.52456723e-02,
         -2.72961240e-02, -1.44634889e-02, -3.06870304e-02, -4.83413301e-02,
         -4.18137014e-02, -4.01800219e-03,  1.86206680e-03,  3.14697884e-02,
          1.38420649e-02,  1.87199004e-02, -1.18637972e-01,  8.43749717e-02,
          2.59437095e-02, -2.51326486e-02, -2.68178228e-02, -2.50488501e-02,
         -2.20293682e-02,  6.06762208e-02,  4.08913270e-02, -2.19497122e-02,
          1.05765820e-01,  4.65754010e-02,  2.69968789e-02,  2.29672389e-03,
          1.41439782e-02,  1.71419571e-03, -4.73565534e-02, -2.55480874e-03,
          2.39225235e-02,  2.64575891e-02, -8.92268587e-03,  2.78359670e-02,
         -1.03641137e-01, -6.89396858e-02, -6.53541163e-02,  4.96467948e-03,
         -7.04662651e-02,  8.13594088e-02, -5.20198792e-02,  4.15572444e-33,
         -1.55388946e-02,  9.97802764e-02, -1.27999121e-02, -1.27179116e-01,
         -2.09269673e-02,  7.31444918e-03, -4.56258245e-02, -2.81520411e-02,
         -8.55858922e-02, -3.25805210e-02, -1.02375537e-01, -3.54063814e-03,
         -1.19569287e-01,  6.25059903e-02, -6.07241206e-02, -8.67390856e-02,
         -1.07692345e-03,  1.23609146e-02, -2.62209233e-02, -6.51643437e-04,
          3.73525992e-02,  6.49832003e-03, -5.17016836e-02, -5.63994572e-02,
         -1.01221733e-01, -2.20970577e-03,  9.40419808e-02, -7.99793843e-03,
          5.39327040e-04,  3.72846127e-02, -1.42044902e-01, -1.33969098e-01,
         -1.05969235e-02, -7.49690365e-03, -5.16725751e-03, -4.04039957e-02,
         -5.39617849e-06, -1.82283670e-02,  2.66579445e-02, -9.95551348e-02,
          1.94980260e-02,  5.35997190e-02, -3.99714615e-03, -7.13566542e-02,
         -5.24765886e-02, -2.02787574e-02, -1.58569552e-02, -7.25378282e-03,
          4.82527092e-02, -5.83994985e-02, -4.12691869e-02, -5.75424023e-02,
         -3.63431908e-02, -8.29436108e-02,  6.55153617e-02, -2.68004332e-02,
          7.37742037e-02,  5.20375259e-02,  8.23125765e-02,  4.14585918e-02,
          2.40911394e-02,  2.33878307e-02,  1.11075498e-01,  6.27120659e-02,
          2.27124318e-02,  5.92119582e-02,  1.62672810e-02,  1.18163852e-02,
          2.58012395e-02, -2.72977054e-02, -3.23688500e-02,  5.08424453e-02,
          2.84070801e-02, -5.11413664e-02, -3.81727144e-02,  5.76622202e-04,
          5.18433712e-02, -7.52379969e-02, -1.20508643e-02,  4.08236906e-02,
          9.72587056e-03,  6.54348135e-02, -2.35396326e-02, -3.00024766e-02,
         -9.13956165e-02, -1.41501818e-02, -6.21311963e-02, -4.51555252e-02,
         -1.36564784e-02, -3.89109366e-03, -4.89741797e-03, -8.44342411e-02,
         -1.79618746e-02,  6.49405178e-03, -1.06731825e-01, -4.63889193e-33,
         -7.25226551e-02,  8.56281221e-02, -3.76880132e-02,  4.65200096e-02,
         -3.31631079e-02, -3.84410881e-02, -2.34393086e-02,  1.61788762e-02,
         -2.39611734e-02,  3.75194736e-02,  8.65861624e-02, -1.10921601e-03,
         -4.30712439e-02, -9.18752402e-02,  4.87544835e-02,  3.12555372e-03,
          2.01192289e-03,  9.38321277e-02,  4.58708107e-02, -4.31644358e-02,
          2.83195842e-02, -5.06298011e-03, -1.14136927e-01,  1.14379920e-01,
         -6.11691996e-02,  2.15682462e-02,  8.80190916e-03,  8.70648995e-02,
         -6.09201379e-02,  7.42105488e-03,  1.46179264e-02, -9.20144096e-02,
         -6.79786429e-02,  6.11508861e-02,  1.67059153e-02, -4.36095297e-02,
          6.44482393e-03,  2.01104078e-02, -7.25956575e-04, -1.10256977e-01,
          1.10064736e-02,  3.32995877e-02, -1.30960895e-02,  3.92954834e-02,
         -6.28362969e-02,  3.54919955e-03, -1.65244434e-02, -6.11170232e-02,
          3.92643437e-02,  3.10409777e-02,  7.95373544e-02,  2.44183140e-03,
         -2.32180208e-02,  3.76365148e-02, -8.26488584e-02,  5.01635522e-02,
          3.19091715e-02,  5.92107996e-02,  9.91745014e-03, -1.72478519e-02,
         -6.48799986e-02, -1.08580112e-01,  5.33731766e-02,  1.98855922e-02,
          9.11015831e-03,  3.86122912e-02, -9.70967263e-02,  9.43843573e-02,
          1.72075275e-02, -1.24951322e-02,  6.67042062e-02,  7.68332109e-02,
          3.61149274e-02,  8.25636387e-02,  9.09157470e-03,  1.95229445e-02,
          2.54388191e-02, -3.44427079e-02,  2.11862149e-04, -2.54248437e-02,
         -3.43459062e-02, -6.09799195e-03, -4.89498824e-02,  8.04707333e-02,
          5.46984598e-02, -3.83707625e-03,  5.07945828e-02,  9.47816446e-02,
         -8.45492468e-04,  5.95080703e-02,  7.65997032e-03,  8.09874237e-02,
         -3.47867124e-02, -2.21162979e-02,  4.28628549e-02, -5.52608341e-08,
          8.55728332e-03, -9.54131186e-02, -1.95453111e-02, -2.12296303e-02,
          4.70826328e-02, -5.85515164e-02, -5.58396168e-02,  3.52958441e-02,
         -1.04047765e-03, -6.54350445e-02,  8.07223916e-02, -2.62531061e-02,
         -1.17448322e-01, -3.81517671e-02,  2.81715710e-02,  5.76115996e-02,
          4.53520007e-02,  7.58117437e-02, -5.68047818e-03,  4.76790126e-03,
          3.63997668e-02,  8.79606232e-02,  7.30427131e-02, -5.36449365e-02,
         -1.37966312e-03, -1.90128945e-02, -4.54565510e-02,  2.39316374e-02,
         -9.49901808e-03,  2.34546443e-03,  4.61052498e-03,  1.08874664e-02,
         -5.49273053e-03, -3.29456963e-02, -5.44808246e-02,  1.23728223e-01,
         -3.27778086e-02,  3.05720996e-02, -3.74199711e-02,  1.21399248e-02,
         -3.70098315e-02,  4.77822423e-02, -2.70306636e-02, -1.33621716e-03,
         -3.12520750e-02, -8.04305892e-04,  3.64811383e-02, -9.73893737e-04,
          1.13654844e-02,  5.23950607e-02, -1.14291217e-02,  1.58208013e-02,
          1.24772005e-02, -1.89484414e-02, -7.39943609e-03, -3.16200964e-02,
         -1.13470212e-01, -8.65365285e-03,  2.32801214e-03,  1.59136914e-02,
          4.28603590e-02,  5.44284582e-02,  1.18613821e-02,  4.35402207e-02],
        dtype=float32)}]

In [24]:
# now save that data (on csv file : "work fine with `Dataframe`")
page_and_Embedding_df = pd.DataFrame(pages_and_chunk)
page_and_Embedding_file_name="page_and_Embedding.csv"
page_and_Embedding_path = os.path.join(os.getcwd(),page_and_Embedding_file_name)
page_and_Embedding_df.to_csv(page_and_Embedding_path,index=False) # `index` parameter mean not add index column to file

In [25]:
# free the variable to make sure that data get back from file as was it is
pages_and_chunk=[]
pages_and_chunk

[]

In [26]:
#get data from file we saved
pages_and_chunk =pd.read_csv(page_and_Embedding_path)

# see the embedding
pages_and_chunk

,paragraphe,word_count,char_count,tokens_count,sentence_count,page_number,embedding
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,222,1767,441,10,1,[-7.36545399e-02 -5.92405871e-02 5.75507209e-...
1,arXiv:2412.19437v2 [cs.CL] 18 Feb 2025,5,38,9,2,1,[-1.14521921e-01 7.90134072e-03 -7.34652132e-...
2,Contents 1 Introduction 4 2 Architecture 6 2.1...,302,952,238,10,2,[-1.76019315e-02 -5.03365174e-02 -4.91420068e-...
3,14 3.3.1 Mixed Precision Framework . . . . . ....,324,912,228,10,2,[-1.62387192e-02 3.45402062e-02 -1.01859689e-...
4,21 4.2 Hyper-Parameters . . . . . . . . . . . ...,267,742,185,9,2,[ 2.22861078e-02 3.54707018e-02 -1.13855258e-...
...,...,...,...,...,...,...,...
148,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2961,740,1,49,[-8.76501650e-02 3.37730325e-03 -2.45083272e-...
149,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2968,742,1,50,[-8.87522995e-02 2.17782613e-03 -2.23974790e-...
150,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2975,743,1,51,[-8.97151008e-02 9.12366062e-03 -2.74221636e-...
151,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,877,2975,743,1,52,[-8.86221156e-02 6.90445770e-03 -2.55782343e-...
152,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,346,1370,342,4,53,[-8.44787136e-02 4.49145865e-03 -2.48290710e-...

In [27]:
# the data is not in right formate to use 
data = pages_and_chunk.to_dict(orient="records")
data[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': '[-5.76343201e-02  1.86270270e-02 -6.96300194e-02 -5.02142822e-03\n -6.43548667e-02  5.39917648e-02 -4.61324938e-02  3.96139584e-02\n -5.72230220e-02  5.44092804e-03 -4.39483412e-02 -6.78680325e-03\n  4.00274545e-02 -1.59041807e-02  7.62046641e-03  4.98709343e-02\n  1.28310859e-01 -3.56771685e-02 -4.98869978e-02 -8.15589055e-02\n  4.34629358e-02 -4.59041335e-02  8.90600234e-02  1.54037038e-02\n -7.79620484e-02  3.06390580e-02 -5.25193140e-02 -6.64414167e-02\n  3.31790745e-02 -6.93640932e-02 -6.77236542e-03  3.17597482e-03\n  5.10903783e-02 -8.24809521e-02 -8.37938562e-02  1.99515168e-02\n -5.22203930e-02 -5.73823862e-02  1.78819150e-02  2.67783534e-02\n  1.22675279e-04 -3.79560106e-02  2.66227871e-03  2.12215502e-02\n  3.83332558e-02 -2.20188908e-02 -5.95768169e-02 -2.69228555e-02\n -4.48380969e-02 -8.05420727e-02 -1.64256301e-02 -6.48153052e-02\n  5.06796781e-03 -2.43174564e-03 -5.40565290e-02 -8.12954269e-03\n  4.19081375e-02 -2.15617232e-02 -1.57968029e-02  3.31748277e-02\n -8.01364779e-02 -1.54115567e-02 -5.74465618e-02  1.44827375e-02\n  3.75398770e-02 -9.97637585e-02 -8.92191008e-03 -6.80584684e-02\n  5.85166328e-02 -3.27328518e-02 -2.40224740e-03 -6.30811881e-03\n  4.79136556e-02 -8.28514621e-02 -2.71539520e-02 -4.32536704e-03\n  2.57454421e-02 -3.27681489e-02  2.09331643e-02 -7.94779658e-02\n  1.91955734e-02 -1.16449250e-02  9.50383767e-03 -4.35635522e-02\n -3.66505831e-02 -9.70793441e-02  8.94263480e-03 -1.46269770e-02\n  5.45645878e-02  6.92140684e-02  1.05012521e-01  1.10859863e-01\n -1.34864897e-02  8.77498277e-03 -1.14634610e-03  1.05595477e-01\n -3.30546014e-02  1.49800964e-02 -7.64259771e-02  4.41714674e-02\n  8.06646198e-02  3.79375182e-02 -1.73762031e-02  4.10951227e-02\n -2.40345858e-02 -4.80215773e-02  1.50006237e-02  3.03008091e-02\n  4.40822588e-03 -1.10763706e-01  5.87852336e-02  5.47064133e-02\n  8.96654464e-03 -4.55786362e-02 -4.77992035e-02  8.83815289e-02\n -1.86152421e-02  2.07291543e-02 -2.19884999e-02  7.60801136e-02\n  1.60370711e-02 -1.16604447e-01  1.25039116e-01 -7.68831559e-03\n  3.03482749e-02 -1.52714383e-02 -6.32316172e-02 -2.49990797e-32\n -8.10584649e-02 -5.51192276e-02 -1.33699803e-02 -5.99329062e-02\n  1.10146971e-02  2.59978063e-02  3.60029861e-02  4.94824443e-03\n  1.81741512e-03 -7.88456351e-02 -5.46012223e-02 -3.52930948e-02\n -6.31594285e-03  6.83288574e-02  1.65331662e-02 -8.12145844e-02\n  5.00025181e-03  1.31413490e-01 -4.67871949e-02 -5.32843843e-02\n  6.42249063e-02 -5.45797199e-02 -4.81015034e-02  2.70939618e-02\n  8.49387944e-02 -5.11556258e-03  8.52151960e-02  4.48352396e-02\n -9.25948396e-02  8.05961620e-03  2.34440453e-02  4.24520411e-02\n -5.95207736e-02  1.05523579e-02 -6.87899515e-02  6.74008217e-04\n  4.62167636e-02 -6.29207445e-03  3.83898988e-02  2.46826978e-03\n -9.38247666e-02  5.74741885e-02  7.89214969e-02 -2.18204726e-02\n -4.18462418e-02 -5.63514195e-02 -4.13206071e-02  2.18045413e-02\n -9.33824182e-02  3.08046620e-02 -6.42291084e-02 -1.99529976e-02\n  3.61034945e-02 -3.50959226e-02  3.22242379e-02  6.15459532e-02\n  5.70552424e-02  1.59136634e-02 -2.45294310e-02  9.99930575e-02\n  5.59421182e-02 -4.10363711e-02 -6.51615709e-02  2.00894140e-02\n  4.90734391e-02  3.07649542e-02 -5.85500188e-02 -5.81289642e-03\n  3.74067686e-02  4.96496968e-02 -6.38445988e-02 -2.64047412e-03\n  5.88807873e-02 -4.38632295e-02  6.60317168e-02 -7.83692896e-02\n  6.36432171e-02  6.92375051e-03 -8.18328410e-02 -3.14816646e-02\n -3.57158552e-03  1.01911850e-01 -5.81695959e-02 -2.84043290e-02\n  1.21233119e-02  2.11805175e-03 -4.04893421e-02 -5.31520844e-02\n -1.43812485e-02  3.91902998e-02 -4.59962562e-02 -2.05658423e-03\n  6.13804394e-03  9.19524580e-02  1.95201207e-02  1.56344848e-32\n  2.62332801e-02  9.64797512e-02 -6.58232719e-02  4.79708686e-02\n  8.70389938e-02  4.03307453e-02  1.44299380e-02 -4.76208404e-02\n -8.86884797e-03  1.93300918e-02 -1.29635213e-02  4.97946069e-02\n -6.92616403e-02  3.16582061e-02 -3.13160494e-02 -3.00070271e-02\n -4.07413021e-03 -1.46254683e-02 -1.23310229e-02  2.74193529e-02\n  8.34065452e-02  6.97516799e-02 -1.05787531e-01  8.78471285e-02\n  5.59022883e-03 -1.86683368e-02 -6.24801703e-02 -3.62284668e-03\n -3.38803716e-02  4.26130444e-02 -3.24046649e-02 -9.78928879e-02\n  1.34581923e-02  4.51985113e-02 -4.52558249e-02 -1.61164254e-02\n  8.62949863e-02  2.88820546e-02 -8.69690627e-03  1.49755552e-01\n  3.60441804e-02  2.37741210e-02 -3.88363227e-02  5.74692711e-02\n -2.12659892e-02 -4.92210779e-03 -7.09290244e-03 -5.32866716e-02\n -8.20563287e-02  4.31006514e-02 -3.67642827e-02 -2.71880459e-02\n -1.35272175e-01 -2.56683826e-02 -2.91683897e-02 -8.94128904e-02\n  1.41426111e-02  7.27055222e-03 -7.77577236e-02 -9.60374530e-03\n -4.91312817e-02  5.92100695e-02 -2.87621040e-02 -1.12884576e-02\n -2.84832381e-02 -8.75001587e-03  1.74761303e-02  4.95308340e-02\n  3.17867361e-02  3.20893899e-02 -8.73306394e-02 -7.09940027e-03\n  5.87638691e-02 -6.80654135e-04  3.69723029e-02 -2.14158762e-02\n  9.12340402e-05 -1.07634906e-02 -5.68082556e-02 -2.79051121e-02\n -1.05843820e-01 -9.68968438e-04  1.14391781e-02 -9.73235071e-03\n -4.10722494e-02  3.72072384e-02  4.89397906e-02  4.51456271e-02\n  1.92308687e-02 -1.15437722e-02  5.01306262e-03  2.97262352e-02\n  6.92122430e-02  1.63907111e-02  8.69889837e-03 -4.69932395e-08\n  9.97948088e-03 -5.11729084e-02  7.04231337e-02  6.84351772e-02\n  3.95479426e-02  1.35918599e-04 -7.60002211e-02  4.00973149e-02\n -3.73462737e-02 -5.88457519e-03  1.22180894e-01  8.05514306e-03\n -1.34175904e-02  1.23288734e-02  2.55202223e-02  1.09683042e-02\n  6.05713169e-04 -2.16499045e-02 -5.05288467e-02 -1.30556300e-02\n  1.05004460e-02  1.00652536e-03 -3.34202163e-02 -1.19563295e-02\n  3.54323387e-02 -7.30695426e-02 -1.92586482e-02  6.82983026e-02\n -5.41707054e-02 -3.45374532e-02  5.45379557e-02  2.30299700e-02\n  1.27890678e-02  2.67073810e-02  2.77424026e-02  1.66754518e-02\n -9.89080220e-03 -1.50999501e-02  1.57295819e-02  1.33830801e-01\n  4.96069668e-03 -5.15580457e-03  2.67172679e-02  9.28948540e-03\n  5.75693548e-02 -3.65180746e-02 -1.39185533e-01 -5.01696095e-02\n  4.19337526e-02 -7.75044262e-02 -4.21275087e-02 -2.39884723e-02\n -6.29835874e-02  7.19865486e-02  1.34467095e-01 -8.73647071e-03\n -7.97655899e-03 -6.91411346e-02  3.03547662e-02  6.15585968e-02\n -2.00267718e-03 -6.09332882e-02 -6.89558908e-02 -6.41390607e-02]'}

In [28]:
# get torch and numpy ready and chick the GPU avilabilty
import torch
import numpy as np
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [29]:
# chick the embedding format 
data[5]['embedding']

'[-5.76343201e-02  1.86270270e-02 -6.96300194e-02 -5.02142822e-03\n -6.43548667e-02  5.39917648e-02 -4.61324938e-02  3.96139584e-02\n -5.72230220e-02  5.44092804e-03 -4.39483412e-02 -6.78680325e-03\n  4.00274545e-02 -1.59041807e-02  7.62046641e-03  4.98709343e-02\n  1.28310859e-01 -3.56771685e-02 -4.98869978e-02 -8.15589055e-02\n  4.34629358e-02 -4.59041335e-02  8.90600234e-02  1.54037038e-02\n -7.79620484e-02  3.06390580e-02 -5.25193140e-02 -6.64414167e-02\n  3.31790745e-02 -6.93640932e-02 -6.77236542e-03  3.17597482e-03\n  5.10903783e-02 -8.24809521e-02 -8.37938562e-02  1.99515168e-02\n -5.22203930e-02 -5.73823862e-02  1.78819150e-02  2.67783534e-02\n  1.22675279e-04 -3.79560106e-02  2.66227871e-03  2.12215502e-02\n  3.83332558e-02 -2.20188908e-02 -5.95768169e-02 -2.69228555e-02\n -4.48380969e-02 -8.05420727e-02 -1.64256301e-02 -6.48153052e-02\n  5.06796781e-03 -2.43174564e-03 -5.40565290e-02 -8.12954269e-03\n  4.19081375e-02 -2.15617232e-02 -1.57968029e-02  3.31748277e-02\n -8.01364779e-02 -1.54115567e-02 -5.74465618e-02  1.44827375e-02\n  3.75398770e-02 -9.97637585e-02 -8.92191008e-03 -6.80584684e-02\n  5.85166328e-02 -3.27328518e-02 -2.40224740e-03 -6.30811881e-03\n  4.79136556e-02 -8.28514621e-02 -2.71539520e-02 -4.32536704e-03\n  2.57454421e-02 -3.27681489e-02  2.09331643e-02 -7.94779658e-02\n  1.91955734e-02 -1.16449250e-02  9.50383767e-03 -4.35635522e-02\n -3.66505831e-02 -9.70793441e-02  8.94263480e-03 -1.46269770e-02\n  5.45645878e-02  6.92140684e-02  1.05012521e-01  1.10859863e-01\n -1.34864897e-02  8.77498277e-03 -1.14634610e-03  1.05595477e-01\n -3.30546014e-02  1.49800964e-02 -7.64259771e-02  4.41714674e-02\n  8.06646198e-02  3.79375182e-02 -1.73762031e-02  4.10951227e-02\n -2.40345858e-02 -4.80215773e-02  1.50006237e-02  3.03008091e-02\n  4.40822588e-03 -1.10763706e-01  5.87852336e-02  5.47064133e-02\n  8.96654464e-03 -4.55786362e-02 -4.77992035e-02  8.83815289e-02\n -1.86152421e-02  2.07291543e-02 -2.19884999e-02  7.60801136e-02\n  1.60370711e-02 -1.16604447e-01  1.25039116e-01 -7.68831559e-03\n  3.03482749e-02 -1.52714383e-02 -6.32316172e-02 -2.49990797e-32\n -8.10584649e-02 -5.51192276e-02 -1.33699803e-02 -5.99329062e-02\n  1.10146971e-02  2.59978063e-02  3.60029861e-02  4.94824443e-03\n  1.81741512e-03 -7.88456351e-02 -5.46012223e-02 -3.52930948e-02\n -6.31594285e-03  6.83288574e-02  1.65331662e-02 -8.12145844e-02\n  5.00025181e-03  1.31413490e-01 -4.67871949e-02 -5.32843843e-02\n  6.42249063e-02 -5.45797199e-02 -4.81015034e-02  2.70939618e-02\n  8.49387944e-02 -5.11556258e-03  8.52151960e-02  4.48352396e-02\n -9.25948396e-02  8.05961620e-03  2.34440453e-02  4.24520411e-02\n -5.95207736e-02  1.05523579e-02 -6.87899515e-02  6.74008217e-04\n  4.62167636e-02 -6.29207445e-03  3.83898988e-02  2.46826978e-03\n -9.38247666e-02  5.74741885e-02  7.89214969e-02 -2.18204726e-02\n -4.18462418e-02 -5.63514195e-02 -4.13206071e-02  2.18045413e-02\n -9.33824182e-02  3.08046620e-02 -6.42291084e-02 -1.99529976e-02\n  3.61034945e-02 -3.50959226e-02  3.22242379e-02  6.15459532e-02\n  5.70552424e-02  1.59136634e-02 -2.45294310e-02  9.99930575e-02\n  5.59421182e-02 -4.10363711e-02 -6.51615709e-02  2.00894140e-02\n  4.90734391e-02  3.07649542e-02 -5.85500188e-02 -5.81289642e-03\n  3.74067686e-02  4.96496968e-02 -6.38445988e-02 -2.64047412e-03\n  5.88807873e-02 -4.38632295e-02  6.60317168e-02 -7.83692896e-02\n  6.36432171e-02  6.92375051e-03 -8.18328410e-02 -3.14816646e-02\n -3.57158552e-03  1.01911850e-01 -5.81695959e-02 -2.84043290e-02\n  1.21233119e-02  2.11805175e-03 -4.04893421e-02 -5.31520844e-02\n -1.43812485e-02  3.91902998e-02 -4.59962562e-02 -2.05658423e-03\n  6.13804394e-03  9.19524580e-02  1.95201207e-02  1.56344848e-32\n  2.62332801e-02  9.64797512e-02 -6.58232719e-02  4.79708686e-02\n  8.70389938e-02  4.03307453e-02  1.44299380e-02 -4.76208404e-02\n -8.86884797e-03  1.93300918e-02 -1.29635213e-02  4.97946069e-02\n -6.92616403e-02  3.16582061e-02 -3.13160494e-02 -3.00070271e-02\n -4.07413021e-03 -1.46254683e-02 -1.23310229e-02  2.74193529e-02\n  8.34065452e-02  6.97516799e-02 -1.05787531e-01  8.78471285e-02\n  5.59022883e-03 -1.86683368e-02 -6.24801703e-02 -3.62284668e-03\n -3.38803716e-02  4.26130444e-02 -3.24046649e-02 -9.78928879e-02\n  1.34581923e-02  4.51985113e-02 -4.52558249e-02 -1.61164254e-02\n  8.62949863e-02  2.88820546e-02 -8.69690627e-03  1.49755552e-01\n  3.60441804e-02  2.37741210e-02 -3.88363227e-02  5.74692711e-02\n -2.12659892e-02 -4.92210779e-03 -7.09290244e-03 -5.32866716e-02\n -8.20563287e-02  4.31006514e-02 -3.67642827e-02 -2.71880459e-02\n -1.35272175e-01 -2.56683826e-02 -2.91683897e-02 -8.94128904e-02\n  1.41426111e-02  7.27055222e-03 -7.77577236e-02 -9.60374530e-03\n -4.91312817e-02  5.92100695e-02 -2.87621040e-02 -1.12884576e-02\n -2.84832381e-02 -8.75001587e-03  1.74761303e-02  4.95308340e-02\n  3.17867361e-02  3.20893899e-02 -8.73306394e-02 -7.09940027e-03\n  5.87638691e-02 -6.80654135e-04  3.69723029e-02 -2.14158762e-02\n  9.12340402e-05 -1.07634906e-02 -5.68082556e-02 -2.79051121e-02\n -1.05843820e-01 -9.68968438e-04  1.14391781e-02 -9.73235071e-03\n -4.10722494e-02  3.72072384e-02  4.89397906e-02  4.51456271e-02\n  1.92308687e-02 -1.15437722e-02  5.01306262e-03  2.97262352e-02\n  6.92122430e-02  1.63907111e-02  8.69889837e-03 -4.69932395e-08\n  9.97948088e-03 -5.11729084e-02  7.04231337e-02  6.84351772e-02\n  3.95479426e-02  1.35918599e-04 -7.60002211e-02  4.00973149e-02\n -3.73462737e-02 -5.88457519e-03  1.22180894e-01  8.05514306e-03\n -1.34175904e-02  1.23288734e-02  2.55202223e-02  1.09683042e-02\n  6.05713169e-04 -2.16499045e-02 -5.05288467e-02 -1.30556300e-02\n  1.05004460e-02  1.00652536e-03 -3.34202163e-02 -1.19563295e-02\n  3.54323387e-02 -7.30695426e-02 -1.92586482e-02  6.82983026e-02\n -5.41707054e-02 -3.45374532e-02  5.45379557e-02  2.30299700e-02\n  1.27890678e-02  2.67073810e-02  2.77424026e-02  1.66754518e-02\n -9.89080220e-03 -1.50999501e-02  1.57295819e-02  1.33830801e-01\n  4.96069668e-03 -5.15580457e-03  2.67172679e-02  9.28948540e-03\n  5.75693548e-02 -3.65180746e-02 -1.39185533e-01 -5.01696095e-02\n  4.19337526e-02 -7.75044262e-02 -4.21275087e-02 -2.39884723e-02\n -6.29835874e-02  7.19865486e-02  1.34467095e-01 -8.73647071e-03\n -7.97655899e-03 -6.91411346e-02  3.03547662e-02  6.15585968e-02\n -2.00267718e-03 -6.09332882e-02 -6.89558908e-02 -6.41390607e-02]'

* the data her is not in list shape so try to fix it

In [30]:
# removing `[]` and seperate the inner data using `,`
embedding = np.fromstring(data[5]['embedding'].strip('[]'), sep=' ')
embedding

array([-5.76343201e-02,  1.86270270e-02, -6.96300194e-02, -5.02142822e-03,
       -6.43548667e-02,  5.39917648e-02, -4.61324938e-02,  3.96139584e-02,
       -5.72230220e-02,  5.44092804e-03, -4.39483412e-02, -6.78680325e-03,
        4.00274545e-02, -1.59041807e-02,  7.62046641e-03,  4.98709343e-02,
        1.28310859e-01, -3.56771685e-02, -4.98869978e-02, -8.15589055e-02,
        4.34629358e-02, -4.59041335e-02,  8.90600234e-02,  1.54037038e-02,
       -7.79620484e-02,  3.06390580e-02, -5.25193140e-02, -6.64414167e-02,
        3.31790745e-02, -6.93640932e-02, -6.77236542e-03,  3.17597482e-03,
        5.10903783e-02, -8.24809521e-02, -8.37938562e-02,  1.99515168e-02,
       -5.22203930e-02, -5.73823862e-02,  1.78819150e-02,  2.67783534e-02,
        1.22675279e-04, -3.79560106e-02,  2.66227871e-03,  2.12215502e-02,
        3.83332558e-02, -2.20188908e-02, -5.95768169e-02, -2.69228555e-02,
       -4.48380969e-02, -8.05420727e-02, -1.64256301e-02, -6.48153052e-02,
        5.06796781e-03, -2.43174564e-03, -5.40565290e-02, -8.12954269e-03,
        4.19081375e-02, -2.15617232e-02, -1.57968029e-02,  3.31748277e-02,
       -8.01364779e-02, -1.54115567e-02, -5.74465618e-02,  1.44827375e-02,
        3.75398770e-02, -9.97637585e-02, -8.92191008e-03, -6.80584684e-02,
        5.85166328e-02, -3.27328518e-02, -2.40224740e-03, -6.30811881e-03,
        4.79136556e-02, -8.28514621e-02, -2.71539520e-02, -4.32536704e-03,
        2.57454421e-02, -3.27681489e-02,  2.09331643e-02, -7.94779658e-02,
        1.91955734e-02, -1.16449250e-02,  9.50383767e-03, -4.35635522e-02,
       -3.66505831e-02, -9.70793441e-02,  8.94263480e-03, -1.46269770e-02,
        5.45645878e-02,  6.92140684e-02,  1.05012521e-01,  1.10859863e-01,
       -1.34864897e-02,  8.77498277e-03, -1.14634610e-03,  1.05595477e-01,
       -3.30546014e-02,  1.49800964e-02, -7.64259771e-02,  4.41714674e-02,
        8.06646198e-02,  3.79375182e-02, -1.73762031e-02,  4.10951227e-02,
       -2.40345858e-02, -4.80215773e-02,  1.50006237e-02,  3.03008091e-02,
        4.40822588e-03, -1.10763706e-01,  5.87852336e-02,  5.47064133e-02,
        8.96654464e-03, -4.55786362e-02, -4.77992035e-02,  8.83815289e-02,
       -1.86152421e-02,  2.07291543e-02, -2.19884999e-02,  7.60801136e-02,
        1.60370711e-02, -1.16604447e-01,  1.25039116e-01, -7.68831559e-03,
        3.03482749e-02, -1.52714383e-02, -6.32316172e-02, -2.49990797e-32,
       -8.10584649e-02, -5.51192276e-02, -1.33699803e-02, -5.99329062e-02,
        1.10146971e-02,  2.59978063e-02,  3.60029861e-02,  4.94824443e-03,
        1.81741512e-03, -7.88456351e-02, -5.46012223e-02, -3.52930948e-02,
       -6.31594285e-03,  6.83288574e-02,  1.65331662e-02, -8.12145844e-02,
        5.00025181e-03,  1.31413490e-01, -4.67871949e-02, -5.32843843e-02,
        6.42249063e-02, -5.45797199e-02, -4.81015034e-02,  2.70939618e-02,
        8.49387944e-02, -5.11556258e-03,  8.52151960e-02,  4.48352396e-02,
       -9.25948396e-02,  8.05961620e-03,  2.34440453e-02,  4.24520411e-02,
       -5.95207736e-02,  1.05523579e-02, -6.87899515e-02,  6.74008217e-04,
        4.62167636e-02, -6.29207445e-03,  3.83898988e-02,  2.46826978e-03,
       -9.38247666e-02,  5.74741885e-02,  7.89214969e-02, -2.18204726e-02,
       -4.18462418e-02, -5.63514195e-02, -4.13206071e-02,  2.18045413e-02,
       -9.33824182e-02,  3.08046620e-02, -6.42291084e-02, -1.99529976e-02,
        3.61034945e-02, -3.50959226e-02,  3.22242379e-02,  6.15459532e-02,
        5.70552424e-02,  1.59136634e-02, -2.45294310e-02,  9.99930575e-02,
        5.59421182e-02, -4.10363711e-02, -6.51615709e-02,  2.00894140e-02,
        4.90734391e-02,  3.07649542e-02, -5.85500188e-02, -5.81289642e-03,
        3.74067686e-02,  4.96496968e-02, -6.38445988e-02, -2.64047412e-03,
        5.88807873e-02, -4.38632295e-02,  6.60317168e-02, -7.83692896e-02,
        6.36432171e-02,  6.92375051e-03, -8.18328410e-02, -3.14816646e-02,
       -3.57158552e-03,  1.01911850e-01, -5.81695959e-02, -2.84043290e-02,
        1.21233119e-02,  2.11805175e-03, -4.04893421e-02, -5.31520844e-02,
       -1.43812485e-02,  3.91902998e-02, -4.59962562e-02, -2.05658423e-03,
        6.13804394e-03,  9.19524580e-02,  1.95201207e-02,  1.56344848e-32,
        2.62332801e-02,  9.64797512e-02, -6.58232719e-02,  4.79708686e-02,
        8.70389938e-02,  4.03307453e-02,  1.44299380e-02, -4.76208404e-02,
       -8.86884797e-03,  1.93300918e-02, -1.29635213e-02,  4.97946069e-02,
       -6.92616403e-02,  3.16582061e-02, -3.13160494e-02, -3.00070271e-02,
       -4.07413021e-03, -1.46254683e-02, -1.23310229e-02,  2.74193529e-02,
        8.34065452e-02,  6.97516799e-02, -1.05787531e-01,  8.78471285e-02,
        5.59022883e-03, -1.86683368e-02, -6.24801703e-02, -3.62284668e-03,
       -3.38803716e-02,  4.26130444e-02, -3.24046649e-02, -9.78928879e-02,
        1.34581923e-02,  4.51985113e-02, -4.52558249e-02, -1.61164254e-02,
        8.62949863e-02,  2.88820546e-02, -8.69690627e-03,  1.49755552e-01,
        3.60441804e-02,  2.37741210e-02, -3.88363227e-02,  5.74692711e-02,
       -2.12659892e-02, -4.92210779e-03, -7.09290244e-03, -5.32866716e-02,
       -8.20563287e-02,  4.31006514e-02, -3.67642827e-02, -2.71880459e-02,
       -1.35272175e-01, -2.56683826e-02, -2.91683897e-02, -8.94128904e-02,
        1.41426111e-02,  7.27055222e-03, -7.77577236e-02, -9.60374530e-03,
       -4.91312817e-02,  5.92100695e-02, -2.87621040e-02, -1.12884576e-02,
       -2.84832381e-02, -8.75001587e-03,  1.74761303e-02,  4.95308340e-02,
        3.17867361e-02,  3.20893899e-02, -8.73306394e-02, -7.09940027e-03,
        5.87638691e-02, -6.80654135e-04,  3.69723029e-02, -2.14158762e-02,
        9.12340402e-05, -1.07634906e-02, -5.68082556e-02, -2.79051121e-02,
       -1.05843820e-01, -9.68968438e-04,  1.14391781e-02, -9.73235071e-03,
       -4.10722494e-02,  3.72072384e-02,  4.89397906e-02,  4.51456271e-02,
        1.92308687e-02, -1.15437722e-02,  5.01306262e-03,  2.97262352e-02,
        6.92122430e-02,  1.63907111e-02,  8.69889837e-03, -4.69932395e-08,
        9.97948088e-03, -5.11729084e-02,  7.04231337e-02,  6.84351772e-02,
        3.95479426e-02,  1.35918599e-04, -7.60002211e-02,  4.00973149e-02,
       -3.73462737e-02, -5.88457519e-03,  1.22180894e-01,  8.05514306e-03,
       -1.34175904e-02,  1.23288734e-02,  2.55202223e-02,  1.09683042e-02,
        6.05713169e-04, -2.16499045e-02, -5.05288467e-02, -1.30556300e-02,
        1.05004460e-02,  1.00652536e-03, -3.34202163e-02, -1.19563295e-02,
        3.54323387e-02, -7.30695426e-02, -1.92586482e-02,  6.82983026e-02,
       -5.41707054e-02, -3.45374532e-02,  5.45379557e-02,  2.30299700e-02,
        1.27890678e-02,  2.67073810e-02,  2.77424026e-02,  1.66754518e-02,
       -9.89080220e-03, -1.50999501e-02,  1.57295819e-02,  1.33830801e-01,
        4.96069668e-03, -5.15580457e-03,  2.67172679e-02,  9.28948540e-03,
        5.75693548e-02, -3.65180746e-02, -1.39185533e-01, -5.01696095e-02,
        4.19337526e-02, -7.75044262e-02, -4.21275087e-02, -2.39884723e-02,
       -6.29835874e-02,  7.19865486e-02,  1.34467095e-01, -8.73647071e-03,
       -7.97655899e-03, -6.91411346e-02,  3.03547662e-02,  6.15585968e-02,
       -2.00267718e-03, -6.09332882e-02, -6.89558908e-02, -6.41390607e-02])

* that made all embedding for chunck as one list of embedding
* then do it to all other data

In [31]:
for item in data:
    item['embedding'] = np.fromstring(item['embedding'].strip('[]'), sep=' ')

In [32]:
# get all embeding in another variable 
embeddings=np.array([item["embedding"] for item in data])
embeddings_df=pd.DataFrame(embeddings)
embeddings_df.shape

(153, 384)

that is mean we have `153` row with each row in `384` space

In [44]:
#define the query
query = "DeepSeek-V3 and notably improves its"
print(f"The query: {query} ")

#see cpu or cuda
# device = "cpu"
# device = "cuda"

#emeding the query (and also make tensor to pass to model - i guiss-)
# make sure is the same model you embeding with the book it self
query_embed= model.encode(query,convert_to_tensor=True).to(device=device)

#modify the `embeddings` to can be dot producted with `query_embed`
embeddings =torch.tensor(embeddings,dtype=torch.float32 ,device=device)

# geting intouation of time
from time import perf_counter as timer
start = timer()
dot_score= util.dot_score(query_embed,embeddings)
end = timer()
print(f"[INFO]: time it take {(end-start):.5f} seconds")

# get the topk
dot_topk = torch.topk(dot_score,3)
dot_topk

The query: DeepSeek-V3 and notably improves its
[INFO]: time it take 0.00043 seconds

C:\Users\Mohamed\AppData\Local\Temp\ipykernel_6100\3709358388.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  embeddings =torch.tensor(embeddings,dtype=torch.float32 ,device=device)

torch.return_types.topk(
values=tensor([[0.6797, 0.6666, 0.6656]], device='cuda:0'),
indices=tensor([[86, 15, 71]], device='cuda:0'))

In [48]:
#chick the values you get in real data
data[86]

{'paragraphe': 'Standard Evaluation Table 6 presents the evaluation results, showcasing that DeepSeek-V3 stands as the best- performing open-source model.Additionally, it is competitive against frontier closed-source models like GPT-4o and Claude-3.5-Sonnet.31',
 'word_count': 29,
 'char_count': 244,
 'tokens_count': 61,
 'sentence_count': 3,
 'page_number': 31,
 'embedding': array([-9.19886604e-02, -8.76681879e-02, -9.45535861e-03, -1.71559863e-02,
         8.38075429e-02, -7.65292123e-02, -1.31917179e-01,  7.15132356e-02,
        -3.88520323e-02, -7.64004281e-03, -9.62210819e-02,  1.88253424e-03,
        -4.69537340e-02, -6.82940036e-02, -1.20635238e-02, -1.68944374e-02,
         1.57806315e-02,  6.44986182e-02, -7.00307339e-02, -8.95429030e-02,
        -2.59138718e-02,  5.63663170e-02,  6.77448660e-02, -8.81967545e-02,
         3.93344276e-02, -4.01454605e-02,  5.25690205e-02,  1.00380732e-02,
         5.76219931e-02, -2.93602925e-02, -1.71895809e-02,  2.38373014e-03,
         1.53108919e-02,  1.02237118e-02, -4.41676490e-02,  9.08308700e-02,
        -5.55472001e-02, -7.17120394e-02, -8.40139538e-02,  6.68972209e-02,
        -9.96400137e-03, -2.50915065e-02,  4.90283966e-03,  3.48331332e-02,
         3.36170383e-02, -6.33230433e-02, -6.73721731e-02, -5.50490879e-02,
        -1.48377903e-02, -6.93740621e-02, -4.59357090e-02, -5.91928847e-02,
        -2.96144448e-02,  3.84602211e-02,  2.28331089e-02, -7.07782852e-03,
         2.80071725e-03, -7.19728693e-02, -4.91269678e-02, -3.79005726e-03,
         5.18246330e-02, -2.00753957e-02, -1.07669756e-01, -2.20736563e-02,
         4.85383235e-02,  6.00387203e-03,  6.27475046e-03,  7.24697411e-02,
         3.25379334e-02, -7.83341378e-02, -5.89380562e-02,  7.78657719e-02,
        -5.72877787e-02, -2.07128283e-02, -4.83552366e-02,  8.31708964e-03,
         6.86583817e-02,  8.46061334e-02,  1.01739600e-01, -8.71851370e-02,
         9.52842161e-02,  6.74114842e-03, -9.20396950e-03, -4.32620943e-02,
         2.69940011e-02, -2.96076406e-02, -1.36987632e-02,  4.61524427e-02,
         8.42047483e-03,  3.64857428e-02, -1.66538102e-03,  6.72790594e-03,
         2.18296461e-02, -2.64101848e-03,  5.58515685e-03,  4.96168099e-02,
         1.70730967e-02, -1.34409264e-01, -8.59956220e-02,  1.12512857e-01,
        -1.47043390e-03, -1.84645467e-02, -1.77433100e-02, -2.85463799e-02,
         1.54257165e-02,  3.47101055e-02,  9.50510278e-02,  4.54177074e-02,
         6.73165694e-02,  2.13794112e-02,  2.19286121e-02,  2.44562794e-02,
         2.91221924e-02, -7.53295869e-02, -7.62853250e-02,  1.28947254e-02,
        -6.87281368e-03, -3.80360372e-02, -1.70098934e-02,  1.31638609e-02,
        -1.12015054e-01, -7.22132798e-04,  3.03103011e-02, -6.28964752e-02,
        -2.55976710e-02,  2.65581068e-02, -3.59090045e-02,  1.67137554e-33,
        -3.88185643e-02,  3.06049548e-02,  1.51212635e-02, -6.11019284e-02,
         4.43205535e-02, -1.79406069e-02, -2.38099671e-03, -4.28192951e-02,
        -9.57935452e-02, -2.08334923e-02, -4.77512702e-02,  5.36484122e-02,
        -1.19082026e-01,  1.07503861e-01,  4.35666256e-02, -1.83395320e-03,
        -3.47441100e-02,  1.28363073e-01, -2.10343730e-02,  1.63103174e-02,
         6.38983697e-02, -4.29395679e-03, -1.83589123e-02, -2.45889612e-02,
         1.85965635e-02, -2.19938904e-02,  2.89668776e-02, -7.73485284e-03,
        -4.61086854e-02,  1.84757989e-02, -8.72595757e-02,  1.04617644e-02,
         1.50737092e-02,  1.40909627e-02,  2.58631748e-03,  7.42051518e-03,
        -5.81071265e-02, -4.00013290e-02,  5.78782968e-02, -7.99759477e-02,
        -5.84782986e-03,  2.89127920e-02, -1.01088304e-02, -9.93202850e-02,
        -2.68824510e-02,  2.57940032e-03,  4.73130271e-02,  1.44877443e-02,
         2.90155560e-02, -2.42680311e-02,  1.97324604e-02,  1.74833704e-02,
        -6.60263598e-02,  2.19462290e-02,  3.94139497e-04,  6.22127652e-02,
         6.04855455e-02,  5.71038313e-02,  8.99824649e-02,  1.05967812e-01,
        -2.20740158e-02,  5.37180007e-02,  3.29890698e-02, -1.61205605e-02,
        -1.45135690e-02,  5.44799902e-02, -4.11546417e-02,  2.08166279e-02,
         3.15190032e-02,  6.18100166e-02, -5.83157800e-02,  1.74941104e-02,
         1.07499342e-02, -4.01822105e-02,  1.78126916e-02, -1.09161781e-02,
        -2.82848850e-02, -5.31789623e-02,  2.35454496e-02, -2.31786687e-02,
        -9.55962297e-03,  1.12064928e-01, -2.07617115e-02, -2.84874793e-02,
        -7.01760128e-02,  2.69417781e-02, -6.81750998e-02, -3.10795605e-02,
        -1.63623411e-02,  1.73255000e-02, -6.01202808e-03, -2.95510981e-02,
         6.30620215e-03,  1.83307286e-02,  3.32510397e-02, -9.09998115e-34,
        -5.20105362e-02,  8.64613205e-02, -1.93162300e-02,  1.41565099e-01,
        -1.45943016e-02, -5.85997552e-02, -6.39588386e-02,  2.16290765e-02,
        -3.97648253e-02,  3.52615751e-02,  9.50979963e-02,  1.25880688e-02,
         4.70341854e-02, -4.73708585e-02,  9.57325026e-02, -4.41588573e-02,
        -1.97757557e-02, -1.04737207e-01, -1.59487892e-02, -1.79804377e-02,
         6.12522885e-02,  2.91008260e-02, -7.98873305e-02, -2.57076509e-02,
        -2.93615814e-02, -2.57537123e-02, -3.91540863e-02,  2.25687306e-02,
        -1.71357170e-02, -5.02427295e-02,  4.36889790e-02, -1.65022817e-02,
        -7.47764409e-02,  3.65736857e-02,  1.91165917e-02,  1.10967355e-02,
         9.86192375e-02, -1.15591316e-02, -4.14489806e-02, -4.22605164e-02,
         6.97528794e-02,  1.77910402e-02, -2.84970505e-03, -2.78071477e-03,
        -4.50671129e-02,  2.51926389e-02, -4.78357822e-02,  3.04354224e-02,
         1.89303774e-02, -4.73750308e-02,  9.49808303e-03, -2.08600424e-02,
        -8.31720699e-03,  1.18591543e-02, -6.88176090e-03, -4.31842729e-02,
         2.93285660e-02,  5.01198843e-02, -2.67754379e-03,  5.55379167e-02,
        -1.07147820e-01, -3.14995907e-02,  2.62251366e-02,  1.46364830e-02,
        -1.48477836e-03, -4.66176979e-02, -4.33251224e-02,  9.13555548e-02,
         2.93849665e-03,  4.53500375e-02, -6.54006051e-03,  1.64960306e-02,
         5.02970591e-02,  9.68332291e-02, -4.08359198e-03,  6.92755505e-02,
         3.48087288e-02,  4.65422422e-02, -3.39299790e-03,  3.82541050e-03,
         2.48277839e-02,  2.16094684e-02,  4.61206958e-02,  2.30811350e-02,
         2.84140930e-02,  1.91139453e-03,  8.37903395e-02, -1.82828754e-02,
        -2.54615527e-02,  9.42331478e-02, -1.03919394e-01,  6.81325570e-02,
        -3.78719009e-02,  9.18154120e-02,  3.55535336e-02, -3.89110468e-08,
         7.06874672e-03,  3.87034416e-02,  4.40291576e-02,  3.58370598e-03,
        -3.51649784e-02, -4.28081974e-02, -6.68517593e-03,  8.11230689e-02,
        -1.25790136e-02,  6.97727650e-02,  8.15832317e-02, -4.52206358e-02,
        -5.85991666e-02, -9.58413072e-03, -1.00110509e-02,  8.33963454e-02,
         5.01508154e-02,  7.24992454e-02, -4.14660424e-02, -3.43066305e-02,
         2.53464356e-02,  9.64492932e-02,  1.02150567e-01, -4.12693620e-02,
         9.20193195e-02, -6.66196495e-02, -4.39895093e-02,  3.10542509e-02,
         2.32133474e-02,  2.09414158e-02,  5.14711849e-02,  7.04292953e-02,
        -1.16032530e-02, -1.74438413e-02,  3.41980644e-02,  1.04227774e-01,
        -8.21013674e-02,  6.09890595e-02,  6.85335174e-02,  3.54027487e-02,
         4.24368307e-03,  9.78788361e-02, -2.03037336e-02, -2.38748398e-02,
        -6.83089569e-02,  1.24891195e-02, -5.54992110e-02, -8.04915056e-02,
        -1.97720365e-03,  6.37955889e-02, -6.33953779e-04, -1.76166426e-02,
        -3.02154068e-02,  1.08358869e-02,  6.41388744e-02,  7.85659775e-02,
        -6.34882078e-02, -2.60339156e-02,  1.70808267e-02,  1.64184961e-02,
         1.80591049e-03, -7.14986101e-02, -1.63723957e-02,  1.01658404e-01])}