In [1]:
!nvidia-smi

Fri May  1 11:12:35 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.86                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro T1000                 WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8              3W /   50W |     113MiB /   4096MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A           13864    C+G   ...ms\Microsoft VS Code\Code.exe      N/A      |
|    0   N/A  N/A           15296    C+G   ...s\Win64\EpicGamesLauncher.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [35]:
import os  # library to deal with operating system
import requests # library use to dell with GET/POST requestes

#the url of book we test on 
url= r"https://arxiv.org/pdf/2412.19437"

#this path automatic assinge to the same folder we are her and name the book : "Data_file.pdf"
pdf_path=os.path.join(os.getcwd() , "Data_file.pdf")

# Confirming the existing of book and reinstall if not found 
if not os.path.exists(pdf_path):    
    response= requests.get(url) #downloadin is get request 
    if response.status_code == 200:
        with open(pdf_path,"wb") as f:  # more efficient than `for` in c level 
            f.write(response.content)
        print(f"[INFO] the file is downloaded at : {pdf_path}")
else:
    print(f"[INFO] file exist : {pdf_path} ")

[INFO] file exist : e:\Tests\Data_file.pdf

In [3]:
# import fitz  # PyMuPDF
# pages_and_texts=[]
# doc = fitz.open("Data_file.pdf")
# data_text = []

# for page_num , page in enumerate(doc):
#     text = page.get_text()
#     pages_and_texts.append({
#         "text_of_page" : text,
#         "page_number" : page_num + 1
#     })
# print(pages_and_texts[3]) 
# for text in pages_and_texts:
#     text["text_of_page"] =text["text_of_page"].replace(r"-\n"," ").strip()
# print(pages_and_texts[3] )

In [36]:
import fitz  # PyMuPDF :{ library used to hadnel PDF files }.

# `clean_text` : remove the spaces from begnining and ending of string
def clean_text(text: str):  
    text = text.replace("\n", " ").strip()
    return text


# open opdf and make array of pages with some statistics and use `clean_text`
def open_pdf(file_path:str):
    document=fitz.open(file_path)
    pages_and_texts=[]
    for page_num , page in enumerate(document):
        text = page.get_text()
        cleaned_text = clean_text(text)
        pages_and_texts.append({
            "text_of_page" : cleaned_text,
            "page_count_char" : len(cleaned_text),
            "page_count_word" : len(cleaned_text.split(" ")),
            "page_count_sentences" : len(cleaned_text.split(". ")),
            "tokens_num" : len(cleaned_text) // 4 , # i dont get it but it is what it is 
            "page_number" : page_num + 1
        })
    return pages_and_texts

pages_and_texts=open_pdf("Data_file.pdf")
pages_and_texts[3]

{'text_of_page': '1. Introduction In recent years, Large Language Models (LLMs) have been undergoing rapid iteration and evolution (Anthropic, 2024; Google, 2024; OpenAI, 2024a), progressively diminishing the gap to- wards Artificial General Intelligence (AGI). Beyond closed-source models, open-source models, including DeepSeek series (DeepSeek-AI, 2024a,b,c; Guo et al., 2024), LLaMA series (AI@Meta, 2024a,b; Touvron et al., 2023a,b), Qwen series (Qwen, 2023, 2024a,b), and Mistral series (Jiang et al., 2023; Mistral, 2024), are also making significant strides, endeavoring to close the gap with their closed-source counterparts. To further push the boundaries of open-source model capa- bilities, we scale up our models and introduce DeepSeek-V3, a large Mixture-of-Experts (MoE) model with 671B parameters, of which 37B are activated for each token. With a forward-looking perspective, we consistently strive for strong model performance and economical costs. Therefore, in terms of architecture, DeepSeek-V3 still adopts Multi-head Latent Attention (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for cost-effective training. These two architectures have been validated in DeepSeek- V2 (DeepSeek-AI, 2024c), demonstrating their capability to maintain robust model performance while achieving efficient training and inference. Beyond the basic architecture, we implement two additional strategies to further enhance the model capabilities. Firstly, DeepSeek-V3 pi- oneers an auxiliary-loss-free strategy (Wang et al., 2024a) for load balancing, with the aim of minimizing the adverse impact on model performance that arises from the effort to encourage load balancing. Secondly, DeepSeek-V3 employs a multi-token prediction training objective, which we have observed to enhance the overall performance on evaluation benchmarks. In order to achieve efficient training, we support the FP8 mixed precision training and implement comprehensive optimizations for the training framework. Low-precision training has emerged as a promising solution for efficient training (Dettmers et al., 2022; Kalamkar et al., 2019; Narang et al., 2017; Peng et al., 2023b), its evolution being closely tied to advancements in hardware capabilities (Luo et al., 2024; Micikevicius et al., 2022; Rouhani et al., 2023a). In this work, we introduce an FP8 mixed precision training framework and, for the first time, validate its effectiveness on an extremely large-scale model. Through the support for FP8 computation and storage, we achieve both accelerated training and reduced GPU memory usage. As for the training framework, we design the DualPipe algorithm for efficient pipeline parallelism, which has fewer pipeline bubbles and hides most of the communication during training through computation-communication overlap. This overlap ensures that, as the model further scales up, as long as we maintain a constant computation-to-communication ratio, we can still employ fine-grained experts across nodes while achieving a near-zero all-to-all communication overhead. In addition, we also develop efficient cross-node all-to-all communication kernels to fully utilize InfiniBand (IB) and NVLink bandwidths. Furthermore, we meticulously optimize the memory footprint, making it possible to train DeepSeek-V3 without using costly tensor parallelism. Combining these efforts, we achieve high training efficiency. During pre-training, we train DeepSeek-V3 on 14.8T high-quality and diverse tokens. The pre-training process is remarkably stable. Throughout the entire training process, we did not encounter any irrecoverable loss spikes or have to roll back. Next, we conduct a two-stage context length extension for DeepSeek-V3. In the first stage, the maximum context length is extended to 32K, and in the second stage, it is further extended to 128K. Following this, we conduct post-training, including Supervised Fine-Tuning (SFT) and Reinforcement Learning (RL) on the base model of DeepSeek-V3, to align it with human preferences and further unlock its potential. During the post-training stage, we distill the reasoning capability from the DeepSeek- R1 series of models, and meanwhile carefully maintain the balance between model accuracy 4',
 'page_count_char': 4248,
 'page_count_word': 594,
 'page_count_sentences': 26,
 'tokens_num': 1062,
 'page_number': 4}

In [37]:
import pandas as pd

# use `DataFrame` to display top 10 rows 
df = pd.DataFrame(pages_and_texts)
df.head(10)

,text_of_page,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,1817,238,11,454,1
1,Contents 1 Introduction 4 2 Architecture 6 2.1...,2634,919,766,658,2
2,4.5.3 Batch-Wise Load Balance VS. Sequence-Wis...,1715,572,462,428,3
3,"1. Introduction In recent years, Large Languag...",4248,594,26,1062,4
4,Training Costs Pre-Training Context Extension ...,3287,468,21,821,5
5,verification and reflection patterns of R1 int...,3475,457,23,868,6
6,… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ...,1557,262,8,389,7
7,where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vecto...,2236,353,9,559,8
8,where 𝑁𝑠and 𝑁𝑟denote the numbers of shared exp...,2901,455,17,725,9
9,Main Model (Next Token Prediction) Embedding L...,2904,451,23,726,10

In [ ]:
# use this `DataFrame` to do some statistics 
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
count,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00
std,799.86,178.18,124.63,199.99,15.44
min,699.00,99.00,1.00,174.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00
50%,2992.00,457.00,23.00,748.00,27.00
75%,3281.00,516.00,29.00,820.00,40.00
max,4248.00,919.00,766.00,1062.00,53.00

# Turn text to sentences

In [7]:
from spacy.lang.en import English

nlp= English()

# add sentencizer to pipeliine

nlp.add_pipe("sentencizer")

#example sentence to test
semtemces = "this my name . hellow mr.ahmed . what is your name ?"

doc = nlp(semtemces)
# list the sentences to show 
list(doc.sents)

[this my name ., hellow mr.ahmed ., what is your name ?]

# Now try the `data`

In [8]:
for page in pages_and_texts:
    page["sentences"] = list(nlp(page["text_of_page"]).sents)
    page["sentences_num"] =len(page["sentences"])

#make sure tha all sentences is string not spacy type
for page in pages_and_texts:
    page["sentences"]=[str(sentences) for sentences in page["sentences"]]

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25}

In [9]:
#read specific sentence
pages_and_texts[5]["sentences"][6]

'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.'

In [10]:
# see some statistics about this data 
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num
count,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94
std,799.86,178.18,124.63,199.99,15.44,14.44
min,699.00,99.00,1.00,174.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00

In [11]:
test=list(range(1,25))
input_list=[]
slice_size=10
x=[test[i:i+slice_size] for i in range(0,len(test),slice_size)]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24]]

In [12]:
def chunker (input_list : list[str],slice_size:int)->list[list[str]]:

    return[input_list[i:i+slice_size] for i in range(0,len(input_list),slice_size)]

for page in pages_and_texts:
    page["sentences_chunk"] = chunker(page["sentences"],slice_size)
    page["sentences_chunk_num"] =len( page["sentences_chunk"]) 

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25,
 'sentences_chunk': [['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
   'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
   'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
   'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
   '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
   'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
   'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
   'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
   '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
   'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.'],
  ['In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
   'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
   'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
   'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
   'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
   '2.',
   'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
   '2024) for economical training.',
   'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
   'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).'],
  ['2.1.',
   'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
   '2017) framework.',
   'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
   'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6']],
 'sentences_chunk_num': 3}

In [13]:
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num,sentences_chunk_num
count,53.00,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94,2.89
std,799.86,178.18,124.63,199.99,15.44,14.44,1.40
min,699.00,99.00,1.00,174.00,1.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00,2.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00,3.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00,3.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00,6.00

In [14]:
pages_and_chunk=[]
for page in pages_and_texts:
    for chunk in page["sentences_chunk"]:
        chunk_dict = {}

        # join all sentences in chunk to be one paragraphe
        paragragh = "".join(chunk).replace("  "," ").strip()
        chunk_dict ["paragraphe"] = paragragh
        
        # Calculate statistics
        words = paragragh.split(" ")
        word_count = len(words)
        char_count = len(paragragh)
        tokens_count = char_count // 4  # approximate tokens
        sentence_count = len(chunk)  # number of sentences in chunk
        
        # Store statistics
        chunk_dict["word_count"] = word_count
        chunk_dict["char_count"] = char_count
        chunk_dict["tokens_count"] = tokens_count
        chunk_dict["sentence_count"] = sentence_count
        chunk_dict ["page_number"] = page["page_number"]

        pages_and_chunk.append(chunk_dict)
pages_and_chunk[5] ,len(pages_and_chunk),len(pages_and_texts)

({'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
  'word_count': 298,
  'char_count': 830,
  'tokens_count': 207,
  'sentence_count': 10,
  'page_number': 3},
 153,
 53)

In [15]:
df = pd.DataFrame(pages_and_chunk)
df.describe().round(2)

       word_count  char_count  tokens_count  sentence_count  page_number
count      153.00      153.00        153.00          153.00       153.00
mean       157.03      974.48        243.26            8.29        26.52
std        145.88      584.64        146.14            2.95        13.86
min          1.00        1.00          0.00            1.00         1.00
25%         74.00      572.00        143.00            7.00        15.00
50%        134.00      912.00        228.00           10.00        28.00
75%        191.00     1301.00        325.00           10.00        39.00
max        877.00     2975.00        743.00           10.00        53.00

In [16]:
df[df["word_count"]<4]
pages_and_texts[8]

{'text_of_page': 'where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts. Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values. Auxiliary-Loss-Free Load Balancing. For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al., 2017) and diminish computational efficiency in scenarios with expert parallelism. Conventional solutions usually rely on the auxiliary loss (Fedus et al., 2021; Lepikhin et al., 2021) to avoid unbalanced load. However, too large an auxiliary loss will impair the model performance (Wang et al., 2024a). To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al., 2024a) to ensure load balance. To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (16) Note that the bias term is only used for routing. The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step. At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed. Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses. Complementary Sequence-Wise Auxiliary Loss. Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence. The sequence-wise balance loss encourages the expert load on each sequence to be balanced. 9',
 'page_count_char': 2901,
 'page_count_word': 455,
 'page_count_sentences': 17,
 'tokens_num': 725,
 'page_number': 9,
 'sentences': ['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
  'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
  'Auxiliary-Loss-Free Load Balancing.',
  'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
  '2017) and diminish computational efficiency in scenarios with expert parallelism.',
  'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
  '2021; Lepikhin et al.,',
  '2021) to avoid unbalanced load.',
  'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
  '2024a).',
  'To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
  '2024a) to ensure load balance.',
  'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
  '16) Note that the bias term is only used for routing.',
  'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
  'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
  'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
  'Complementary Sequence-Wise Auxiliary Loss.',
  'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
  'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.',
  '9'],
 'sentences_num': 21,
 'sentences_chunk': [['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
   'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
   'Auxiliary-Loss-Free Load Balancing.',
   'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
   '2017) and diminish computational efficiency in scenarios with expert parallelism.',
   'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
   '2021; Lepikhin et al.,',
   '2021) to avoid unbalanced load.',
   'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
   '2024a).'],
  ['To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
   '2024a) to ensure load balance.',
   'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
   '16) Note that the bias term is only used for routing.',
   'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
   'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
   'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
   'Complementary Sequence-Wise Auxiliary Loss.',
   'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
   'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.'],
  ['9']],
 'sentences_chunk_num': 3}

In [17]:
#filter out tokens less than 30
filtered_chunks = [chunk for chunk in pages_and_chunk if chunk["tokens_count"] >= 30]
filtered_chunks[111]

{'paragraphe': 'A study of bfloat16 for deep learning training.arXiv preprint arXiv:1905.12322, 2019.S. Krishna, K. Krishna, A. Mohananey, S. Schwarcz, A. Stambler, S. Upadhyay, and M. Faruqui.Fact, fetch, and reason: A unified evaluation of retrieval-augmented generation.CoRR, abs/2409.12941, 2024.doi: 10.48550/ARXIV.2409.12941.URL https://doi.org/10.485 50/arXiv.2409.12941.T. Kwiatkowski, J. Palomaki, O. Redfield, M. Collins, A. P. Parikh, C. Alberti, D. Epstein, I. Polosukhin, J. Devlin, K. Lee, K. Toutanova, L. Jones, M. Kelcey, M. Chang, A. M. Dai, J. Uszkoreit, Q. Le, and S. Petrov.Natural questions: a benchmark for question answering research.Trans.',
 'word_count': 84,
 'char_count': 648,
 'tokens_count': 162,
 'sentence_count': 10,
 'page_number': 39}

In [18]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

c:\Users\Mohamed\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<?, ?it/s]

In [19]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True

In [20]:
set = ["my name", "her name", "the naem"]
embeding = model.encode(set)
embeding = dict(zip(set,embeding))

embeding,embeding["my name"].shape

({'my name': array([-1.11268602e-01,  3.23448591e-02, -3.83405834e-02,  2.23898627e-02,
         -4.03140783e-02, -5.62008433e-02,  2.33329967e-01,  3.92086729e-02,
         -1.01079242e-02, -6.38170391e-02,  1.64090227e-02, -3.45564671e-02,
          4.02090251e-02, -7.56014660e-02, -8.34888965e-03,  2.65754387e-02,
         -1.42914923e-02,  6.17231149e-03, -8.46135616e-02, -7.72886351e-02,
         -4.17721868e-02,  6.27691001e-02, -3.23680506e-05, -2.02984773e-02,
         -8.92573744e-02,  6.10294333e-03, -3.12835611e-02,  9.11155194e-02,
         -3.69639173e-02, -1.61543280e-01, -3.80769518e-04,  7.48009467e-03,
          9.98783186e-02,  5.72648980e-02, -4.66816034e-03, -4.17357311e-02,
         -1.26731142e-01, -2.11646669e-02,  5.62063567e-02, -1.07810488e-02,
         -4.70565679e-03, -1.19292334e-01,  2.42646299e-02,  5.37948310e-03,
          7.11644581e-03,  7.88039621e-03,  6.28924463e-04,  2.45067645e-02,
          1.61230303e-02,  9.47958231e-02, -9.59324986e-02, -8.88254344e-02,
         -5.96604422e-02,  1.89628787e-02,  1.31215407e-02, -7.77191371e-02,
          2.44201161e-02,  5.09177484e-02, -3.09437583e-03,  2.27765311e-04,
          4.02659625e-02,  1.79442074e-02, -7.26719275e-02,  3.98123711e-02,
          1.57936160e-02,  8.13504867e-03, -6.94837375e-03,  1.39237326e-02,
          4.64227656e-03, -9.63736884e-03, -2.38478649e-02, -6.72965450e-03,
          7.07242340e-02, -3.35569419e-02, -1.96107812e-02, -1.45387556e-02,
          1.61475949e-02, -1.77206695e-02, -1.31568862e-02,  6.13829195e-02,
         -8.46485496e-02,  4.43952717e-03, -9.70008671e-02, -8.54695868e-03,
         -2.76289042e-02,  4.83488068e-02,  3.65964994e-02, -3.85117233e-02,
         -2.87031792e-02, -5.48657775e-03,  2.66993325e-03, -7.49976933e-02,
          2.27707773e-02, -3.73113062e-03, -2.44773440e-02, -5.23784664e-03,
         -3.77394812e-04, -4.05308045e-02, -3.87832411e-02,  1.85519353e-01,
         -6.50252774e-02,  3.38606313e-02, -5.62591217e-02,  7.47068524e-02,
         -7.21330149e-03, -8.54292046e-03, -5.87108247e-02,  5.19497925e-03,
          5.03454125e-03, -2.29808614e-02, -5.23379929e-02, -2.39632837e-02,
         -5.20040542e-02,  4.00796086e-02,  3.42810489e-02,  7.10861087e-02,
          2.96648638e-03, -2.60684136e-02,  3.05782016e-02, -2.95661837e-02,
          4.49147262e-02,  2.99034249e-02, -8.65572020e-02, -1.93888042e-02,
         -2.02058069e-02,  1.09100919e-02, -1.28705765e-03, -3.38961069e-33,
          5.94924437e-03,  1.89252160e-02, -4.11714369e-04,  1.40347689e-01,
          2.08696984e-02,  1.44509543e-02, -5.77049702e-02,  7.57386768e-03,
         -3.34116220e-02, -4.86473931e-04,  1.18632261e-02,  1.23979710e-02,
         -2.82271616e-02,  6.32571504e-02,  2.87447739e-02,  3.98514457e-02,
         -2.19962839e-02,  5.86499237e-02, -3.66562046e-02,  2.81827636e-02,
         -3.64034772e-02,  6.67515323e-02,  3.82383214e-03,  3.85378189e-02,
         -5.31675816e-02, -1.20789595e-01, -1.26687186e-02, -7.43082836e-02,
          3.59357931e-02,  2.43287757e-02, -5.68793975e-02, -1.62085071e-02,
          8.52153525e-02, -1.06991231e-02,  2.98596621e-02, -8.78666714e-02,
         -1.15062119e-02,  1.56421755e-02, -4.40782085e-02,  1.03963681e-01,
         -9.96414479e-03,  1.12467455e-02, -7.92487264e-02,  4.75009345e-02,
         -2.51976848e-02, -1.84205454e-02,  3.58203575e-02,  5.33687398e-02,
         -9.88210589e-02, -1.01148849e-02, -5.02877273e-02,  3.62836011e-02,
         -1.07462898e-01, -1.13364054e-04, -8.78018439e-02,  2.03307029e-02,
         -1.38519984e-03,  9.96504165e-03, -1.05820306e-01, -1.08255902e-02,
         -5.61665418e-03,  3.54209617e-02, -1.99718494e-02,  1.85143687e-02,
          1.84967872e-02, -4.77539301e-02,  7.75206983e-02, -5.72839528e-02,
          2.59807035e-02,  3.01387981e-02, -7.60096982e-02, -5.30696213e-02,
          4.44190018e-03,  4.09771018e-02,  7.15029314e-02,  6.62903022e-03,
         -8.63277167e-03,  5.87880649e-02, -3.33780386e-02, -9.79795307e-03,
          3.39137428e-02, -1.12670697e-02,  2.68006767e-03,  3.78638431e-02,
          2.98797954e-02, -2.79733795e-03, -1.43967113e-02, -3.69952619e-02,
         -1.53701017e-02, -3.44166532e-02, -1.34393826e-01, -1.39013270e-03,
          1.08393133e-01, -2.45960653e-02, -5.27150147e-02,  1.20526999e-33,
         -1.27882026e-02,  4.35465351e-02,  1.87254958e-02,  9.56210569e-02,
          4.67719603e-03, -2.69599725e-02,  5.32101979e-03,  1.07820265e-01,
          1.92453689e-03,  5.60386255e-02, -2.19701175e-02, -8.23149979e-02,
          4.67025489e-03, -2.90252338e-03,  8.16676468e-02,  4.96277139e-02,
          4.06118482e-02, -1.76349177e-03, -4.65383530e-02,  2.63393368e-03,
         -5.90300523e-02,  5.77562898e-02, -1.08629251e-02, -6.16722032e-02,
         -4.12747310e-03,  1.70052815e-02,  3.90952788e-02,  2.52950341e-02,
          7.08593577e-02,  6.80857077e-02,  5.44357393e-03,  2.39246972e-02,
         -1.16943434e-01,  2.93325037e-02, -2.60607079e-02,  6.45446777e-02,
         -1.89389009e-02, -1.98988672e-02,  1.02715334e-02, -3.32666491e-03,
         -1.41809136e-02,  3.20844874e-02, -7.18639344e-02,  1.08568095e-01,
         -1.31833227e-02, -3.98828611e-02, -5.78845441e-02,  3.01687773e-02,
          1.03621352e-02,  4.26096991e-02, -3.35614532e-02, -6.73616007e-02,
         -6.93707392e-02, -3.82362455e-02,  1.17582828e-03,  3.61948758e-02,
          6.44930154e-02,  2.16483474e-02,  9.53725539e-03,  4.65247361e-03,
          1.59357935e-02,  3.41445282e-02,  6.12317175e-02,  7.34104589e-02,
          3.04528922e-02, -1.78817715e-02, -6.13178089e-02, -4.10457030e-02,
         -2.72018649e-02, -4.76150028e-02, -5.27509265e-02,  2.03911513e-02,
         -4.46444489e-02,  2.69611403e-02, -9.46116373e-02,  3.20556834e-02,
          1.63121428e-02,  2.63476055e-02, -2.50775199e-02,  5.37288971e-02,
          3.02447416e-02,  8.66488442e-02, -2.48541404e-02,  3.00489012e-02,
          1.60620119e-02, -2.64488161e-02,  3.59426700e-02,  8.03072080e-02,
         -2.33003721e-02, -3.87402549e-02,  2.93709300e-02,  3.48940790e-02,
         -1.20453164e-02, -1.63013488e-02, -9.69538465e-02, -1.50699115e-08,
          4.22302522e-02,  5.01371957e-02,  3.11900470e-02, -4.23698360e-03,
          5.10957800e-02,  8.86452645e-02, -3.07830912e-03, -2.18302403e-02,
          4.13647331e-02,  6.56360015e-02,  9.79078338e-02,  5.34657985e-02,
          3.15143391e-02,  9.64247156e-03,  9.51067731e-02, -2.79179197e-02,
         -5.68721481e-02,  8.92903190e-03, -4.92045935e-03, -2.21010149e-02,
         -3.58192995e-02, -2.98429020e-02,  8.19763839e-02, -7.19112009e-02,
          4.26656641e-02,  9.13801696e-03,  3.62761579e-02,  9.37117562e-02,
         -5.74504621e-02,  7.81974643e-02,  1.13642160e-02,  1.17897831e-01,
          1.24910325e-02,  6.13725260e-02, -3.99509855e-02, -9.76392010e-04,
          2.87474766e-02,  8.35280120e-02,  5.63313179e-02, -8.02361127e-03,
         -3.31368297e-02,  5.76817542e-02,  9.86445621e-02, -1.26726562e-02,
         -6.93444908e-02,  6.50679320e-02, -2.79120664e-04, -1.52545832e-02,
         -4.63721994e-03, -2.10705902e-02,  8.71946383e-03,  1.70729980e-02,
          2.25880053e-02,  7.89605752e-02,  2.01135594e-02,  4.21369486e-02,
          3.23688388e-02,  5.68196215e-02, -6.11764826e-02, -5.45439497e-02,
          7.75278136e-02,  5.29305823e-03, -9.12822634e-02,  1.33655965e-02],
        dtype=float32),
  'her name': array([-1.08516805e-01,  1.40265562e-02, -1.97903570e-02,  4.03933004e-02,
         -3.66050415e-02, -1.11382268e-03,  1.42931879e-01,  4.01251875e-02,
         -9.60893184e-03, -7.14012906e-02,  2.60373130e-02, -9.37794447e-02,
         -1.03091607e-02, -7.65828341e-02, -4.02911119e-02,  7.74797127e-02,
          3.67319472e-02,  3.94580625e-02, -9.53144431e-02, -5.77405542e-02,
         -2.17363127e-02, -2.40650773e-02,  3.27846035e-02,  4.04388905e-02,
         -3.74303870e-02,  2.06175190e-03, -5.38016632e-02,  1.28083434e-02,
         -3.16409841e-02, -1.22112051e-01,  1.27528738e-02, -1.95463300e-02,
          4.58517894e-02,  7.62845352e-02, -1.12639777e-02,  3.25133726e-02,
         -7.22714812e-02,  4.53227870e-02,  2.71108262e-02, -1.35518415e-02,
         -1.94000956e-02, -1.14641130e-01, -4.72653173e-02, -4.64220420e-02,
         -3.94386947e-02, -4.94745895e-02,  5.11805341e-02,  3.23775671e-02,
          2.72550080e-02, -2.67371908e-02, -6.49755448e-02, -5.32744825e-02,
         -1.18825644e-01,  2.55613402e-03,  7.93129951e-02, -2.25096010e-02,
          5.34011275e-02,  5.47847375e-02,  3.82738262e-02,  1.02928244e-02,
          6.06006309e-02,  5.18806875e-02, -7.12646097e-02,  4.85623032e-02,
         -5.31427562e-03, -9.10784490e-03,  3.76583636e-02, -4.69223112e-02,
          3.90819050e-02,  6.33175904e-03,  2.00461652e-02,  3.55321430e-02,
         -1.72345887e-03, -3.88698317e-02,  2.61442214e-02,  1.99030880e-02,
          7.56488964e-02,  1.09233195e-02,  2.11198498e-02,  6.88376352e-02,
         -7.15844184e-02,  1.77171398e-02,  5.93838398e-04,  1.94033179e-02,
          4.28241678e-03,  4.30800878e-02, -3.16122100e-02, -2.20458545e-02,
         -2.73830909e-02, -5.10557480e-02, -4.97698188e-02, -6.01557270e-02,
          3.76522504e-02, -1.17023699e-02, -2.06190459e-02, -2.93967631e-02,
         -2.07708031e-02, -2.78658532e-02, -1.51965749e-02,  1.78603187e-01,
         -9.23539177e-02,  1.01476848e-01, -9.04801860e-03,  9.42860693e-02,
         -3.34172510e-02, -5.97187690e-02,  4.86570559e-02, -5.82064129e-03,
         -3.47071066e-02, -1.29233170e-02, -1.64538657e-03, -1.47645706e-02,
         -9.90036204e-02, -5.19061787e-03,  3.52939293e-02,  3.13790590e-02,
          4.73542251e-02, -1.23639191e-02,  2.38938183e-02, -9.74604487e-02,
          4.04632837e-02, -4.96868864e-02, -4.79107834e-02, -2.40673106e-02,
         -5.60441054e-02, -2.87502948e-02,  2.83523630e-02, -3.16461226e-33,
         -3.55151370e-02,  2.95765921e-02,  8.10843781e-02,  8.34556818e-02,
          5.95203601e-02,  2.11190581e-02,  1.59793403e-02,  1.16894916e-02,
          3.46234115e-03, -2.01443806e-02, -2.27796333e-03, -8.82629082e-02,
         -5.42954467e-02, -8.02553818e-02,  1.01886146e-01,  1.27109950e-02,
         -3.21838632e-02,  7.77680203e-02, -7.86050484e-02,  5.41977845e-02,
          4.28526364e-02,  8.47250149e-02,  2.49308385e-02,  5.01613766e-02,
         -3.17425765e-02, -9.03306454e-02,  7.80699626e-02,  1.17246397e-02,
          1.61143474e-03,  3.63856368e-02, -2.68512685e-02,  1.80523188e-04,
          8.83467346e-02, -1.63772944e-02,  5.22143096e-02, -4.44411039e-02,
         -5.81525406e-03, -1.12066157e-02,  3.63274524e-03,  7.74847865e-02,
          2.00559217e-02, -1.65881235e-02,  2.73299608e-02,  1.84894260e-02,
         -1.34903491e-01,  4.32647988e-02,  5.84352836e-02,  1.03551196e-02,
          4.11864370e-02, -6.93740367e-05, -9.41860825e-02,  3.53580117e-02,
         -1.00075260e-01,  5.65286353e-02, -6.15794547e-02,  8.11114460e-02,
          3.31929997e-02, -1.32226441e-02, -1.87826250e-02, -3.98740135e-02,
          1.16542084e-02,  2.19120793e-02, -6.86919540e-02,  9.83211026e-03,
          4.92209084e-02, -5.10650724e-02,  2.85478700e-02, -1.02851331e-01,
          3.24431285e-02,  1.23117128e-02, -1.13674045e-01,  1.87593140e-02,
          2.25785431e-02,  4.31682058e-02, -5.41481152e-02,  2.82279607e-02,
          3.29296663e-02, -2.86128316e-02, -3.13659832e-02, -5.98061783e-03,
          1.17117343e-02,  3.75699550e-02, -2.54161488e-02,  8.43513682e-02,
         -4.38703373e-02, -3.62565741e-03, -2.06886549e-02, -1.42937908e-02,
         -3.48394141e-02, -7.15545565e-02, -6.16803728e-02,  2.06668545e-02,
          7.54758492e-02, -4.97289374e-02, -2.12219357e-02,  1.31706244e-33,
         -5.28452778e-03,  1.54752489e-02, -4.34725322e-02,  6.07264303e-02,
          5.43512739e-02, -1.14345578e-02, -1.48575346e-03,  1.01141483e-01,
         -4.60984372e-03, -1.25182383e-02,  2.76288278e-02, -1.24480315e-01,
          1.22275706e-02, -1.49447229e-02,  6.50415197e-02,  6.65459111e-02,
          8.23930651e-02, -6.69729263e-02, -3.24602276e-02, -6.40190020e-02,
         -9.25135538e-02,  1.08705871e-02,  1.46334730e-02, -7.67764524e-02,
         -2.50701830e-02,  2.24010088e-02,  9.63630825e-02, -2.89402250e-03,
         -4.82729189e-02, -1.27476687e-02,  3.41592059e-02,  1.86355300e-02,
         -7.29231089e-02,  6.13725185e-02, -3.97584289e-02,  4.89614829e-02,
          2.06597354e-02, -4.81188521e-02,  2.89741941e-02,  2.80811973e-02,
          4.12800573e-02,  8.84461682e-03, -2.17010900e-02,  1.02579340e-01,
          2.75865197e-02,  2.12727152e-02, -1.27490787e-02,  4.89049293e-02,
          8.61027986e-02,  2.64374278e-02, -2.06164587e-02, -7.87167028e-02,
         -2.70623583e-02,  8.11806042e-03,  5.95773123e-02, -3.19411531e-02,
          5.81039898e-02,  1.95025001e-02,  3.71584073e-02,  5.88323036e-03,
          1.53962849e-02,  3.51784602e-02, -2.35251132e-02,  7.92885572e-02,
         -3.05617563e-02, -1.99384745e-02, -8.13734904e-02, -1.25664771e-01,
         -2.59873886e-02, -5.24826422e-02,  3.75156617e-03,  2.80722268e-02,
         -4.10410799e-02,  6.88030943e-02, -9.14724991e-02,  1.63114406e-02,
         -9.08275172e-02, -2.50380971e-02, -2.15020496e-02,  3.57075408e-02,
          1.56707522e-02,  2.72470638e-02, -5.09988181e-02,  1.73475698e-03,
          2.54247282e-02, -4.76679951e-03,  8.02696571e-02,  1.11472152e-01,
         -2.18369029e-02, -1.08616456e-01, -1.27692120e-02, -8.22651293e-03,
         -1.66713204e-02, -6.58632964e-02, -7.73727074e-02, -1.59770792e-08,
          1.07898936e-02, -4.41672280e-03,  5.39550669e-02, -6.93759844e-02,
          4.82009724e-02,  7.87588656e-02,  2.61549931e-02, -1.01904087e-02,
          2.86767855e-02,  7.04269260e-02,  8.22025687e-02,  2.00291593e-02,
          5.73524386e-02,  3.10402717e-02,  6.98653609e-02, -3.70384194e-02,
          1.93623975e-02,  1.15336105e-01, -4.57215821e-03,  1.14648025e-02,
         -6.67652395e-03, -4.16180827e-02,  5.23354597e-02, -1.36465088e-01,
          1.81709565e-02,  6.24541007e-03, -1.47890877e-02,  1.09797210e-01,
         -4.21142466e-02,  1.01671284e-02, -3.07445507e-02,  1.13257244e-01,
          3.45925428e-02,  1.96992867e-02,  1.25573715e-03,  3.80590148e-02,
          4.83893678e-02,  2.26374716e-02, -1.67597476e-02,  3.04050911e-02,
         -1.51804108e-02,  2.86381226e-02,  9.29250717e-02, -2.69179512e-02,
         -5.29072173e-02,  2.60877945e-02,  1.27067398e-02, -4.53396812e-02,
         -2.70353723e-03, -1.21021578e-02, -7.78898690e-03,  1.35551114e-02,
          4.36936915e-02,  3.78443748e-02, -2.25434843e-02, -1.41144283e-02,
          2.71069203e-02, -2.39804778e-02, -3.96825001e-02,  1.36273113e-04,
          7.66980182e-03,  1.05080036e-02,  6.80240169e-02,  1.96243785e-02],
        dtype=float32),
  'the naem': array([-6.02948368e-02,  1.08011052e-01, -4.00737152e-02,  2.84987706e-04,
         -5.78279756e-02,  3.90510634e-02,  1.63081363e-02, -6.27290532e-02,
         -2.72917245e-02,  6.48954511e-02, -1.36009976e-02, -1.12080678e-01,
          4.29547355e-02, -3.33018713e-02,  3.84274125e-02,  1.98117574e-04,
         -9.92214028e-03,  3.54607147e-03, -1.39897885e-02, -5.76529354e-02,
         -3.93402390e-02,  4.99700494e-02,  2.77685262e-02, -9.71353520e-03,
         -7.29377046e-02,  3.06774338e-04,  5.28396070e-02,  1.97455753e-02,
          6.62655681e-02, -1.39705881e-01,  5.01716742e-04,  6.13604039e-02,
         -2.77932715e-02,  1.24620153e-02, -6.92577884e-02, -7.66454451e-03,
         -6.53420836e-02, -5.53790107e-03,  1.61085222e-02,  6.49704505e-03,
          7.51554444e-02, -4.55971509e-02, -3.45250918e-03, -3.36859189e-02,
          3.02659664e-02, -7.05948770e-02, -2.51310728e-02, -1.06170345e-02,
          4.80370186e-02,  5.61027899e-02,  3.07876095e-02, -5.77379651e-02,
         -2.93143485e-02,  2.36564446e-02,  6.86284453e-02,  3.42092179e-02,
         -3.66425514e-02, -1.07707478e-01,  2.47657727e-02, -1.87081704e-03,
          8.02794322e-02, -6.56674523e-03, -7.98377916e-02,  6.52273372e-02,
          6.82051927e-02, -9.37174484e-02,  6.07989393e-02,  3.30210067e-02,
         -3.37643698e-02,  2.64172200e-02,  3.17097791e-02, -5.40623739e-02,
          7.14883283e-02, -5.86151982e-05, -5.46505861e-02, -2.46138684e-03,
          6.93024918e-02,  2.13217065e-02,  4.47886698e-02, -1.18316235e-02,
          3.43479067e-02,  3.82323861e-02,  3.36475745e-02, -3.92940417e-02,
          5.31843379e-02, -2.18139612e-03,  8.81356448e-02, -2.54524872e-03,
          2.20382381e-02,  3.63924839e-02, -5.86666018e-02, -3.01842000e-02,
         -8.23798683e-03, -4.73330878e-02,  3.13263424e-02, -3.42283696e-02,
         -2.73820106e-02,  1.87601261e-02,  1.42660681e-02,  1.50501013e-01,
          8.95082653e-02,  1.07485525e-01,  3.75267747e-03,  2.73721553e-02,
          2.50877477e-02,  1.64601672e-02,  1.33112883e-02,  9.83588491e-03,
         -1.44914724e-02,  7.16948509e-02, -4.74362597e-02, -1.86514575e-02,
         -2.84116659e-02, -5.88079542e-03,  3.09784003e-02, -2.49706283e-02,
         -1.90918464e-02, -2.12573595e-02,  5.94183663e-03,  2.15574298e-02,
          6.16730470e-03, -8.75436887e-02, -8.20264295e-02,  3.19139361e-02,
          3.29091623e-02,  5.75121380e-02, -1.16018206e-02, -3.45252829e-33,
         -1.07773626e-02,  7.30658788e-03, -1.63617525e-02, -4.64672260e-02,
          3.70621607e-02,  2.73215473e-02, -2.31236815e-02,  5.66564575e-02,
         -9.57396105e-02, -1.78244039e-02, -2.85459794e-02,  7.88214877e-02,
         -7.85891488e-02,  1.38537521e-02,  8.36979896e-02,  1.03458334e-02,
         -7.59366751e-02, -2.64888834e-02, -3.77846546e-02, -9.53301787e-02,
         -1.12825751e-01,  1.13505095e-01,  7.91859906e-03,  4.91239540e-02,
         -4.25062217e-02,  2.93205623e-02, -2.66452655e-02, -8.48129988e-02,
         -2.70097535e-02,  3.14407498e-02,  4.99393530e-02,  4.24260907e-02,
         -5.03373332e-02,  4.26193252e-02, -8.63207206e-02, -7.60602811e-03,
         -2.76761204e-02, -2.03614421e-02, -5.48336618e-02, -3.26869451e-02,
         -3.44958529e-02,  2.51876283e-02,  1.70821920e-02,  6.42866492e-02,
         -8.01584050e-02, -4.63353507e-02, -1.50233721e-02, -6.26032725e-02,
          8.19116533e-02,  2.78966185e-02,  2.92819412e-03, -3.42843216e-03,
         -4.39038277e-02, -2.01127920e-02,  9.56660230e-03, -1.93480980e-02,
          1.94181470e-04,  4.55720685e-02,  6.61208481e-02, -1.77856423e-02,
          3.08940876e-02,  4.35537174e-02,  3.67996246e-02,  9.71465036e-02,
          3.79517041e-02,  3.49885598e-02, -6.32042298e-03, -6.03008382e-02,
          5.28266616e-02, -3.05552352e-02, -4.74490300e-02,  5.96354567e-02,
          6.59352094e-02,  7.80555457e-02, -1.09360891e-03,  1.21456832e-02,
         -5.06833196e-03, -8.68264735e-02, -9.48877335e-02, -3.95371765e-02,
          2.56637298e-02,  5.39868511e-02, -2.76523568e-02,  6.43403605e-02,
          3.58118936e-02, -1.93711687e-02, -2.32705586e-02, -1.75262950e-02,
          1.40554244e-02, -2.48366334e-02,  1.45109603e-02,  4.32571582e-02,
          1.46898115e-02, -6.47579730e-02, -5.66580184e-02,  3.23795980e-33,
          2.35630665e-02,  1.24059962e-02, -1.02182642e-01,  6.69505373e-02,
          6.45909831e-02, -4.55888845e-02,  4.77874316e-02,  2.63668355e-02,
         -1.10716738e-01,  3.60688604e-02,  1.58359949e-02, -2.84001231e-02,
          1.29867524e-01,  4.72247377e-02,  8.71693417e-02, -5.97081184e-02,
          1.27869114e-01, -8.50947872e-02,  2.15539802e-02, -3.34259607e-02,
          2.41573919e-02, -3.29210460e-02,  1.49753746e-02, -1.72330551e-02,
          1.08727654e-02,  7.22939223e-02,  1.39474655e-02, -7.08193704e-02,
         -7.42303282e-02, -2.18185224e-02,  1.94082949e-02,  3.13056856e-02,
         -1.57291405e-02,  9.62476339e-03, -4.63565923e-02,  3.84134576e-02,
          2.73783859e-02,  6.42660111e-02, -6.87038526e-02, -4.55769077e-02,

In [21]:
print(type(pages_and_chunk[0]))
print(pages_and_chunk[0])

<class 'dict'>
{'paragraphe': 'DeepSeek-V3 Technical Report DeepSeek-AI research@deepseek.com Abstract We present DeepSeek-V3, a strong Mixture-of-Experts (MoE) language model with 671B total parameters with 37B activated for each token.To achieve efficient inference and cost-effective training, DeepSeek-V3 adopts Multi-head Latent Attention (MLA) and DeepSeekMoE architec- tures, which were thoroughly validated in DeepSeek-V2.Furthermore, DeepSeek-V3 pioneers an auxiliary-loss-free strategy for load balancing and sets a multi-token prediction training objective for stronger performance.We pre-train DeepSeek-V3 on 14.8 trillion diverse and high-quality tokens, followed by Supervised Fine-Tuning and Reinforcement Learning stages to fully harness its capabilities.Comprehensive evaluations reveal that DeepSeek-V3 outperforms other open-source models and achieves performance comparable to leading closed-source models.Despite its excellent performance, DeepSeek-V3 requires only 2.788M H800 GPU hours for its full training.In addition, its training process is remarkably stable.Throughout the entire training process, we did not experience any irrecoverable loss spikes or perform any rollbacks.The model checkpoints are available at https://github.com/deepseek-ai/DeepSeek-V3.MMLU-Pro (EM) GPQA-Diamond (Pass@1) MATH 500 (EM) AIME 2024 (Pass@1) Codeforces (Percentile) SWE-bench Verified (Resolved) 0 20 40 60 80 100 Accuracy / Percentile (%) 75.9 59.1 90.2 39.2 51.6 42.0 66.2 41.3 74.7 16.7 35.6 22.6 71.6 49.0 80.0 23.3 24.8 23.8 73.3 51.1 73.8 23.3 25.3 24.5 72.6 49.9 74.6 9.3 23.6 38.8 78.0 65.0 78.3 16.0 20.3 50.8 DeepSeek-V3 DeepSeek-V2.5 Qwen2.5-72B-Inst Llama-3.1-405B-Inst GPT-4o-0513 Claude-3.5-Sonnet-1022 Figure 1 | Benchmark performance of DeepSeek-V3 and its counterparts.', 'word_count': 222, 'char_count': 1767, 'tokens_count': 441, 'sentence_count': 10, 'page_number': 1}

In [22]:
from tqdm import tqdm

for chunk in tqdm(pages_and_chunk):
    chunk["embedding"] = model.encode(chunk["paragraphe"], device="cuda")

100%|██████████| 153/153 [00:01<00:00, 80.02it/s]

In [23]:
import random
random.sample(pages_and_chunk,k=1)

[{'paragraphe': 'Benchmark (Metric) # Shots DeepSeek-V2 Qwen2.5 LLaMA-3.1 DeepSeek-V3 Base 72B Base 405B Base Base Architecture - MoE Dense Dense MoE # Activated Params - 21B 72B 405B 37B # Total Params - 236B 72B 405B 671B English Pile-test (BPB) - 0.606 0.638 0.542 0.548 BBH (EM) 3-shot 78.8 79.8 82.9 87.5 MMLU (EM) 5-shot 78.4 85.0 84.4 87.1 MMLU-Redux (EM) 5-shot 75.6 83.2 81.3 86.2 MMLU-Pro (EM) 5-shot 51.4 58.3 52.8 64.4 DROP (F1) 3-shot 80.4 80.6 86.0 89.0 ARC-Easy (EM) 25-shot 97.6 98.4 98.4 98.9 ARC-Challenge (EM) 25-shot 92.2 94.5 95.3 95.3 HellaSwag (EM) 10-shot 87.1 84.8 89.2 88.9 PIQA (EM) 0-shot 83.9 82.6 85.9 84.7 WinoGrande (EM) 5-shot 86.3 82.3 85.2 84.9 RACE-Middle (EM) 5-shot 73.1 68.1 74.2 67.1 RACE-High (EM) 5-shot 52.6 50.3 56.8 51.3 TriviaQA (EM) 5-shot 80.0 71.9 82.7 82.9 NaturalQuestions (EM) 5-shot 38.6 33.2 41.5 40.0 AGIEval (EM) 0-shot 57.5 75.8 60.6 79.6 Code HumanEval (Pass@1) 0-shot 43.3 53.0 54.9 65.2 MBPP (Pass@1) 3-shot 65.0 72.6 68.4 75.4 LiveCodeBench-Base (Pass@1) 3-shot 11.6 12.9 15.5 19.4 CRUXEval-I (EM) 2-shot 52.5 59.1 58.5 67.3 CRUXEval-O (EM) 2-shot 49.8 59.9 59.9 69.8 Math GSM8K (EM) 8-shot 81.6 88.3 83.5 89.3 MATH (EM) 4-shot 43.4 54.4 49.0 61.6 MGSM (EM) 8-shot 63.6 76.2 69.9 79.8 CMath (EM) 3-shot 78.7 84.5 77.3 90.7 Chinese CLUEWSC (EM) 5-shot 82.0 82.5 83.0 82.7 C-Eval (EM) 5-shot 81.4 89.2 72.5 90.1 CMMLU (EM) 5-shot 84.0 89.5 73.7 88.8 CMRC (EM) 1-shot 77.4 75.8 76.0 76.3 C3 (EM) 0-shot 77.4 76.7 79.7 78.6 CCPM (EM) 0-shot 93.0 88.5 78.6 92.0 Multilingual MMMLU-non-English (EM) 5-shot 64.0 74.8 73.8 79.4 Table 3 | Comparison among DeepSeek-V3-Base and other representative open-source base models.All models are evaluated in our internal framework and share the same evaluation setting.Scores with a gap not exceeding 0.3 are considered to be at the same level.DeepSeek- V3-Base achieves the best performance on most benchmarks, especially on math and code tasks.of DeepSeek-V2-Base exhibits a slight difference from our previously reported results.Overall, DeepSeek-V3-Base comprehensively outperforms DeepSeek-V2-Base and Qwen2.5 72B Base, and surpasses LLaMA-3.1 405B Base in the majority of benchmarks, essentially becoming the strongest open-source model.From a more detailed perspective, we compare DeepSeek-V3-Base with the other open-source base models individually. (1) Compared with DeepSeek-V2-Base, due to the improvements in our model architecture, the scale-up of the model size and training tokens, and the enhancement of data quality, DeepSeek-V3-Base achieves significantly better performance as expected. (2) Compared with Qwen2.5 72B Base, the state-of-the-art Chinese open-source model, with only half of the activated parameters, DeepSeek-V3-Base also demonstrates remarkable advantages, 25',
  'word_count': 424,
  'char_count': 2771,
  'tokens_count': 692,
  'sentence_count': 9,
  'page_number': 25,
  'embedding': array([-5.01994416e-02, -3.33216377e-02, -1.84493233e-02, -2.35037189e-02,
         -3.50803174e-02,  1.76849440e-02, -4.35857102e-02,  9.34758708e-02,
         -8.87131244e-02, -2.44207052e-03, -5.74489906e-02, -9.16464999e-02,
         -2.17794012e-02,  2.04236787e-02,  5.98461134e-03,  5.17949834e-02,
          1.27181202e-01,  4.37072180e-02,  8.32290854e-03, -1.53113634e-03,
         -2.85389088e-03, -6.92775799e-03,  8.22467171e-03, -4.19047428e-03,
          6.56951144e-02,  5.75566925e-02, -8.81351009e-02,  5.43310121e-02,
         -3.14604454e-02, -2.16490552e-01,  1.37128737e-02, -1.66515086e-03,
          3.59620079e-02, -3.65710258e-02, -3.87352444e-02, -1.93835292e-02,
         -2.97913514e-02,  9.91785526e-03, -4.69038151e-02,  3.62687893e-02,
         -1.40382685e-02,  2.34168302e-02,  7.84199908e-02, -9.31387302e-03,
          1.68117341e-02,  4.76038549e-03, -4.98427898e-02, -2.29017306e-02,
          8.08578543e-03,  2.13262290e-02, -2.57895868e-02, -4.18635309e-02,
         -4.26914878e-02,  5.91079518e-02,  3.77882794e-02,  3.54279578e-02,
         -1.88298114e-02, -2.21894570e-02,  1.63503690e-03, -3.68616469e-02,
         -7.80020840e-04, -4.63172086e-02, -6.59161657e-02, -1.53476894e-02,
          3.62464860e-02, -3.08548901e-02, -3.47597115e-02, -3.91237885e-02,
          8.29123333e-03, -5.38702495e-03,  3.28603685e-02,  5.79407811e-02,
         -6.26796111e-02,  2.75356807e-02, -4.88173738e-02,  1.14368126e-01,
          6.47318661e-02,  2.16941442e-02, -3.15773264e-02, -2.13639140e-02,
          2.90835247e-04, -2.31859880e-03, -5.75423799e-02, -1.27981110e-02,
          2.65471693e-02,  3.12043056e-02,  1.24535691e-02,  6.52464107e-02,
          4.61419858e-02, -5.92582785e-02,  7.85984918e-02,  3.59878428e-02,
         -6.61460534e-02,  2.18451135e-02,  9.49513540e-02,  3.57197188e-02,
         -2.30030939e-02, -3.97308283e-02, -1.01267844e-01,  7.69843683e-02,
          6.32848367e-02,  2.05844883e-02, -3.19859311e-02, -5.37746511e-02,
          4.96016769e-03,  3.42758708e-02,  2.49284916e-02,  1.58189330e-02,
          5.94253326e-03, -1.45154698e-02,  7.07316697e-02, -1.99381467e-02,
          2.40825303e-02, -3.38232191e-03, -8.20544735e-03, -6.18243739e-02,
         -1.09249257e-01,  1.92390848e-02, -3.67512442e-02, -3.68233807e-02,
         -2.45431717e-02,  9.98211326e-04,  1.91228148e-02,  1.60205215e-02,
          2.63044261e-03,  3.21518555e-02,  3.22696716e-02,  8.77743983e-33,
          6.01803958e-02,  4.12872843e-02, -4.21315916e-02, -3.84058878e-02,
         -1.05711930e-02, -5.52365407e-02,  8.21354147e-03,  6.11598305e-02,
         -5.56534790e-02, -2.78884685e-03, -9.15817991e-02,  3.37723605e-02,
         -4.22879755e-02,  2.33840365e-02,  1.08591601e-01, -8.80560651e-02,
          2.60577574e-02,  4.93388735e-02, -3.73219177e-02,  5.60271330e-02,
         -1.96057633e-02,  4.40151319e-02, -7.55517185e-02, -8.20816234e-02,
         -3.46094966e-02,  6.76646158e-02,  5.70872389e-02, -3.53977382e-02,
         -1.77718833e-01,  4.35062684e-02, -7.62081742e-02, -7.30410069e-02,
         -4.37946059e-02,  5.66660911e-02, -3.24172378e-02, -2.96144877e-02,
         -7.17219338e-02, -1.74844544e-02, -4.18618545e-02, -3.52739692e-02,
         -1.33465268e-02,  6.98208511e-02, -1.12246938e-01, -3.70556652e-03,
         -2.39597876e-02, -6.18917905e-02, -3.16484943e-02, -9.21849348e-03,
          1.54608106e-02,  1.26583660e-02,  3.41991596e-02, -4.59372997e-02,
          2.20079049e-02,  6.88767210e-02,  3.12755145e-02,  3.52283046e-02,
         -2.19815336e-02,  3.38204391e-02,  5.55836707e-02,  1.21123701e-01,
          3.58288437e-02,  1.97444744e-02, -7.72870332e-02,  1.79284513e-02,
         -6.65872172e-02,  6.25917837e-02, -3.41488495e-02,  2.13865917e-02,
          6.60726801e-02,  2.96000242e-02,  1.38625652e-02, -3.41988504e-02,
          8.94475281e-02, -2.32779402e-02,  8.36057886e-02, -2.79228552e-03,
          5.18965982e-02,  8.35500937e-03,  3.04674497e-03, -2.16390453e-02,
         -8.76196772e-02,  7.92951062e-02, -6.16552234e-02, -1.12876901e-02,
         -4.50174287e-02,  2.21484248e-02,  1.33901844e-02, -1.55597022e-02,
         -9.00709704e-02,  3.81930880e-02, -2.34664250e-02, -6.17007203e-02,
          1.66348536e-02, -6.65354216e-03, -1.22400350e-03, -5.28056711e-33,
          6.09268621e-03,  4.68709022e-02, -4.30669114e-02,  1.07349001e-01,
          3.02224811e-02,  1.35193849e-02,  9.33523402e-02, -8.19660898e-04,
          1.05679221e-02,  3.50551903e-02, -2.94794925e-02,  9.23535600e-02,
          3.96638317e-03, -4.95440923e-02,  6.52749240e-02, -3.25278006e-02,
         -3.87469754e-02, -7.31317848e-02,  2.93993093e-02, -2.60371696e-02,
          1.02378353e-01,  7.93946758e-02, -1.99650899e-02,  2.76435986e-02,
          4.59855944e-02,  9.79732946e-02, -5.76192774e-02, -4.65911031e-02,
          3.42772435e-03, -1.05948774e-02,  2.34360471e-02, -2.50489591e-03,
         -2.59267371e-02,  2.01037005e-02, -7.21939430e-02,  3.64185907e-02,
          3.12871523e-02,  8.78254846e-02, -7.83769041e-03,  3.95451859e-02,
          6.55506877e-03,  5.71450442e-02, -3.39184850e-02,  6.96289018e-02,
          1.79045752e-03,  4.55752909e-02, -1.84310842e-02, -2.54994817e-02,
          5.10611162e-02,  5.99985458e-02, -4.32795994e-02,  2.94601638e-02,
         -6.79442063e-02,  9.16808322e-02, -1.80318132e-02, -1.22627057e-01,
         -1.90513264e-02, -5.94605096e-02, -7.41091743e-02,  9.60698649e-02,
          1.99254267e-02,  1.52971093e-02, -1.52974576e-02,  3.46699776e-03,
          3.12303547e-02,  5.79248294e-02, -3.96787226e-02, -6.88056462e-03,
         -1.14751227e-01,  6.46799952e-02, -2.32613683e-02, -3.32402205e-03,
          7.62016550e-02, -1.54961245e-02,  4.42269072e-02,  4.26142616e-03,
          4.09751981e-02,  1.71301328e-02,  3.44322920e-02,  1.37844752e-03,
         -7.38661885e-02,  1.02847610e-02, -8.33139718e-02,  6.94748312e-02,
          2.67424490e-02,  4.48079742e-02, -1.90368965e-02, -8.43789801e-03,
          4.26396877e-02,  5.14577888e-02, -1.06893787e-02,  7.98089653e-02,
          1.00764416e-01, -1.58593357e-02,  1.31123057e-02, -6.53266383e-08,
         -2.73770723e-03,  2.74422411e-02,  3.19314562e-03,  8.26160386e-02,
          3.65405530e-02,  1.67681044e-03, -5.23654111e-02,  1.05982877e-01,
          4.61602211e-02, -3.35240774e-02,  1.32013336e-01, -3.73915210e-02,
         -4.72993441e-02, -1.46989971e-02,  4.56637517e-02,  3.33748152e-03,
         -1.02436673e-02,  3.54905725e-02, -4.02607806e-02, -8.15993361e-03,
          4.63525988e-02,  2.24088356e-02,  3.05394866e-02, -6.17656857e-02,
         -6.87838420e-02, -3.53932381e-02, -3.78881283e-02, -3.92033271e-02,
          3.10851820e-02,  6.54364973e-02,  3.40570249e-02,  1.28532096e-03,
          4.10569794e-02,  1.03798611e-02,  4.68482962e-03,  8.38846341e-02,
         -1.91024207e-02,  4.79012765e-02, -4.60638711e-03,  4.37777974e-02,
         -4.31739949e-02,  1.17100058e-02,  5.88498497e-03, -1.37106013e-02,
         -1.21002016e-03, -7.18462002e-03, -8.23498592e-02, -6.71962127e-02,
         -2.43269466e-02, -8.57651159e-02, -2.19528433e-02,  1.29079437e-02,
         -6.19976074e-02,  3.31394561e-02,  4.29817215e-02,  8.64023715e-02,
          1.18656713e-03, -1.06826290e-01,  1.28046367e-02, -3.22286249e-03,
          1.45720035e-01, -1.32775843e-01, -9.81606636e-03,  4.84405383e-02],
        dtype=float32)}]

In [24]:
page_and_Embedding_df = pd.DataFrame(pages_and_chunk)
page_and_Embedding_file_name="page_and_Embedding.csv"
page_and_Embedding_path = os.path.join(os.getcwd(),page_and_Embedding_file_name)
page_and_Embedding_df.to_csv(page_and_Embedding_path,index=False)

In [25]:
pages_and_chunk[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': array([-5.76343201e-02,  1.86270270e-02, -6.96300194e-02, -5.02142822e-03,
        -6.43548667e-02,  5.39917648e-02, -4.61324938e-02,  3.96139584e-02,
        -5.72230220e-02,  5.44092804e-03, -4.39483412e-02, -6.78680325e-03,
         4.00274545e-02, -1.59041807e-02,  7.62046641e-03,  4.98709343e-02,
         1.28310859e-01, -3.56771685e-02, -4.98869978e-02, -8.15589055e-02,
         4.34629358e-02, -4.59041335e-02,  8.90600234e-02,  1.54037038e-02,
        -7.79620484e-02,  3.06390580e-02, -5.25193140e-02, -6.64414167e-02,
         3.31790745e-02, -6.93640932e-02, -6.77236542e-03,  3.17597482e-03,
         5.10903783e-02, -8.24809521e-02, -8.37938562e-02,  1.99515168e-02,
        -5.22203930e-02, -5.73823862e-02,  1.78819150e-02,  2.67783534e-02,
         1.22675279e-04, -3.79560106e-02,  2.66227871e-03,  2.12215502e-02,
         3.83332558e-02, -2.20188908e-02, -5.95768169e-02, -2.69228555e-02,
        -4.48380969e-02, -8.05420727e-02, -1.64256301e-02, -6.48153052e-02,
         5.06796781e-03, -2.43174564e-03, -5.40565290e-02, -8.12954269e-03,
         4.19081375e-02, -2.15617232e-02, -1.57968029e-02,  3.31748277e-02,
        -8.01364779e-02, -1.54115567e-02, -5.74465618e-02,  1.44827375e-02,
         3.75398770e-02, -9.97637585e-02, -8.92191008e-03, -6.80584684e-02,
         5.85166328e-02, -3.27328518e-02, -2.40224740e-03, -6.30811881e-03,
         4.79136556e-02, -8.28514621e-02, -2.71539520e-02, -4.32536704e-03,
         2.57454421e-02, -3.27681489e-02,  2.09331643e-02, -7.94779658e-02,
         1.91955734e-02, -1.16449250e-02,  9.50383767e-03, -4.35635522e-02,
        -3.66505831e-02, -9.70793441e-02,  8.94263480e-03, -1.46269770e-02,
         5.45645878e-02,  6.92140684e-02,  1.05012521e-01,  1.10859863e-01,
        -1.34864897e-02,  8.77498277e-03, -1.14634610e-03,  1.05595477e-01,
        -3.30546014e-02,  1.49800964e-02, -7.64259771e-02,  4.41714674e-02,
         8.06646198e-02,  3.79375182e-02, -1.73762031e-02,  4.10951227e-02,
        -2.40345858e-02, -4.80215773e-02,  1.50006237e-02,  3.03008091e-02,
         4.40822588e-03, -1.10763706e-01,  5.87852336e-02,  5.47064133e-02,
         8.96654464e-03, -4.55786362e-02, -4.77992035e-02,  8.83815289e-02,
        -1.86152421e-02,  2.07291543e-02, -2.19884999e-02,  7.60801136e-02,
         1.60370711e-02, -1.16604447e-01,  1.25039116e-01, -7.68831559e-03,
         3.03482749e-02, -1.52714383e-02, -6.32316172e-02, -2.49990797e-32,
        -8.10584649e-02, -5.51192276e-02, -1.33699803e-02, -5.99329062e-02,
         1.10146971e-02,  2.59978063e-02,  3.60029861e-02,  4.94824443e-03,
         1.81741512e-03, -7.88456351e-02, -5.46012223e-02, -3.52930948e-02,
        -6.31594285e-03,  6.83288574e-02,  1.65331662e-02, -8.12145844e-02,
         5.00025181e-03,  1.31413490e-01, -4.67871949e-02, -5.32843843e-02,
         6.42249063e-02, -5.45797199e-02, -4.81015034e-02,  2.70939618e-02,
         8.49387944e-02, -5.11556258e-03,  8.52151960e-02,  4.48352396e-02,
        -9.25948396e-02,  8.05961620e-03,  2.34440453e-02,  4.24520411e-02,
        -5.95207736e-02,  1.05523579e-02, -6.87899515e-02,  6.74008217e-04,
         4.62167636e-02, -6.29207445e-03,  3.83898988e-02,  2.46826978e-03,
        -9.38247666e-02,  5.74741885e-02,  7.89214969e-02, -2.18204726e-02,
        -4.18462418e-02, -5.63514195e-02, -4.13206071e-02,  2.18045413e-02,
        -9.33824182e-02,  3.08046620e-02, -6.42291084e-02, -1.99529976e-02,
         3.61034945e-02, -3.50959226e-02,  3.22242379e-02,  6.15459532e-02,
         5.70552424e-02,  1.59136634e-02, -2.45294310e-02,  9.99930575e-02,
         5.59421182e-02, -4.10363711e-02, -6.51615709e-02,  2.00894140e-02,
         4.90734391e-02,  3.07649542e-02, -5.85500188e-02, -5.81289642e-03,
         3.74067686e-02,  4.96496968e-02, -6.38445988e-02, -2.64047412e-03,
         5.88807873e-02, -4.38632295e-02,  6.60317168e-02, -7.83692896e-02,
         6.36432171e-02,  6.92375051e-03, -8.18328410e-02, -3.14816646e-02,
        -3.57158552e-03,  1.01911850e-01, -5.81695959e-02, -2.84043290e-02,
         1.21233119e-02,  2.11805175e-03, -4.04893421e-02, -5.31520844e-02,
        -1.43812485e-02,  3.91902998e-02, -4.59962562e-02, -2.05658423e-03,
         6.13804394e-03,  9.19524580e-02,  1.95201207e-02,  1.56344848e-32,
         2.62332801e-02,  9.64797512e-02, -6.58232719e-02,  4.79708686e-02,
         8.70389938e-02,  4.03307453e-02,  1.44299380e-02, -4.76208404e-02,
        -8.86884797e-03,  1.93300918e-02, -1.29635213e-02,  4.97946069e-02,
        -6.92616403e-02,  3.16582061e-02, -3.13160494e-02, -3.00070271e-02,
        -4.07413021e-03, -1.46254683e-02, -1.23310229e-02,  2.74193529e-02,
         8.34065452e-02,  6.97516799e-02, -1.05787531e-01,  8.78471285e-02,
         5.59022883e-03, -1.86683368e-02, -6.24801703e-02, -3.62284668e-03,
        -3.38803716e-02,  4.26130444e-02, -3.24046649e-02, -9.78928879e-02,
         1.34581923e-02,  4.51985113e-02, -4.52558249e-02, -1.61164254e-02,
         8.62949863e-02,  2.88820546e-02, -8.69690627e-03,  1.49755552e-01,
         3.60441804e-02,  2.37741210e-02, -3.88363227e-02,  5.74692711e-02,
        -2.12659892e-02, -4.92210779e-03, -7.09290244e-03, -5.32866716e-02,
        -8.20563287e-02,  4.31006514e-02, -3.67642827e-02, -2.71880459e-02,
        -1.35272175e-01, -2.56683826e-02, -2.91683897e-02, -8.94128904e-02,
         1.41426111e-02,  7.27055222e-03, -7.77577236e-02, -9.60374530e-03,
        -4.91312817e-02,  5.92100695e-02, -2.87621040e-02, -1.12884576e-02,
        -2.84832381e-02, -8.75001587e-03,  1.74761303e-02,  4.95308340e-02,
         3.17867361e-02,  3.20893899e-02, -8.73306394e-02, -7.09940027e-03,
         5.87638691e-02, -6.80654135e-04,  3.69723029e-02, -2.14158762e-02,
         9.12340402e-05, -1.07634906e-02, -5.68082556e-02, -2.79051121e-02,
        -1.05843820e-01, -9.68968438e-04,  1.14391781e-02, -9.73235071e-03,
        -4.10722494e-02,  3.72072384e-02,  4.89397906e-02,  4.51456271e-02,
         1.92308687e-02, -1.15437722e-02,  5.01306262e-03,  2.97262352e-02,
         6.92122430e-02,  1.63907111e-02,  8.69889837e-03, -4.69932395e-08,
         9.97948088e-03, -5.11729084e-02,  7.04231337e-02,  6.84351772e-02,
         3.95479426e-02,  1.35918599e-04, -7.60002211e-02,  4.00973149e-02,
        -3.73462737e-02, -5.88457519e-03,  1.22180894e-01,  8.05514306e-03,
        -1.34175904e-02,  1.23288734e-02,  2.55202223e-02,  1.09683042e-02,
         6.05713169e-04, -2.16499045e-02, -5.05288467e-02, -1.30556300e-02,
         1.05004460e-02,  1.00652536e-03, -3.34202163e-02, -1.19563295e-02,
         3.54323387e-02, -7.30695426e-02, -1.92586482e-02,  6.82983026e-02,
        -5.41707054e-02, -3.45374532e-02,  5.45379557e-02,  2.30299700e-02,
         1.27890678e-02,  2.67073810e-02,  2.77424026e-02,  1.66754518e-02,
        -9.89080220e-03, -1.50999501e-02,  1.57295819e-02,  1.33830801e-01,
         4.96069668e-03, -5.15580457e-03,  2.67172679e-02,  9.28948540e-03,
         5.75693548e-02, -3.65180746e-02, -1.39185533e-01, -5.01696095e-02,
         4.19337526e-02, -7.75044262e-02, -4.21275087e-02, -2.39884723e-02,
        -6.29835874e-02,  7.19865486e-02,  1.34467095e-01, -8.73647071e-03,
        -7.97655899e-03, -6.91411346e-02,  3.03547662e-02,  6.15585968e-02,
        -2.00267718e-03, -6.09332882e-02, -6.89558908e-02, -6.41390607e-02],
       dtype=float32)}

In [26]:
pages_and_chunk=[]
pages_and_chunk

[]

In [27]:
pages_and_chunk =pd.read_csv(page_and_Embedding_path)
data = pages_and_chunk.to_dict(orient="records")
data[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': '[-5.76343201e-02  1.86270270e-02 -6.96300194e-02 -5.02142822e-03\n -6.43548667e-02  5.39917648e-02 -4.61324938e-02  3.96139584e-02\n -5.72230220e-02  5.44092804e-03 -4.39483412e-02 -6.78680325e-03\n  4.00274545e-02 -1.59041807e-02  7.62046641e-03  4.98709343e-02\n  1.28310859e-01 -3.56771685e-02 -4.98869978e-02 -8.15589055e-02\n  4.34629358e-02 -4.59041335e-02  8.90600234e-02  1.54037038e-02\n -7.79620484e-02  3.06390580e-02 -5.25193140e-02 -6.64414167e-02\n  3.31790745e-02 -6.93640932e-02 -6.77236542e-03  3.17597482e-03\n  5.10903783e-02 -8.24809521e-02 -8.37938562e-02  1.99515168e-02\n -5.22203930e-02 -5.73823862e-02  1.78819150e-02  2.67783534e-02\n  1.22675279e-04 -3.79560106e-02  2.66227871e-03  2.12215502e-02\n  3.83332558e-02 -2.20188908e-02 -5.95768169e-02 -2.69228555e-02\n -4.48380969e-02 -8.05420727e-02 -1.64256301e-02 -6.48153052e-02\n  5.06796781e-03 -2.43174564e-03 -5.40565290e-02 -8.12954269e-03\n  4.19081375e-02 -2.15617232e-02 -1.57968029e-02  3.31748277e-02\n -8.01364779e-02 -1.54115567e-02 -5.74465618e-02  1.44827375e-02\n  3.75398770e-02 -9.97637585e-02 -8.92191008e-03 -6.80584684e-02\n  5.85166328e-02 -3.27328518e-02 -2.40224740e-03 -6.30811881e-03\n  4.79136556e-02 -8.28514621e-02 -2.71539520e-02 -4.32536704e-03\n  2.57454421e-02 -3.27681489e-02  2.09331643e-02 -7.94779658e-02\n  1.91955734e-02 -1.16449250e-02  9.50383767e-03 -4.35635522e-02\n -3.66505831e-02 -9.70793441e-02  8.94263480e-03 -1.46269770e-02\n  5.45645878e-02  6.92140684e-02  1.05012521e-01  1.10859863e-01\n -1.34864897e-02  8.77498277e-03 -1.14634610e-03  1.05595477e-01\n -3.30546014e-02  1.49800964e-02 -7.64259771e-02  4.41714674e-02\n  8.06646198e-02  3.79375182e-02 -1.73762031e-02  4.10951227e-02\n -2.40345858e-02 -4.80215773e-02  1.50006237e-02  3.03008091e-02\n  4.40822588e-03 -1.10763706e-01  5.87852336e-02  5.47064133e-02\n  8.96654464e-03 -4.55786362e-02 -4.77992035e-02  8.83815289e-02\n -1.86152421e-02  2.07291543e-02 -2.19884999e-02  7.60801136e-02\n  1.60370711e-02 -1.16604447e-01  1.25039116e-01 -7.68831559e-03\n  3.03482749e-02 -1.52714383e-02 -6.32316172e-02 -2.49990797e-32\n -8.10584649e-02 -5.51192276e-02 -1.33699803e-02 -5.99329062e-02\n  1.10146971e-02  2.59978063e-02  3.60029861e-02  4.94824443e-03\n  1.81741512e-03 -7.88456351e-02 -5.46012223e-02 -3.52930948e-02\n -6.31594285e-03  6.83288574e-02  1.65331662e-02 -8.12145844e-02\n  5.00025181e-03  1.31413490e-01 -4.67871949e-02 -5.32843843e-02\n  6.42249063e-02 -5.45797199e-02 -4.81015034e-02  2.70939618e-02\n  8.49387944e-02 -5.11556258e-03  8.52151960e-02  4.48352396e-02\n -9.25948396e-02  8.05961620e-03  2.34440453e-02  4.24520411e-02\n -5.95207736e-02  1.05523579e-02 -6.87899515e-02  6.74008217e-04\n  4.62167636e-02 -6.29207445e-03  3.83898988e-02  2.46826978e-03\n -9.38247666e-02  5.74741885e-02  7.89214969e-02 -2.18204726e-02\n -4.18462418e-02 -5.63514195e-02 -4.13206071e-02  2.18045413e-02\n -9.33824182e-02  3.08046620e-02 -6.42291084e-02 -1.99529976e-02\n  3.61034945e-02 -3.50959226e-02  3.22242379e-02  6.15459532e-02\n  5.70552424e-02  1.59136634e-02 -2.45294310e-02  9.99930575e-02\n  5.59421182e-02 -4.10363711e-02 -6.51615709e-02  2.00894140e-02\n  4.90734391e-02  3.07649542e-02 -5.85500188e-02 -5.81289642e-03\n  3.74067686e-02  4.96496968e-02 -6.38445988e-02 -2.64047412e-03\n  5.88807873e-02 -4.38632295e-02  6.60317168e-02 -7.83692896e-02\n  6.36432171e-02  6.92375051e-03 -8.18328410e-02 -3.14816646e-02\n -3.57158552e-03  1.01911850e-01 -5.81695959e-02 -2.84043290e-02\n  1.21233119e-02  2.11805175e-03 -4.04893421e-02 -5.31520844e-02\n -1.43812485e-02  3.91902998e-02 -4.59962562e-02 -2.05658423e-03\n  6.13804394e-03  9.19524580e-02  1.95201207e-02  1.56344848e-32\n  2.62332801e-02  9.64797512e-02 -6.58232719e-02  4.79708686e-02\n  8.70389938e-02  4.03307453e-02  1.44299380e-02 -4.76208404e-02\n -8.86884797e-03  1.93300918e-02 -1.29635213e-02  4.97946069e-02\n -6.92616403e-02  3.16582061e-02 -3.13160494e-02 -3.00070271e-02\n -4.07413021e-03 -1.46254683e-02 -1.23310229e-02  2.74193529e-02\n  8.34065452e-02  6.97516799e-02 -1.05787531e-01  8.78471285e-02\n  5.59022883e-03 -1.86683368e-02 -6.24801703e-02 -3.62284668e-03\n -3.38803716e-02  4.26130444e-02 -3.24046649e-02 -9.78928879e-02\n  1.34581923e-02  4.51985113e-02 -4.52558249e-02 -1.61164254e-02\n  8.62949863e-02  2.88820546e-02 -8.69690627e-03  1.49755552e-01\n  3.60441804e-02  2.37741210e-02 -3.88363227e-02  5.74692711e-02\n -2.12659892e-02 -4.92210779e-03 -7.09290244e-03 -5.32866716e-02\n -8.20563287e-02  4.31006514e-02 -3.67642827e-02 -2.71880459e-02\n -1.35272175e-01 -2.56683826e-02 -2.91683897e-02 -8.94128904e-02\n  1.41426111e-02  7.27055222e-03 -7.77577236e-02 -9.60374530e-03\n -4.91312817e-02  5.92100695e-02 -2.87621040e-02 -1.12884576e-02\n -2.84832381e-02 -8.75001587e-03  1.74761303e-02  4.95308340e-02\n  3.17867361e-02  3.20893899e-02 -8.73306394e-02 -7.09940027e-03\n  5.87638691e-02 -6.80654135e-04  3.69723029e-02 -2.14158762e-02\n  9.12340402e-05 -1.07634906e-02 -5.68082556e-02 -2.79051121e-02\n -1.05843820e-01 -9.68968438e-04  1.14391781e-02 -9.73235071e-03\n -4.10722494e-02  3.72072384e-02  4.89397906e-02  4.51456271e-02\n  1.92308687e-02 -1.15437722e-02  5.01306262e-03  2.97262352e-02\n  6.92122430e-02  1.63907111e-02  8.69889837e-03 -4.69932395e-08\n  9.97948088e-03 -5.11729084e-02  7.04231337e-02  6.84351772e-02\n  3.95479426e-02  1.35918599e-04 -7.60002211e-02  4.00973149e-02\n -3.73462737e-02 -5.88457519e-03  1.22180894e-01  8.05514306e-03\n -1.34175904e-02  1.23288734e-02  2.55202223e-02  1.09683042e-02\n  6.05713169e-04 -2.16499045e-02 -5.05288467e-02 -1.30556300e-02\n  1.05004460e-02  1.00652536e-03 -3.34202163e-02 -1.19563295e-02\n  3.54323387e-02 -7.30695426e-02 -1.92586482e-02  6.82983026e-02\n -5.41707054e-02 -3.45374532e-02  5.45379557e-02  2.30299700e-02\n  1.27890678e-02  2.67073810e-02  2.77424026e-02  1.66754518e-02\n -9.89080220e-03 -1.50999501e-02  1.57295819e-02  1.33830801e-01\n  4.96069668e-03 -5.15580457e-03  2.67172679e-02  9.28948540e-03\n  5.75693548e-02 -3.65180746e-02 -1.39185533e-01 -5.01696095e-02\n  4.19337526e-02 -7.75044262e-02 -4.21275087e-02 -2.39884723e-02\n -6.29835874e-02  7.19865486e-02  1.34467095e-01 -8.73647071e-03\n -7.97655899e-03 -6.91411346e-02  3.03547662e-02  6.15585968e-02\n -2.00267718e-03 -6.09332882e-02 -6.89558908e-02 -6.41390607e-02]'}

In [28]:
import torch
import numpy as np
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [29]:
data[5]['embedding']

'[-5.76343201e-02  1.86270270e-02 -6.96300194e-02 -5.02142822e-03\n -6.43548667e-02  5.39917648e-02 -4.61324938e-02  3.96139584e-02\n -5.72230220e-02  5.44092804e-03 -4.39483412e-02 -6.78680325e-03\n  4.00274545e-02 -1.59041807e-02  7.62046641e-03  4.98709343e-02\n  1.28310859e-01 -3.56771685e-02 -4.98869978e-02 -8.15589055e-02\n  4.34629358e-02 -4.59041335e-02  8.90600234e-02  1.54037038e-02\n -7.79620484e-02  3.06390580e-02 -5.25193140e-02 -6.64414167e-02\n  3.31790745e-02 -6.93640932e-02 -6.77236542e-03  3.17597482e-03\n  5.10903783e-02 -8.24809521e-02 -8.37938562e-02  1.99515168e-02\n -5.22203930e-02 -5.73823862e-02  1.78819150e-02  2.67783534e-02\n  1.22675279e-04 -3.79560106e-02  2.66227871e-03  2.12215502e-02\n  3.83332558e-02 -2.20188908e-02 -5.95768169e-02 -2.69228555e-02\n -4.48380969e-02 -8.05420727e-02 -1.64256301e-02 -6.48153052e-02\n  5.06796781e-03 -2.43174564e-03 -5.40565290e-02 -8.12954269e-03\n  4.19081375e-02 -2.15617232e-02 -1.57968029e-02  3.31748277e-02\n -8.01364779e-02 -1.54115567e-02 -5.74465618e-02  1.44827375e-02\n  3.75398770e-02 -9.97637585e-02 -8.92191008e-03 -6.80584684e-02\n  5.85166328e-02 -3.27328518e-02 -2.40224740e-03 -6.30811881e-03\n  4.79136556e-02 -8.28514621e-02 -2.71539520e-02 -4.32536704e-03\n  2.57454421e-02 -3.27681489e-02  2.09331643e-02 -7.94779658e-02\n  1.91955734e-02 -1.16449250e-02  9.50383767e-03 -4.35635522e-02\n -3.66505831e-02 -9.70793441e-02  8.94263480e-03 -1.46269770e-02\n  5.45645878e-02  6.92140684e-02  1.05012521e-01  1.10859863e-01\n -1.34864897e-02  8.77498277e-03 -1.14634610e-03  1.05595477e-01\n -3.30546014e-02  1.49800964e-02 -7.64259771e-02  4.41714674e-02\n  8.06646198e-02  3.79375182e-02 -1.73762031e-02  4.10951227e-02\n -2.40345858e-02 -4.80215773e-02  1.50006237e-02  3.03008091e-02\n  4.40822588e-03 -1.10763706e-01  5.87852336e-02  5.47064133e-02\n  8.96654464e-03 -4.55786362e-02 -4.77992035e-02  8.83815289e-02\n -1.86152421e-02  2.07291543e-02 -2.19884999e-02  7.60801136e-02\n  1.60370711e-02 -1.16604447e-01  1.25039116e-01 -7.68831559e-03\n  3.03482749e-02 -1.52714383e-02 -6.32316172e-02 -2.49990797e-32\n -8.10584649e-02 -5.51192276e-02 -1.33699803e-02 -5.99329062e-02\n  1.10146971e-02  2.59978063e-02  3.60029861e-02  4.94824443e-03\n  1.81741512e-03 -7.88456351e-02 -5.46012223e-02 -3.52930948e-02\n -6.31594285e-03  6.83288574e-02  1.65331662e-02 -8.12145844e-02\n  5.00025181e-03  1.31413490e-01 -4.67871949e-02 -5.32843843e-02\n  6.42249063e-02 -5.45797199e-02 -4.81015034e-02  2.70939618e-02\n  8.49387944e-02 -5.11556258e-03  8.52151960e-02  4.48352396e-02\n -9.25948396e-02  8.05961620e-03  2.34440453e-02  4.24520411e-02\n -5.95207736e-02  1.05523579e-02 -6.87899515e-02  6.74008217e-04\n  4.62167636e-02 -6.29207445e-03  3.83898988e-02  2.46826978e-03\n -9.38247666e-02  5.74741885e-02  7.89214969e-02 -2.18204726e-02\n -4.18462418e-02 -5.63514195e-02 -4.13206071e-02  2.18045413e-02\n -9.33824182e-02  3.08046620e-02 -6.42291084e-02 -1.99529976e-02\n  3.61034945e-02 -3.50959226e-02  3.22242379e-02  6.15459532e-02\n  5.70552424e-02  1.59136634e-02 -2.45294310e-02  9.99930575e-02\n  5.59421182e-02 -4.10363711e-02 -6.51615709e-02  2.00894140e-02\n  4.90734391e-02  3.07649542e-02 -5.85500188e-02 -5.81289642e-03\n  3.74067686e-02  4.96496968e-02 -6.38445988e-02 -2.64047412e-03\n  5.88807873e-02 -4.38632295e-02  6.60317168e-02 -7.83692896e-02\n  6.36432171e-02  6.92375051e-03 -8.18328410e-02 -3.14816646e-02\n -3.57158552e-03  1.01911850e-01 -5.81695959e-02 -2.84043290e-02\n  1.21233119e-02  2.11805175e-03 -4.04893421e-02 -5.31520844e-02\n -1.43812485e-02  3.91902998e-02 -4.59962562e-02 -2.05658423e-03\n  6.13804394e-03  9.19524580e-02  1.95201207e-02  1.56344848e-32\n  2.62332801e-02  9.64797512e-02 -6.58232719e-02  4.79708686e-02\n  8.70389938e-02  4.03307453e-02  1.44299380e-02 -4.76208404e-02\n -8.86884797e-03  1.93300918e-02 -1.29635213e-02  4.97946069e-02\n -6.92616403e-02  3.16582061e-02 -3.13160494e-02 -3.00070271e-02\n -4.07413021e-03 -1.46254683e-02 -1.23310229e-02  2.74193529e-02\n  8.34065452e-02  6.97516799e-02 -1.05787531e-01  8.78471285e-02\n  5.59022883e-03 -1.86683368e-02 -6.24801703e-02 -3.62284668e-03\n -3.38803716e-02  4.26130444e-02 -3.24046649e-02 -9.78928879e-02\n  1.34581923e-02  4.51985113e-02 -4.52558249e-02 -1.61164254e-02\n  8.62949863e-02  2.88820546e-02 -8.69690627e-03  1.49755552e-01\n  3.60441804e-02  2.37741210e-02 -3.88363227e-02  5.74692711e-02\n -2.12659892e-02 -4.92210779e-03 -7.09290244e-03 -5.32866716e-02\n -8.20563287e-02  4.31006514e-02 -3.67642827e-02 -2.71880459e-02\n -1.35272175e-01 -2.56683826e-02 -2.91683897e-02 -8.94128904e-02\n  1.41426111e-02  7.27055222e-03 -7.77577236e-02 -9.60374530e-03\n -4.91312817e-02  5.92100695e-02 -2.87621040e-02 -1.12884576e-02\n -2.84832381e-02 -8.75001587e-03  1.74761303e-02  4.95308340e-02\n  3.17867361e-02  3.20893899e-02 -8.73306394e-02 -7.09940027e-03\n  5.87638691e-02 -6.80654135e-04  3.69723029e-02 -2.14158762e-02\n  9.12340402e-05 -1.07634906e-02 -5.68082556e-02 -2.79051121e-02\n -1.05843820e-01 -9.68968438e-04  1.14391781e-02 -9.73235071e-03\n -4.10722494e-02  3.72072384e-02  4.89397906e-02  4.51456271e-02\n  1.92308687e-02 -1.15437722e-02  5.01306262e-03  2.97262352e-02\n  6.92122430e-02  1.63907111e-02  8.69889837e-03 -4.69932395e-08\n  9.97948088e-03 -5.11729084e-02  7.04231337e-02  6.84351772e-02\n  3.95479426e-02  1.35918599e-04 -7.60002211e-02  4.00973149e-02\n -3.73462737e-02 -5.88457519e-03  1.22180894e-01  8.05514306e-03\n -1.34175904e-02  1.23288734e-02  2.55202223e-02  1.09683042e-02\n  6.05713169e-04 -2.16499045e-02 -5.05288467e-02 -1.30556300e-02\n  1.05004460e-02  1.00652536e-03 -3.34202163e-02 -1.19563295e-02\n  3.54323387e-02 -7.30695426e-02 -1.92586482e-02  6.82983026e-02\n -5.41707054e-02 -3.45374532e-02  5.45379557e-02  2.30299700e-02\n  1.27890678e-02  2.67073810e-02  2.77424026e-02  1.66754518e-02\n -9.89080220e-03 -1.50999501e-02  1.57295819e-02  1.33830801e-01\n  4.96069668e-03 -5.15580457e-03  2.67172679e-02  9.28948540e-03\n  5.75693548e-02 -3.65180746e-02 -1.39185533e-01 -5.01696095e-02\n  4.19337526e-02 -7.75044262e-02 -4.21275087e-02 -2.39884723e-02\n -6.29835874e-02  7.19865486e-02  1.34467095e-01 -8.73647071e-03\n -7.97655899e-03 -6.91411346e-02  3.03547662e-02  6.15585968e-02\n -2.00267718e-03 -6.09332882e-02 -6.89558908e-02 -6.41390607e-02]'

* the data her is not in list shape so try to fix it

In [30]:
embedding = np.fromstring(data[5]['embedding'].strip('[]'), sep=' ')
embedding

array([-5.76343201e-02,  1.86270270e-02, -6.96300194e-02, -5.02142822e-03,
       -6.43548667e-02,  5.39917648e-02, -4.61324938e-02,  3.96139584e-02,
       -5.72230220e-02,  5.44092804e-03, -4.39483412e-02, -6.78680325e-03,
        4.00274545e-02, -1.59041807e-02,  7.62046641e-03,  4.98709343e-02,
        1.28310859e-01, -3.56771685e-02, -4.98869978e-02, -8.15589055e-02,
        4.34629358e-02, -4.59041335e-02,  8.90600234e-02,  1.54037038e-02,
       -7.79620484e-02,  3.06390580e-02, -5.25193140e-02, -6.64414167e-02,
        3.31790745e-02, -6.93640932e-02, -6.77236542e-03,  3.17597482e-03,
        5.10903783e-02, -8.24809521e-02, -8.37938562e-02,  1.99515168e-02,
       -5.22203930e-02, -5.73823862e-02,  1.78819150e-02,  2.67783534e-02,
        1.22675279e-04, -3.79560106e-02,  2.66227871e-03,  2.12215502e-02,
        3.83332558e-02, -2.20188908e-02, -5.95768169e-02, -2.69228555e-02,
       -4.48380969e-02, -8.05420727e-02, -1.64256301e-02, -6.48153052e-02,
        5.06796781e-03, -2.43174564e-03, -5.40565290e-02, -8.12954269e-03,
        4.19081375e-02, -2.15617232e-02, -1.57968029e-02,  3.31748277e-02,
       -8.01364779e-02, -1.54115567e-02, -5.74465618e-02,  1.44827375e-02,
        3.75398770e-02, -9.97637585e-02, -8.92191008e-03, -6.80584684e-02,
        5.85166328e-02, -3.27328518e-02, -2.40224740e-03, -6.30811881e-03,
        4.79136556e-02, -8.28514621e-02, -2.71539520e-02, -4.32536704e-03,
        2.57454421e-02, -3.27681489e-02,  2.09331643e-02, -7.94779658e-02,
        1.91955734e-02, -1.16449250e-02,  9.50383767e-03, -4.35635522e-02,
       -3.66505831e-02, -9.70793441e-02,  8.94263480e-03, -1.46269770e-02,
        5.45645878e-02,  6.92140684e-02,  1.05012521e-01,  1.10859863e-01,
       -1.34864897e-02,  8.77498277e-03, -1.14634610e-03,  1.05595477e-01,
       -3.30546014e-02,  1.49800964e-02, -7.64259771e-02,  4.41714674e-02,
        8.06646198e-02,  3.79375182e-02, -1.73762031e-02,  4.10951227e-02,
       -2.40345858e-02, -4.80215773e-02,  1.50006237e-02,  3.03008091e-02,
        4.40822588e-03, -1.10763706e-01,  5.87852336e-02,  5.47064133e-02,
        8.96654464e-03, -4.55786362e-02, -4.77992035e-02,  8.83815289e-02,
       -1.86152421e-02,  2.07291543e-02, -2.19884999e-02,  7.60801136e-02,
        1.60370711e-02, -1.16604447e-01,  1.25039116e-01, -7.68831559e-03,
        3.03482749e-02, -1.52714383e-02, -6.32316172e-02, -2.49990797e-32,
       -8.10584649e-02, -5.51192276e-02, -1.33699803e-02, -5.99329062e-02,
        1.10146971e-02,  2.59978063e-02,  3.60029861e-02,  4.94824443e-03,
        1.81741512e-03, -7.88456351e-02, -5.46012223e-02, -3.52930948e-02,
       -6.31594285e-03,  6.83288574e-02,  1.65331662e-02, -8.12145844e-02,
        5.00025181e-03,  1.31413490e-01, -4.67871949e-02, -5.32843843e-02,
        6.42249063e-02, -5.45797199e-02, -4.81015034e-02,  2.70939618e-02,
        8.49387944e-02, -5.11556258e-03,  8.52151960e-02,  4.48352396e-02,
       -9.25948396e-02,  8.05961620e-03,  2.34440453e-02,  4.24520411e-02,
       -5.95207736e-02,  1.05523579e-02, -6.87899515e-02,  6.74008217e-04,
        4.62167636e-02, -6.29207445e-03,  3.83898988e-02,  2.46826978e-03,
       -9.38247666e-02,  5.74741885e-02,  7.89214969e-02, -2.18204726e-02,
       -4.18462418e-02, -5.63514195e-02, -4.13206071e-02,  2.18045413e-02,
       -9.33824182e-02,  3.08046620e-02, -6.42291084e-02, -1.99529976e-02,
        3.61034945e-02, -3.50959226e-02,  3.22242379e-02,  6.15459532e-02,
        5.70552424e-02,  1.59136634e-02, -2.45294310e-02,  9.99930575e-02,
        5.59421182e-02, -4.10363711e-02, -6.51615709e-02,  2.00894140e-02,
        4.90734391e-02,  3.07649542e-02, -5.85500188e-02, -5.81289642e-03,
        3.74067686e-02,  4.96496968e-02, -6.38445988e-02, -2.64047412e-03,
        5.88807873e-02, -4.38632295e-02,  6.60317168e-02, -7.83692896e-02,
        6.36432171e-02,  6.92375051e-03, -8.18328410e-02, -3.14816646e-02,
       -3.57158552e-03,  1.01911850e-01, -5.81695959e-02, -2.84043290e-02,
        1.21233119e-02,  2.11805175e-03, -4.04893421e-02, -5.31520844e-02,
       -1.43812485e-02,  3.91902998e-02, -4.59962562e-02, -2.05658423e-03,
        6.13804394e-03,  9.19524580e-02,  1.95201207e-02,  1.56344848e-32,
        2.62332801e-02,  9.64797512e-02, -6.58232719e-02,  4.79708686e-02,
        8.70389938e-02,  4.03307453e-02,  1.44299380e-02, -4.76208404e-02,
       -8.86884797e-03,  1.93300918e-02, -1.29635213e-02,  4.97946069e-02,
       -6.92616403e-02,  3.16582061e-02, -3.13160494e-02, -3.00070271e-02,
       -4.07413021e-03, -1.46254683e-02, -1.23310229e-02,  2.74193529e-02,
        8.34065452e-02,  6.97516799e-02, -1.05787531e-01,  8.78471285e-02,
        5.59022883e-03, -1.86683368e-02, -6.24801703e-02, -3.62284668e-03,
       -3.38803716e-02,  4.26130444e-02, -3.24046649e-02, -9.78928879e-02,
        1.34581923e-02,  4.51985113e-02, -4.52558249e-02, -1.61164254e-02,
        8.62949863e-02,  2.88820546e-02, -8.69690627e-03,  1.49755552e-01,
        3.60441804e-02,  2.37741210e-02, -3.88363227e-02,  5.74692711e-02,
       -2.12659892e-02, -4.92210779e-03, -7.09290244e-03, -5.32866716e-02,
       -8.20563287e-02,  4.31006514e-02, -3.67642827e-02, -2.71880459e-02,
       -1.35272175e-01, -2.56683826e-02, -2.91683897e-02, -8.94128904e-02,
        1.41426111e-02,  7.27055222e-03, -7.77577236e-02, -9.60374530e-03,
       -4.91312817e-02,  5.92100695e-02, -2.87621040e-02, -1.12884576e-02,
       -2.84832381e-02, -8.75001587e-03,  1.74761303e-02,  4.95308340e-02,
        3.17867361e-02,  3.20893899e-02, -8.73306394e-02, -7.09940027e-03,
        5.87638691e-02, -6.80654135e-04,  3.69723029e-02, -2.14158762e-02,
        9.12340402e-05, -1.07634906e-02, -5.68082556e-02, -2.79051121e-02,
       -1.05843820e-01, -9.68968438e-04,  1.14391781e-02, -9.73235071e-03,
       -4.10722494e-02,  3.72072384e-02,  4.89397906e-02,  4.51456271e-02,
        1.92308687e-02, -1.15437722e-02,  5.01306262e-03,  2.97262352e-02,
        6.92122430e-02,  1.63907111e-02,  8.69889837e-03, -4.69932395e-08,
        9.97948088e-03, -5.11729084e-02,  7.04231337e-02,  6.84351772e-02,
        3.95479426e-02,  1.35918599e-04, -7.60002211e-02,  4.00973149e-02,
       -3.73462737e-02, -5.88457519e-03,  1.22180894e-01,  8.05514306e-03,
       -1.34175904e-02,  1.23288734e-02,  2.55202223e-02,  1.09683042e-02,
        6.05713169e-04, -2.16499045e-02, -5.05288467e-02, -1.30556300e-02,
        1.05004460e-02,  1.00652536e-03, -3.34202163e-02, -1.19563295e-02,
        3.54323387e-02, -7.30695426e-02, -1.92586482e-02,  6.82983026e-02,
       -5.41707054e-02, -3.45374532e-02,  5.45379557e-02,  2.30299700e-02,
        1.27890678e-02,  2.67073810e-02,  2.77424026e-02,  1.66754518e-02,
       -9.89080220e-03, -1.50999501e-02,  1.57295819e-02,  1.33830801e-01,
        4.96069668e-03, -5.15580457e-03,  2.67172679e-02,  9.28948540e-03,
        5.75693548e-02, -3.65180746e-02, -1.39185533e-01, -5.01696095e-02,
        4.19337526e-02, -7.75044262e-02, -4.21275087e-02, -2.39884723e-02,
       -6.29835874e-02,  7.19865486e-02,  1.34467095e-01, -8.73647071e-03,
       -7.97655899e-03, -6.91411346e-02,  3.03547662e-02,  6.15585968e-02,
       -2.00267718e-03, -6.09332882e-02, -6.89558908e-02, -6.41390607e-02])

In [31]:
for item in data:
    item['embedding'] = np.fromstring(item['embedding'].strip('[]'), sep=' ')

In [32]:
embeddings=[item["embedding"] for item in data]

In [33]:
embeddings

[array([-7.36545399e-02, -5.92405871e-02,  5.75507209e-02,  7.15857744e-02,
         1.54401045e-02, -1.63372401e-02, -7.57386908e-02, -7.95276021e-04,
        -2.40842067e-02, -6.18494265e-02, -1.24292083e-01, -1.00587495e-01,
        -2.54352149e-02, -4.82991673e-02,  1.18151819e-02,  2.85590924e-02,
         5.89606278e-02,  6.40023053e-02, -1.25724867e-01, -8.45907629e-02,
         2.48466004e-02,  1.34899504e-02,  5.55628613e-02, -2.93893926e-02,
         2.66429521e-02,  5.07843383e-02, -1.18937413e-03, -1.09014072e-01,
         1.42404707e-02, -6.30986914e-02,  4.47497219e-02, -3.49188931e-02,
         3.93742993e-02,  1.80439316e-02, -4.82038818e-02,  1.15270421e-01,
        -1.40792534e-01, -8.29446465e-02,  3.17647830e-02, -6.87950626e-02,
         2.28418782e-03,  1.05707645e-02, -1.77034885e-02,  6.14538752e-02,
         5.65050840e-02,  5.83483651e-02,  3.36036719e-02, -7.81908482e-02,
         4.88183610e-02, -2.30751541e-02, -6.04354963e-02, -8.41500685e-02,
         4.49783206e-02,  5.46326302e-02, -5.16212508e-02,  7.21403805e-04,
         4.17706743e-02,  2.89895609e-02,  5.72451437e-03,  3.40613425e-02,
        -1.68883260e-02, -9.43698213e-02,  4.41690907e-03, -5.72452135e-02,
         6.95675658e-03, -4.72279750e-02,  5.50261093e-03,  4.24454994e-02,
        -2.06548292e-02,  4.80771437e-03,  4.01679706e-03,  1.35990903e-01,
        -1.70331690e-02, -5.26659656e-03, -5.73399803e-03,  9.73371565e-02,
         7.63154998e-02,  2.71088872e-02,  1.15384959e-01, -8.60132203e-02,
         6.24585524e-03, -1.76614989e-02,  1.49291717e-02, -3.23114358e-02,
         1.20315813e-01, -1.37789771e-02, -8.84562917e-03,  2.89110430e-02,
        -3.97716500e-02,  3.87413315e-02, -4.51677740e-02, -1.99127235e-02,
         7.55467489e-02, -1.02539249e-02,  5.05392179e-02,  7.40994066e-02,
        -5.52553087e-02, -8.12891424e-02, -1.27333522e-01,  9.85729322e-02,
        -3.42261815e-03,  7.89162442e-02,  7.80439824e-02,  1.86082367e-02,
         1.12325419e-02, -1.78674851e-02,  4.59726676e-02, -6.15704339e-04,
         2.82679703e-02,  4.67749964e-03,  6.36407062e-02,  5.93631752e-02,
         9.21989605e-02, -1.61986351e-02, -1.96268912e-02,  6.67902082e-02,
        -5.10301776e-02, -4.22006957e-02, -8.15444347e-03,  8.30098093e-02,
        -4.52640988e-02, -2.43692491e-02, -7.55411247e-03, -4.52204198e-02,
        -2.43634498e-03, -1.28824422e-02, -2.17346009e-02,  4.66412244e-33,
        -1.92291364e-02,  3.38959768e-02,  3.02155986e-02, -4.38047089e-02,
         8.15879460e-03, -4.60115485e-02, -5.31846797e-03,  3.41555402e-02,
        -6.64872974e-02, -2.31052637e-02, -2.03916430e-02, -1.87411457e-02,
        -6.49014860e-02,  1.46500811e-01, -1.07832132e-02, -2.74298713e-02,
        -3.59992385e-02,  6.53540418e-02, -2.21362393e-02, -8.84282636e-04,
         7.90865943e-02, -3.85904610e-02, -6.55978918e-02, -6.07736260e-02,
         3.70103912e-03, -7.66619993e-03,  9.32073817e-02, -6.14669733e-02,
        -6.73084380e-03,  1.01368148e-02, -1.30949453e-01, -3.43734287e-02,
        -2.12248676e-02,  4.29290161e-02,  1.55341728e-02, -5.71325310e-02,
        -2.98370607e-02, -4.55812626e-02, -6.02532690e-03, -1.21637564e-02,
         4.42576176e-03,  6.30749017e-02,  1.62854698e-02, -2.60944888e-02,
        -8.20358843e-02, -5.87974489e-02,  3.03449878e-03, -2.76656244e-02,
        -2.90018693e-02,  8.78184289e-03,  1.61610134e-02, -3.56829204e-02,
        -2.37761680e-02, -5.01886047e-02,  3.18018273e-02, -3.44655998e-02,
         5.44531941e-02,  9.16673988e-02,  4.57443930e-02,  3.14397812e-02,
         7.44730467e-03,  2.81543601e-02,  1.57229751e-02,  1.13029644e-01,
         8.45998805e-03,  6.37475327e-02, -9.57022049e-03,  1.46056026e-01,
         1.61170568e-02,  2.47888248e-02, -8.03015835e-04,  1.64082311e-02,
         3.95082906e-02, -2.65461262e-02, -6.04660064e-03,  1.16666770e-02,
         4.71573919e-02, -1.01466373e-01,  1.52230291e-02,  3.13782655e-02,
         1.87015794e-02,  6.05213083e-02, -2.29711719e-02,  2.80696359e-02,
        -1.19734453e-02, -3.50229405e-02,  6.42540213e-03, -8.83940607e-02,
         1.88683402e-02,  1.53513290e-02, -2.00652517e-02, -4.57691140e-02,
        -3.07951421e-02, -2.99284002e-03, -7.25531653e-02, -2.80538063e-33,
        -1.79770344e-04,  6.79054558e-02, -4.98998798e-02,  6.09748550e-02,
        -3.32329236e-02, -1.72711965e-02, -4.13232185e-02,  5.03201038e-02,
        -6.12706803e-02,  1.30293304e-02,  8.57343338e-03, -2.62614135e-02,
         6.47766367e-02, -2.39429194e-02,  6.25177771e-02, -1.66654252e-02,
        -2.22486313e-02,  8.12775642e-03,  1.64038669e-02, -1.03466427e-02,
         3.06867957e-02,  6.58852160e-02, -7.84938037e-02,  6.46218807e-02,
        -4.69757654e-02, -1.86146908e-02, -5.43936975e-02,  7.00666085e-02,
        -5.85724320e-03, -1.42591633e-02, -5.12145599e-03, -1.62344761e-02,
        -2.01102886e-02,  3.34333032e-02, -1.92593914e-02,  3.36539261e-02,
         6.61961138e-02, -1.80942193e-02, -1.77126713e-02,  3.14083286e-02,
         1.13496073e-01, -5.68226427e-02, -1.65281799e-02,  2.57995240e-02,
        -1.08513094e-01,  1.69489849e-02, -5.26490062e-02, -4.25187945e-02,
        -4.67194617e-03,  1.56408958e-02, -2.20717993e-02, -7.89548084e-03,
        -8.79504755e-02, -1.41688366e-03, -7.41648972e-02, -6.89151734e-02,
         1.32032169e-03,  7.18299393e-03,  4.22402658e-02, -1.29507445e-02,
        -5.94598353e-02, -2.15145592e-02,  4.72501926e-02, -4.47048619e-02,
         1.82686578e-02, -3.41442972e-02, -2.28104591e-02,  3.97903994e-02,
         2.98105944e-02, -1.37345260e-02,  1.47424918e-02, -8.66574980e-03,
         6.74799755e-02,  9.42609981e-02, -6.54757582e-03,  6.23168461e-02,
         5.53143211e-02, -7.30767772e-02, -1.26313874e-02, -3.48973386e-02,
         3.29142553e-03,  1.93192866e-02, -5.01432782e-03,  4.39123958e-02,
         6.30708411e-02,  7.76557401e-02,  1.89034045e-02,  6.32456020e-02,
        -2.61266045e-02,  4.19540070e-02, -6.05344996e-02,  5.59334308e-02,
        -4.70449924e-02,  1.07230507e-01, -4.37843017e-02, -4.39244339e-08,
        -4.54437211e-02,  5.85300773e-02,  3.94488052e-02,  3.78576294e-02,
         1.00979498e-02, -7.13360608e-02, -2.50397269e-02,  9.42401811e-02,
        -4.34389617e-03,  4.68531772e-02,  9.48943049e-02, -1.58426315e-02,
        -5.22854254e-02, -6.73166886e-02,  2.37377826e-02,  6.27046749e-02,
         2.45904643e-02,  1.48554007e-02, -7.40335789e-03, -5.34284785e-02,
         6.22455999e-02,  4.06174920e-02,  7.12228492e-02, -7.54844621e-02,
         5.87192103e-02, -7.54838064e-02, -2.89884377e-02,  8.29492882e-02,
        -1.11948857e-02, -3.05846967e-02,  6.50353497e-04,  2.79335678e-02,
        -2.71966867e-02, -9.44096744e-02,  2.87865382e-02,  1.28622815e-01,
        -2.21352167e-02, -2.42821090e-02,  5.68571389e-02, -2.05315370e-03,
         2.89760679e-02,  1.02703772e-01, -2.61279810e-02,  1.42625934e-02,
        -1.83888767e-02, -6.10382995e-03, -5.25135435e-02, -4.78076190e-02,
         5.91903515e-02, -3.91051956e-02, -7.87664670e-03,  5.99237531e-03,
         1.03719095e-02,  9.41201299e-02,  2.99628992e-02,  5.04731908e-02,
        -3.61867882e-02, -1.43789663e-03,  3.96512300e-02,  5.43301404e-02,
         6.14602827e-02, -7.25979656e-02, -4.58648168e-02,  2.27013007e-02]),
 array([-1.14521921e-01,  7.90134072e-03, -7.34652132e-02,  3.13613303e-02,
         2.16853172e-02, -5.83156087e-02,  1.58812888e-02, -2.72330772e-02,
        -1.13712132e-01, -6.55377936e-03, -8.49493605e-04, -5.58765605e-03,
         1.67666338e-02, -2.13291738e-02, -1.26991242e-01, -8.52217060e-03,
        -1.12560578e-01, -1.15131490e-01,  6.56480268e-02, -7.28071388e-03,
        -3.49060595e-02,  4.19287980e-02, -2.20058654e-02,  5.87661797e-03,
        -8.49295873e-04,  2.06241361e-03, -2.29054000e-02,  4.58148383e-02,
        -1.91787388e-02, -1.20299056e-01,  3.31707448e-02,  7.09628165e-02,
        -1.77346952e-02, -1.78957079e-02,  7.57021233e-02,  6.73394352e-02,
         2.93626934e-02,  1.29727963e-02, -2.32241373e-03, -3.92797999e-02,
         5.91743970e-03, -7.69666359e-02,  5.19315116e-02,  6.93272725e-02,
         2.51195636e-02,  5.81528768e-02,  2.31369399e-02, -3.75788994e-02,
        -2.82934960e-02,  9.48016644e-02, -6.43884391e-02,  1.41073912e-02,
         2.85122469e-02, -1.70723442e-02,  5.88897467e-02, -5.12493439e-02,
        -5.29040117e-03, -3.69137712e-02, -9.72598512e-03, -7.76583254e-02,
         6.57883584e-02, -1.43246772e-02, -8.34956467e-02, -2.51432452e-02,
        -6.36166930e-02, -2.39132233e-02,  1.24855086e-01, -8.81870743e-04,
         2.04717573e-02,  1.67688895e-02,  2.40083481e-03,  9.37746763e-02,
        -4.71508466e-02,  8.29052087e-03,  4.37057503e-02,  4.16780002e-02,
         3.10722739e-02, -9.23381448e-02,  1.20536521e-01, -1.68706641e-01,
        -1.57716963e-03, -5.06318435e-02,  1.23326238e-02,  5.89367040e-02,
         1.47082163e-02,  1.98826455e-02, -4.56485786e-02,  3.49411219e-02,
         7.70492479e-02, -5.22322729e-02,  9.20494832e-03, -1.27681354e-02,
         7.40753338e-02,  2.94319186e-02,  7.59765273e-03,  4.75656129e-02,
         7.71162137e-02, -3.59195061e-02, -1.75121296e-02,  9.10690874e-02,
         5.34712225e-02, -4.45895046e-02, -3.64287980e-02,  3.72273251e-02,
         1.46583486e-02,  5.28315315e-03,  4.00658362e-02,  3.04541774e-02,
        -5.08740619e-02, -4.20135558e-02, -2.00043786e-02,  2.10384447e-02,
         7.58729875e-03, -8.40534270e-02,  1.17242588e-02,  7.67138228e-02,
        -2.83231772e-02,  1.73959099e-02, -5.65249473e-02, -2.67434716e-02,
        -6.72518685e-02,  3.46088372e-02, -8.14321414e-02,  3.59769538e-03,
        -5.94548285e-02, -1.29957339e-02,  4.68543097e-02,  3.11075552e-33,
        -5.24419285e-02, -2.59196572e-02, -5.06777205e-02,  1.08582310e-01,
         3.43738943e-02, -1.84982866e-02,  3.43602151e-02, -5.42532131e-02,
        -7.28170052e-02, -2.47531161e-02, -1.14516072e-01, -5.79710789e-02,
         2.35516746e-02,  2.57022642e-02,  3.65344770e-02, -6.65364042e-02,
        -1.37150437e-02,  4.50751670e-02, -5.05846702e-02, -3.41726169e-02,
         1.90298799e-02, -5.94472848e-02, -9.11915451e-02, -5.22500761e-02,
         6.10000938e-02,  7.91333169e-02,  2.17660852e-02, -2.02539582e-02,
         4.57969867e-02,  4.87440974e-02,  6.26598746e-02,  4.08577733e-02,
         7.47623714e-03,  1.30898245e-02,  4.90898192e-02, -1.52360015e-02,
        -5.16297966e-02,  1.33300386e-03, -5.38349375e-02, -3.61093730e-02,
         5.13958149e-02,  9.34072509e-02, -5.75774871e-02, -4.01219018e-02,
         2.73893066e-02, -5.07439747e-02,  4.01816331e-02,  3.62771526e-02,
         5.82200065e-02,  6.00221977e-02, -5.73248267e-02,  3.19686420e-02,
         7.80633232e-03, -3.03195212e-02, -4.73768567e-04,  3.21669541e-02,
         2.04290804e-02,  1.25584276e-02,  2.65230350e-02, -8.62164330e-03,
         8.08330551e-02,  8.04162025e-02,  7.64021091e-03,  1.65242038e-03,
        -4.43332503e-03,  2.54183486e-02,  4.02044803e-02, -1.40621290e-02,
         4.28879037e-02,  3.60294175e-03, -5.07352166e-02,  2.66947057e-02,
         2.39245575e-02, -9.23289433e-02,  7.27571547e-02, -2.10034307e-02,
        -3.20199430e-02, -2.62820050e-02,  1.31031014e-02, -4.48081493e-02,
        -1.59404859e-01,  1.33111719e-02,  1.58001427e-02,  1.80206839e-02,
        -1.70703717e-02, -5.13760559e-02,  1.94990113e-02,  3.23183904e-03,
        -4.02095392e-02,  1.21478820e-02,  1.28566278e-02, -4.88763191e-02,
        -8.99926701e-04, -7.26068718e-03, -4.10946608e-02, -2.72177397e-33,
         3.37951034e-02,  4.30003107e-02, -2.54120138e-02,  5.36998175e-03,
        -8.00438970e-02, -3.78508540e-03,  9.27124452e-03,  4.82314900e-02,
        -5.18373474e-02,  8.50488059e-03,  7.77947754e-02,  6.02790117e-02,
         4.45943251e-02,  3.17270495e-02, -1.82977726e-03, -4.71380446e-03,
         2.53879242e-02, -4.47602049e-02,  2.42201127e-02,  1.23118013e-02,
        -3.71463299e-02,  1.38966125e-02, -1.50949154e-02, -1.61211956e-02,
        -3.78417075e-02,  7.27905333e-02,  1.08641617e-01, -2.94866543e-02,
         3.82298575e-04,  9.70194233e-04, -5.21493815e-02, -6.33746013e-02,
        -7.19366297e-02,  3.78357396e-02,  8.06179270e-03, -2.40225717e-02,
         1.84199736e-01, -1.63553916e-02, -9.56168324e-02, -1.02062516e-01,
         4.51718085e-02,  7.98871070e-02, -5.95463403e-02,  7.67815858e-02,
         2.65228823e-02,  2.38523670e-02,  7.98063949e-02,  2.25176895e-03,
         3.20168883e-02, -1.03166871e-01,  4.97279642e-03, -5.72819263e-02,
         5.50791547e-02,  5.32983840e-02,  2.28819549e-02,  1.23270843e-02,
        -1.90459806e-02,  4.86444011e-02,  1.18935220e-02, -2.36964915e-02,
        -1.63988695e-02,  3.45184430e-02, -6.09932914e-02,  1.96207780e-02,
         5.12631275e-02, -2.73195747e-03, -3.09042055e-02,  7.04135150e-02,
        -1.93130970e-02, -9.11993533e-02,  3.80248800e-02,  2.77513638e-02,
        -5.17711081e-02, -1.73084624e-02, -1.54164592e-02, -4.55113277e-02,
         4.05072980e-02,  2.13369448e-02,  2.84438813e-03, -2.47022547e-02,
         2.74098199e-02, -2.14135684e-02, -4.79996949e-02,  1.06791243e-01,
        -5.22234738e-02, -2.28257198e-03,  3.55023369e-02,  3.32866423e-02,
         5.57103492e-02, -1.32941771e-02, -5.01564331e-02,  3.50138098e-02,
        -1.67549141e-02, -1.26585998e-02,  2.49192715e-02, -2.90612441e-08,
         2.47945730e-02,  1.33275345e-01, -5.36851361e-02, -1.08191874e-02,
        -2.94857919e-02,  5.80754802e-02, -7.00118244e-02, -7.82099552e-03,
         2.62095276e-02,  4.16845903e-02,  2.78527644e-02,  1.62595529e-02,
         4.11304198e-02, -1.16744470e-02,  3.24816606e-03, -7.11077172e-03,
        -1.05787814e-01,  8.91843345e-03, -4.37302552e-02, -6.95154890e-02,
         1.79324625e-03,  1.81078482e-02,  7.15545341e-02, -2.84759309e-02,
         1.00749638e-03,  2.28697341e-02,  4.35694680e-03, -6.01860322e-02,
         1.84260309e-02, -3.85510102e-02, -1.83014106e-02,  8.70772749e-02,
        -2.69840341e-02, -4.48351726e-02,  1.23093650e-02,  7.25843012e-02,
        -1.56507567e-02,  4.38426174e-02,  8.22704881e-02, -6.50406256e-03,
        -2.16607377e-02,  4.47601490e-02, -5.65634109e-02,  3.48572508e-02,
         4.33957875e-02,  4.45255637e-02, -3.00301313e-02, -8.56725723e-02,
         1.77508276e-02, -1.07550718e-01, -1.92638263e-02, -4.47204076e-02,
         8.48933160e-02,  2.81044133e-02, -3.29713970e-02,  6.73989579e-02,
        -4.35747840e-02, -3.50436419e-02,  6.12366796e-02,  5.95407411e-02,
         1.43924057e-01,  5.05434163e-03, -9.88887697e-02,  5.47500066e-02]),
 array([-1.76019315e-02, -5.03365174e-02, -4.91420068e-02, -2.67864037e-02,
        -2.11639684e-02, -3.51148024e-02, -2.85749864e-02,  7.06635341e-02,
        -8.06428194e-02, -3.10145188e-02, -1.25572354e-01, -8.18972439e-02,
         6.26901314e-02, -1.06560618e-01,  1.71216931e-02,  2.10714154e-02,
         4.85191755e-02, -1.09884087e-02, -6.04407229e-02, -7.21042827e-02,
         2.87862513e-02,  5.78069268e-03, -2.71266308e-02, -8.43138248e-02,
        -1.65599603e-02,  1.36788823e-02,  3.34897568e-03, -7.38364682e-02,
         2.32743397e-02, -2.26949714e-02,  2.17097811e-02,  3.66063379e-02,
        -1.33340368e-02,  3.47882062e-02, -7.52905458e-02,  6.21431768e-02,
        -3.14933322e-02, -8.83233622e-02, -5.61803021e-02, -2.10757088e-02,
        -3.75674739e-02, -3.35875787e-02, -7.13375583e-02,  2.97992700e-03,
         1.51336938e-02, -2.02294830e-02, -3.26653905e-02, -5.82189746e-02,
        -2.30376404e-02, -6.78525865e-02, -6.18189536e-02, -9.60645154e-02,
         2.73446795e-02,  6.65325969e-02, -1.00979961e-01,  9.28773824e-03,
        -9.41884331e-03, -2.10380908e-02, -4.72933687e-02,  2.14503054e-02,
        -5.61120221e-03, -6.30997866e-02, -4.86090221e-03,  1.09378318e-03,
         3.98655608e-02, -2.33366080e-02,  2.66449116e-02,  1.15886107e-02,
         3.64392549e-02, -1.01747895e-02, -8.40332918e-03, -3.75114717e-02,
        -6.16826699e-04, -4.39690091e-02, -1.60297006e-02,  4.37864885e-02,
         4.56061177e-02,  2.08404455e-02,  8.35703090e-02, -8.42563286e-02,
         2.17194650e-02,  5.64461537e-02, -1.02709774e-02, -3.10200509e-02,
         5.87496385e-02, -2.51186043e-02, -4.06530648e-02,  1.22026363e-02,
        -3.45984735e-02, -4.82924432e-02,  1.30593749e-02, -1.21560674e-02,
         4.32368368e-02,  1.64662618e-02,  4.47574668e-02,  2.90455502e-02,
        -4.52055112e-02, -5.68112768e-02,  3.30337789e-03,  9.09403190e-02,
        -1.58251692e-02,  1.75257307e-02,  4.22259904e-02,  2.09214259e-02,
        -2.69691814e-02,  1.68937594e-02, -3.34032886e-02,  7.10103512e-02,
         4.51791212e-02, -1.28518149e-01, -8.57814448e-04,  8.23351741e-02,
        -1.92921534e-02, -7.67287165e-02, -2.34795772e-02,  5.15716448e-02,
        -3.99690792e-02, -3.96374688e-02, -1.64538138e-02,  9.70269516e-02,
        -8.32322761e-02, -1.06569536e-01,  2.78160144e-02,  2.08293069e-02,
         6.46927431e-02, -2.44819652e-02, -7.92279094e-02, -1.70035772e-32,
        -8.47389922e-02,  3.36993369e-03, -4.96138968e-02, -7.46288896e-02,
         1.32793067e-02, -1.80579629e-02,  6.82975166e-03, -1.10734832e-02,
        -2.81403475e-02, -4.53512333e-02, -2.99682301e-02,  1.22093903e-02,
         3.91570106e-02,  1.06385216e-01,  3.29999179e-02, -1.18821837e-01,
         4.52494174e-02,  1.08704112e-01,  2.64669657e-02, -3.48591693e-02,
         4.44954857e-02,  1.82079934e-02, -7.13612710e-04, -6.98008388e-02,
         9.96400416e-02,  1.33902812e-02,  1.04348414e-01, -4.53811884e-02,
        -5.01633771e-02,  3.91014665e-02, -1.69256851e-02, -2.20518745e-02,
        -4.17717285e-02,  4.83728461e-02, -2.87748333e-02, -3.21229622e-02,
        -1.66043621e-02, -2.19527017e-02,  1.46573056e-02, -3.82603742e-02,
        -6.05040640e-02,  5.69181219e-02,  2.93610562e-02, -1.20060682e-01,
        -5.22322208e-02, -6.65216148e-02, -3.43150608e-02,  2.24656779e-02,
        -1.25614246e-02, -6.02216981e-02,  5.46144694e-02, -4.88449112e-02,
        -3.28399278e-02, -9.12775006e-03,  9.32900608e-02,  2.79504526e-02,
         4.08750661e-02,  5.99293038e-02,  6.17008768e-02,  1.61272466e-01,
        -5.83145618e-02, -8.40037987e-02, -8.68290067e-02,  5.20217456e-02,
         4.08934727e-02,  2.98098121e-02,  1.82429273e-02,  1.37744565e-02,
         6.47608563e-02,  2.19360925e-02, -3.46104391e-02,  1.89134143e-02,
         4.37507518e-02,  2.49589253e-02,  3.17165777e-02,  2.88716927e-02,
         6.45167530e-02, -4.22137082e-02, -6.45064414e-02,  3.78341861e-02,
        -3.26147452e-02,  1.16436496e-01, -5.82268052e-02, -1.31504890e-02,
        -1.78511888e-02,  9.86969844e-03, -4.50869178e-04, -8.82414207e-02,
        -1.33502454e-01,  5.19611984e-02, -6.11520782e-02,  5.27509628e-03,
        -1.81404930e-02,  3.14381681e-02, -5.75904809e-02,  9.29834839e-33,
        -3.34457830e-02,  9.49194282e-02, -1.19547404e-01,  2.64467373e-02,
         3.75640914e-02, -4.91913548e-03,  1.19948862e-02, -2.17731874e-02,
        -8.46098587e-02,  5.50462194e-02,  1.01681184e-02, -4.27041687e-02,
         3.30820605e-02,  1.35010434e-02, -1.68469660e-02, -3.30918953e-02,
         6.96457038e-03, -6.70922622e-02,  1.29356456e-03,  1.28887305e-02,
         1.06542381e-02,  7.86014348e-02, -6.87824190e-02, -1.24181341e-02,
        -1.21671669e-02, -2.04219334e-02, -8.82314146e-02,  4.93101291e-02,
        -6.62501827e-02, -2.16864105e-02, -8.76820609e-02, -9.38247293e-02,
        -4.84009879e-03,  4.02982123e-02,  5.10270223e-02, -9.78142116e-03,
         8.17413032e-02,  6.59386255e-03,  1.78067237e-02,  4.86117750e-02,
         5.53757846e-02, -1.46036949e-02, -4.41236049e-02, -1.98721290e-02,
        -5.75494654e-02, -3.81330140e-02, -6.84074014e-02,  1.73331331e-02,
        -5.67757450e-02, -1.81357209e-02, -4.77161771e-03, -2.10513715e-02,
        -7.71226659e-02, -2.11191643e-03, -4.08133790e-02,  1.44615527e-02,
         7.37872496e-02,  3.95747013e-02, -3.47848870e-02,  1.15301916e-02,